microsoft/STL

README.md

Please note that acceptance of community PRs will be delayed while we are
bringing our test and CI systems online. For more information, see the
README.md.
On line 157 of README. md, corrected URI to URL. 
Working Draft.
submission).

Corrected URI to URL

---

README.md

fixes #137 
* Capitalised the first letter of every word in the header
* Replaced Microsoft/STL with microsoft/STL in README
that's …

Fixed minor capitalization issue in README

---

docs/cgmanifest.json

This updates some internal metadata.

update stl cgmanifest

---

stl/inc/xutility

Also write the requires clause similar to the other examples
- [] The STL builds successfully and all tests have passed (must be manually
and LWG issues as reference material. If they were derived …

Adopt LWG-3264 unconditionally

---

azure-devops/run-build.yml
tests/CMakeLists.txt
tests/libcxx/expected_results.txt
tests/libcxx/skipped_tests.txt
tests/tr1/CMakeLists.txt
tests/tr1/expected_results.txt
tests/tr1/lit.cfg
tests/tr1/lit.site.cfg.in
tests/tr1/tests/cwchar1/__init__.py
tests/tr1/tests/cwchar1/custom_format.py
tests/tr1/tests/cwchar1/lit.local.cfg

Description
===========
Enable tr1 tests.

Add tr1 testsuite

---

tests/std/tests/P0067R5_charconv/double_general_precision_to_chars_test_cases.hpp
tests/std/tests/P0067R5_charconv/double_scientific_precision_to_chars_test_cases_1.hpp
tests/std/tests/P0067R5_charconv/double_to_chars_test_cases.hpp
tests/std/tests/P0067R5_charconv/float_to_chars_test_cases.hpp

Add charconv test cases

---

stl/inc/coroutine
stl/inc/experimental/coroutine
stl/inc/experimental/resumable

This mirrors Ayesha Gagguturi's Microsoft-internal MSVC-PR-258040.
Works towards #40. Followup to #894.

Implement noop_coroutine()

---

README.md
azure-devops/provision-image.ps1
azure-devops/run-build.yml
azure-pipelines.yml

... and hopefully get the CI infrastructure up off the floor in the process.

Update VM Scale Set to VS 2019 Preview 3

---

README.md
azure-devops/provision-image.ps1
azure-devops/run-build.yml
azure-pipelines.yml

This should be a fast-forward merge as `feature/spaceship` hasn't accumulated any work yet. I believe this will be necessary for the CI to pass.

feature/spaceship: Merge #1015 (Update VM Scale Set)

---

daily_table.js
package-lock.json
package.json
weekly_table.js

Status Chart update

---

stl/inc/valarray

add bound check assertion to valarray::operator[]

---

tests/libcxx/expected_results.txt
tests/std/tests/P0896R4_P1614R2_comparisons/test.cpp

Fix 2 VS 16.8p3 blocked issues

---

daily_table.js
weekly_table.js

New datapoints, no other changes.
===

Status Chart: Weekly update

---

README.md
azure-devops/provision-image.ps1
azure-pipelines.yml
stl/inc/condition_variable
stl/inc/experimental/generator
stl/inc/memory
stl/inc/mutex
stl/inc/optional
stl/inc/shared_mutex
stl/inc/thread
stl/inc/xutility
stl/inc/yvals_core.h
tests/CMakeLists.txt
tests/std/include/test_death.hpp
tests/std/test.lst
tests/std/tests/P0220R1_optional_death/env.lst
tests/std/tests/P0220R1_optional_death/test.cpp
tests/std/tests/P0660R10_jthread_and_cv_any/test.cpp
tests/std/tests/P0660R10_stop_token_death/test.cpp
tests/std/tests/P0896R4_common_iterator_death/test.cpp
tests/std/tests/P0896R4_counted_iterator_death/test.cpp
tests/std/tests/P0896R4_views_filter_death/test.cpp
tests/std/tests/P0896R4_views_transform_death/test.cpp
tests/std/tests/P1020R1_smart_pointer_for_overwrite/env.lst
tests/std/tests/P1020R1_smart_pointer_for_overwrite/test.cpp
tests/std/tests/VSO_0157762_feature_test_macros/test.cpp

feature/format: Merge toolset update

---

README.md

Updated working draft revision in README.MD to n4868
Fixes #1387

Updated working draft revision to n4868

---

daily_table.js
package-lock.json

@mnatsuhara wanted to see the Status Chart after we merged #323. Behold, 13.7 PR-months have vanished!
===

Status Chart: <chrono> update

---

README.md
azure-pipelines.yml
stl/inc/charconv
stl/inc/chrono
stl/inc/random
stl/inc/regex
stl/inc/xhash
stl/inc/xmemory
stl/inc/xutility
stl/inc/yvals_core.h
tests/libcxx/expected_results.txt
tests/libcxx/skipped_tests.txt
tests/std/test.lst
tests/std/tests/GH_001530_binomial_accuracy/env.lst
tests/std/tests/GH_001530_binomial_accuracy/test.cpp
tests/std/tests/GH_001638_dllexport_derived_classes/env.lst
tests/std/tests/GH_001638_dllexport_derived_classes/test.compile.pass.cpp
tests/std/tests/P0355R7_calendars_and_time_zones_dates/test.cpp
tests/std/tests/P0784R7_library_support_for_more_constexpr_containers/test.cpp
tests/std/tests/P0898R3_concepts/test.cpp
tests/std/tests/P1502R1_standard_library_header_units/test.cpp
tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
tools/CMakeLists.txt

feature/spaceship: Merge toolset update

---

azure-devops/create-vmss.ps1
azure-devops/cross-build.yml
azure-pipelines.yml
stl/inc/vector
stl/inc/xmemory
stl/inc/yvals_core.h
tests/libcxx/expected_results.txt
tests/libcxx/skipped_tests.txt
tests/std/test.lst
tests/std/tests/Dev10_816787_swap_vector_bool_elements/test.cpp
tests/std/tests/P0784R7_library_machinery/env.lst
tests/std/tests/P0784R7_library_machinery/test.cpp
tests/std/tests/P1004R2_constexpr_vector/env.lst
tests/std/tests/P1004R2_constexpr_vector/test.cpp
tests/std/tests/P1004R2_constexpr_vector_bool/env.lst
tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp
tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp

Picks up #1654.
Nothing special here, just a simple merge without conflicts.
===

feature/format: Merge VMSS update

---

stl/inc/functional
stl/inc/scoped_allocator
stl/inc/xmemory
stl/inc/xpolymorphic_allocator.h
tests/std/tests/P1614R2_spaceship/test.cpp

Covers: `allocator`, `memory_resource`, `polymorphic_allocator`, `scoped_allocator_adaptor`, `function`

feature/spaceship: Clause 20: various synthesized equality operators

---

stl/inc/chrono

Resolves #1641.
No functional code change.

Comment calendar date conversion algorithm

---

stl/inc/chrono
tests/std/tests/P0355R7_calendars_and_time_zones_dates/test.cpp

<chrono>: fix year_month_day_last::day()

---

README.md

I updated the readme according to what was proposed in issue #1659

Update outdated test options in readme (#1659)

---

tests/std/tests/P1502R1_standard_library_header_units/lit.local.cfg
tests/utils/stl/test/config.py

Add standard library header units test to parallelism group

---

tests/std/tests/P1502R1_standard_library_header_units/custom_format.py
tests/std/tests/P1502R1_standard_library_header_units/custombuild.pl
tests/std/tests/P1502R1_standard_library_header_units/test.cpp

<format>: Add header unit test

---

stl/inc/chrono
tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp

Add multi-spec support to day

---

stl/inc/chrono
tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp

Add month formatting

---

README.md
index.html
package-lock.json
weekly_table.js

Status Chart: Weekly updates, chart.js 3.2.0.

---

stl/debugger/STL.natvis

Visualize `🛸_ordering`

---

CMakeLists.txt

Fixes #1734. Ports Daniel Griffing's MSVC-PR-316297.

Build the STL with /ZH:SHA_256

---

index.html
package-lock.json
package.json
weekly_table.js

This increases the maximums for the main chart to 70/700 and the PR Age chart to 220.
===

Status Chart: Weekly updates

---

README.md

update working draft revision to N4892

---

tests/std/tests/P0122R7_span/test.cpp
tests/std/tests/P0220R1_string_view/test.cpp

There's no behavioural change, This just adds extra tests and updates a comment.

Tests: Prepare for P2251 (trivially copyable `span`/`basic_string_view`)

---

stl/inc/xmemory
tests/std/tests/P0475R1_P0591R4_uses_allocator_construction/test.cpp

Forward declare uses_allocator_construction_args

---

README.md
azure-devops/provision-image.ps1
azure-pipelines.yml

This adds ASAN for #2071 and should unblock #2032.

Toolset update: VS 2022 17.0 Preview 3 with ASAN

---

index.html
package-lock.json
package.json
weekly_table.js

Status Chart: Weekly updates, adjust PR Age max/stepSize

---

docs/cgmanifest.json

Update cgmanifest.json for 17.0

---

stl/inc/type_traits

Remove DevCom-936696 workaround

---

index.html
package-lock.json
package.json
usernames_contributors.txt
weekly_table.js

Status Chart: Weekly updates, chart.js 3.6.2

---

stl/inc/yvals_core.h

updated _MSVC_STL_UPDATE

---

stl/inc/yvals_core.h

Changed the month to march.
closes #2601.

fix 2601: update month to March 2022

---

docs/cgmanifest.json

update cgmanifest for april

---

index.html
package-lock.json
package.json
src/weekly_table.ts
usernames_maintainers.txt

Welcome @strega-nil-ms to `usernames_maintainers.txt`!
This adds 4 weeks of vso/libcxx updates (not much change), updates our `npm` dependencies, and also updates our `index.html` dependencies.
:warning: As usual, this contains a "DROP BEFORE MERGING" commit so that the live preview will be useful.
===

Status Chart: Weekly/dependency updates, new maintainer

---

stl/inc/yvals_core.h

Update `_MSVC_STL_UPDATE` (may 2022)

---

stl/inc/complex
tests/std/tests/Dev10_555491_complex_linker_errors/test.cpp

Fixes #2728
tests: https://gcc.godbolt.org/z/66bEr6j4M

`<complex>`: fix complex division by zero

---

stl/inc/mutex
stl/inc/xcall_once.h
stl/src/StlCompareStringA.cpp
stl/src/cthread.cpp
stl/src/excptptr.cpp
stl/src/format.cpp
stl/src/taskscheduler.cpp

@strega-nil-ms suggested new rules

New BOOL rules

---

stl/src/cthread.cpp

Don't get thread exit code as we don't care anyway

---

tests/std/run.pl
tests/tr1/run.pl

Allow passing additional compiler flags if the compiler is cl.exe.

Port MSVC-PR-407767

---

stl/inc/yvals_core.h

<yvals_core.h>: Update _MSVC_STL_UPDATE to July 2022

---

stl/inc/ranges
stl/inc/xstring
tests/libcxx/expected_results.txt
tests/libcxx/skipped_tests.txt

Cleanup comments after merging LWG-3670 and LWG-3705

---

stl/inc/yvals_core.h

<yvals_core.h> Update _MSVC_STL_UPDATE to #define _MSVC_STL_UPDATE  202208L

---

stl/inc/yvals_core.h

Update _MSVC_STL_UPDATE to December 2022 #3251

---

azure-pipelines.yml

This updates our 1ES Hosted Pool for Jan 2023's Patch Tuesday. Somewhat unusually (but not surprisingly, given the holidays), there are no other changes - our other dependencies (e.g. VS, Python, PowerShell) are currently up-to-date.

Pool update: Jan 2023 Patch Tuesday

---

stl/inc/yvals_core.h

Update _MSVC_STL_UPDATE to January 2023 #3317

---

stl/inc/yvals_core.h

Updated _MSVC_STL_UPDATE to February 2023

---

index.html
package-lock.json
package.json
src/weekly_table.ts
src_gather/video_table.ts

As usual, this contains a "DROP BEFORE MERGING" commit to make the live preview work, which will accumulate merge conflicts.
===

Status Chart: Weekly updates, dependency updates

---

stl/inc/yvals_core.h

Update _MSVC_STL_UPDATE to March 2023

---

stl/inc/yvals_core.h

Change `_MSVC_STL_UPDATE` to May 2023

---

tests/std/tests/P0009R18_mdspan_layout_stride/test.cpp

Add missing tests in `P0009R18_mdspan_layout_stride/test.cpp`.

`<mdspan>`: Improve `layout_stride` tests

---

README.md

Updated working draft revision from N4944 to N4950.
Fixes N4944/N4950 on line 535.
Fixes #3695

updated working draft revision to N4950

---

stl/inc/yvals_core.h

Change _MSVC_STL_UPDATE to June 2023

---

tests/std/include/range_algorithm_support.hpp
tests/std/tests/P2415R2_owning_view/test.cpp

* Closes #3613.
* Drive-by:
* Test `c(begin|end)` too (towards #3391),
* Fix `owning_view::size` test.

Make `P2415R2_owning_view/test.cpp` test something

---

stl/debugger/STL.natvis

Better char vector visualization
This is a duplicate of MSVC-PR-478382 and [VS PR 477513](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/477513).

Better char vector visualization

---

stl/inc/mdspan

`<mdspan>`: Drop `#pragma once`

---

stl/inc/yvals_core.h

Update _MSVC_STL_UPDATE to August 2023 

---

stl/inc/yvals_core.h

Update _MSVC_STL_UPDATE to September 2023

---

README.md

updated working draft to N4958 

---

stl/inc/yvals_core.h

Fixes https://github.com/microsoft/STL/issues/4061

Update _MSVC_STL_UPDATE to October 2023

---

stl/inc/ranges
tests/std/tests/P2278R4_ranges_const_range_machinery/test.cpp

Implement LWG-3946 The definition of `const_iterator_t` should be reworked

---

azure-devops/config.yml

Merge `main` to `feature/flat_set`

---

stl/inc/yvals_core.h

Update _MSVC_STL_UPDATE to November 2023

---

stl/inc/yvals_core.h

Update yvals_core to February 2024

---

stl/src/vector_algorithms.cpp

Return after SSE2 code

---

stl/inc/yvals_core.h

Fix [issues#4429](https://github.com/microsoft/STL/issues/4429)

<yvals_core.h> Update _MSVC_STL_UPDATE to March 2024

---

stl/inc/ranges
tests/std/tests/P0896R4_views_single/test.cpp

Implement LWG-4035 single_view should provide empty

---

stl/inc/yvals_core.h

Update _MSVC_STL_UPDATE to April 2024

---

docs/cgmanifest.json

https://github.com/boostorg/math/releases/tag/boost-1.85.0

Update boost-math to 1.85

---

stl/inc/yvals_core.h

Fixes #4704 
This PR is going to fix this issue. Update the month to June 2024

Update month to June 2024

---

README.md

Update `README.md` working draft revision to N4986

---

README.md

Updated C++ latest working draft to N4988

---

stl/inc/yvals_core.h

Updated _MSVC_STL_UPDATE to September 2024

---

stl/inc/yvals_core.h

Update _MSVC_STL_UPDATE to October 2024

---

index.html
package-lock.json
package.json
src/weekly_table.mts

Other than primer/css slightly changing shades, nothing notable this month.
===

Status Chart: Weekly/dependency updates

---

README.md
stl/inc/regex

Fixes  #5018
changed line 61 and 572 
From : N4988
To :N4993

Update N4988 to N4993 in README.md

---

README.md

Mention ASan testing steps in `README.md`

---

.mailmap
README.md
benchmarks/CMakeLists.txt
benchmarks/inc/skewed_allocator.hpp
benchmarks/src/adjacent_difference.cpp
benchmarks/src/search.cpp
benchmarks/src/swap_ranges.cpp
stl/inc/__msvc_string_view.hpp
stl/inc/__msvc_threads_core.hpp
stl/inc/algorithm
stl/inc/chrono
stl/inc/numeric
stl/inc/regex
stl/inc/xhash
stl/inc/xmemory
stl/inc/xtree
stl/src/vector_algorithms.cpp
tests/libcxx/expected_results.txt
tests/std/tests/P0088R3_variant/test.cpp
tests/std/tests/P0220R1_any/test.cpp
tests/std/tests/P0220R1_optional/test.cpp
tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
tests/std/tests/VSO_0131167_associative_emplacement_allocations/test.cpp

This picks up the submodule update #5038 so it isn't a headache when switching between `main` and `feature/flat_map`.

Merge `main` to `feature/flat_map`

---

stl/src/mutex.cpp

Inspired by https://github.com/microsoft/STL/issues/4418#issuecomment-2484715880

More specific assertion for unlocking mutex not owned by the current thread

---

stl/inc/yvals_core.h

Update _MSVC_STL_UPDATE to December 2024

---

README.md

Updating README.md to reflect latest working draft.
Fixes #5195 
Changed line 61 and 568 from N4993 to N5001

Update N4993 to N5001 in README.md

---

stl/inc/yvals_core.h

Update `_MSVC_STL_UPDATE` to February 2025

---

stl/inc/yvals_core.h

Update _MSVC_STL_UPDATE to March 2025

---

stl/inc/yvals_core.h

Update _MSVC_STL_UPDATE to April 2025

---

README.md

Replaced N5008 to N5014

---

stl/inc/yvals_core.h

Update _MSVC_STL_UPDATE macro to September 2025
