- stl/inc/chrono
- stl/inc/yvals_core.h
- tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp
- tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Continuation of #1892 
In addition to that pull requests content (which is mirrored here, although squashed into one commit) I have
* merged the new tests from #1892 into the tests into some existing locale tests from a subsequent pr (#2017 )
* fixed that PRs new test to use the locale specifier as is now required.
fixes: #2237 
approved by plenary a week ago:
https://github.com/cplusplus/papers/issues/1039
> P2372R3: Fix handling of locale in chrono formatters

- stl/CMakeLists.txt
Fixes #2311
I verified the fix manually; open to suggestions for test coverage.
> Don't /LTCG CRT initializers

- stl/inc/format
- tests/std/tests/P1502R1_standard_library_header_units/test.cpp
> `<format>`: delay vformat instantiation

- stl/inc/limits
- tests/std/tests/GH_001103_countl_zero_correctness/test.cpp
Resolves #2330
Fixes VSO-1434895/AB#1434895.
> Remove attempt to use tzcnt as bsf

- stl/inc/xstring
* `basic_string(const T& t, size_type, size_type, Alloc = Alloc())` constructor _should_ allow `t`'s convertible to pointer-to-element
* Each family of `find` functions is (1) missing conditional `noexcept` on the "convertible-to-`string_view`" overload, and (2) incorrect that `noexcept` on the "element, offset" overload is strengthened
We apparently overlooked these bits when implementing P1148R0 which was largely a clean rewording paper. A new internal test suite noticed one of the missed changes, I audited P1148 to find the others.
Fixes VSO-1411144
Fixes AB#1411144
> Implement changes missed from P1148R0

- stl/inc/algorithm
- tests/std/tests/P0896R4_ranges_alg_find_end/test.cpp
...and add full test coverage.
Fixes #2268
> Fix ranges::find_end return for bidi-common case

- stl/inc/algorithm
- stl/inc/ranges
- stl/inc/xutility
- tests/std/tests/P0896R4_ranges_alg_find_end/test.cpp
- tests/std/tests/P0896R4_ranges_alg_search/test.cpp
- tests/std/tests/P0896R4_ranges_alg_sort/test.cpp
- tests/std/tests/P0896R4_views_split/test.cpp
If there's one thing that _must_ work in C++, it's sorting `vector` =)
For ease of review: DevCom-1559808.
This also moves `_Rewrap_subrange` to `<xutility>` because it's already being used there:
https://github.com/microsoft/STL/blob/ee5a216b516ef033d9153b324842369eee7653d1/stl/inc/xutility#L5674
> Workaround Devcom-1559808 in ranges::sort

- stl/inc/array
- tests/libcxx/expected_results.txt
- tests/libcxx/skipped_tests.txt
Previously, these types were non-instantiable; we can't break ABI for something that doesn't compile. (Why do I always end up coding the PRs that fire salvos at the ODR?)
Fixes #942
Fixes VSO-207715 / AB#207715.
Note that the proposed resolution of LWG-2157 clarifies how `array<T, 0>` should behave. It hasn't been merged yet due to many of us despising the bit about "When `a` and `b` are distinct objects of the same zero-sized array type, `a.begin()` and `b.begin()` are not iterators over the same underlying sequence. [Note: Therefore `begin()` does not return a value-initialized iterator — end note]". If `begin` and `end` cannot return a value-initialized iterator (either a `nullptr` or a wrapper around a `nullptr`) it's not clear how they are to be implemented so as to be usable in …
> Specially handle `array<T, 0>` for non-default-constructible `T`

- stl/inc/xmemory
... on `std::allocator::allocate_at_least`. This attribute may only be used to annotate functions that return pointers.
I'm not adding test coverage since (1) doing so would require disabling the global suppression of C4494 which, although possible, is a bit invasive and feels fragile, and (2) I think we're unlikely to regress.
Thanks to @Hannes-Harnisch for reporting the bug on Discord.
> Remove improper use of __declspec(allocator)

- index.html
- package-lock.json
- package.json
- weekly_table.js
* 2 weekly updates.
* Update dependencies. I've verified that the generator's output is unchanged.
* Increase the PR Age `max` and `stepSize`. We've been prioritizing C++20/23 PRs so the total age has been increasing. We're trying to drain the backlog, but the holidays will reduce throughput.
===
> Status Chart: Weekly updates, increase PR Age

- stl/inc/xutility
- tests/std/include/timezone_data.hpp
- tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp
- tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
- tests/std/tests/P0645R10_text_formatting_utf8/test.cpp
- tests/std/tests/P0898R3_concepts/test.cpp
The workaround for GH-2326 isn't needed for the internal MSVC compiler; let's ensure it doesn't regress. Since this workaround is in product code let's rename `MSVC_INTERNAL_TESTING` to `_MSVC_INTERNAL_TESTING` (because `_Ugly`). Don't forget to update the name in `$/src/qa/distrib.yml` consistently when merging.
Resolves #2326
> Internally disable `subrange` workaround

- stl/inc/filesystem
- tests/std/test.lst
- tests/std/tests/LWG3480_directory_iterator_range/env.lst
- tests/std/tests/LWG3480_directory_iterator_range/test.compile.pass.cpp
> Implement LWG-3480, `directory_iterator` and `recursive_directory_iterator` are ranges

- tests/tr1/include/tdefs.h
Apparently previously compiler's static analysis did not understand `%a`, so the string was hidden.
Now let's show it!
It fixes warning C4774: 'printf' : format string expected in argument 1 is not a string literal.
Currently the warning is disabled, as it is a warning disabled by default.
Salvages the useful part from #2142
> Don't hide format string from the compiler

- tests/std/tests/P0898R3_concepts/test.cpp
DevCom-952724 is "Fixed In: Visual Studio 2022 version 17.0".
> Remove outdated `#if` guard

- stl/inc/ranges
- tests/std/tests/P0896R4_views_join/test.cpp
When piping into `std::views::join`, Clang eagerly instantiates the `join_view::_InnerRng` template alias. This alias is used in the requirements of the resulting view's `const` qualified `begin()` and `end()` methods. This check is performed and causes a hard compile error even if the source contains no calls to the `const` qualified methods. 
I used the workaround applied to the same methods of [`std::views::transform_view`](https://github.com/microsoft/STL/blob/3c2fd04d441d46ec9d914d9cbb621a3bac96c3a5/stl/inc/ranges#L1857).
A simplified reproduction of code that fails to compile under Clang can be found [here](https://godbolt.org/z/d8xzj3Gbf). Piping a `filter_view` or a view composed on top of a `filter_view` will cause this erroneous compile error; `filter_view` has no const …
> Applied LLVM-47414 workaround to `std::ranges::join_view`

- tests/std/tests/P0898R3_concepts/test.cpp
I noticed this when preparing #2351. After investigation, I found that there's already a bug report (LLVM-48305), and there's a simple workaround.
The only non-whitespace changes are the addition of a semicolon and a comment, and the removal of two comments.
> Workaround clang-format misbehavior in `P0898R3_concepts` test

- stl/inc/bit
- tests/std/tests/P0553R4_bit_rotating_and_counting_functions/test.cpp
> Rotate bits using intrinsics

- stl/inc/memory
- stl/inc/optional
- tests/std/tests/P0220R1_optional/test.cpp
> implemented the proposed resolution for LWG-2762

- stl/src/vector_algorithms.cpp
by defining permutation by the macro instead of magic decimal value
if not this, then maybe let's use hex or binary constant,
but decimal is very obscure
> Clarify vector_algorithms a bit

- stl/inc/type_traits
- stl/inc/xtr1common
This ports @xiangfan-ms's MSVC-PR-360974, which was merged on 2021-10-29 but we forgot to mirror it.
Xiang optimized the MSVC compiler front-end to recognize `type_identity_t` and `_Identity_t`, which became heavily used after we merged #2032 implementing [P1518R2](https://wg21.link/P1518R2) Stop Overconstraining Allocators In Container Deduction Guides.
As part of this work, our internal aliases `_Identity_t` and `_Remove_cvref_t` need to be marked with the attribute `_MSVC_KNOWN_SEMANTICS`:
https://github.com/microsoft/STL/blob/18019346af33d90fab4e65a2f2a2efe741ec050b/stl/inc/yvals_core.h#L424-L434
> Compiler type trait optimizations

- CMakeLists.txt
- stl/inc/chrono
- stl/inc/format
- stl/inc/yvals_core.h
- tests/libcxx/expected_results.txt
- tests/libcxx/skipped_tests.txt
- tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp
- tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp
- tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
- tests/std/tests/P0645R10_text_formatting_legacy_text_encoding/test.cpp
- tests/std/tests/P0645R10_text_formatting_parse_contexts/test.cpp
- tests/std/tests/P0645R10_text_formatting_utf8/test.cpp
- tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
This is the second half of P2216R3 (the first half is already implemented), and continues @vitaut's work from #1882
There's no new tests accompanying this PR because we don't really have "tests that should not compile". I did mess remove the throw_helper call from around several of the tests in P0645R10_text_formatting_formatting to verify those invalid strings failed to compile.
The compile time format string checking is disabled if we can't figure out that you're using a utf-8 execution character set at compile time. The compiler does have a new feature that lets us find out about other character sets, but in addition to that we'd need constexpr decoding for GB18030/GBK and CP932 (or any other legacy codepages that don't self-synchronize, or move format control characters around). This …
> <format>: compile time checks

- stl/inc/limits
- tests/std/tests/GH_001103_countl_zero_correctness/env.lst
- tests/std/tests/GH_001103_countl_zero_correctness/test.cpp
> Update test for bsf private helper

- stl/inc/sstream
- tests/std/tests/P0408R7_efficient_access_to_stringbuf_buffer/test.cpp
Currently we were always taking the buffer from the moved in string, but would only store it when the buffer could be read or written to.
Consequently if that was not the case we would leak the allocated memory.
Also simplify the code a bit, we know that the capacity `_Res` will always be nonzero due to the way `_Release_to_buffer` works
Also add tests for the error cases
@BRevzin
> Fix Efficient access to streambuf buffer

- stl/inc/format
- stl/inc/ranges
Our supported C++latest frontends (clang-cl and msvc) both have concepts support, so this appears redundant.
Fixes DevCom-1603100
Closes VSO-1445646 / AB#1445646
> Strike "with concepts support" from the GH-1814 messages

- stl/inc/ranges
- tests/std/tests/P0896R4_views_split/test.cpp
> Implement LWG-3590: `split_view::base() const &` is overconstrained

- stl/inc/concepts
> Implement LWG-3557: The `static_cast` expression in `convertible_to` has the wrong operand

- stl/inc/type_traits
- tests/std/test.lst
- tests/std/tests/LWG3146_excessive_unwrapping_ref_cref/env.lst
- tests/std/tests/LWG3146_excessive_unwrapping_ref_cref/test.compile.pass.cpp
- tests/tr1/tests/functional9/test.cpp
> Implement LWG-3146: Excessive unwrapping in `std::ref`/`cref` 

- stl/inc/iterator
- tests/std/include/range_algorithm_support.hpp
- tests/std/tests/P0896R4_common_iterator/test.cpp
- tests/std/tests/P0896R4_counted_iterator/test.cpp
- tests/std/tests/P0896R4_views_counted/test.cpp
> Implement LWG-3574 and LWG-3595: `common_iterator` should be completely `constexpr`-able

- stl/inc/ranges
> Implement LWG-3591 and LWG-3592 for `lazy_split_view`

- stl/inc/xutility
- tests/std/tests/P0896R4_ranges_subrange/test.compile.pass.cpp
> Implement LWG-3470: `convertible-to-non-slicing` seems to reject valid case

- stl/inc/ranges
> improve iota_view's iterator's binary operator+ (LWG-3580)

- stl/inc/iterator
- tests/libcxx/expected_results.txt
- tests/libcxx/skipped_tests.txt
- tests/std/include/range_algorithm_support.hpp
- tests/std/tests/P0896R4_ranges_alg_copy_if/test.cpp
- tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
We've had a few of the latter sneak in - let's correct them now.
Totally unrelated drive-by: Skip flaky libcxx test that detaches threads. (See https://dev.azure.com/vclibs/STL/_build/results?buildId=9815&view=ms.vss-test-web.build-test-results-tab&runId=1172522&resultId=101145&paneView=debug)
> Prefer `friend constexpr` to `constexpr friend`

- stl/inc/vector
- tests/std/tests/GH_002030_asan_annotate_vector/test.cpp
@joemmett experienced ASan errors while attempting to build and run the compiler under ASan after my ASan vector change.
Upon inspection of the failure point @CaseyCarter noticed that we were passing the change of the size to the ASan annotator guard instead of the absolute target size in both `_Resize` and `assign`.
Casey and I also would like to see more vector tests running with ASan turned on but it is difficult to insert `/fsanitize=address` into an arbitrary matrix because it currently only supports the default IDLs and clang-cl currently does not support debug flavors of the CRT.
> `<vector>`: Correctly pass target size, not size change to ASan annotator

- .vscode/settings.json
- README.md
- index.html
- package-lock.json
- package.json
- src/gather_stats.ts
- weekly_table.js
* `npm install [dependencies]@latest`
+ This removes an indirect dependency on `colors`, a package which has had problems recently.
* chart.js 3.7.0.
+ No visual differences.
* Set terminal.integrated.cwd.
+ This is for personal convenience, so the integrated terminal opens in the workspace folder.
* Update Node.js version.
+ This contains npm 8.3.0 which supports `overrides`, which we might need in the future (not right now though).
* weekly_table.js updates.
* Increase chart limits.
+ Hopefully, as activity picks up after the holidays, we'll be able to keep the lines from rising.
* Optimize gather_stats.ts with events.
+ There's a comment explaining the strategy.
+ To further improve things, I now allow cooked PR/issue nodes to contain `null` for closed/merged dates. This allows us to …
> Status Chart: Optimize, chart.js 3.7.0, weekly updates

- stl/inc/xmemory
- tests/std/tests/Dev09_126254_persistent_aux_allocators/test.cpp
> `<memory>`: Add `nullptr` check in `std::allocator`

- stl/inc/xmemory
- stl/inc/yvals_core.h
...by LWG-3170. We improperly reused the "allocator features deprecated in C++17" deprecation warning macro instead of devising a new macro name, and therefore incorrectly "promoted" `is_always_equal` to "removed" when the other such marked features were removed for C++20.
Fixes #2422
> `allocator::is_always_equal` is deprecated, not removed, in C++20

- stl/inc/ranges
- tests/std/tests/P0896R4_views_elements/test.cpp
(There's an argument to be made that they were useless before when they named the result type of `views::keys(declval<Rng>())` and `views::values(declval<Rng>())`, but they certainly are now.) Change our test coverage to `views::keys` and `views::values`, the intended UX for extracting fields from ranges.
Fixes #2389
> Render keys_view and values_view useless per LWG-3563

- tools/move_only_function_specializations/move_only_function_specializations.py
TIL what is string interpolation
> `move_only_function`: more concise Python script

- stl/inc/valarray
- tests/tr1/tests/valarray/test.cpp
This issue also causes range-based for loops to break for empty valarrays.
I also added regression tests, which I hope are fine.
If there's anything wrong just tell me and I'll happily adjust!
> Fix begin/end for valarray crashing on empty instance

- stl/inc/iterator
- stl/inc/ranges
- stl/inc/xutility
> Remove some `strengthened` comments 

- index.html
- package-lock.json
- package.json
- src/gather_stats.ts
- tsconfig.json
- weekly_table.js
* Enable `esModuleInterop`.
+ This is a highly recommended modern option that disables legacy behavior. See the [compiler option docs](https://www.typescriptlang.org/tsconfig#esModuleInterop) and the [TypeScript 2.7 changelog](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-from-commonjs-modules-with---esmoduleinterop) when this was added.
* Fix issues found by TypeScript (that conversion is a work in progress, not present here).
+ The `weekly_table` lacks `'cxx23'`, so `get_values()` wasn't getting anything.
+ The `daily_table`'s current values can be `null` (when lines reach 0 and disappear), causing nothing to be printed. (It would look like "() C++20 STL features".) We need to detect this and print 0.
+ The current values …
> Status Chart: Modern modules, fix minor issues, weekly update

- tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
The sporadic failure mentioned in #2449 has happened twice, in unrelated PRs, affecting both x86 and x64 (but curiously affecting clang-cl both times). We can't figure out why this is happening, so printing the return value of `format()` might help.
The output will look like this (with 2,000 zeroes, and there will be some difference between the strings):
```
Encountered sporadic failure GH-2449!
str1: "1.34a1c000...000p+10"
expected: "1.34a1c000...000p+10"
DO NOT IGNORE/RERUN THIS FAILURE.
You must report it to the STL maintainers.
Assertion failed: false, file D:\GitHub\STL\tests\std\tests\P0645R10_text_formatting_formatting\test.cpp, line 829
```
> Add diagnostics for sporadic failures in a `<format>` test

- stl/inc/xutility
- tests/std/tests/P0896R4_ranges_subrange/test.compile.pass.cpp
> subrange `get<0>` requires a copyable iterator

- stl/inc/iterator
Per LWG-3543. (This is _almost_ a pure non-functional change, but I added a word to the error message we emit on failure.)
Fixes #2184
> Update counted_iterator's "same sequence" definition

- stl/inc/chrono
- stl/inc/ratio
Fixes #2291
~~Blocked on https://developercommunity.visualstudio.com/t/1202945~~
`std::gcd` includes large headers such as `<xutility>` and `<limits>`. I did not dare try to make a new header (`<xratio>`?) because I was not 100% sure if I can do it correctly.
The callers of `_Gcd` only work with `intmax_t`, so I figured it is easier to just update `_Gcd` and its callers rather than worrying about making a new header.
> `<ratio>`: Use `constexpr` functions instead of TMPs

- README.md
- azure-devops/create-vmss.ps1
- azure-devops/provision-image.ps1
- azure-pipelines.yml
- stl/inc/format
- stl/inc/functional
- stl/inc/xutility
- tests/std/tests/P0220R1_optional/test.cpp
- tools/scripts/move_only_function_specializations.py
- tools/scripts/print_failures.py
* Rename `tools/move_only_function_specializations` to `tools/scripts`.
+ Now we can add other scripts to this directory, and it avoids repeating the filename `move_only_function_specializations.py`.
+ Update the comment in `<functional>` accordingly.
+ Add a comment to `move_only_function_specializations.py` explaining what it does - even though the filename and code are fairly self-explanatory, as we accumulate scripts, it will be helpful for each of them to briefly mention what they do, so we don't need to deduce their intent from their code.
* Add `tools/scripts/print_failures.py`.
+ This automates the process of searching through test logs to find `FAIL` and `XPASS` tests, then decoding their JSON with search-and-replace (replacing CRLFs and LFs with newlines, unescaping double …
> Toolset update: VS 2022 17.1 Preview 4, ARM64EC

- stl/inc/format
- tests/std/tests/P0645R10_text_formatting_legacy_text_encoding/test.cpp
This should drastically increase format's performance in the "default" case (still need to rerun my toy benchmarks though)
For clang use ____clang_literal_encoding__, clang 14 will learn
_MSVC_EXECUTION_CHARACTER_SET, but ____clang_literal_encoding__
is in clang 13.
Additionally for the "slow path" get the "format codepage" using
these new macros (at compile-time) rather than assuming the
active codepage is the same as the execution character set.
ABI Impact:
This changes which versions of some templates get used, and could cause ODR violations, but in general should make people's ABI situation better rather than worse.
In particular windows 1251 will now use the "fast path" on msvc, so if you link clang code (which always used the fast path) to
non-clang code you no longer have an ODR …
> <format> use _MSVC_EXECUTION_CHARACTER_SET

- stl/inc/vector
Fixes #2470 and changes instances of `_Unfancy_maybe_null()` to `_Unfancy()`.
> Changed _Unfancy_maybe_null() to _Unfancy()

- stl/inc/random
- tests/std/test.lst
- tests/std/tests/GH_001964_constexpr_generate_canonical/env.lst
- tests/std/tests/GH_001964_constexpr_generate_canonical/test.cpp
...up to 64 bits of entropy. Leave the original implementation for
more bits and naughty generators (I'm looking at you, tr1) whose
min and max functions aren't static.
Fixes #1964. Alternative to #2452.
A slightly modified version of @CaseyCarter's release (`/O2 /fp:strict` for me) codegen test:
```cpp
#include <random>
template <size_t kMax>
struct Engine {
using result_type = size_t;
static constexpr result_type min() noexcept {
return 0;
}
static constexpr result_type max() noexcept {
return kMax;
}
result_type operator()() noexcept;
};
template <class R, class G>
R meow(G& g) {
return std::generate_canonical < R, ~std::size_t{ 0 } > (g);
}
template double meow(Engine<10'000>&);
template double meow(Engine<~size_t{0}>&);
```
<details>
<summary>asm diff</summary>
```diff
diff --git …
```
> constexpr all the generate_canonical parameters

- stl/inc/yvals_core.h
Fixes #2135.
Note: I noticed that cl defines `__cpp_impl_coroutine` when `/await:strict` is on, so I believe that there's no need to check `defined(_DOWNLEVEL_COROUTINES_SUPPORTED)`. I also relocated the definition of `__cpp_lib_coroutine` to make it next to the other C++20 feature-test macro that's not guarded by `_HAS_CXX20`.
> Rearrange feature test macros

- stl/inc/xutility
- tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
to fix a regression when calling `ranges::distance` with array arguments which _should_ decay to pointers.
If you look at LWG-3664 soon, you'll notice this doesn't match the proposed resolution. That original P/R is insufficient (Outlook Code™). Yes, that's right, the fix I suggested for the regression resulting from the fix I made in LWG-3392 is broken. :thonk: I've sent an updated PR with this change to LWG Chair, it will be a few days before the issue gets updated.
> Speculatively implement LWG-3664

- .github/ISSUE_TEMPLATE/cxx23-feature.md
- CMakeLists.txt
- README.md
- azure-devops/checkout-sources.yml
- azure-pipelines.yml
- tools/CMakeLists.txt
Update the toolset to VS 2022 17.1 Preview 5 containing CMake 3.22 (now required).
Use `--sparse-index` when checking out libcxx from llvm-project. See GitHub's blog post [Make your monorepo feel small with Git's sparse index](https://github.blog/2021-11-10-make-your-monorepo-feel-small-with-gits-sparse-index/).
git 2.36 is expected to improve `git clean` performance with the sparse index, but AFAIK there are no correctness concerns.
Also, `git sparse-checkout init` has been deprecated and fused into `git sparse-checkout set`. See GitHub's blog post [Highlights from Git 2.35](https://github.blog/2022-01-24-highlights-from-git-2-35/) and Git's [documentation](https://git-scm.com/docs/git-sparse-checkout#Documentation/git-sparse-checkout.txt-eminitem).
Tested with:
```
git clone …
```
> Toolset update: VS 2022 17.1 Preview 5, CMake 3.22, sparse index

- stl/inc/xstring
- tests/std/tests/P0980R1_constexpr_strings/test.cpp
Fixes #2524
`cmp_less_equal` is in `utility`
`xutility` includes `utility`
`xmemory` includes `xutility`
`xstring` includes `xmemory`
> resize_and_overwrite: fix warning C4018

- stl/inc/utility
- stl/inc/yvals_core.h
- tests/std/test.lst
- tests/std/tests/P0627R6_unreachable/env.lst
- tests/std/tests/P0627R6_unreachable/test.cpp
- tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
> P0627R6: Function to mark unreachable code

- stl/inc/format
Implements the proposed resolution of LWG-3654.
> LWG-3654: `basic_format_context::arg(size_t)` should be noexcept

- stl/inc/xutility
- stl/inc/yvals_core.h
Our integer-class types (`_Signed128` and `_Unsigned128`) were implemented to the revised wording, so they require no changes.
We _do_ need the `subrange` constructor change.
We don't need the `drop_view`, `take_view`, `views::counted`, and `views::take` changes. We already implement them or something functionally equivalent.
Update `<yvals_core.h>` to indicate that P2393R1 is implemented in C++20 (and later) modes.
Drive-by: Indicate that P1522 is now fully implemented in `<yvals_core.h>`.
Fixes #2254
There's no test coverage here because it just seems silly to write two ranges with custom iterators just to verify the presence of one `static_cast`. As always, reviewers - yell at me if you disagree.
> P2393R1 Cleaning Up Integer-Class Types

- stl/inc/memory
- tests/std/tests/P0718R2_atomic_smart_ptrs/test.cpp
Implements the proposed resolution of LWG-3661
partially addressed #2527
> LWG-3661: `constinit` `atomic<shared_ptr<T>>` a(nullptr); should work

- stl/inc/memory
LWG-3632 specifies that `unique_ptr` constructors that accept `pointer` inhibit CTAD with `type_identity_t`. We inhibit CTAD differently, but it's not obvious to a reader why these constructors don't look like they do in the Standard - let's add a comment to explain why.
> "Implement" LWG-3632 by commenting `unique_ptr` CTAD

- stl/inc/iterator
- stl/inc/syncstream
- tests/std/tests/P0896R4_common_iterator/test.cpp
LWG-3660 "`iterator_traits<common_iterator>::pointer` should conform to [iterator.traits]" requires a tweak to `iterator_traits` so it always agrees with `operator->()`.
Also removes comments for LWG-3601 and LWG-3616 which have been voted into the Standard, see #2527.
> Implement LWG-3660 for `iterator_traits<common_iterator>::pointer`

- stl/inc/system_error
- tests/std/tests/Dev11_0493504_error_category_lifetime/test.cpp
- tests/tr1/tests/system_error/test.cpp
Fixes #2552 
Should I add a reminder for moving the fix to syserror.cpp when we will be able to modify the file?
`cond.message()` == `"Операция успешно завершена."` on my PC.
it's definitely something else on your PC so I decided to test with `!=` the fallback.
> Implement LWG-3598 `system_category().default_error_condition(0)`

- stl/inc/filesystem
- tests/std/tests/P0218R1_filesystem/test.cpp
> Implement LWG-3657 `std::hash<std::filesystem::path>` is not enabled

- stl/inc/ranges
- tests/libcxx/expected_results.txt
- tests/libcxx/skipped_tests.txt
- tests/std/tests/P0896R4_views_transform/test.cpp
> Implement LWG-3618 Unnecessary `iter_move` for `transform_view::iterator`

- stl/inc/format
`format` would access uninitialized stack when trying to find the position of the exponent. When the junk in `_Buffer` (or past it, if `to_chars` used up all available space in the buffer) happened to be `'p'` in `hex` mode (or `'e'` in `scientific` mode, or their uppercased forms), this produced incorrect results.
Fixes #2449. Thanks to @statementreply for investigating!
> `<format>`: fix single byte out of bounds access

- stl/inc/chrono
- stl/inc/format
- tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp
> Speculatively implement LWG-3636: `formatter<T>::format` should be const-qualified

- stl/CMakeLists.txt
- stl/set_environment.bat.in
- stl/set_environment.ps1.in
These are intended for development,
because I kept forgetting to add in the arch prefix
This is a github-only change, there's nothing that will touch the internal build, and
the files are copied over outside the "output" directory.
> Add scripts to set the environment up to use just-built artifacts

- stl/inc/xstring
Towards #189
It might be worth to:
* do assign not only for pointers, but for all contiguous iterators
* apply an optimization similar to #1794 
Currently it isn't done, only pure untag dispatch.
> Untag dispatch string constructor

- tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
> Revert "Add diagnostics for sporadic failures in a `<format>` test"

- stl/inc/format
- tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
> Implement LWG-3612: Inconsistent pointer alignment in `std::format`

- stl/inc/format
- tests/libcxx/expected_results.txt
- tests/libcxx/skipped_tests.txt
- tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
> Implement LWG-3648: `format` should not print `bool` with `'c'`

- stl/src/fiopen.cpp
Also the if statements are now consistent with returning nullptr now.
> Optimize fiopen

- azure-devops/cross-build.yml
- azure-devops/run-tests.yml
- tools/scripts/print_failures.py
Fixes #2557.
* Extend `tools/scripts/print_failures.py` to understand the XML produced by `--xunit-xml-output`. This detects `.xml` versus any other extension and acts accordingly. Like the JSON codepath, success is silence. Note that a `"testcase"` element can have 0 or 1 `"failure"` elements; looping with `for failure_elem` was the most elegant way to handle this optionality. I checked `lit`'s generation logic to make sure that I wasn't missing any potential forms of output (AFAICT, both unexpected failures and unexpected passes are reported with `"failure"` here.) The CRLF replacement needed for JSON doesn't appear to be needed for XML.
* Remove dead logic - `publishArtifact` was disabled a year ago due to #1653.
* Add a new `publish` step, that will upload `test-results.xml`. This is …
> Azure Pipelines: Upload test logs as artifacts

- stl/inc/format
... for now, at least. This corrects a defect in our implementation of [[format.args]/4](https://eel.is/c++draft/format.arg#4)'s requirement that:
> ```c++
> typename Context::template formatter_type<remove_cvref_t<T>>()
>   .format(declval<T&>(), declval<Context&>())
> ```
be a valid expression. We were incorrectly stripping cv-qualifiers from `T`.
> format (and friends) should reject volatile arguments

- stl/CMakeLists.txt
Resolves #2605 
From cmake help:
Generated files are modified and their timestamp updated on subsequent cmake runs only if their content is changed.
> avoid relink `msvcp140_atomic_wait_oss.dll`

- README.md
- azure-devops/cmake-configure-build.yml
- azure-devops/provision-image.ps1
- azure-pipelines.yml
- stl/inc/bit
- stl/inc/csignal
- stl/inc/cstdio
- tests/std/tests/P1502R1_standard_library_header_units/custom_format.py
- tests/std/tests/P1502R1_standard_library_header_units/test.cpp
This updates the Azure VMSS pool to StlBuild-2022-03-17-T1445, containing March 2022's Patch Tuesday, VS 2022 17.2 Preview 2, and Python 3.10.3. (Built with PowerShell 7.2.2.)
The CMake/Ninja versions are unchanged. The README still mentions Python 3.9 as the minimum, as that's what the VS Installer still offers. This is not increasing the minimum `_MSC_VER` required as the internal build still uses an older compiler version.
Since switching to Server 2022 in #2496, we've had remarkably well-behaved checks, with virtually no stalled checks. I'd like to try removing the hack of using N - 2 for test parallelism (i.e. 30 for our 32-core VMs).
This removes a number of compiler bug workarounds:
* DevCom-1162647 (`constexpr variant` stores wrong pointer) was fixed in 17.1.
* VSO-1466711 …
> Toolset update: VS 2022 17.2 Preview 2

- stl/inc/xstring
> Untag dispatch find_first_of

- stl/inc/ranges
- tests/std/tests/P0896R4_views_empty/test.cpp
....which we somehow missed when implementing P1870R1 "`forwarding-range<T>` is too subtle".
> Even rvalue `empty_view`s are `borrowed_range`s

- .github/workflows/update-status-chart.yml
Companion PR for #2588 (will be merged simultaneously). This updates the commands needed to rebuild and commit the chart. Tested in my fork.
> Status Chart: Update GitHub Actions

- stl/inc/chrono
- tests/std/tests/P0355R7_calendars_and_time_zones_io/test.cpp
(and literals) of the format spec, even if it is sufficient to fully
specify the parsable argument.
For example "23:59" is not a valid input for "%H:%M:%S" (or for "%T").
https://eel.is/c++draft/time.parse#17.sentence-1
> If the from_stream overload fails to parse everything specified by
> the format string, or if insufficient information is parsed to specify a
> complete duration, time point, or calendrical data structure,
> setstate(ios_base::failbit) is called on the basic_istream.
> Fail time parsing if input is insufficient to supply all fields

- stl/inc/format
This is an alternative to #2596.
Fixes #2594 
I thought of simply returning a global `_Fmt_codec<char>` object in `_Get_fmt_codec<char>()`, but I think this might make `std::format` unusable in initialization of variable template instances. (The standard says that such initializations are unordered with other initializations.)
> Cache `_Fmt_codec<char, false>`

- stl/inc/stdatomic.h
Because this header needs to work in C and C++, we needed to move the check for a non-broken preprocessor outside of yvals_core, but we didn't actually skip the whole header if it failed!
This PR fixes that. In addition, it:
* Reverses the conditional logic to avoid needing to use an "else" branch
* Changes the `#if _STL_COMPILER_PREPROCESSOR` to `_STL_INTERNAL_STATIC_ASSERT(_STL_COMPILER_PREPROCESSOR);`
> <stdatomic.h>: Fix preprocessor logic

- README.md
There's a new Working Paper. Additionally, I used to use Wandbox so I mentioned it in the initial README, but as Compiler Explorer has improved (most recently and notably with MSVC execution support), I haven't used Wandbox for a couple of years. While nothing's wrong with Wandbox, I think we should drop it from the README to simplify things for readers.
> README.md: WP N4910, drop Wandbox

- .github/workflows/update-status-chart.yml
- stl/inc/charconv
- stl/inc/codecvt
- stl/inc/cwctype
- stl/inc/future
- stl/inc/shared_mutex
- stl/inc/sstream
- stl/inc/variant
- stl/inc/vector
- stl/inc/xmemory
- stl/inc/xtree
- tests/libcxx/expected_results.txt
Some of these are things I've noticed while reading every line of the STL's headers for Standard Library Modules, but they aren't blocking anything.
* In `tests/libcxx/expected_results.txt`, change 2 tests from `FAIL` to `SKIPPED`. This avoids unexpected passes when running `set_environment` before running the tests. (Because `set_environment` puts the freshly-built STL on the `INCLUDE` path, Clang suppresses warnings from those "system headers", so if tests are expected to `FAIL` due to such warnings, they will instead unexpectedly pass.)
+ This is a quality-of-life improvement for myself, as I always run `set_environment`.
* Update `.github/workflows/update-status-chart.yml` as new versions of `actions/checkout` and `actions/setup-node` are now available. Also update `node-version` (as …
> More various cleanups

- stl/inc/charconv
- stl/inc/compare
- stl/inc/exception
- stl/inc/filesystem
- stl/inc/functional
- stl/inc/iosfwd
- stl/inc/iterator
- stl/inc/ranges
- stl/inc/span
- stl/inc/stop_token
- stl/inc/system_error
- stl/inc/valarray
- stl/inc/xcharconv.h
- stl/inc/xutility
Thanks to @MattStephanson in #2208, we now have `_NODISCARD_FRIEND`, a centralized workaround for a bug that affects CUDA.
In theory, we could restrict usage of `_NODISCARD_FRIEND` to C++14 (and possibly C++17 - I'm not sure if the newer CUDA versions that accept C++17 are affected by this bug). However, we've already accumulated some usage in C++20 code: https://github.com/microsoft/STL/blob/27877181dc50fc5f0dc9d679703437eb105e2b9f/stl/inc/__msvc_int128.hpp#L298
As the macro is exactly the same number of characters, it seems simpler to use it everywhere.
This should fix DevCom-1555597 / VSO-1426765 "VS2019 standard exception headers: warning C5240: 'nodiscard': attribute is ignored in this syntactic position".
> Use `_NODISCARD_FRIEND` everywhere

- stl/inc/charconv
We have a comment explaining how `_Big_integer_flt` accesses only `[0, _Myused)` and tolerates all other elements being garbage:
https://github.com/microsoft/STL/blob/27877181dc50fc5f0dc9d679703437eb105e2b9f/stl/inc/charconv#L366-L369
Now, look at the following code at the end of `_Divide`:
https://github.com/microsoft/STL/blob/27877181dc50fc5f0dc9d679703437eb105e2b9f/stl/inc/charconv#L1034-L1045
I claim that the first loop is unnecessary. It's zeroing out elements in the range `[_Max_numerator_element_index + 1, original _Myused)`. Then, the following code updates `_Myused` to *at most* `_Max_numerator_element_index + 1`. (Possibly less, if we discover that there are more zero elements at the end of this range.)
According to `_Big_integer_flt`'s invariants, the `_Myused` update already …
> `<charconv>`: `_Divide` can trim `_Big_integer_flt` more efficiently

- stl/inc/xutility
- tests/std/include/instantiate_algorithms.hpp
- tests/std/tests/Dev11_0253803_debug_pointer/test.cpp
Fixes #2626.
On Discord, @CaseyCarter additionally explained why these don't exist:
> The only reason to use `meow_backward` over `meow` is to avoid aliasing issues when the head of the destination overlaps the tail of the source. Since the parallel algorithms all forbid overlapping, parallel `meow_backward` would be useless.
> Remove parallel `copy_backward()` and `move_backward()`

- stl/inc/iterator
- stl/inc/ranges
- tests/std/tests/P0896R4_common_iterator/test.cpp
- tests/std/tests/P0896R4_views_join/test.cpp
- tests/std/tests/P0896R4_views_single/test.cpp
This implements workaround for LLVM-46269 ("Only first destructor is considered when constraints are used").
If the constrained (and defaulted) destructor comes first, clang-cl uses it unconditionally, even if its constraints are not satisfied. This leads to an error when the defaulted destructor is implicitly deleted (due to a non-trivially-destructible member).
By moving the constrained destructor after the unconstrained one (which is always valid, but is non-trivial), this patch sidesteps the abovementioned error.
This is suboptimal, because this makes the affected types never trivially destructible when compiled with clang-cl. A perfect fix would need to use something akin to the existing [`_Optional_destruct_base`], which I assume that we want to avoid.
[`_Optional_destruct_base`]: …
> Implement workaround for LLVM-46269 by ensuring that constrained destructor appears after the unconstrained one

- .github/workflows/compile-typescript.yml
- README.md
- index.html
- package-lock.json
- package.json
- src/status_chart.ts
- src/weekly_table.ts
* Weekly updates.
* Update dependencies:
+ actions/checkout v3, actions/setup-node v3, Node 17.8.0.
- Tested in my fork, also takes effect in the checks here.
+ `index.html`: Use luxon 2.3.1.
- I missed this while working on #2588. The dependency versions in `index.html` (which are used in the browser) should match the versions in `package.json` (which are used when type-checking and building the chart).
+ `npm update`
+ `npm install [dependencies]@latest`
* Adjust axes:
+ Increase PR Age max to 600.
+ Increase time units: `timeframe_all` to year, `timeframe_2021` to quarter.
* DROP BEFORE MERGING: Regen `built/status_chart.mjs`.
+ This commit is for the live preview; I will drop it to avoid merge conflicts.
:chart_with_downwards_trend: Live preview: …
> Status Chart: Weekly updates, increase time units

- stl/CMakeLists.txt
- stl/msbuild/stl_base/msvcp.settings.targets
- stl/src/ppltasks.cpp
With the adoption of WinUI3 (via Windows App SDK), Desktop Xaml apps are now supported. However, ppltasks client code in a Desktop app would fail to capture the apartment context for continuation callbacks, by default (globally, without needing to pass an explicit task_continuation_context to every continuation). This PR fixes that bug.
For C++/CX client code (which may be in process of migration to Desktop C++/WinRT code), no other changes are needed.
For ISO C++ client code, this fix builds on work to recover ppltasks functionality lost during the UCRT migration (see https://www.osgwiki.com/wiki/Universal_CRT#PPL_Tasks  for details), which requires adding
`#define PPL_TASK_CONTEXT_ERROR_CONTROL 1 `
to opt into using context callbacks and error reporting (UWP behavior).
Note that C++/CLI …
> Coordinated fix for capturing continuation context for tasks in Desktop apps

- CMakeLists.txt
- README.md
- azure-devops/provision-image.ps1
- azure-pipelines.yml
- stl/inc/yvals_core.h
- tests/libcxx/expected_results.txt
- tests/libcxx/skipped_tests.txt
- tests/std/tests/P0784R7_library_support_for_more_constexpr_containers/test.cpp
- tests/std/tests/P1502R1_standard_library_header_units/test.cpp
* Unskip `three_way_comparable.compile.pass.cpp` as it's now passing with 17.2 Preview 3.
* Add workarounds to `P1502R1_standard_library_header_units` for VSO-1496084 "Standard Library Header Units: Splitting `<chrono>` emits fatal error C1116: unrecoverable error importing header unit '`<chrono>`'"
+ This has already been fixed in 17.3 Preview 2, so we can run the affected code when `defined(_MSVC_INTERNAL_TESTING)`.
+ It also repros only for separate header units, so we can run the affected code when `defined(TEST_TOPO_SORT)` (deduplicated header units).
* Remove workaround for VSO-1049320 "conditional operator errors" in `P0784R7_library_support_for_more_constexpr_containers`.
* Toolset update:
+ 17.2 Preview 3 (now required, as the internal toolset has also been updated).
+ Python …
> Toolset update: VS 2022 17.2 Preview 3

- stl/inc/chrono
- tests/std/tests/P0355R7_calendars_and_time_zones_io/test.cpp
> fix `treat_as_floating_point_v<_DurationType>`

- stl/inc/bit
Fix countl_zero on arm64 to properly subtract the zeros resulting from widening.
Because of a lack of test coverage, we forgot that `_CountLeadingZeros` takes `unsigned long`, and thus for types shorter than that we need to subtract the extra zeros from the result.
> `<bit>`: fix `countl_zero` on arm64

- stl/inc/system_error
- stl/inc/yvals_core.h
- stl/src/excptptr.cpp
Define `_MSVC_MEOW` macro in `<yvals_core.h>`for each `[[msvc::meow]]` custom attribute with surrounding push_macro/pop_macro guards.
Fixes #2645
> Guard use of custom attributes against macroization

- stl/inc/memory
- stl/inc/xutility
- stl/inc/yvals_core.h
Which is meaningless now, but will eventually become `[[msvc::constexpr]]` when VCRuntime changes (and the corresponding compiler) ship.
This mirrors internal MSVC-PR-391437.
> Annotate some functions `_MSVC_CONSTEXPR`

- tests/std/tests/P0896R4_ranges_alg_remove_copy/test.cpp
- tests/std/tests/P0896R4_ranges_alg_remove_copy_if/test.cpp
By making the stateful lambda a namespace-scope function object (at the suggestion of the FE team) and reducing the combinatorics of the test matrix of range properties.
> Reduce memory consumption of two ranges tests

- stl/inc/xstring
Towards #189
Same as #2479, nothing to see here
> Untag dispatch `<xstring>`

- stl/inc/execution
> Untag dispatch `<execution>`

- stl/inc/xloctime
- tests/std/tests/Dev11_0836436_get_time/test.cpp
Fixes #2618.
ABI note: this replaces a call to the separately-compiled function `_Getint` with a call to the header-only function `_Getint_v2`. The two functions are virtually identical, so `_Getint` is rewritten as a wrapper that discards the number of digits read. I think both of these changes are safe, but want to highlight them for closer scrutiny.
> `<xloctime>`: apply two-digit year logic only if exactly two digits are read

- stl/src/syserror_import_lib.cpp
Fixes #2451 
```c++
type main.cpp
#include <clocale>
#include <Windows.h>
int main() {
setlocale(LC_ALL, "");
auto file_handle(CreateFile(
L"D:\\non_exist_file.txt", GENERIC_READ, FILE_SHARE_READ, NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL));
if (file_handle == INVALID_HANDLE_VALUE) {
const auto error_code = GetLastError();
std::string errmsg    = std::system_category().message(error_code); // Sometimes the string only contains "???"
std::cout << errmsg << '\n';
}
}
```
If we have different “user language id” and “system language id” (this is how we can reach it: https://github.com/microsoft/STL/issues/2451#issuecomment-1107744166) FormatMessageA can choose “user language id” instead of “system language id” if we pass 0.
Before
```
>main
??????? …
```
> <system_error>: explicitly pass the system locale ID for system_category messages

- stl/inc/complex
- stl/inc/cstddef
- stl/inc/exception
- stl/inc/filesystem
- stl/inc/memory
- stl/inc/ostream
- stl/inc/random
- stl/inc/string
- stl/inc/type_traits
- stl/inc/utility
- stl/inc/xutility
* Detach comments.
+ This isn't attempting to be a global cleanup. Many of these will prevent the addition of `_EXPORT_STD` from causing wrapping, some fix wrapping that's already bad, some are for local consistency.
* `<string>`: Remove unnecessary comments for `to_string()`, `to_wstring()`, and `stoi()` etc. - they're just repeating the function names.
+ A few (like `stold()`) would also cause wrapping with `_EXPORT_STD`.
* `<cstddef>`: Remove SHOUTY RELICS and unnecessary comments, detach remaining comments.
* `<type_traits>`: Comment `_Refwrap_ctor_fun` as `// not defined`.
* `<random>`: Remove extra newline.
* `<random>`: Unwrap string literals for assertions.
* `<xutility>`: Shrink `clang-format off` region, add newline after declaring `ranges::less`.
> Cleanups 1: Comments and formatting

- stl/inc/chrono
- stl/inc/format
- stl/inc/future
- stl/inc/system_error
- stl/src/future.cpp
* `<future>`: Bypass `_Throw_future_error`, `_Rethrow_future_exception`.
+ We don't need separately compiled functions for this (I believe we were imitating older code that was avoiding header circularity issues). We can add a header-only `_Throw_future_error2()` that's more convenient to call directly with a `future_errc`, and we can call `_STD rethrow_exception()` directly.
+ `future.cpp`: Mark the unused functions as preserved for bincompat. (No redist change.)
* `<chrono>`: Add `_Throw_nonexistent_local_time()`, `_Throw_ambiguous_local_time()`. We need extra parens for the macro, due to direct-list-init.
* `<format>`, `<chrono>`: Add `_Throw_format_error()`.
* Change `"charT"` to either `"char"` or `"wchar_t"` when throwing `format_error`.
* Rename `meow_errc _Errno` to `_Ec`.
In …
> Cleanups 2: Exception handling

- stl/inc/array
- stl/inc/chrono
- stl/inc/complex
- stl/inc/exception
- stl/inc/execution
- stl/inc/future
- stl/inc/memory_resource
- stl/inc/scoped_allocator
- stl/inc/typeinfo
- stl/inc/xlocbuf
- stl/inc/xmemory
- stl/src/tzdb.cpp
- tests/std/tests/P0753R2_manipulators_for_cpp_synchronized_buffered_ostream/test.cpp
- tests/std/tests/VSO_0000000_initialize_everything/test.cpp
* `<complex>`: Fuse `#if !_HAS_CXX20` sections.
* `<xlocbuf>`: `wbuffer_convert` and `wstring_convert` were using implicit `private:`.
* `<scoped_allocator>`: `scoped_allocator_adaptor` was using implicit `private:`.
* `<exception>`: Remove repeated `protected:`.
* `<typeinfo>`: Mark `_Small_object_num_ptrs` as `_INLINE_VAR`.
* `<xmemory>`: Mark constants as `_INLINE_VAR`.
+ We conventionally mark constants as `_INLINE_VAR` (or `inline` in C++17+) even when there's no real risk of odr-using them.
* `<xmemory>`: Use `_STL_INTERNAL_STATIC_ASSERT` for `_Big_allocation_alignment`.
+ This is a constant that we control, so there's no reason to evaluate these `static_assert`s for user code.
* `<future>`: Mark `_Future_error_map` as `_NODISCARD`.
* `<array>`: Extract `_Array_const_iterator` …
> Cleanups 3: Simple changes

- stl/inc/iomanip
* Avoid repeating types in `quoted()` by using `return {m,e,o,w};`.
+ The types are verbose, and the constructors are implicit. I considered this slightly more convenient/readable than returning `auto`.
* Use `char_traits::length()` instead of a raw loop in `quoted()`.
+ Please verify my claim that this does not change runtime behavior (we're getting the same answer, number of characters before the null terminator).
+ I think we might have thought that `char_traits` was unavailable, but it is *totally* available here, just through an epic-length chain of dependencies. Using `char_traits` is not only simpler, it has the potential to be faster for `char` (especially) and `wchar_t`.
> Cleanups 4: `quoted()`

- stl/inc/scoped_allocator
This combines 2 namespace-scope functions into the 1 function depicted by [[scoped.adaptor.operators]](https://wg21.link/scoped.adaptor.operators).
Noticed while marking functions as `export`. Works towards #189.
> Cleanups 5: `if constexpr` for `<scoped_allocator>` `operator==`

- stl/inc/fstream
- stl/inc/iostream
- stl/inc/xlocnum
* `<fstream>`, `<xlocnum>`: `_Fiopen()` and the `_Stofx()` family don't need to be declared as `extern` (that's the default, and we don't say `extern` when declaring other separately compiled functions).
+ Noticed while implementing Standard Library Modules, where I'll have to add `extern "C++"` which is different.
* `<iostream>`: Prevent `_Winit` from being seen by users.
+ Nothing else mentions this, so we don't need to declare it for users. We still need to export it to preserve bincompat, but I believe that it is completely dead (nothing constructs an object of this type, nor the macroized `_UShinit`), so I'm adding a comment that it appears to be unused (and thus can be completely removed during vNext).
> Cleanups 6: iostreams: drop `extern`, hide `_Winit`

- stl/inc/new
This removes the (very strange) guard `#if !defined(_INC_NEW) || !defined(_MSC_EXTENSIONS)` around the `new_handler` typedef.
It appears that this guard may have been intended to avoid duplicate typedefs because `<new.h>` can include `<new>` (weirdly). However, duplicate typedefs have always been possible - if `<new>` was included first, `!defined(_INC_NEW)` would be true, so `<new>` would emit `new_handler`. Then if `<new.h>` is included, with the default of `/Ze`, `#if defined _MSC_EXTENSIONS && !defined _CORECRT_BUILD` would be true, so it would also emit `new_handler` within `namespace std`. (See `C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\ucrt\new.h`.) There's no conflict as long as the typedefs are identical.
With this removal, there is no conflict regardless of …
> Cleanups 7: Unnecessary guard around `new_handler`

- tests/libcxx/expected_results.txt
- tests/libcxx/skipped_tests.txt
DevCom-1628714 is dead; long live DevCom-10026599!
> Update reason for libc++ test failure

- stl/inc/concepts
- stl/inc/type_traits
- stl/inc/utility
- stl/inc/xutility
- tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Fixes #2683.
The (minor) main difficulty here is that the vectorized machinery was defined in `<xutility>`, but `swap()` for arrays is defined in its parent header `<utility>`, and `ranges::swap` is defined in `<concepts>`. To solve this, I'm moving the definition of `_USE_STD_VECTOR_ALGORITHMS` up to `<type_traits>` (unchanged), then extracting only the declaration of `__std_swap_ranges_trivially_swappable_noalias()`, with a comment directing the reader to `<xutility>`. (Any merge conflicts with vectorization PRs in flight should be trivial to resolve.)
Because `<utility>` and `<concepts>` are "core" headers, I'm also adding a comment that if users want to use them without linking to the STL, they might need to disable our use of vectorized algorithms.
Since we've already extensively …
> Vectorize `swap` and `ranges::swap` for arrays

- stl/inc/atomic
This mirrors Victor Tong's internal MSVC-PR-396294 "Fix missing ARM64EC ifdefs in atomic header" (as of Iteration 3, with fixed `#endif` comments).
It fixes `atomic_thread_fence()` which wasn't emitting a fence, and also fixes `_Atomic_storage<_Ty, 8>::store()`.
> `<atomic>`: Fix missing ARM64EC ifdefs

- stl/inc/functional
> Reduce _Invoker_ret specializations with if constexpr

- stl/inc/random
> Untag dispatch `<random>`

- stl/inc/vector
> Untag dispatch vector<👻>::_Insert

- stl/inc/cmath
- tests/std/test.lst
- tests/std/tests/LWG3234_math_special_overloads/env.lst
- tests/std/tests/LWG3234_math_special_overloads/test.cpp
Fixes #910.
IIUC LWG-3234 will be resolved by the recently approved paper WG21-P1467, so perhaps it is not speculative to implement the resolution.
No separated `float`/`long double` overloads are added according to #1335. I've filed LWG-3693 for this. I'm not sure whether non-template `double` overloads can be removed.
I'm also strengthening exception specifications of math special functions as the underlying operations only call `noexcept` functions, and updating comments to reference WG21-N4910.
> Speculatively implement LWG-3234: Sufficient Additional Special Math Overloads

- CMakeLists.txt
I am looking at the CMake build, and was investigating whether it was worth it to remove `/Os` from the release flags. I do not believe it is, but maybe if the performance numbers are _staggering_ it could be.
> [CMakeLists.txt] add more information to the `/Os` transition comment

- stl/inc/yvals_core.h
C++98's `unexpected()` was removed by C++17, then C++23 reused the identifier for `<expected>`'s `unexpected<E>` (being implemented in #2643).
We support escape hatches for restoring Standard-removed machinery, but we need to avoid this conflict. Instead of limiting what C++23 provides, we should simply disable this escape hatch when it conflicts with the Standard. (Note that C++98 `unexpected()` and its related functions weren't very useful, *and* MSVC never properly implemented them, thus this is mostly relevant for library test suites. It's a very different situation than `auto_ptr`, for example.)
This PR will be paired with internal changes to VCRuntime, as its `<eh.h>` defines `unexpected()` et al. in the global scope, and we need to prevent that conflict too. We can complete this PR …
> Block C++98 `unexpected()` from being restored in C++23 mode

- stl/msbuild/stl_1/msvcp_1.settings.targets
- stl/msbuild/stl_2/msvcp_2.settings.targets
- stl/msbuild/stl_atomic_wait/msvcp_atomic_wait.settings.targets
- stl/msbuild/stl_base/msvcp.settings.targets
- stl/msbuild/stl_codecvt_ids/msvcp_codecvt_ids.settings.targets
Doesn't affect the OSS build at all. (I don't think anything here is worth Changlelogging, shout if you disagree.)
Mirror of MSVC-PR-398691
> Remove unnecessary copy of _clr DLLS from internal build

- stl/debugger/STL.natvis
Fixes #2688 
It works, but perhaps there is an option without the duplication...
> STL.natvis: add specializations for `shared_ptr<void>`, `weak_ptr<void>`, and `unique_ptr<void, deleter>`

- stl/inc/ranges
- tests/libcxx/usual_matrix.lst
- tests/std/tests/P0896R4_views_join/test.cpp
As pointed out in LWG-3698, `join_view` is currently broken for "stashing iterators" (iterators that return a reference to a member object). The issue mentions that `join_view` would need to store the outer iterator in a non-propagating-cache for input ranges.
The fix might change the layout of `join_view` (and of its iterator type, if we don't want to store a redundant outer iterator). So I believe that it is useful to flag the affected uses of `join_view`.
This requires users to define a macro if they don't depend on the ABI of `join_view` and want to use `join_view` for input ranges. I hope it's not too much of a problem.
> `<ranges>`: Temporarily disable `join_view` for non-`forward_range`s, pending resolution of LWG-3698

- CMakeLists.txt
Toolset update #2714 began requiring the Windows 11 SDK 22000 to build and test the STL. Although it's mentioned in the README, if a contributor misses this dependency, the resulting error message is incomprehensible (as @miscco discovered). @strega-nil-ms suggested adding a build check.
Fortunately, the Windows SDK provides a macro to identify itself, `WDK_NTDDI_VERSION`. (Unlike `NTDDI_VERSION`, this is not subject to user overrides.) It's present in the default WinSDK, where it was set to "Vibranium", whereas in the latest WinSDK, it's set to "Cobalt":
* `C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\shared\sdkddkver.h`
+ `#define WDK_NTDDI_VERSION                   NTDDI_WIN10_VB /* ABRACADABRA_WIN10_VB */`
* `C:\Program Files (x86)\Windows …
> CMakeLists.txt: Check the Windows SDK version

- index.html
- package-lock.json
- package.json
- src/weekly_table.ts
As usual, this updates dependencies, including es-module-shims 1.5.5 and luxon 2.4.0 for the browser.
===
> Status Chart: Weekly updates

- stl/CMakeLists.txt
- stl/msbuild/stl_base/stl.files.settings.targets
- stl/src/alias.asm
- stl/src/alias_init_once_begin_initialize.asm
- stl/src/alias_init_once_complete.asm
Turns out the thing about requiring <> around the parameters of the ALIAS directive was for real. If they are actually needed, I think it's impossible to use macros to generate that directive, so I have removed the macros and duplicated the directives.
This actually makes the file somewhat simpler and easier to read, I think it was overly clever and compressed before.
> Avoid an assertion failure in alias.asm

- stl/CMakeLists.txt
- stl/inc/__msvc_all_public_headers.hpp
- stl/inc/__msvc_iter_core.hpp
- stl/inc/header-units.json
- stl/inc/tuple
- stl/inc/utility
- stl/inc/xutility
May be related to #1405.
I've found that `<tuple>` is nearly a core header in MSVC STL now, except that it requires `allocator_arg` and `uses_allocator`. IIUC neither `allocator_arg` nor `uses_allocator` needs any non-core mechanism, so I'm moving them from `<xutility>` to `<utility>`, and making `<tuple>` a core header.
----
In order to keep `apply` and `make_from_tuple` working with `subrange`, I decided to separate the needed parts of `<xutility>` into a new internal header `<__msvc_iter_core.hpp>`.
The intent is providing forward declaration of `subrange` and the `get` overloads, while avoiding separate the forward declaration of `iterator_traits` and its definition into different headers.
Internal-only changes seem required as in #2518.
> `<tuple>`: Becomes a core header

- stl/inc/xlocale
> codecvt: no conversion for all char-like types of size 1.

- stl/inc/filesystem
- stl/inc/xstring
- tests/libcxx/expected_results.txt
- tests/libcxx/skipped_tests.txt
Fixes #757. Perhaps libcxx tests are enough.
I also move `_Is_EcharT` to `<xstring>` because I think its usage may be more general.
> `<xstring>`: Restrict enabled `hash` specializations as required by the standard

- stl/CMakeLists.txt
I got annoyed at the continual `Assembling:` lines
cc @barcharcraz
this shouldn't change output at all, but it will make it so we only build the asm files once.
it is also extremely unimportant.
> [aliasobj] just build the alias objects once

- azure-devops/create-vmss.ps1
- azure-devops/provision-image.ps1
- azure-pipelines.yml
We are required to move our Azure Virtual Machine Scale Set to another region. We've previously obtained quota in northeurope. (The STL's PR/CI aren't latency-sensitive, so the region doesn't matter to us.)
> Toolset update: Move to northeurope

- stl/msbuild/stl_1/dirs.proj
- stl/msbuild/stl_1/md/dirs.proj
- stl/msbuild/stl_1/msvcp_1.settings.targets
- stl/msbuild/stl_1/xmd/dirs.proj
- stl/msbuild/stl_2/dirs.proj
- stl/msbuild/stl_2/md/dirs.proj
- stl/msbuild/stl_2/msvcp_2.settings.targets
- stl/msbuild/stl_2/xmd/dirs.proj
- stl/msbuild/stl_asan/dirs.proj
- stl/msbuild/stl_atomic_wait/dirs.proj
- stl/msbuild/stl_atomic_wait/md/dirs.proj
- stl/msbuild/stl_atomic_wait/msvcp_atomic_wait.settings.targets
- stl/msbuild/stl_atomic_wait/xmd/dirs.proj
- stl/msbuild/stl_base/dirs.proj
- stl/msbuild/stl_base/md/dirs.proj
- stl/msbuild/stl_base/msvcp.settings.targets
- stl/msbuild/stl_base/mt/dirs.proj
- stl/msbuild/stl_base/mt1/dirs.proj
- stl/msbuild/stl_base/xmd/dirs.proj
- stl/msbuild/stl_base/xmt/dirs.proj
- stl/msbuild/stl_base/xmt0/dirs.proj
- stl/msbuild/stl_base/xmt1/dirs.proj
- stl/msbuild/stl_codecvt_ids/dirs.proj
- stl/msbuild/stl_codecvt_ids/md/dirs.proj
- stl/msbuild/stl_codecvt_ids/msvcp_codecvt_ids.settings.targets
- stl/msbuild/stl_codecvt_ids/xmd/dirs.proj
- stl/msbuild/stl_post/dirs.proj
- stl/msbuild/stl_post/md/dirs.proj
- stl/msbuild/stl_post/msvcp_post.settings.targets
- stl/msbuild/stl_post/xmd/dirs.proj
This mirrors the `stl/msbuild` changes from Andrew Dean's internal MSVC-PR-388582 "Build Improvements" (as of iteration 19). This doesn't affect the GitHub build at all.
> Mirror MSBuild changes

- stl/inc/utility
Towards #189.
Error message is emitted by `tuple_element_t` if `_Idx >= 2`, so it is not needed to be repeated in `get`.
> Untag dispatch `get` for `pair`

- stl/inc/syncstream
- tests/std/test.lst
- tests/std/tests/GH_002760_syncstream_memory_leak/env.lst
- tests/std/tests/GH_002760_syncstream_memory_leak/test.cpp
- tests/std/tests/usual_20_matrix.lst
> `<syncstream>`: fix `std::osyncstream` memory leak

- stl/inc/yvals_core.h
>  <yvals_core.h>: Update _MSVC_STL_UPDATE to June 2022

- stl/inc/format
- tests/std/tests/P0645R10_text_formatting_args/test.cpp
- tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp
- tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
Fixes #2765
Although @cpplearner wrote everything in the issue, I was able to write  
```c++
typename _Format_arg_traits<_FormatContext>::template _Storage_type<_Ty>
``` 
correctly only the third time :)
> fix `format` a `long` value with `formatter`

- stl/inc/xhash
The prior implementation that used `vector` directly had bugs that sometimes result in differing size and capacity. Since old and new code may link, we need to tolerate this condition.
Fixes DevCom-1190124/VSO-1220461/AB#1220461
> Don't assume that `_Hash_vec`'s size and capacity are always equal

- CMakeLists.txt
- README.md
- azure-devops/provision-image.ps1
- azure-pipelines.yml
- stl/inc/format
- stl/inc/vector
- stl/inc/xmemory
- stl/inc/yvals_core.h
- tests/std/include/timezone_data.hpp
- tests/std/tests/GH_000639_nvcc_include_all/env.lst
- tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp
- tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
- tests/std/tests/P0645R10_text_formatting_utf8/test.cpp
- tests/std/tests/P1502R1_standard_library_header_units/test.cpp
- tools/CMakeLists.txt
- tools/format/CMakeLists.txt
- tools/validate/CMakeLists.txt
This updates the toolset to:
* VS 2022 17.3 Preview 2.
+ Required in the README, but not in `<yvals_core.h>` because the internal build still uses 19.32.
* CMake 3.23.
+ Required in the README and `CMakeLists.txt`.
* Python 3.10.5.
+ We still require Python 3.9 because the VS Installer still has 3.9.7.
* CUDA 11.6.0.
+ `azure-devops/provision-image.ps1` now installs all CUDA features, which is much easier than enumerating almost all of them.
+ Required in `<yvals_core.h>`.
- CUDA 11.6.0 was the first release that officially supported VS 2022, so this aligns our support.
- Approved by our boss and double boss, who are awesome! :smile_cat:
Then we can remove workarounds:
* `tests/std/tests/GH_000639_nvcc_include_all/env.lst`
+ Drop `--allow-unsupported-compiler`, now that we're using a …
> Toolset update: VS 2022 17.3 Preview 2, CUDA 11.6.0

- stl/inc/chrono
- tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp
Fixes #2761
I'm not sure if it's correct.
C++ standard is unclear: https://eel.is/c++draft/time.format#6
But cppreference says that `%x` is supported for [year_month_day](https://en.cppreference.com/w/cpp/chrono/year_month_day/formatter), [year_month_day_last](https://en.cppreference.com/w/cpp/chrono/year_month_day_last/formatter), [year_month_weekday](https://en.cppreference.com/w/cpp/chrono/year_month_weekday/formatter) and [year_month_weekday_last](https://en.cppreference.com/w/cpp/chrono/year_month_weekday_last/formatter)
> allow `%x` for formatting `year_month_day`

- stl/inc/xhash
- tests/std/test.lst
- tests/std/tests/GH_002789_Hash_vec_Tidy/env.lst
- tests/std/tests/GH_002789_Hash_vec_Tidy/test.cpp
... since we probably didn't get `nullptr` from an allocator, and user-defined allocators aren't required to tolerate dellocating `nullptr`.
Fixes #2789.
> Don't deallocate nullptr in _Hash_vec::_Tidy

- stl/inc/functional
- stl/inc/regex
- stl/inc/vector
- stl/inc/xstring
@cdacamar explained why he's implementing a new compiler warning:
> I have been tightening up c1xx's modules implementation by making the compiler more strict and correct when it comes to assigning out linkage to entities emitted into associated .objs.
This warning will complain about non-`inline` constants in headers. We're *almost* completely consistent about using `inline` in C++17-and-later (or `_INLINE_VAR` in potentially-C++14), but Cameron found our inconsistent occurrences:
```
C:\msvc\binaries\x86chk\inc\vector(2113): warning C5260: the constant variable 'std::_VBITS' has internal linkage in an included header file context, but external linkage in imported header unit context; consider declaring it 'inline' as well if it will be shared across translation units, or 'static' to …
```
> Mark constants as `_INLINE_VAR constexpr`.

- azure-devops/cross-build.yml
- azure-devops/native-build-test.yml
Fixes #2794, which silently degraded our test coverage.
Thanks to @CaseyCarter for investigating the bizarre symptoms and finding [this documented option](https://llvm.org/docs/CommandGuide/lit.html#cmdoption-lit-order).
> Fix non-deterministic test sharding with `--order=lexical`

- stl/inc/xstring
- tests/std/tests/P0980R1_constexpr_strings/test.cpp
In #1502 we found that it should be possible to enable SSO, but we wanted to get constexpr string in.
It turns out that we were not that far off. I verified that all test compile fine with clang-12. That said, it seems I uncovered 2 distinct MSVC bugs:
1. The test for basic_string::operator-> is failing. MSVC complains about an uninitialized symbol. Clang is happy. I have no idea what is wrong there.
2. Clang complained heavily about switching back to SSO form. It turns out that previously we were directly constructing the sentinel in the first slot of the SSO array. However, we never switched from the `_Ptr` to the `_Buf` member. So I believe clang is correct here and MSVC should recognize that `_Buf`s lifetime did not yet start
> Implement SSO for constexpr string

- stl/src/atomic_wait.cpp
Minimum scope of #2755 - based on https://github.com/microsoft/STL/issues/2755#issuecomment-1145467753 suggestion.
Reduces size of x64 `msvcp140_atomic_wait_oss.dll` from 44.5 KB to 28.0 KB - did not investigate exactly why, but expect reduction of relocation table and initialized data segment.
Full scope of #2755 as initially suggested can be implemented, but there are some complexities:
* Fallback path
* Safe de-initialization
Using lazy initialization for list head
* Single linked list does not look like a good idea, as there's no efficient removal of the current waiter from list
* Double linked list that is not head is feasible, but it is more complex that the circular one, and, as a consequence, will take more ops at runtime
> Atomic wait: zero-initialize wait list head

- stl/inc/yvals_core.h
- tests/libcxx/expected_results.txt
- tests/libcxx/skipped_tests.txt
- tests/std/tests/P2273R3_constexpr_unique_ptr/test.compile.pass.cpp
- tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Fixes #1972.
I updated `<vcruntime_typeinfo.h>` in internal MSVC-PR-392482, which we just picked up in toolset update #2791. All that remains is to add it to our comment-list of implemented features, add the feature-test macro, and add some test coverage (which doesn't have to be especially thorough; the compiler is doing all of the hard work here, and the library's involvement is just a pointer comparison).
> P1328R1 `constexpr` `type_info::operator==()`

- stl/src/fiopen.cpp
- stl/src/locale.cpp
- stl/src/locale0.cpp
- stl/src/ushcerr.cpp
- stl/src/ushcin.cpp
- stl/src/ushclog.cpp
- stl/src/ushcout.cpp
- stl/src/ushiostr.cpp
- stl/src/wlocale.cpp
This is structured as a series of commits for easier reviewing.
* `stl/src` is always built with real `wchar_t`, so we don't need to test `#ifdef _NATIVE_WCHAR_T_DEFINED`.
* `ushMEOW.cpp` cleanups:
+ Only the `ushMEOW.cpp` files `#define wistream`, so we don't need to test `#ifndef wistream`.
+ Each `ushMEOW.cpp` only needs to macroize its corresponding `_Init_wMEOW` and `init_wMEOW`.
+ Consistency: `ushMEOW.cpp` should `#define _Winit` last (as `ushcerr.cpp` already did).
+ Each `wMEOW.cpp` already includes `<iostream>`, so `ushMEOW.cpp` doesn't need to do so explicitly.
+ Fix copy-pasted comments in `ushMEOW.cpp` (only `ushcerr.cpp` was correct).
* `fiopen.cpp` cleanups:
+ `fiopen.cpp` doesn't need to include `<Windows.h>` at all.
+ Move `fiopen.cpp` helpers into an unnamed namespace.
- …
> Various source cleanups, especially `ushMEOW.cpp` and `fiopen.cpp`

- stl/inc/array
- stl/inc/chrono
- stl/inc/complex
- stl/inc/cvt/ebcdic
- stl/inc/cvt/one_one
- stl/inc/cvt/utf16
- stl/inc/cvt/utf8
- stl/inc/cvt/utf8_utf16
- stl/inc/cvt/xjis
- stl/inc/cvt/xtwo_byte
- stl/inc/deque
- stl/inc/experimental/filesystem
- stl/inc/filesystem
- stl/inc/format
- stl/inc/forward_list
- stl/inc/future
- stl/inc/list
- stl/inc/locale
- stl/inc/memory_resource
- stl/inc/regex
- stl/inc/system_error
- stl/inc/tuple
- stl/inc/xlocale
- stl/inc/xlocmon
- stl/inc/xlocnum
- stl/inc/xstring
* `<deque>`, `<forward_list>`, `<list>`: Use `nullptr` instead of `_Mapptr()` and `_Nodeptr()`.
+ At first, I was going to change these empty parens to empty braces for consistency with our modern conventions (braces make it clear when we're constructing a temporary instead of calling a function), but `nullptr` is even clearer.
+ This is guaranteed to work because they're "nullable pointers", and we're already using `nullptr` with these types:
https://github.com/microsoft/STL/blob/ea32e86deed6e8a8cd6116dc275e358a901d2b50/stl/inc/deque#L771
https://github.com/microsoft/STL/blob/ea32e86deed6e8a8cd6116dc275e358a901d2b50/stl/inc/forward_list#L841
https://github.com/microsoft/STL/blob/ea32e86deed6e8a8cd6116dc275e358a901d2b50/stl/inc/list#L445
* `<array>`, `<tuple>`: We don't need `return` …
> Various header cleanups

- stl/inc/optional
- stl/inc/tuple
- stl/inc/utility
- stl/inc/yvals_core.h
Fixes #1301. This is possible now that toolset update #2791 requires CUDA 11.6.0.
Thanks to @AlexGuteniev for verifying that CUDA 11.6.0 supports this, and to @cpplearner for verifying the Intel compiler's behavior. :heart_eyes_cat:
This doesn't affect our primary compilers (MSVC, Clang, EDG IntelliSense), as we were already using the Future Technology codepath for them. It's a massive maintainability improvement, and also a throughput improvement for CUDA.
In `<yvals_core.h>`, I opted to keep the `#if !_HAS_CXX20` order, despite our usual preference to avoid negated tests. This is consistent with `#if !_HAS_CXX17` immediately above, and in this case I think the "if we don't have C++20, then suppress the warning" phrasing is easier to understand than the reverse.
> Use conditional `explicit` unconditionally

- stl/inc/array
- stl/inc/chrono
- stl/inc/deque
- stl/inc/iomanip
- stl/inc/vector
- stl/inc/xstring
This changes all of the STL's operators that are required to exist, but that aren't required to be namespace-scope functions, into "hidden friends". (For example, `n + vector::iterator`.)
Hidden friends are great in two different ways:
* They improve **compiler throughput**, because they don't pollute unqualified name lookup. Only argument-dependent lookup finds them when they're needed.
* They automatically work with **named modules**, when their parent class (or a function returning their parent class, etc.) is `export`ed. (Namespace-scope operators would have to be individually `export`ed.)
A few notes:
* `span::iterator` has used hidden friends since #474 and currently says: https://github.com/microsoft/STL/blob/ea32e86deed6e8a8cd6116dc275e358a901d2b50/stl/inc/span#L117
* The …
> My Little Operator: Friendship Is Magic

- stl/src/xdtest.cpp
- stl/src/xfdtest.cpp
- stl/src/xldtest.cpp
- stl/src/xmath.hpp
- stl/src/xxxprec.hpp
This xmath machinery in `stl/src` was neither dllexported nor mentioned by `stl/inc`, so it can be safely removed.
There is no change to the DLL sizes, not even a single byte, because we ask the linker to drop unreferenced code, even for the debug DLLs: https://github.com/microsoft/STL/blob/ea32e86deed6e8a8cd6116dc275e358a901d2b50/stl/CMakeLists.txt#L559-L560
The static libs shrink slightly (all IDL flavors). For example, the x64 static libs shrink like this:
| File | Old size<br>(bytes) | New size<br>(bytes) | Improvement<br>(bytes) |
|:----:|:-------------------:|:-------------------:|:----------------------:|
| `libcpmt.lib`  | 35,544,492 | 35,522,704 | 21,788 |
| `libcpmtd.lib` | 36,858,914 | 36,840,400 | 18,514 |
> Delete unused, non-exported xmath machinery

- stl/inc/yvals_core.h
Fixes #2243. Thanks to @frederick-vs-ja and @CaseyCarter for analyzing the issue (see their comments there).
We implemented this in C++20 mode:
https://github.com/microsoft/STL/blob/7f04137880e1c3df5125c1baf808f16f399dee2e/stl/inc/xutility#L1698
https://github.com/microsoft/STL/blob/7f04137880e1c3df5125c1baf808f16f399dee2e/stl/inc/xutility#L1829
https://github.com/microsoft/STL/blob/7f04137880e1c3df5125c1baf808f16f399dee2e/stl/inc/xutility#L2003
https://github.com/microsoft/STL/blob/7f04137880e1c3df5125c1baf808f16f399dee2e/stl/inc/xutility#L2072
While this is theoretically observable, it would require some effort to test, and the risk of damaging this is extremely low, so I have chosen the lazy kitty path of "comment the feature as done, then flop over". :cat2:
> P0849R8 `auto(x)`: `decay-copy` In The Language

- CMakeLists.txt
- azure-devops/cmake-configure-build.yml
- stl/src/tzdb.cpp
- stl/src/winapisupp.cpp
> fix analyze in CI

- stl/src/vector_algorithms.cpp
- tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
This fixes a regression caused by #2447 that was specific to 64-bit types on x86, reported by internal VSO-1558536 "[RWC][prod/fe][Regression][x86] LLVM one test 'Profile/c-counter-overflows.c' failed".
Thanks to @AlexGuteniev for finding the root cause and providing the fix. The problem is that `_mm_extract_epi32` and `_mm_cvtsi128_si32` both return `int`. By directly casting to `_Unsigned_t`, i.e. `uint64_t` in `_Minmax_traits_8`, high-bit values were being sign-extended, but the desired behavior was zero-extension. Adding initial casts of `static_cast<uint32_t>` fixes this.
Then, I'm enhancing the test coverage:
* Adding a few specific test cases that failed.
* Truly randomizing the test, so that every run provides unique coverage.
* Using wider distributions of values for the min/max …
> Fix vectorized `min/max/minmax_element` for 64-bit types on x86

- stl/debugger/STL.natvis
Fixes #2783
test:
```c++
#define _SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS
#include <hash_set>
#include <hash_map>
int main() {
stdext::hash_set<int> hs = { 1,2,3 };
stdext::hash_multiset<int> hms = { 1,1,2,3 };
stdext::hash_map<int, char> hm = { {1, 'a'}, {2,'b'} };
stdext::hash_multimap<int, char> hmm = { {1, 'a'}, {1, 'c'}, {2,'b'} };
}
```
_Traitsobj class: https://github.com/microsoft/STL/blob/e178ea2c5219b00ae8e0d1d5fd0c0ad7186cff7a/stl/inc/hash_map#L41-L110
_Tr class: https://github.com/microsoft/STL/blob/37b51205fbac24c1cc839bd3aa793c341229acf4/stl/inc/xhash#L59-L87
So we don't visualize `[hash_function]` and `[key_eq]`, we could visualize `[comp]` but it doesn't seem useful...
> fix hash_* visualizer issue

- stl/debugger/STL.natvis
> drop VC 2013 visualizers

- stl/debugger/STL.natvis
Fixes #2787
test:
```c++
#include <memory>
int main() {
std::allocator<int> alloc{};
auto ms = std::make_shared<int>();
auto as = std::allocate_shared<int>(alloc, 10);
return 0;
}
```
Do we need some comments for them like `` ?
> add a visualizer for `_Ref_count_obj_alloc3` and `_Ref_count_obj2`

- azure-devops/checkout-sources.yml
- azure-pipelines.yml
This should fix #396 - see my analysis there.
I initially wanted to annihilate the entire workspace with `workspace: clean: all`. While I believe that would be effective and simpler to reason about (making reused machines perform completely fresh clones), it would be slower when machines are reused. Even though the actual time savings are rather small (~15 seconds), the total machine time across many VMs is more significant.
This uses `git clean --quiet -x -d -f -f` with two force options because we want to clean up any leftover submodules; git will refuse to do that if there's only one force option. (`--quiet` suppresses potentially voluminous log output which we aren't interested in.)
This also makes a vaguely related change to the submodule checkout scripts. They now use two force …
> Fix cross-PR contamination by cleaning after checkout

- stl/inc/system_error
- stl/src/syserror.cpp
Fixes #2561 
This PR affects redist.
It is expected that the fix can be included in VS 2022 17.4 Preview 2.
The changes is tested via: https://github.com/microsoft/STL/blob/60decd0d829e68666b556780002c83605d748d80/tests/std/tests/Dev11_0493504_error_category_lifetime/test.cpp#L31-L40
> `syserror.cpp`: update `_Syserror_map`

- stl/src/filesys.cpp
- stl/src/filesystem.cpp
Replace SetFilePointerEx with SetFileInformationByHandle
Fixes #2767.
> Improve filesystem file resizing

- stl/inc/source_location
- tests/std/tests/P1208R6_source_location/test.cpp
> workaround for `std::source_location::current()`

- stl/inc/algorithm
- tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
> Extend range of min max optimization

- stl/inc/ymath.h
- stl/src/xmath.hpp
While looking at the STL's separately compiled machinery for modules, I noticed that `inc/ymath.h` was declaring a bunch of stuff that isn't needed by any other header in `inc`. We can move this to `src/xmath.hpp` (which is being included by everything in `src` that needs it) without disrupting users or affecting ABI. (That is, the exported machinery in `src` will still be exported; there's no reason to declare it as imported in `inc` if we aren't going to use it there.)
This is theoretically an extremely slight throughput improvement (fewer things being declared), but realistically it just makes the codebase easier to understand - fewer spurious connections between `inc` and `src`.
---
I'm changing one thing while moving this from `inc` to `src`: changing `_CRTIMP2_PURE_IMPORT` to …
> Move machinery from `inc/ymath.h` to `src/xmath.hpp`

- stl/inc/tuple
- tests/std/tests/Dev11_0000000_tuple_cat/test.cpp
Resolves #260. Inspired by @ArtemSarmini's #461, although this takes a different approach. See https://github.com/microsoft/STL/pull/461#issuecomment-1169541206 for rationale: despite the issue's title, this PR is not generalizing `tuple_cat()` beyond `pair` and `array` at this time (except for `ranges::subrange`), nor is it using `get` as a customization point.
This PR can be viewed as a series of transformations (see individual commits, each of which build and pass tests), but it's simpler to explain as an overall before-and-after change:
* This removes `_Cat_sequences`, `_View_as_tuple`, and `_Repeat_for`. We'll achieve the same results in different ways.
* `tuple_cat()`:
+ The return type is now a `_Ret` typedef instead of `type`, for increased consistency.
+ The tag types are being …
> `<tuple>`: Overhaul `tuple_cat()` for simplicity and less special-casing

- stl/debugger/STL.natvis
This PR adds .natvis entries using `std::unique_ptr`/`std::vector` to hold various character types so that these are displayed as null terminated strings instead as generic arrays. This is useful when debugging code that uses one of these types as a character buffer, for example in order to call a Windows API.
NOTE: For std::vector, I considered setting the display string to use `[size()]` or similar as a format specifier in order to better handle the case that the string wasn't null terminated. But this winds up with a worse result if it is null terminated, so I wound up deciding to leave it as-is.
> .natvis: Add view for unique_ptr/vector of chars

- index.html
- package-lock.json
- package.json
- src/status_chart.ts
- src/weekly_table.ts
* Major appearance improvements:
+ Colorize counters to match datasets.
- As in #2835, styles like `color-bg-severe-emphasis` have no inherent meaning, and are being used for their colors only.
- Four counters need special treatment. The Old Bugs need to manually specify `--color-scale-red-7`. The GitHub Issues and Average Age datasets are gray lines, so `Counter--primary` results in a readable gray for both dark mode and light mode. Finally, the Combined Age dataset uses the default foreground color (i.e. text color), so for its counter we use inverted colors: the counter's background is the default foreground color, while the counter's foreground is the default canvas color.
- I believe this significantly helps readability.
+ Use a mobile-optimized viewport.
- Thanks to @cpplearner for …
> Status Chart: Colorized counters, mobile-optimized

- stl/src/awint.hpp
- stl/src/winapisupp.cpp
Now that we've merged #2317, there are only a couple of functions we're dynamically loading.
* Dramatically shrink the `__KERNEL32Functions` table.
+ The only direct uses of `__KERNEL32Functions` are in `STOREFUNCTIONPOINTER` and `DYNAMICGETCACHEDFUNCTION`.
+ The only use of `DYNAMICGETCACHEDFUNCTION` is in `IFDYNAMICGETCACHEDFUNCTION`.
+ There are only two uses of `IFDYNAMICGETCACHEDFUNCTION`, loading `GetCurrentPackageId` and `GetSystemTimePreciseAsFileTime`.
+ Therefore, all other table entries are unused.
+ The comment `// This enum should not change` was introduced by #1194, but we were being overly cautious. The enum and table aren't mentioned outside of `stl/src`. Also, while the table was `extern "C"`, it wasn't exported. Therefore, they're purely internal to the separately …
> `winapisupp.cpp`: Dramatically shrink the function pointer table

- stl/inc/cstdlib
`<cstdlib>`'s `using`-declarations for making `getenv` and `system` available in `namespace std` were originally guarded by `#ifdef _CRT_USE_WINAPI_FAMILY_DESKTOP_APP` when the Windows App Certification Kit was very restrictive.
[OS-PR-1077295](https://microsoft.visualstudio.com/OS/_git/os/pullrequest/1077295) "Add a bunch more CRT APIs to the WACK", merged on 2017-11-09, removed those guards from `<stdlib.h>`. Thus, we should remove the guards from `<cstdlib>`, which will both simplify the header and improve conformance as viewed by UWP apps.
Noticed while implementing Standard Library Modules.
> `<cstdlib>`: Provide `std::getenv` and `std::system` for UWP apps

- tests/std/tests/Dev10_908702_string_memory_leak/test.cpp
- tests/std/tests/Dev11_0485243_condition_variable_crash/test.cpp
- tests/std/tests/Dev11_0748972_function_crash_out_of_memory/test.cpp
I noticed the tests while changing `<meow.h>` to `<cmeow>`.
Based on the comment: https://github.com/microsoft/STL/pull/2763#discussion_r890671742
We also have another test with `_CrtDumpMemoryLeaks`: `tests\std\tests\P0718R2_atomic_smart_ptrs\test.cpp`
But it seems the test is checking more things and Release CRT tests make sense...
> run memory leaks tests only with Debug CRT

- stl/inc/filesystem
- stl/inc/yvals_core.h
- tests/std/tests/P0218R1_filesystem/test.cpp
> remove `directory_entry::clear_cache`

- stl/inc/complex
Mixed real/complex multiplication and addition are commutative (and I don't think there are any observable side effects), so it's unnecessary to strictly follow the *Returns* clauses in [[complex.ops]/2](https://eel.is/c++draft/complex.ops#2) and [[complex.ops]/5](https://eel.is/c++draft/complex.ops#5). Converting a real parameter on the LHS to `complex` results in a full complex/complex operation that the optimizer is unable to clean up.
https://godbolt.org/z/KW3sWE6YY
<details>
<summary>Multiplication codegen</summary>
```asm
std::complex<double> Mult(double const &,std::complex<double> const &) PROC   ; Mult, COMDAT
movups  xmm0, XMMWORD PTR [r8]
mov     rax, rcx
movsd   xmm1, QWORD PTR [rdx]
unpcklpd xmm1, xmm1
mulpd   xmm1, xmm0
movups  XMMWORD PTR [rcx], xmm1
ret     0 …
```
> `<complex>`: avoid unnecessary conversion of real arguments to complex

- stl/src/awint.hpp
- stl/src/filesys.cpp
- stl/src/filesystem.cpp
- stl/src/winapisupp.cpp
As a security measure, Windows 11 introduces a new temporary directory API, GetTempPath2.
When the calling process is running as SYSTEM, a separate temporary directory
will be returned inaccessible to non-SYSTEM processes. For non-SYSTEM processes
the behavior will be the same as before.
This can help mitigate against attacks such as this one:
https://medium.com/csis-techblog/cve-2020-1088-yet-another-arbitrary-delete-eop-a00b97d8c3e2
This PR updates the filesystem library to call into this new API when available.
Note that there is a small possible compatibility impact if software relies on temporary files to
communicate between SYSTEM and non-SYSTEM processes and one uses GetTempPath (prior to this change)
and the other GetTempPath2. In many cases, such patterns may be vulnerable to the …
> Update filesystem library to use GetTempPath2 on Windows 11

- stl/inc/type_traits
The workaround for DevCom-876860 is now a workaround for DevCom-10095944. Progress!
Fixes #2860
> Update workaround bug number

- tests/std/tests/P1135R6_atomic_wait_vista/test.cpp
> Don't assume that WaitOnAddress is not statically available on ARM/ARM64

- stl/inc/filesystem
- stl/inc/type_traits
- stl/inc/xfilesystem_abi.h
- stl/src/filesystem.cpp
The helper functions `_Bitmask_includes()` and `_Bitmask_includes_all()` can be templates instead of being stamped out for every enum bitmask. These functions are used for only a few types.
We need to add `_STD` qualification to callsites that are outside `namespace std`, as we're no longer stamping out overloads in the global namespace.
Also remove unnecessary comments (ignore whitespace to see this clearly).
Also rename `_Bitmask_includes()` to `_Bitmask_includes_any()` for clarity.
Found while implementing Standard Library Modules, but this was blocked until toolset update #2861 with the fix for internal VSO-1509503 "Standard Library Header Units: Deduplication interferes with ADL for global `operator&`".
> Extract `_Bitmask_includes_any()`, `_Bitmask_includes_all()` from `_BITMASK_OPS`

- stl/inc/complex
- tests/std/tests/GH_000935_complex_numerical_accuracy/log_test_cases.hpp
- Perma-workaround bad codegen of `vfma_f64` ARM64 intrinsic, using `std::fma` instead. This also improves codegen (https://godbolt.org/z/7rd4rc3nY).
- Use `std::fma` for clang on ARM64.
- Drive-by: Fix two lines of comments that are swapped.
Fixes #2857. Fixes DevCom-10088405 and internal VSO-1567425 / AB#1567425 .
I'd appreciate help to run the tests on ARM64 and ARM64EC (especially GH_000935_complex_numerical_accuracy), as I don't have access to an ARM64 Windows machine now.
> Fix incorrect result of `complex` `log`/`log10`/`pow` on ARM64

- stl/inc/filesystem
- tests/std/tests/P0218R1_filesystem/test.cpp
Fixes #2256 and LWG-3699
This is one choice of how to implement this; it makes `lexically_relative` treat `\\?\<drive letter>:\` as equivalent to `<drive letter>:\`; another option would _just_ be to allow `\\?\<drive letter>:\` and not have them be equivalent.
> Fix LWG-3699 `lexically_relative` on UNC drive paths (`\\?\C:\...`) results in a default-constructed value

- stl/inc/filesystem
- stl/inc/xfilesystem_abi.h
- stl/src/filesystem.cpp
- tests/std/tests/P0218R1_filesystem/test.cpp
* `is_symlink(junction)` is still `false`
* `read_symlink(junction)` works and does the obvious thing
* `copy_symlink(junction)` doesn't work - creating a directory symlink is bad, and creating a junction is not _really_ supported by the windows API (and also a junction is not a symlink)
* `copy(junction)` works and does the obvious thing
Fixes #2818
> `<filesystem>` support junctions in `read_symlink`

- stl/inc/ranges
- tests/std/tests/P2442R1_views_chunk/test.cpp
Implements the proposed resolution of [LWG-3710](https://cplusplus.github.io/LWG/issue3710)
> Implement LWG-3710: The `end` of `chunk_view` for input ranges can be `const`

- stl/inc/ranges
- tests/std/tests/P2442R1_views_chunk/test.cpp
Implements [LWG-3707](https://cplusplus.github.io/LWG/issue3707).
Towards https://github.com/microsoft/STL/issues/2872.
> Implement LWG-3707: `chunk_view::outer-iterator::value_type::size` should return unsigned type

- stl/inc/filesystem
- stl/inc/regex
- tests/std/tests/P0896R4_stream_iterators/test.cpp
Towards #2872. Adding test coverage to the test file for stream iterators and `default_sentinel_t`.
> Implement LWG-3719: Directory iterators should be usable with default sentinel

- stl/inc/format
- tests/std/tests/P0645R10_text_formatting_death/test.cpp
- tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
> Implement LWG-3721: Allow an arg-id with a value of zero for width in std-format-spec

- stl/inc/ranges
- tests/std/tests/P2442R1_views_chunk/test.cpp
- tests/std/tests/P2442R1_views_slide/test.cpp
> Implement LWG-3712: `chunk_view` and `slide_view` should not be `default_initializable`

- stl/inc/xutility
- tests/std/tests/P0896R4_ranges_subrange/test.compile.pass.cpp
- tests/std/tests/P0896R4_views_drop/test.cpp
- tests/std/tests/P0896R4_views_elements/test.cpp
- tests/std/tests/P0896R4_views_take/test.cpp
- tests/std/tests/P0896R4_views_transform/test.cpp
- tests/std/tests/P2442R1_views_chunk/test.cpp
> Implement LWG-3715: `view_interface::empty` is overconstrained

- index.html
- package-lock.json
- package.json
- src/status_chart.ts
- src/weekly_table.ts
Fixes #2963.
* Weekly updates.
* Update dependencies:
+ es-module-shims 1.5.9.
+ Primer CSS 20.4.0.
+ luxon 2.5.0.
- Not 3.x yet - https://github.com/chartjs/chartjs-adapter-luxon/issues/61 has been fixed, but we need a new release.
+ chart.js 3.8.2.
* Ensure that we have `legend_item.datasetIndex`.
- This reacts to a breaking change in chart.js 3.8.1 caused by https://github.com/chartjs/Chart.js/pull/10436.
* Wait for stylesheets to finish loading.
- Ignore whitespace when reviewing.
As usual, this contains a "DROP BEFORE MERGING: Regen `built/status_chart.mjs`." commit to make the live preview work.
===
> Status Chart: Fix CSS loading race

- README.md
- index.html
- package-lock.json
- package.json
- src/status_chart.ts
My previous PR #2967 which attempted to address #2963 appeared to solve the problem for desktop Chrome, but broke mobile Safari such that the charts wouldn't even load.
I don't understand the root cause, but I suspect that it has something to do with how es-module-shims has to do actual work for mobile Safari (so perhaps the window is considered "loaded" before the JS finishes executing, and the `addEventListener` did nothing).
This PR uses a different technique that appears to work reliably in both environments. Now I run a function, `check_css()`, that detects whether Primer CSS has loaded. If it hasn't, we'll wait 50ms and check again. (Chosen semi-arbitrarily - we don't need to check every frame, but we do want to notice it quickly.)
This also updates dependencies slightly, including …
> Status Chart: Fix mobile Safari

- stl/inc/format
> Implement LWG-3701: Make `formatter<remove_cvref_t<const charT[N]>, charT>` requirement explicit

- stl/inc/xutility
- stl/inc/yvals_core.h
- tests/libcxx/expected_results.txt
- tests/libcxx/skipped_tests.txt
- tests/std/tests/GH_002581_common_reference_workaround/test.compile.pass.cpp
- tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
- tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
> Implement P2520R0: `move_iterator<T*>` should be a random access iterator

- stl/inc/algorithm
- stl/inc/execution
- stl/inc/functional
- stl/inc/numeric
- stl/inc/regex
- stl/inc/vector
- stl/inc/xstring
- stl/inc/xutility
- stl/inc/yvals_core.h
- tests/std/test.lst
- tests/std/tests/P2408R5_ranges_iterators_to_classic_algorithms/env.lst
- tests/std/tests/P2408R5_ranges_iterators_to_classic_algorithms/test.cpp
- tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Fixes #2925 
Changes from paper:
* parallel algorithms: require `forward_iterator<FwdIt>` when in concepts mode for read-only iterators
* other algorithms: if there is a `static_assert(_Is_blah_iter_v)`, turn it into a `static_assert(_Is_ranges_blah_iter_v)`, when the iterator is non-mutable
* `sample`: check for `_Is_ranges_fwd_iter_v` 
* `unique_copy`: check for `_Is_ranges_fwd_iter_v`
Other changes, not explicitly specified in the paper:
* many algorithms: if there is a check for different `_Is_blah_iter_v`, and the iterator in question is non-mutable, check `_Is_ranges_blah_iter_v`
* for example, check for `_Is_ranges_random_iter_v` in `advance`
* `prev`: check for `_Is_ranges_bidi_iter_v`
* `_Use_atomic_iterators` -> check for `_Is_ranges_random_iter_v` - this has ABI impact
Drive …
> Implement P2408R5: Ranges Iterators As Inputs To Non-Ranges Algorithms

- stl/inc/memory
- tests/std/tests/P0896R4_ranges_alg_uninitialized_copy/test.cpp
- tests/std/tests/P0896R4_ranges_alg_uninitialized_copy_n/test.cpp
- tests/std/tests/P0896R4_ranges_alg_uninitialized_move/test.cpp
- tests/std/tests/P0896R4_ranges_alg_uninitialized_move_n/test.cpp
...as is necessary to properly unwrap-and-rewrap input iterators. Test `ranges::uninitialized_(copy|move)(_n)?` with iterators that require rvalues to unwrap properly which would have caught this bug.
Fixes #2962.
> Pass rvalues to `_Seek_to` in `ranges::uninitialized_(copy|move)_n`

- stl/inc/bitset
- stl/inc/yvals_core.h
- tests/std/test.lst
- tests/std/tests/P2417R2_constexpr_bitset/env.lst
- tests/std/tests/P2417R2_constexpr_bitset/test.cpp
- tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Fixes #2926 
I added a new test file because the previous `bitset` test is `tr1/bitset` and we don't change `tr1` tests.
> Implement P2417R2 More `constexpr` `bitset`

- stl/inc/xutility
- tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
Currently the implementation of `std::ranges::enable_view` in MSVC STL doesn't reject reference types.
```C++
static_assert(std::ranges::enable_view<std::ranges::empty_view<int>&>); // currently passes, but should not
```
And it doesn't handle incomplete types whenever possible due to ADL.
```C++
struct Incomplet;
template <class T>
struct Holder {
T t;
};
static_assert(!std::ranges::enable_view<Holder<Incomplet>*>); // hard error, should be avoided
```
These bugs are revealed by the libc++ test `std/ranges/range.req/range.view/enable_view.compile.pass.cpp`.
The fixes are
- requiring the type to be an object type in the derive-from-`view_interface` mechanism, and
- using qualified call to avoid ADL.
> `<xutility>`: Some fixes around `std::ranges::enable_view`

- stl/inc/xstring
- tests/std/tests/GH_002030_asan_annotate_string/env.lst
- tests/std/tests/GH_002030_asan_annotate_string/test.cpp
Disabling string annotations to unblock ASAN testing. Work to re-enable is ongoing.
> Temporarily disable ASAN string annotations

- stl/inc/ranges
- stl/inc/xutility
- tests/std/tests/P2443R1_views_chunk_by/test.cpp
Fixes #2889
Casey's drive-by: Give up on the Standard's dream that we can avoid defining `projected::operator*`. There are just too many interactions with the "need for constant evaluation" rules and the use of types with internal linkage - it's not worth fighting anymore.
> `chunk_by_view`'s helper lambda returns `bool`

- stl/inc/type_traits
- tests/std/tests/Dev11_0535636_functional_overhaul/test.cpp
- tests/std/tests/P0433R2_deduction_guides/test.cpp
Fixes #2952.
I think we should detect the predefined core language feature-test macro `__cpp_explicit_this_parameter`, but MSVC didn't define it in VS2022 17.2 and 17.3, so I filed DevCom-10107077.
I can imagine the future where there will be "C++17/20 with explicit object parameters" dialects, so I guess we should not restrict these library changes to C++23, and just use `_HAS_CXX17 && defined(__cpp_explicit_this_parameter)` to enable these changes.
> Implement LWG-3617: `function`/`packaged_task` deduction guides and deducing `this`

- stl/inc/variant
- tests/std/tests/P0088R3_variant/test.cpp
Fixes #2970.
`std::visit<R>` may need similar strategy to `std::is_invocable_r` to handle conversions to non-movable types.
> `<variant>`: Make `visit<R>` correctly handle conversions to non-movable types

- stl/inc/__msvc_iter_core.hpp
- stl/inc/utility
- stl/inc/yvals_core.h
- tests/std/test.lst
- tests/std/tests/P2445R1_forward_like/env.lst
- tests/std/tests/P2445R1_forward_like/test.compile.pass.cpp
- tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Fixes #2931.
Intentionally don't call `std::move`, `std::forward`, or `std::as_const`. Also move `_Can_reference` to `<utility>` for error message.
> Implement P2445R1 `forward_like()`

- stl/inc/__msvc_chrono.hpp
- tests/libcxx/expected_results.txt
- tests/libcxx/skipped_tests.txt
...by avoiding ill-formed uses of the conditional operator in `std::chrono::abs`.
Fixes #2839
> `<chrono>`: `chrono::abs` incorrectly uses `?:` with expressions that don't always have a common type

- stl/inc/algorithm
- stl/inc/memory
- stl/inc/numeric
- stl/inc/xutility
- stl/inc/yvals_core.h
- tests/std/tests/GH_000545_include_compare/test_ranges.cpp
- tests/std/tests/P0220R1_string_view/test.cpp
- tests/std/tests/P0980R1_constexpr_strings/test.cpp
- tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
* Add `__cpp_lib_concepts` guard for `__cpp_lib_move_iterator_concept`.
+ Noticed while merging #2958 - its product code changes to `<xutility>` affected only `__cpp_lib_concepts`, so the feature-test macro should be similarly guarded.
* Consistently test `__cpp_lib_concepts` and cite GH-395.
+ Only the actual definition and test for `__cpp_lib_concepts` still mention `__EDG__` to avoid circularity.
+ In `P0980R1_constexpr_strings`, explain how the `equalRanges` workaround should be removed.
* When testing `_HAS_CXX23 && defined(__cpp_lib_concepts)`, always say `// TRANSITION, GH-395`.
* Use `#ifdef __cpp_lib_concepts` for consistency.
+ Cite GH-395 by `__cpp_lib_algorithm_iterator_requirements`.
> Add `__cpp_lib_concepts` guard for `__cpp_lib_move_iterator_concept`

- stl/debugger/STL.natvis
- stl/inc/ranges
- stl/inc/yvals_core.h
- tests/std/test.lst
- tests/std/tests/P1899R3_views_stride/env.lst
- tests/std/tests/P1899R3_views_stride/test.cpp
- tests/std/tests/P1899R3_views_stride_death/env.lst
- tests/std/tests/P1899R3_views_stride_death/test.cpp
- tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Implements [P1899R3](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p1899r3.html) - `stride_view`. Closes #2915.
<details>
<summary>Note(s)</summary>
* I've `std::`-qualified all calls to `std::forward` and `std::move` in tests, because next Clang release (15) is going to [warn about "unqualified std cast calls"](https://clang.llvm.org/docs/DiagnosticsReference.html#wunqualified-std-cast-call).
</details>
> P1899R3: `views::stride`

- stl/inc/xhash
Reported by: https://www.reddit.com/r/cpp/comments/wgb8xo/fun_times_with_msvc_functional/
This does two things:
* `<xhash>` includes `<xstring>` for `basic_string`, `<cstring>` for `strlen`, and `<cwchar>` for `wcslen`, because it's defining non-Standard `stdext` machinery for `<hash_map>` and `<hash_set>`. This throughput cost is paid by everyone who drags in `<xhash>`, including highly indirect routes like `<functional>`. There's a simple way to avoid this (i.e. without adding a new sub-header to be included by `<hash_meow>`). Because we hard-deprecated `<hash_meow>` with an error-and-escape-hatch, we can guard the `stdext` machinery with that same escape hatch. Result: the `stdext` machinery and `<xstring>` etc. dependencies disappear for the vast majority of users, and are still …
> `<xhash>` should avoid including `<xstring>`

- stl/inc/xstring
> `<xstring>`: `basic_string::_Is_elem_cptr` should be a variable template

- stl/inc/format
- tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
... per [[format.string.std]/22](http://eel.is/c++draft/format#string.std-22).
Reported by Mark de Wever after we tried to break their perfectly good test with https://reviews.llvm.org/D131336.
> <format>: all nans are "nan"

- stl/inc/xutility
- tests/std/tests/P0896R4_ranges_alg_shuffle/test.cpp
C++20 `uniform_random_bit_generator` does not require the presence of member `result_type`.
This is tested in libc++ tests [`std/algorithms/alg.modifying.operations/alg.random.shuffle/ranges_shuffle.pass.cpp`](https://github.com/llvm/llvm-project/blob/ba0407ba86d0a87f01e1a676f9dc23bae3e9c169/libcxx/test/std/algorithms/alg.modifying.operations/alg.random.shuffle/ranges_shuffle.pass.cpp) and [`std/algorithms/alg.modifying.operations/alg.random.sample/ranges_sample.pass.cpp`](https://github.com/llvm/llvm-project/blob/ba0407ba86d0a87f01e1a676f9dc23bae3e9c169/libcxx/test/std/algorithms/alg.modifying.operations/alg.random.sample/ranges_sample.pass.cpp). Unfortunately they fail even after this change, because they assume that `std::array` iterators are pointers.
> Use `_Invoke_result_t<_Urng&>` instead of `_Urng::result_type` in `_Rng_from_urng`

- stl/src/filesystem.cpp
@zacklj89 found this while updating the STL in Windows. (Thanks Zack, for investigating this for over a week - it wasn't easy! :smile_cat:)
#2302 (merged for VS 2022 17.4 Preview 2) made `filesystem.cpp` (which is injected into the STL's import lib) include `<atomic>` to cache a function pointer. Unfortunately, `<atomic>` is a non-core header, and it's the first non-core header included by `filesystem.cpp`:
https://github.com/microsoft/STL/blob/2263d931f48a4e196036b2523af7a0048bb96b46/stl/inc/atomic#L9
This drags in `_Init_locks`, which is separately compiled and has an implicitly defined assignment operator:
https://github.com/microsoft/STL/blob/2263d931f48a4e196036b2523af7a0048bb96b46/stl/inc/yvals.h#L456-L475
In a certain project, this was leading to linker errors, as the STL's DLL …
> Avoid `<atomic>` in `filesystem.cpp`

- README.md
- azure-devops/provision-image.ps1
- azure-pipelines.yml
- stl/inc/yvals_core.h
- tests/std/tests/P0220R1_string_view/test.cpp
* Python 3.10.6.
* New pool.
+ Contains Aug 2022's Patch Tuesday.
* README.md: VS 2022 17.4 Preview 1, Ninja 1.11.0.
* Require MSVC 19.34.
+ The MSVC-internal build is already using a checked-in 19.34 compiler.
* Attempt to remove workaround for internal VSO-284079 "C1XX's C++14 `constexpr` emits bogus warnings C4146, C4308, C4307 for `basic_string_view::iterator`".
+ Although this bug hasn't been updated in 3 years, I observe that the warnings no longer repro. Let's try to activate this test coverage now.
> Toolset update: VS 2022 17.4 Preview 1

- stl/inc/algorithm
- stl/inc/vector
- stl/inc/xutility
- tests/std/test.lst
- tests/std/tests/GH_000177_forbidden_aliasing/env.lst
- tests/std/tests/GH_000177_forbidden_aliasing/test.cpp
- tests/std/tests/P0202R3_constexpr_algorithm_and_exchange/test.cpp
- tests/std/tests/VSO_0180466_algorithm_overhauls/test.cpp
> detect forbidden aliasing

- stl/inc/experimental/coroutine
- stl/inc/experimental/filesystem
- stl/inc/hash_map
- stl/inc/hash_set
- stl/inc/ranges
- stl/inc/type_traits
- stl/inc/yvals_core.h
Fixes #237
Fixed broken PR history of #2969
> `yvals_core.h`: Consistent diagnostics and warnings

- stl/inc/random
This PR proposes the following improvements for some static member variables in `<random>`:
1. `_Swc_01_traits` will have all of its static member variables statically initialized.
2. No redeclarations (since C++17, definitions in C++14 and former revisions) of constexpr static member variables will ever exist, even if one attempt to revive `tr1` in C++17 (and later modes). They are deprecated in C++17, even though warnings seem to be silenced.
3. (According to the suggestion) Out-of-class definitions will also be removed in C++14 mode.
The first should be reverted if changing from dynamic initialization to static one or removal of odr-using breaks ABI.
> `<random>`: Improvements around `static constexpr` member variables

- stl/inc/ranges
- stl/inc/yvals_core.h
- tests/std/test.lst
- tests/std/tests/P2446R2_views_as_rvalue/env.lst
- tests/std/tests/P2446R2_views_as_rvalue/test.cpp
- tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Implements [P2446R2](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2446r2.html) - `views::as_rvalue`. Closes #2929.
Notes:
* ~~Marked as draft - I'm unable to implement full test coverage due to iterator unwrapping problems.~~ Not anymore - I've implemented custom `test_equal` function that should be replaced with `ranges::equal` after #3009 is fixed,
* Just like in #2981: 
> I've `std::`-qualified all calls to `std::forward` and `std::move` in tests, because next Clang release (15) is going to [warn about "unqualified std cast calls"](https://clang.llvm.org/docs/DiagnosticsReference.html#wunqualified-std-cast-call).
> P2446R2: `views::as_rvalue`

- stl/inc/bitset
- stl/inc/ccomplex
- stl/inc/ciso646
- stl/inc/cstdalign
- stl/inc/cstdbool
- stl/inc/ctgmath
- stl/inc/filesystem
- stl/inc/functional
- stl/inc/map
- stl/inc/memory
- stl/inc/random
- stl/inc/system_error
- stl/inc/thread
- stl/inc/type_traits
- stl/inc/typeindex
- stl/inc/variant
- stl/inc/vector
- stl/inc/xmemory
- stl/inc/xstddef
Mechanically replaced `(\w+) typedef (.+) (\w+);` with `using $3 $1 = $2;`.
Long long ago, we replaced every occurrence of `typedef` in product code with `using`, as it's more readable and consistent (alias templates must be `using`). However, there were compiler bugs with `using` and attributes, so we didn't replace deprecated `typedef`s. Those compiler bugs were fixed long ago, and we've already accumulated a few occurrences of deprecated `using`, e.g.:
https://github.com/microsoft/STL/blob/5aae6780236208577b4e8a000cbe7aa3cbc24c41/stl/inc/type_traits#L1097-L1098
This finishes the overhaul for product code.
> Change `typedef` to `using`

- stl/inc/forward_list
- stl/inc/list
- stl/inc/variant
- stl/inc/vector
- stl/inc/yvals.h
- stl/src/filesystem.cpp
- stl/src/xdateord.cpp
- stl/src/xrngdev.cpp
- stl/src/xtime.cpp
- tests/std/tests/P0220R1_polymorphic_memory_resources/test.cpp
- tools/validate/CMakeLists.txt
* `<forward_list>`, `<list>`, `<vector>`: Drop redundant access control.
* `<variant>`: `_Convertible_from_all` can be an alias template.
* `src/xrngdev.cpp`: Drop totally redundant declaration of `_Random_device()`.
* `src/xrngdev.cpp`: Include less machinery.
+ We don't need all of `<stdexcept>`, and we don't need `<random>` commented-out.
+ We need `<cstdlib>` for `rand_s()` and `<xutility>` for `_Xout_of_range()`.
* `P0220R1_polymorphic_memory_resources/test.cpp`: Use https URL.
* `tools/validate/CMakeLists.txt`: Use C++23.
* `src/xdateord.cpp`: Repeat `_CRTIMP2_PURE` from the declaration in `<xlocinfo>`.
* `src/xtime.cpp`: Add `_CRTIMP2_PURE` and `__cdecl` to match declarations in `<xtimec.h>`.
* `src/filesystem.cpp`: Comment "copying from 2 consecutive DWORDs".
* `<yvals.h>`: Guard …
> Various cleanups

- stl/inc/vector
> `<vector>`: Apply append-and-rotate for `vector<bool>` insertion

- stl/inc/ranges
- tests/std/tests/P1899R3_views_stride_death/test.cpp
- tests/std/tests/P2442R1_views_chunk_death/test.cpp
Speculatively implements what will be the proposed resolution of an LWG issue filed per GH-2995 once the new working draft is out with `stride_view` and `chunk_view`. Also avoid checking the precondition when it can't be done in O(1).
Drive-by:
* inline `ranges::advance(i, n)` since it's simply `i += n` for random-access iterators
* check for overflow of `-n` when calling `*this += -n` in `operator-=`
Partially addresses #2995
> Implement `(chunk_view<forward>|stride_view)::iterator::operator(\+=|-=)` in O(1)

- stl/inc/functional
- stl/inc/xhash
Originally, `_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS` was the escape hatch to allow `<hash_map>` and `<hash_set>` to be included. #2996 extended this to restore `<xhash>`'s inclusion of `<cstring>`/`<cwchar>`/`<xstring>` and defining common `stdext` machinery. However, I attempted to unconditionally remove the non-Standard using-declaration that provided `std::hash_compare`. Unfortunately, there are still projects depending on this. :crying_cat_face: We can preserve the throughput improvement and give affected projects a way out by extending the escape hatch to also provide the using-declaration.
Also, #2998 got `<functional>` to stop including `<memory>` in C++17 mode. We're seeing at least one affected project (Qt5) where fixing the source may be difficult. We can add a targeted …
> Add escape hatches for source-breaking throughput improvements

- stl/inc/xmemory
- tests/std/tests/P1206R7_vector_from_range/test.cpp
... so the `memmove` optimization should check `_Bitcopy_constructible` and not `_Bitcopy_assignable`.
Fixes VSO-1591034/AB#1591034, fixes VSO-1590866/AB#1590866.
Credit to StephanTLavavej for the minimal repro.
> `<xmemory>`: `_Uninitialized_copy` doesn't assign, it constructs

- stl/inc/xutility
This improves the exception specification of `move_iterator` and `reverse_iterator` as well as the `begin()` function and friends.
Note that this (should be) merge clean with #2991 - there are no `_Unwrapped()` changes, to allow #2991 to make those changes.
> Improve exception specification of iterator machinery

- stl/inc/filesystem
- stl/inc/iterator
- stl/inc/ranges
- stl/inc/xutility
- tests/std/test.lst
- tests/std/tests/GH_002989_nothrow_unwrappable/env.lst
- tests/std/tests/GH_002989_nothrow_unwrappable/test.cpp
additionally:
* add `_Unwrapped() && noexcept` to `path::iterator`
* add `_Unwrapped() &&` to `reverse_iterator`
* add conditional noexcepts to:
- `counted_iterator`
- `take_view::_Sentinel`
- `take_while_view::_Sentinel`
- `move_iterator`
Fixes #2989
~~Requires testing~~
> make _Get_unwrapped noexcept when possible

- stl/inc/xstring
- tests/std/tests/P0220R1_string_view/test.cpp
Fixes warning C6510: Invalid annotation: 'NullTerminated' property may only be used on buffers whose elements are of integral or pointer type: Function `'{ctor}' _Param_(1)`.
https://gcc.godbolt.org/z/bPqs167he
Can we do something else and don't remove the annotation but fix the warning?
Found in one of LLVM tests.
> `<string_view>`: suppress warning about annotation 'NullTerminated'

- .vscode/settings.json
This tells VSCode's Python extension, Pylance, where to find our test support machinery, so that modules can be fully resolved without squiggles.
(I found these paths by the ultra-scientific method of opening all of our `.py` files, and seeing which modules generated squiggles. With these paths, only `psutil` needs to be installed locally in order to resolve one remaining squiggle.)
:snake:
> `.vscode/settings.json`: Teach Pylance about our paths

- tests/std/tests/P1208R6_source_location/test.cpp
The compiler team just merged MSVC-PR-418361, fixing the behavior of `source_location::column()` under `/analyze`. Accordingly, `P1208R6_source_location` needs to be updated to accept both the old and new behavior until VS 2022 17.4 Preview 3 ships.
> Update `P1208R6_source_location` for a compiler fix

- stl/inc/chrono
- stl/inc/filesystem
- stl/inc/yvals_core.h
- tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp
Fixes #2927.
When the literal encoding is UTF-8, This ensures that the strings produced by chrono formatters are always encoded in UTF-8, by first formatting with `wchar_t`, then converting the output to UTF-8. (Is there a better way?)
I didn't convert the output of `_Custom_write`, because it seems that `_Custom_write` generally does not deal with localized formatting.
> Implement P2419R2 Clarify Handling Of Encodings In Localized Formatting Of `chrono` Types

- stl/inc/xstring
- tests/std/tests/GH_002030_asan_annotate_string/test.cpp
To avoid regressing DevCom-10116361 / VSO-1590908
Reviewer note: I did temporarily enable ASAN annotation and [verify that all tests (including the new regression test) pass](https://dev.azure.com/vclibs/STL/_build/results?buildId=12177&view=results).
> Test ASAN SSO string copies; improve `basic_string::_Construct` preconditions

- stl/inc/expected
- stl/inc/ranges
- stl/inc/type_traits
- stl/inc/xstddef
- stl/inc/xutility
* Replace `_Implicitly_convert_to` and `_Fake_decay_copy` with `_Fake_copy_init`.
+ Followup to #1937.
* Adjust warning suppressions.
+ In `<type_traits>`, `_Is_nothrow_convertible_v` isn't declaring any functions, so we don't need to suppress the `volatile` deprecation warnings about WG21-N4910 [[depr.volatile.type]/3](https://eel.is/c++draft/depr.volatile.type#3).
+ In `<xstddef>`, we're just declaring `_Fake_copy_init()` but not calling it, so we don't need to suppress truncation/sign-conversion warnings.
+ However, `_Fake_copy_init()` returns `_Ty`, unlike `_Implicitly_convert_to` which returned `void`. There's a different warning number about `volatile` return types that we need to suppress.
As mentioned in #1937's comments, this return type change from `void` to `_Ty` has no other …
> `_Fake_copy_init` unification

- stl/inc/tuple
- stl/inc/utility
- tests/std/tests/GH_001638_dllexport_derived_classes/test.compile.pass.cpp
Fixes #3013, a high-priority customer-reported bug (see DevCom-10109884).
Normally, member functions of class templates are instantiated "on demand". (I like to remember this rule by thinking of `list<T>`, which does not require `T` to be less-than comparable until `list<T>::sort()` is called.) However, if a user derives from a Standard Library class (which we don't encourage, but which is widely done) and then dllexports their derived class, that attempts to instantiate all member functions (that are not templated themselves).
By adding member functions (as required by the Standard) that won't compile when force-instantiated like this, #2687 regressed this scenario. The fix is simple (and something we've used elsewhere): add `template <int = 0>` to make instantiation truly on-demand. …
> Fix `pair::swap(const pair&)` and `tuple::swap(const tuple&)` errors with `__declspec(dllexport)`

- stl/inc/chrono
- stl/inc/deque
- stl/inc/expected
- stl/inc/format
- stl/inc/forward_list
- stl/inc/list
- stl/inc/map
- stl/inc/queue
- stl/inc/set
- stl/inc/stack
- stl/inc/system_error
- stl/inc/unordered_map
- stl/inc/unordered_set
- stl/inc/vector
- stl/inc/xhash
- stl/inc/xmemory
- stl/inc/xstring
- stl/inc/xtree
- stl/inc/yvals_core.h
- tests/std/tests/GH_000545_include_compare/test_ranges.cpp
- tests/std/tests/GH_002989_nothrow_unwrappable/test.cpp
- tests/std/tests/P0355R7_calendars_and_time_zones_clocks/test.cpp
- tests/std/tests/P0433R2_deduction_guides/test.cpp
- tests/std/tests/P0980R1_constexpr_strings/test.cpp
- tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
We should try to minimize the number of feature-test macros used to guard conditionally-compiled product code, so that readers aren't required to memorize the content of SD-6 in order to comprehend the STL. Consequently, feature-test macros should only be used in product code when their values are not implied by language mode or a conjunction of language mode and some other feature-test macro. We should instead test `_HAS_CXXYY && defined(__other_feature_macro)` directly. Feature-test macros whose values vary according to compiler flags other than language modes, or for features that aren't yet implemented by all compilers should be tested directly (although latter will eventually be replace by langage mode tests when the minimum required versions of all supported compilers implement the …
> Cleanup product code uses of feature-test macros

- index.html
- package-lock.json
- package.json
- src/weekly_table.ts
- src_gather/gather_stats.ts
This week, in addition to the usual dependency updates, TypeScript 4.8 is performing stricter type checking. Now we need to immediately apply the type system to GraphQL responses, so I'm adding `ResponseTotalCounts`, `PageInfo`, and `ResponsePRsAndIssues`, completing the types that were started with `RawPRNode` etc.
As usual, this contains a "DROP BEFORE MERGING: Regen `built/status_chart.mjs`." commit to make the live preview work, which will accumulate merge conflicts.
===
> Status Chart: Weekly update, TypeScript 4.8

- stl/inc/utility
Co-authored-by: Alexander Bessonov <alexbav@hhdsoftware.com>
From https://github.com/microsoft/STL/discussions/3051
And we already use `__forceinline` there: https://github.com/microsoft/STL/blob/febb6430ac48a6650b174d567a335afcc0db8dc8/stl/inc/xcharconv_ryu.h#L166
> add `__forceinline` to `std::unreachable` instead of `inline`

- stl/inc/execution
The overloads of `for_each` and `for_each_n` that take an execution policy argument do not require that the iterator arguments always be mutable iterators.  Whether or not the iterators need to be mutable depends on what the function object does.  `for_each` and `for_each_n` are unusual, if not unique, in this regard; for all other algorithms the mutability of the iterators is specified by the algorithm.  See http://eel.is/c++draft/alg.foreach#7 , though I admit that the wording is not particularly clear about this.
Since the compiler can't reliably figure out whether or not the function object modifies the elements in the sequence, `for_each` and `for_each_n` should only check for constant iterators (`_REQUIRE_PARALLEL_ITERATOR`), not mutable iterators …
> Parallel for_each iterators don't have to be mutable

- stl/inc/__msvc_int128.hpp
- tests/std/tests/P1522R1_difference_type/env.lst
- tests/std/tests/P1522R1_difference_type/test.cpp
Thanks to @MattStephanson for having done the most works in #3012. As mentioned in #3012, having 128-bit integer-like types in all modes is useful for random number generation. 
This PR also provides a library solution for DevCom-879048 with literal suffixes (`__i128` and `__u128`) support.
> `<__msvc_int128.hpp>`: Backport 128-bit integer-class types to C++14 mode

- stl/inc/xstring
- stl/inc/yvals_core.h
- tests/std/test.lst
- tests/std/tests/GH_003022_substr_allocator/env.lst
- tests/std/tests/GH_003022_substr_allocator/test.cpp
- tests/std/tests/P2438R2_substr_rvalue/env.lst
- tests/std/tests/P2438R2_substr_rvalue/test.cpp
And make the old and new `substr` use default constructed allocators.
(And consistently refer to WG21-N4910 in `<xstring>`.)
Fixes #2928.
Fixes #3022.
As implementation details, the rvalue substring constructors reuse the source storage if and only if
- the provided allocator and the allocator of the source compare equal, and
- the constructed string doesn't fit into SSO buffer.
I have no idea how to portably test the probably intended behavior of newly added overloads...
> Implement P2438R2 `string::substr() &&`

- docs/cgmanifest.json
This pull request adds the JSON schema for `cgmanifest.json`.
A JSON schema helps you to ensure that your `cgmanifest.json` file is valid.
JSON schema validation is a build-in feature in most modern IDEs like Visual Studio and Visual Studio Code.
Most modern IDEs also provide code-completion for JSON schemas.
Most modern IDEs like Visual Studio and Visual Studio Code have a built-in feature to validate JSON files.
You can also use [this small script](https://github.com/JamieMagee/verify-cgmanifest) to validate your `cgmanifest.json` file.
Component Detection is able to read camel case and pascal case properties.
However, the JSON schema doesn't have a case-insensitive mode.
We therefore suggest camel case as it's the most common format for JSON.
To deserialize the `cgmanifest.json` file, …
> Add `$schema` to `cgmanifest.json`

- stl/inc/complex
- stl/inc/xutility
NVIDIA informed us of some great news: `__builtin_bit_cast` has been supported since CUDA 11.3 in all Standard modes. Our minimum supported and tested version is CUDA 11.6 (since #2791), so we can fully remove our `memcpy` workaround.
Fixes internal VSO-1601623 / AB#1601623 . High priority as this blocks NVIDIA.
> Enable `__builtin_bit_cast` for CUDA

- azure-devops/create-1es-hosted-pool.ps1
- azure-pipelines.yml
This updates our 1ES Hosted Pools (#3054) to use spot VMs, like our old Virtual Machine Scale Sets did. The tradeoff is the same: they are occasionally subject to eviction due to fluctuating capacity, but they're cheaper.
To do this, we need to pass an `'enableSpot' = $true;` property in `create-1es-hosted-pool.ps1`, and then we need to [specify demands](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/demands?view=azure-devops&tabs=yaml) in `azure-pipelines.yml`.
Also, some script improvements/refactorings (as usual, apologies for mixing this into a PR with a behavioral change, but it's cleanly factored into separate commits, and updating the pool is a big enough production that I don't want to create a separate PR for this).
* Print elapsed time.
+ This is so I can notice …
> 1ES Hosted Pools: Use spot VMs

- stl/inc/yvals_core.h
@CaseyCarter https://github.com/microsoft/STL/pull/2211#discussion_r959892472 follow up.
> Update `get_future`'s `[[nodiscard("message")]]`

- stl/inc/algorithm
- stl/inc/atomic
- stl/inc/format
- stl/inc/ranges
- stl/inc/regex
- stl/inc/span
- stl/inc/thread
- stl/inc/xstring
- stl/inc/xutility
This is a perma-workaround for DevCom-10097021 / VSO-1581774 "C++ STL header `<format>` causes C4296 warning that need to be suppressed every time". @cdacamar is investigating the underlying compiler bug, where `#pragma`s within functions aren't properly stored within an IFC. In the meantime, if we consistently push/disable/pop around a function, we'll avoid this problem.
Most of our push/disable/pops are already outside functions, so only a couple of occurrences need to be changed:
* `<format>`: Move push/disable/pop outside of `_Write_integral`.
* `<thread>`: Move push/disable/pop outside `_Start`.
+ Also update comment to exactly match the printed warning.
And one more occurrence can avoid pragmas entirely (I verified that this continues to suppress the warning):
* `<regex>`: Use …
> Improve warning suppressions for header units

- stl/inc/type_traits
- stl/inc/variant
- tests/libcxx/expected_results.txt
- tests/libcxx/skipped_tests.txt
- tests/std/tests/P0088R3_variant/test.cpp
And a few other minor changes while we're here. I've separated changes out by commit for ease of review, but this should be squash merged. The most significant change here - others are self-explanatory - replaces the metaprogramming used to enforce the Standard's requirements that "For each valid pack m, e(m) is a valid expression. All such expressions are of the same type
and value category" ([variant.visit]/5). 
here are different mechanisms to validate the requirement for `visit<R>` and for plain `visit`. Previously, we created a single typelist where each type represented one possible configuration of the set of argument variants to a visit call, and then folded over a single giant pack expansion of visitor evaluations ensuring they had the same type and value category (or are all …
> Update `variant` "all types same/convertible" metaprogramming

- stl/inc/yvals_core.h
Updates _MSVC_STL_UPDATE to "202209L" (September 2022).
Resolves #3067.
> <yvals_core.h>: Update _MSVC_STL_UPDATE to September 2022

- stl/inc/yvals_core.h
Information:
Changes yval_core.h to have the "correct" revision number
closes #2873
closes #2940
> <yvals_core.h> Update P2549 to new revision 

- azure-pipelines.yml
- stl/inc/yvals_core.h
* [Build GitHub repositories: Draft PR validation](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#draft-pr-validation)
> By default, pull request triggers fire on draft pull requests and pull requests that are ready for review. To disable pull request triggers for draft pull requests, set the `drafts` property to `false`.
* [YAML schema: pr definition](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/pr?view=azure-pipelines#pr-autocancel-branches-paths-drafts)
As desired, creating a draft PR doesn't run checks (except for the CLA check, which is independent). The experience is that microsoft.STL remains "Expected -- Waiting for status to be reported". Internally, nothing appears in the logs for the agent pool in Azure …
> Skip Azure Pipelines for draft PRs

- tools/validate/validate.cpp
We can use ranges::is_sorted and ranges::binary_search and pass the checked extensions instead of passing the iterators directly.
> Clean up validation

- stl/src/xdscale.cpp
- stl/src/xfdscale.cpp
We can just check for 0 since -0 is just 0
> Remove unneeded static_cast for xexp

- stl/src/xstoxflt.cpp
- stl/src/xwstoxfl.cpp
Since `s` is a pointer to a `wchar_t`, it makes more sense to use the `wchar_t` field of the localeconv struct returned. `decimal_point` and `_W_decimal_point` are identical for all supported locales, so this is not a behavioral change.
Additional cleanups, keeping narrow `xstoxflt.cpp` and wide `xwstoxfl.cpp` in sync:
* Move the definition of `int word;` down; it doesn't need to be initialized because it's always assigned.
* Upgrade `digits` and `vals` to `constexpr`. Consistently comment them at the end. Consistently use a string literal to initialize `digits`, which provides a null terminator.
* Narrow `xstoxflt.cpp` should use a `while`-loop, as wide `xwstoxfl.cpp` was already doing.
+ This is doing something complicated and less structured, so the `while`-loop is more appropriate.
* …
> Compare the _W_decimal_point of the localeconv, not the decimal_point of said localeconv

- stl/inc/__msvc_int128.hpp
We already know that __n, __j, and __m are already integers, so there is no need to use static casts
> Remove unneeded static casts

- tests/std/tests/P2446R2_views_as_rvalue/test.cpp
Changes:
* After merging #3024 `test_equal` function became unnecessary - we can replace it with `ranges::equal`,
* Fixed two comments, that mentioned `as_const_view` instead of `as_rvalue_view`.
> Cleanup `views::as_rvalue` tests

- stl/inc/cvt/wbuffer
- stl/inc/cvt/xjis
- stl/inc/cvt/xone_byte
- stl/inc/cvt/xtwo_byte
- stl/inc/regex
- stl/inc/xlocbuf
- stl/src/xdateord.cpp
- stl/src/xlsinh.cpp
- stl/src/xsinh.cpp
This is more concise than sizeof/sizeof, and std::size is a constexpr so there shouldn't be any cost.
> Use std::size over sizeof/sizeof

- stl/src/xdnorm.cpp
- stl/src/xfdnorm.cpp
This follows best practices without changing behavior
> Move assignment of xchar to declaration

- stl/src/vector_algorithms.cpp
This is faster in some instances and is clearer in intent
> Use a bitwise and instead of shifts

- stl/src/xdscale.cpp
- stl/src/xdtest.cpp
- stl/src/xfdscale.cpp
- stl/src/xfdtest.cpp
It just makes more noise were it should not happen.
> Remove unneeded static_cast of return values.

- README.md
https://wg21.link/n4917 is not working currently but probably will be updated before this PR will be merged.
github release: https://github.com/cplusplus/draft/releases/download/n4917/n4917.pdf
> update working draft revision to N4917

- stl/inc/iterator
- stl/inc/xutility
- tests/std/tests/GH_002992_unwrappable_iter_sent_pairs/test.compile.pass.cpp
fixes #3009 
There are two new concepts - `_Weakly_unwrappable_sentinel` and `_Weakly_unwrappable_iterator` - these are useful for implementation of wrapper types which are unwrappable when their underlying type is unwrappable (like `move_iterator`/`move_sentinel`)
> Add unwrapping to move_sentinel

- CMakeLists.txt
- README.md
- azure-devops/provision-image.ps1
- azure-pipelines.yml
- tools/CMakeLists.txt
- tools/format/CMakeLists.txt
- tools/validate/CMakeLists.txt
* Updated build compiler to VS 2022 17.4 Preview 2.
* Updated CMake to 3.24 (now required).
* Updated Python to 3.10.7.
Contains Patch Tuesday.
> Toolset update: VS 2022 17.4 Preview 2

- stl/inc/format
- stl/inc/yvals_core.h
- tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
- tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
This implements [P2508R1](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2508r1.html).
Fixes #2937.
The paper mentions that
> This doesn’t strictly have to be a DR, and could certainly just be a C++23 feature.
But I strongly hope that this can be applied to C++20, so the signature of `std::format` does not change between C++20 and C++23.
> Implement P2508R1 basic_format_string, format_string, wformat_string

- stl/inc/random
- tests/std/test.lst
- tests/std/tests/GH_003105_piecewise_densities/env.lst
- tests/std/tests/GH_003105_piecewise_densities/test.compile.pass.cpp
- tests/std/tests/GH_003105_piecewise_densities/test.cpp
This function converts a `vector` of `double` to a `vector` of `_Ty`, which is a narrowing conversion when `Ty` is `float`. It's silly to warn about this when the Standard makes it clear that the narrowing will occur, and the user has asked for such explicitly by calling `piecewise_constant_distrubution<float>::densities`.
Fixes #3105.
> Suppress narrowing warnings in `piecewise_constant_distribution::densities`

- stl/inc/algorithm
- tests/std/tests/P0896R4_ranges_alg_is_permutation/test.cpp
> Fix `ranges::is_permutation`'s helper lambdas

- stl/inc/any
- stl/inc/yvals_core.h
- stl/modules/std.ixx
- tests/std/include/test_header_units_and_modules.hpp
- tests/std/tests/P2465R3_standard_library_modules/env.lst
- tests/std/tests/VSO_0000000_has_static_rtti/test.cpp
- tests/std/tests/VSO_0157762_feature_test_macros/env.lst
- tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
This PR is making `#include <any>` effectless rather than erroneous when static RTTI is disabled.
Fixes #3114.
> `<any>`: Skip the contents when static RTTI is disabled

- stl/inc/xatomic.h
- stl/inc/xbit_ops.h
- stl/inc/xerrc.h
- tests/std/tests/GH_001411_core_headers/test.cpp
And add test coverage for internal core headers in `std/tests/GH_001411_core_headers`.
Some internal core headers are not separatedly tested because they are included by standard core headers.
Fixes #3103.
> Make `<xatomic.h>`, `<xbit_ops.h>`, and `<xerrc.h>` core headers

- tests/std/tests/P0356R5_bind_front/test.cpp
- tests/std/tests/P2387R3_bind_back/test.cpp
Closes #968.
This PR *constexprizes* already existing tests and adds extra PMF test for `bind_back`.
> Constexprize `bind_front` and `bind_back` tests

- tests/std/tests/P0896R4_ranges_subrange/test.compile.pass.cpp
The intent is that `illformed<T>()` be ill-formed so the primary `kind_of` template fails instantiation, but unfortunately it's ill-formed with no diagnostic required since no specialization of this template could be valid. (Unqualified lookup for `illformed` finds nothing, and ADL can find nothing since there are no arguments and therefore no associated namespaces.)
Reported internally by the FE team. This is the STL-specific portion of MSVC-PR-425776.
> Fix ill-formed primary template in P0896R4_ranges_subrange

- stl/msbuild/stl_1/dirs.proj
- stl/msbuild/stl_1/md/dirs.proj
- stl/msbuild/stl_1/msvcp_1.settings.targets
- stl/msbuild/stl_1/xmd/dirs.proj
- stl/msbuild/stl_2/dirs.proj
- stl/msbuild/stl_2/md/dirs.proj
- stl/msbuild/stl_2/msvcp_2.settings.targets
- stl/msbuild/stl_2/xmd/dirs.proj
- stl/msbuild/stl_asan/dirs.proj
- stl/msbuild/stl_atomic_wait/dirs.proj
- stl/msbuild/stl_atomic_wait/md/dirs.proj
- stl/msbuild/stl_atomic_wait/msvcp_atomic_wait.settings.targets
- stl/msbuild/stl_atomic_wait/xmd/dirs.proj
- stl/msbuild/stl_base/dirs.proj
- stl/msbuild/stl_base/md/dirs.proj
- stl/msbuild/stl_base/msvcp.settings.targets
- stl/msbuild/stl_base/mt/dirs.proj
- stl/msbuild/stl_base/mt1/dirs.proj
- stl/msbuild/stl_base/xmd/dirs.proj
- stl/msbuild/stl_base/xmt/dirs.proj
- stl/msbuild/stl_base/xmt0/dirs.proj
- stl/msbuild/stl_base/xmt1/dirs.proj
- stl/msbuild/stl_codecvt_ids/dirs.proj
- stl/msbuild/stl_codecvt_ids/md/dirs.proj
- stl/msbuild/stl_codecvt_ids/msvcp_codecvt_ids.settings.targets
- stl/msbuild/stl_codecvt_ids/xmd/dirs.proj
- stl/msbuild/stl_post/dirs.proj
- stl/msbuild/stl_post/md/dirs.proj
- stl/msbuild/stl_post/msvcp_post.settings.targets
- stl/msbuild/stl_post/xmd/dirs.proj
This mirrors the `src/vctools/crt/github` changes from Andrew Dean's internal MSVC-PR-422642.
Note that that PR must target `prod/be`, so this will result in temporary divergence between microsoft/STL's GitHub repo and the internal `prod/fe` branch (with which we're usually binary-identical at all times). I believe that this is tolerable because the `stl/msbuild` files change so rarely, and even if we do need to make changes (e.g. adding a new source file), there should be no major conflicts.
> Port MSBuild refactoring

- stl/inc/format
[[format.arg.store]](http://eel.is/c++draft/format.arg.store#2)
> *Preconditions*: The type <code>typename Context​::​template formatter_­type<T<sub>i</sub>></code> meets the *BasicFormatter* requirements ([[formatter.requirements]](http://eel.is/c++draft/formatter.requirements)) for each <code>T<sub>i</sub></code> in `Args`.
Currently, this precondition isn't checked. If an user passes an unformattable type, the error message will likely start with "'std::_Format_arg_traits<_Context>::_Phony_basic_format_arg_constructor': none of the 5 overloads could convert all the argument types", which isn't quite helpful.
Before LWG-3701, It was impractical to check this precondition, because even `std::format("Hello {}!\n", "world")` was a precondition violation. This is no longer a concern after …
> Check `make_format_args`'s preconditions

- stl/src/tzdb.cpp
When no mapping for a Unicode character existed in the target multi-byte code page, we just returned that error from
`__std_fs_convert_wide_to_narrow`; instead, we additionally needed to `SetLastError()` after that call.
Fixes #3097 (kind of)
The issue was that if the language of the system was not representable by the current code page, we would throw `GetLastError()`; however, last error was never actually set.
> No more 'operation completed successfully' in `time_zone::get_info`

- stl/inc/format
* Remove `#include <algorithm>` after changing uses of `_RANGES transform` to a simple for-loop.
* I considered using `std::copy` when `_CharT` is same as `char`, but since `_OutputIt` is usually `std::back_insert_iterator<_Fmt_buffer<_CharT>>`, I believe that `std::copy` is not more optimized than a simple loop.
* Remove `#include <exception>`. AFAIK `<format>` does not directly use anything in it (and `<stdexcept>` already includes it).
* Replace `#include <string>` and `#include <string_view>` with `#include <xstring>`. AFAIK `<format>` does not need `getline`, `stoi` or `to_string` defined in `<string>`, so `<xstring>` should suffice.
> <format>: reduce header dependency

- tests/std/tests/P0898R3_concepts/test.cpp
- tests/tr1/include/tspec_random.h
I validated the STL against Clang 15.0.1, which may be shipping Soon(TM) with Visual Studio.
* Clang's "initialized but unused variable" warning got smarter, and noticed that `do_random_test::gen_data` in `tests/tr1/include/tspec_random.h` initialized `int n = 0`, incremented `n` some number of times, and never used the resulting value. I've removed the offending variable.
* Clang diagnosed the subsumption test in `tests/std/P0898R3_concepts` as ill-formed due to ambiguity. The test does something like: ```c++ constexpr bool f(auto&&) { return false; } constexpr bool f(integral auto) { return true; } static_assert(f(42)); ``` intending that `f(integral auto)` is called with the belief that its contraints subsume those of `f(auto&&)`. This was derived from similar subsumption tests I wrote …
> Fix test suite issues discovered by Clang 15

- stl/inc/yvals_core.h
Updates _MSVC_STL_UPDATE to "202210L" (October 2022).
Resolves https://github.com/microsoft/STL/issues/3143
> <yvals_core.h>: Update _MSVC_STL_UPDATE to October 2022

- stl/inc/variant
- tests/std/tests/P0088R3_variant/test.cpp
Qualifies calls to namespace-scope functions in `<variant>`, and enables the libc++ ADL test that now passes.
Partially addresses #140
> `_STD`-qualify `_Ugly` non-member function calls in `<variant>`

- stl/inc/atomic
- stl/inc/memory
- stl/inc/xatomic.h
- stl/inc/xmemory
Towards #3048.
@MattStephanson @barcharcraz
I think we can include `<xatomic.h>` in `locale0.cpp` once this PR gets merged as `<xatomic.h>` has been made a core header, and avoid the third copy of these macro definitions. This should have no undesired impact on the size of import library.
~I guess these macros should still be `#undef`ed in `<atomic>`, so I copied the comments in `<atomic>` with modifications.~
The separated `#undef` directives in `<atomic>` are being removed.
> Move barrier macros from `<atomic>` to `<xatomic.h>`

- CMakeLists.txt
- README.md
- azure-devops/cmake-configure-build.yml
- azure-devops/cross-build.yml
- azure-devops/native-build-test.yml
- azure-pipelines.yml
- benchmarks/CMakeLists.txt
- benchmarks/src/std_copy.cpp
Additionally makes benchmarks separate from the STL build, since we keep having problems when google benchmark is built in the STL build.
> Update google-benchmark to 1.7.0

- stl/inc/__msvc_int128.hpp
- tests/std/tests/P1522R1_difference_type/test.cpp
These partial specializations are unnecessary, because the default mechanisms (the conditional operator and implicit conversions) are already doing right things. It's surprising that the necessity of these specializations hasn't been discussed in #2518.
https://github.com/microsoft/STL/blob/1fe4d4319b74d6d0738420b549fdfdacb304a647/stl/inc/__msvc_int128.hpp#L1029-L1043
https://github.com/microsoft/STL/blob/1fe4d4319b74d6d0738420b549fdfdacb304a647/stl/inc/__msvc_int128.hpp#L1430-L1444
And the non-concept versions (added by me) may do evil - they may opt-out common types when there can be valid ones. Although this is probably not a conformance issue, as when concepts are not available, these integer-class types are just implementation details.
> `<__msvc_int128.hpp>`: Remove unnecessary `common_type` partial specializations

- tests/std/tests/P0024R2_parallel_algorithms_is_partitioned/test.cpp
* Guard test case that requires ranges of length at least 4
* Remove unnecessary `std::`-qualifications
Validated both normal and `EXHAUSTIVE` runs complete successfully.
See #3172.
> Cleanup tests/P0024R2_parallel_algorithms_is_partitioned

- stl/inc/execution
- stl/inc/ranges
- stl/inc/span
- stl/inc/system_error
- stl/inc/xstring
- tests/std/tests/P0896R4_views_transform_death/test.cpp
- tests/std/tests/P2278R4_basic_const_iterator/test.cpp
- tests/std/tests/P2322R6_ranges_alg_fold/test.cpp
Mostly things I noticed while reviewing the last import batch at the last minute that were not worth resetting testing for, but does include a couple of "old" changes as well.
Separate commits to ease review:
* "`basic_string::_Move_construct_from_substr` already knows the allocator": avoids passing an allocator to this member function which can simply retrieve the stored allocator.
* "Consistently guard `_Verify_offset(-n)` against `-INT_MIN`" (in `<ranges>`): we had a couple of places that guarded against overflow negating the argument to `_Verify_offset`, we should do so consistently.
* "Cleanup `_NOEXCEPT_IDL0`": Removes this variation in `noexcept` between debug and release builds - it was a terrible idea. Make `transform_view::iterator::_Verify_offset` always `noexcept` by avoiding …
> Miscellaneous Cleanups

- README.md
I asked Matt Godbolt how he'd prefer this sentence, he said
> I don't have a strong opinion, I'd probably just say Compiler Explorer if it were up to me though
> README.md: Adjust Compiler Explorer link wording

- stl/inc/type_traits
- stl/inc/utility
- stl/inc/yvals_core.h
This adds support for the detection and application of the `[[msvc::intrinsic]]` attribute which will allow the compiler to internally implement _some_ functionality of the STL without a function call.
> add support for [[msvc::intrinsic]]

- README.md
- azure-devops/provision-image.ps1
- azure-pipelines.yml
- stl/inc/xstring
- tests/std/tests/Dev10_816787_swap_vector_bool_elements/test.cpp
- tests/std/tests/P0980R1_constexpr_strings/test.cpp
- tests/std/tests/P1004R2_constexpr_vector/test.cpp
- tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp
- tests/std/tests/P2321R2_proxy_reference/test.cpp
- tests/std/tests/VSO_0000000_allocator_propagation/test.cpp
* New 1ES Hosted Pool, containing Patch Tuesday.
* New toolset, VS 2022 17.5 Preview 1.
+ This is not yet required in `<yvals_core.h>`, because the MSVC-internal build is still using MSVC 19.34.
* This also contains Python 3.11.0 (with major performance improvements, although it doesn't make a massive difference for our test runs, which are dominated by compile time).
+ Not updating the minimum required version, as the VS Installer still offers Python 3.9.7.
* Use PowerShell 7.3.0 while preparing the VM.
+ Note that PowerShell 7.3.0 can't be used locally while preparing the 1ES Hosted Pool. As mentioned in the [Checklist for Toolset Updates](https://github.com/microsoft/STL/wiki/Checklist-for-Toolset-Updates), there's an active Azure PowerShell bug about this.
* Remove EDG compiler bug …
> Toolset update: VS 2022 17.5 Preview 1, Python 3.11.0

- tests/std/tests/P0943R6_stdatomic_h/test.compile.pass.cpp
> enable P0943R6_stdatomic_h test for clang

- stl/inc/yvals_core.h
Updates _MSVC_STL_UPDATE to "202211L" (November 2022).
Resolves #3189
> <yvals_core.h>: Update _MSVC_STL_UPDATE to November 2022

- stl/inc/__msvc_cxx_stdatomic.hpp
> Change an error message in `<__msvc_cxx_stdatomic.hpp>`

- .vscode/settings.json
This is a workaround for microsoft/vscode#103235.
I kept being annoyed that my submodules would open in VS Code, despite turning detection off. This fixes that issue.
> [vscode settings] add `git.ignoredRepositories`

- stl/inc/type_traits
- tests/std/tests/VSO_0493909_is_aggregate/test.compile.pass.cpp
Fixes #3229.
I suppose this is a temporary workaround. It would become unnecessary when compiler changes land.
> Implement LWG-3823 Unnecessary precondition for `is_aggregate` (workaround)

- stl/inc/xlocale
- stl/inc/xloctime
- tests/std/include/test_header_units_and_modules.hpp
* Related cleanup: don't mark `time_put` partial specializations as `_CRTIMP2_PURE_IMPORT`.
+ The primary template isn't marked: https://github.com/microsoft/STL/blob/009881898c2112f92ab7ee743eadb148c01329c9/stl/inc/xloctime#L651-L652 @cdacamar made the surprising discovery that the compiler has always ignored marked partial specializations in this scenario - see VSO-1674115 "`__declspec(dllimport)` on partial specialization has no semantic meaning". It's deeply confusing to retain something that has no effect, so I'm removing it.
+ I audited for other occurrences, and these appear to be the only ones.
+ I verified that the release and debug dllexports are unchanged. (Additionally, we have dllexport validation in the MSVC-internal build.)
* Mark `time_put` partial specializations as …
> Standard Library Modules: Fix `time_put<wchar_t>` linker errors

- stl/inc/yvals.h
- stl/src/cerr.cpp
- stl/src/cin.cpp
- stl/src/clog.cpp
- stl/src/cout.cpp
- stl/src/init_locks.hpp
- stl/src/iosptrs.cpp
- stl/src/stacktrace.cpp
- stl/src/syncstream.cpp
- stl/src/taskscheduler.cpp
- stl/src/wcerr.cpp
- stl/src/wcin.cpp
- stl/src/wclog.cpp
- stl/src/wcout.cpp
- stl/src/xlock.cpp
I observed a curious message "Creating library meow.lib and object meow.exp" when consuming `import std;` with VS 2022 17.5 Preview 1. This doesn't repro when using the 17.5p1 compiler to consume `import std;` from microsoft/STL `main`; it repros only with the shipped machinery. I haven't figured out what the difference is yet, but I did find the root cause of the message.
The problem is that when we inject `stacktrace.cpp` into the import lib, it drags in `yvals.h` and the headache-inducing `_Init_locks`. In #3019, we guarded `_Init_locks` with `_CRTBLD` so it wouldn't affect users of `stl/inc`, but the problem here is that `stacktrace.cpp` *is* part of the STL's build, so `_Init_locks` is being emitted.
I have two fixes for this (either alone would be sufficient but I want to be extra …
> Standard Library Modules: Fix spurious `_Init_locks` dllexport

- stl/inc/xstring
... or we will have horrible failures when linking with object files from 17.3. `_Construct` must null-terminate the string itself on all control paths. I've added a comment to the `_String_val::_Bxty` constructor directing us not to rely on the semantic changes introduced in 17.4 to avoid regressing.
> Don't rely on SSO zeroing in `basic_string::_Construct`

- stl/inc/atomic
- stl/inc/ranges
- stl/inc/thread
- stl/inc/type_traits
- stl/inc/xutility
- tests/std/tests/P0660R10_jthread_and_cv_any/test.cpp
We no longer need comments for LWG issues that are now Standard. This includes comment cleanup for:
* LWG-3569,
* LWG-3766, and
* LWG-3788.
This also removes `/* strengthened */` comments for functions that are now `noexcept`:
* `atomic_meow` functions made `noexcept` by LWG-3745, and
* `reference_wrapper::operator()` made conditionally `noexcept` by LWG-3764.
> Update comments for approved LWG issues

- stl/src/ppltasks.cpp
This fixes internal VSO-1684985, a high-priority bug reported by 4 customers through support cases. The scenario happens when a program:
* Was built with VS 2015
* Uses a "Single-Threaded Apartment"
+ DirectX reportedly requires this, so it's common
+ In the provided repro, this is activated by calling `CoInitialize(nullptr)`
* Calls `get()` on a `future` returned by `std::async()`
* Runs on an end user's machine with the VS 2022 17.4 redist installed
+ This is why we're hearing about it now
When these stars align, the program crashes due to ppltasks machinery throwing an `invalid_operation` exception that slams into `noexcept`, so no recovery is possible.
`future::get()` eventually calls into this code in `ppltasks.h`:
```cpp
struct _Task_impl_base
{
// ...
task_status _Wait()
{
bool …
```
> ppltasks.cpp: Fix bincompat for VS 2015

- stl/inc/algorithm
- stl/inc/xutility
- tests/std/tests/Dev11_0316853_find_memchr_optimization/test.cpp
> fix and rename `_Within_limits`, add tests

- stl/debugger/STL.natvis
This PR aims to implement the requested fixes outlined in https://github.com/microsoft/STL/pull/3044/files
In general, I prefer the approach of requiring function evaluation as it helps keep the visualizer code layout-independent.
Let me know if there's anything to be changed!
> Add error_code, error_category support to visualizer

- stl/inc/xutility
- tests/std/test.lst
- tests/std/tests/LWG3545_pointer_traits_sfinae/env.lst
- tests/std/tests/LWG3545_pointer_traits_sfinae/test.compile.pass.cpp
> Implement LWG-3545 `std::pointer_traits` should be SFINAE-friendly

- stl/debugger/STL.natvis
`optional<*>` originally used `<Intrinsic>`s for `_Has_value` and `_Value`; however, apparently VS doesn't like doing custom visualizers for `<Intrinsic>` calls.
Fixes VSO-1631025 / DevCom-10155697
> fix stl.natvis `std::optional<*>`

- stl/inc/xlocale
- tests/std/tests/Dev09_056375_locale_cleanup/test.cpp
And then the exception specification can be strengthened.
`_C_str` always returns a non-null pointer to an NTBS, so it's safe to directly pass the result to `strcmp`.
> `<xlocale>`: Avoid allocation when comparing two `locale` values

- stl/inc/cmath
- tests/std/test.lst
- tests/std/tests/GH_003246_cmath_narrowing/env.lst
- tests/std/tests/GH_003246_cmath_narrowing/test.compile.pass.cpp
This template implements the "sufficient additional overloads" for two-argument `<cmath>` functions (`atan2`, `hypot`, `pow`, `fmod`, `remainder`, `copysign`, `nextafter`, `fdim`, `fmax`, and `fmin`) by calling either an intrinsic or a C library function either of which expects `double` arguments. We previously converted the arguments to `_Common_float_type_t` which is `long double` when at least one argument is `long double`, resulting in narrowing conversion warnings at `/W4`. We now convert the arguments to `double` instead of `_Common_float_type_t`.
Fixes #3246
> Convert arguments to double in `_GENERIC_MATH2_BASE`

- stl/inc/execution
- stl/inc/iosfwd
These `operator!=` and `operator==` overloads are being removed in C++20 and later modes in the spirit of [P1614R2](https://wg21.link/p1614r2). Also strengthening the exception specifications for some members and friends of `fpos`, given they don't rely on `_Statetype`.
`<experimental/*>`, `<hash_map>`, and `<hash_set>` are not touched, because they are subject to removal in vNext, and it's unwise for everyone to used these components in C++20 and later modes.
It seems that MSVC STL delegates test cases for `fpos` to libcxx, so I haven't added a test...
> `<execution>`, `<iosfwd>`: Cleanup for `operator!=` and `operator==` with reversed order

- stl/inc/compare
- stl/inc/yvals_core.h
- tests/std/tests/P0768R1_spaceship_cpos/test.cpp
Fixes #3211. I believe that these changes should be applied to C++20 mode, as the paper is very near to an LWG DR.
No change is needed for the rest of P2167R3, because it's "something that increases the restrictions placed on users, but implementers aren't expected to enforce those restrictions".
> Implement P2167R3 Improving `boolean-testable` Usage (for comparison fallback CPOs)

- stl/inc/xutility
- tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
> Implement LWG-3646 `std::ranges::view_interface::size` returns a signed type 

- stl/inc/xutility
Fixed #3245
My test: https://godbolt.org/z/a7zaa4Yqo
> `<algorithm>`: `count()` could use vectorization in C++14/C++17

- stl/inc/optional
- stl/inc/xutility
- tests/std/tests/P1614R2_spaceship/test.cpp
Fixes #3225.
I found that MSVC's behavior is strange during testing ([Godbolt link](https://godbolt.org/z/dfhqqKaPn)), so currently I haven't add the [original example](https://godbolt.org/z/T7f4sr8jv) yet.
```C++
#include <optional>
struct derived_optional : std::optional<int> {
friend bool operator==(const derived_optional&, const derived_optional&) = default;
friend auto operator<=>(const derived_optional&, const derived_optional&) = default;
};
int main()
{
derived_optional a;
std::optional<derived_optional> b;
#ifdef LESS // If b < a is not skipped, then MSVC accepts b <=> a.
(void) (b < a);
#endif
(void) (b <=> a);
}
```
> Implement LWG-3746 `optional`'s spaceship with `U` with a type derived from `optional` causes infinite constraint meta-recursion

- stl/inc/ranges
- tests/std/tests/P0896R4_views_common/test.cpp
Fixes #3221.
Perhaps "random access iterators that only work with its difference type" is useful for conformance test and can be used elsewhere....
> Implement LWG-3717 `common_view::end` should improve `random_access_range` case

- CMakeLists.txt
- README.md
- azure-devops/provision-image.ps1
- azure-pipelines.yml
- benchmarks/CMakeLists.txt
- stl/inc/xstring
- stl/inc/yvals_core.h
- tests/std/tests/P2321R2_views_zip/test.cpp
- tests/std/tests/P2465R3_standard_library_modules/env.lst
- tools/CMakeLists.txt
- tools/format/CMakeLists.txt
- tools/validate/CMakeLists.txt
+ Updated build compiler to VS 2022 17.5 Preview 2 (now required).
+ Updated CMake to 3.25 (now required).
+ Updated Python to 3.11.1.
* New 1ES Hosted Pool, containing Patch Tuesday.
* Use PowerShell 7.3.1 while preparing the VM.
* Remove workaround for VSO-1655459 "C1XX Assertion failed ... in ParseTree.cpp, with C++23 `zip_view`".
* Remove workaround for VSO-1675318 "EDG `__builtin_memcmp` misbehavior, part 3".
* Add workaround for VSO-1705654 "Standard Library Modules: `/analyze` ICE".
* Add workaround for CMake-24249 'Error when requiring CMake 3.25: "`MSVC_DEBUG_INFORMATION_FORMAT` value `'ProgramDatabase'` not known for this `ASM_MASM` compiler"'.
> Toolset update: VS 2022 17.5 Preview 2

- stl/inc/ranges
- stl/inc/yvals_core.h
- tests/std/test.lst
- tests/std/tests/P2278R4_views_as_const/env.lst
- tests/std/tests/P2278R4_views_as_const/test.cpp
- tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Closes #2918 - "`cbegin` should always return a constant iterator".
* Implemented ["As const view"](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2278r4.html#as-const-view-range.as.const) section from the paper,
* Implemented LWG-3811.
> P2278R4: `views::as_const`

- stl/inc/xutility
- tests/std/tests/Dev11_0316853_find_memchr_optimization/test.cpp
Fixes #3249 
~~Depends on #3247~~
> `<algorithm>`: `find`/`count` vectorize moar

- stl/inc/algorithm
- stl/inc/functional
- stl/inc/xutility
- stl/inc/yvals_core.h
- tests/std/test.lst
- tests/std/tests/P1223R5_ranges_alg_find_last/env.lst
- tests/std/tests/P1223R5_ranges_alg_find_last/test.cpp
- tests/std/tests/P1223R5_ranges_alg_find_last_if/env.lst
- tests/std/tests/P1223R5_ranges_alg_find_last_if/test.cpp
- tests/std/tests/P1223R5_ranges_alg_find_last_if_not/env.lst
- tests/std/tests/P1223R5_ranges_alg_find_last_if_not/test.cpp
- tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Fixes #2913.
I hope I'm doing the unwrapping, re-unwrapping stuff correctly.
> P1223R5: find_last, et al.

- stl/inc/algorithm
- stl/inc/execution
- stl/inc/format
- stl/inc/memory
- stl/inc/regex
- stl/inc/vector
- stl/inc/xlocnum
- stl/inc/xmemory
- stl/inc/xutility
- tests/std/tests/P0784R7_library_machinery/test.cpp
I've also consistently qualified calls to namespace-scope function templates ("things") defined in `_RANGES` that have both qualified and unqualified calls. I have _not_ qualified calls to things defined only in either `_STD` or `_RANGES` for which all existing calls are unqualified. (This isn't trying to be a "let's qualify all ugly calls" change, but only "let's make it clear that we're fixing #3203".)
Fixes #3203
> Qualify calls to helpers that are in both _STD and _RANGES

- stl/inc/future
- stl/inc/system_error
- stl/inc/valarray
- stl/inc/xiosbase
- tests/std/tests/Dev11_0493504_error_category_lifetime/test.cpp
Fixes #3216.
Also adding `_STD`-qualifications to calls in `<future>` and `<xiosbase>`, because these calls always find overloads declared in `std::` and it is unnecessary to enable ADL for them.
Some previously accepted codes will be rejected after these changes. Unfortunately, I don't know how to examine such cases in tests, because only hard errors would occur.
> Implement LWG-3629 `make_error_code` and `make_error_condition` are customization points

- stl/inc/memory
- tests/std/tests/P1132R7_out_ptr/test.cpp
> Implement LWG-3594 `inout_ptr` - inconsistent `release()` in destructor

- stl/inc/experimental/filesystem
emplace_front would work better here than push_front, especially when we don't have to copy the object then
> Use emplace_front in filesystem

- stl/inc/vector
> Add checks for invalid iterator when _ITERATOR_DEBUG_LEVEL is non-zero

- stl/inc/future
- tests/std/tests/Dev11_0235721_async_and_packaged_task/test.cpp
This PR is making some enhancements for `<future>`.
1. Currently `std::is_nothrow_move_assignable_v<std::shared_future<void>>` is `false` in MSVC STL ([Godbolt link](https://godbolt.org/z/fvb85K8Wv)), which is non-conforming. This PR fixes this bug by making internal functions `noexcept` (inspired by #3278) and some special member functions defaulted.
2. Currently users can touch internal constructors by definition `std::future<T> ft(another_future, {});` (where `another_future` is of type `std::future<T>` or `std::shared_future<T>`) ([Godbolt link](https://godbolt.org/z/eqvr8nzPx)). This PR forbids such definitions - because I think the internal constructors shouldn't be directly touched when no _Ugly name is explicitly specified, although the status quo is conforming due to …
> Enhancements for `future` and `shared_future`

- stl/inc/__msvc_int128.hpp
- stl/inc/bit
- stl/inc/charconv
- stl/inc/cmath
- stl/inc/limits
- stl/inc/xatomic.h
- stl/inc/xbit_ops.h
- stl/inc/xcharconv_ryu.h
- stl/inc/yvals_core.h
- stl/src/vector_algorithms.cpp
- tests/std/tests/Dev11_1086953_call_once_overhaul/test.cpp
Addresses the problem mentioned in https://github.com/microsoft/STL/issues/2520#issuecomment-1345822701. We've had several issues with Clang and `intrin0.h` in the past, hopefully we can fix them "forever" by avoiding `intrin0.h` when compiling with Clang.
The existence of `intrin0.h` is purely an optimization in that it allows us to avoid including the entirety of `intrin.h`. We could support this optimization with Clang in the future by adding an `intrin0.h` to Clang's set of override headers. If we were to do so we should synchronize with libc++ on the proper set of intrinsics to move into `intrin0.h`.
> Don't use `<intrin0.h>` with Clang

- stl/inc/__msvc_int128.hpp
- tests/std/tests/P1522R1_difference_type/test.cpp
Hello,
I've noticed that the MSVC's STL provides `std::numeric_limits` template specialization
for the `std::_Signed128` (a type which models the `signed-integer-class` concept) slightly incorrectly,
that is the `std::numeric_limits<std::_Signed128>::is_signed` is `false` instead of `true`:
- https://godbolt.org/z/EcbE7Mrnq
This change fixes that issue and adds a couple of compile-time checks
verifying that the `std::numeric_limits<std::_Signed128>` is properly specialized.
> Fix for `std::numeric_limits<std::_Signed128>::is_signed`

- stl/src/stacktrace.cpp
... to avoid errors.
Fixes #3283
> Use symbolic constants in implementation of stacktrace

- README.md
- stl/inc/type_traits
- stl/inc/vector
- stl/inc/xutility
- tests/std/include/range_algorithm_support.hpp
Some changes too small to submit individually that I've been accumulating.
* `ranges_algorithm_support.hpp` includes `<cstddef>` but uses `size_t` unqualified; add `std::`-qualifications.
* MSVC (unreleased) and Clang (unreleased) have fixed `__is_aggregate`, but EDG has not. Disable the workaround in internal testing to avoid regression, and update the TRANSITION comment appropriately.
* `_To_signed_like` is unused, remove it.
* Improve error when `_Verify_offset` is called on an invalidated `vector` iterator.
* Mention `set_environment.bat` in `README.md`, and use it in the "How To Consume" example.
> Casey's miscellaneous branch

- stl/inc/xcharconv_ryu.h
- tests/std/tests/GH_002711_Zc_alignedNew-/env.lst
- tests/std/tests/GH_002711_Zc_alignedNew-/test.compile.pass.cpp
> Fix `C4365: '=': signed/unsigned mismatch` with `/J`

- stl/inc/deque
- stl/inc/format
- stl/inc/regex
- stl/inc/variant
- stl/inc/xmemory
- stl/inc/xutility
- stl/src/parallel_algorithms.cpp
> remove unused internal identifiers

- stl/inc/xiosbase
> add transition comment to `ios_base::hexfloat`

- README.md
Updated working draft to N4928 from N4917 in README.md. Fixes #3307
> Update working draft from N4917 to N4928

- stl/inc/future
- tests/std/tests/Dev11_0235721_async_and_packaged_task/test.cpp
Also update references to working draft to WG21-N4928 in `<future>`.
This is a follow-up change of #3284, and partially addresses #3278.
> Make some special member functions of `promise` and `packaged_task` defaulted

- stl/inc/xutility
- tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
When the argument is an _rvalue_ of an array, `ranges::cbegin`, `ranges::cend`, `ranges::crbegin`, and `ranges::crend` should reject it with substitution failures, despite of whether the element type is complete or not. I think such requirements haven't been changed by [P2278R4](https://wg21.link/p2278r4) (i.e. unchanged between C++20 and C++23).
(On the other hand, if the argument is an _lvalue_ of an array of an incomplete element type, the program is ill-formed, no diagnostic required.)
I originally discovered the bug of implementation in https://github.com/microsoft/STL/pull/3187#discussion_r1011340383, but hadn't determined how to fix it at that time. 
----
Clang 15 is buggy - it fails to perform shortcut in concept substitution when using requires-clause. This is probably LLVM-55945 …
> Fix handling of array rvalues for `ranges::cbegin` and its friends

- stl/inc/xutility
- tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
> Implement LWG-3736 `move_iterator` missing `disable_sized_sentinel_for` specialization

- stl/inc/ranges
- tests/std/tests/P1206R7_ranges_to_misc/test.cpp
Fixes #3227.
I failed to figure out how to "convert a range of `expected<T, E>` to `expected<vector<T>, E>`" with `ranges::to`, so I just added some trivial test cases...
> Implement LWG-3785 `ranges::to` is over-constrained on the destination type being a range

- stl/inc/ranges
- tests/std/tests/P0896R4_views_take/test.cpp
Fixes #3223.
(`counted_iterator<counted_iterator<T>>` seems a bit messy. Should I add a prettier test case?)
> Implement LWG-3737 `take_view::sentinel` should provide `operator-`

- stl/inc/mutex
This PR changes `_RERAISE` in `<mutex>` to scope guards (towards #2307).
And strengthens exception specifications for
- `_Mutex_base::unlock` (i.e. `mutex::unlock` and `recursive_mutex::unlock`), and
- move assignment operator of `unique_lock` ("reverting LWG-2104", addressing #3278).
> `<mutex>`: Scope guards for lock algorithms and exception specification strengthening

- stl/inc/expected
- tests/std/tests/P0323R12_expected/test.cpp
Clang is confused by explicit `noexcept` on a constexpr destructor for (I think) objects with non-trivially destructible anonymous union members. The workaround is to remove the explicit `noexcept` and let the compiler default it. ~~I think this is fine as a permanent condition, so I've added no transition comments.~~
> `<expected>`: Workaround LLVM-59854

- stl/inc/ranges
Test coverage will be in the next LLVM update.
Drive-by: let clang-format handle some more bits of code.
> `<ranges>`: Workaround LLVM-47414

- stl/inc/xfilesystem_abi.h
temporary export `_BITMASK_OPS` for `__std_fs_file_attr`
https://developercommunity.visualstudio.com/t/10247495
Fixes #3330
> workaround DevCom-10247495

- stl/inc/vector
- tests/std/tests/Dev11_0437519_container_requirements/test.compile.pass.cpp
- tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp
Fixes #3226.
Notes:
- The default constructor of `vector<bool, _Alloc>` need to default-construct an `_Alloc` instead of `_Alvbase` in order to implement the required exception specification. I think this is not related to allocator propagation and thus possibly not covered by LWG-3267.
- Edit: I have to change the test `P1004R2_constexpr_vector_bool` due to this. Not sure whether such change is right now...
- The constructor of `_Vb_val` from an allocator is always `noexcept`, so I changed the superfluous conditional `noexcept` to unconditional one.
- The constructor of `vector<bool, _Alloc>` from `(vector&&, const _Identity_t<_Alloc>&)` is not `noexcept` in the current working draft, so I added `// strengthened`.
- Exception specification of the move assignment operator of `vector<bool, …
> Implement LWG-3778 `vector<bool>` missing exception specifications

- stl/inc/xstring
- tests/libcxx/expected_results.txt
- tests/libcxx/skipped_tests.txt
I've never trusted our use of `_Traits::assign` to start the lifetimes of the elements given that, err, that's not what `_Traits::assign` does. Let's use a `construct_at` loop instead, and centralize it into a helper function instead of repeating nine times.
Test coverage is in libcxx - 7 skips fixed!
Drive-by: Use `_Traits::copy` instead of `_Traits::move` in `_Construct`. Since we're constructing a new string, we know the argument doesn't alias our content.
> `<xstring>`: constexpr string element lifetime

- docs/cgmanifest.json
- tests/std/tests/LWG3234_math_special_overloads/test.cpp
I will be the first to say it; I did in fact contribute to this release of Boost. However, it fixes a platitude of issues as this is a bugfix release.
Therefore, I think updating to 1.81 is worth it.
> Update Boost to 1.81

- CMakeLists.txt
- README.md
- azure-pipelines.yml
- stl/inc/memory
- stl/src/special_math.cpp
- tests/std/tests/GH_002030_asan_annotate_string/env.lst
- tests/std/tests/P0980R1_constexpr_strings/test.cpp
- tests/std/tests/P1004R2_constexpr_vector/test.cpp
- tests/std/tests/P1004R2_constexpr_vector_bool/test.cpp
- tests/std/tests/P2321R2_proxy_reference/test.cpp
- tests/std/tests/VSO_0000000_allocator_propagation/test.cpp
* Toolset update: VS 2022 17.5 Preview 3.
* Remove workarounds for VSO-1595465 "`/clr` `/std:c++17` ICE with `int = 0` SFINAE".
+ Verified with an internal build.
* Remove workaround for boostorg/math#853.
+ We picked up the fix with #3312.
* Drop `/Za` configs from `GH_002030_asan_annotate_string/env.lst`.
+ The rest of these were dropped by #2714 on 2022-05-12, then this file was added by #2196 on 2022-05-16.
* Drop the `STL_BUILD_BENCHMARKING` message.
+ This machinery was removed by #3151 on 2022-10-24, and we don't need to worry about anyone following the old instructions now.
* Update EDG bug workarounds:
+ VSO-1674140 (attempt to access expired storage) was partially fixed, so we can remove some workarounds.
+ Update the remaining workarounds to cite VSO-1726722 "EDG rejects …
> Toolset update: VS 2022 17.5 Preview 3

- stl/inc/fstream
- stl/inc/ios
- stl/inc/istream
- stl/inc/ostream
- stl/inc/spanstream
- stl/inc/sstream
- stl/inc/streambuf
- stl/inc/strstream
- stl/inc/syncstream
- stl/inc/xiosbase
- tests/std/tests/GH_001858_iostream_exception/test.cpp
This PR partially addresses #3278, but also strengthens exception specifications for some other functions. References to working draft are also updated to WG21-N4928.
Move assignment operators and `swap` functions are generally marked with `noexcept`. But I think move assignment operators of `basic_filebuf` and `basic_(i|o)fstream` shouldn't be `noexcept`, because they call `basic_filebuf::close` which may in turn call virtual functions that are possibly overridden. In other words, exception may be thrown from these move assignment operators. `basic_syncbuf`'s should neither be `noexcept` due to LWG-3498.
Many move constructors remain non-`noexcept`, because they need to _copy-construct_ a `basic_streambuf`, and hence need to dynamically allocate storage for `locale`. Maybe we should fix …
> Strengthen exception specifications for stream types

- stl/inc/__msvc_iter_core.hpp
- stl/inc/ranges
- stl/inc/span
- stl/inc/tuple
- stl/inc/utility
- stl/inc/xutility
- stl/inc/yvals_core.h
- tests/std/test.lst
- tests/std/tests/P2165R4_tuple_like_pair/env.lst
- tests/std/tests/P2165R4_tuple_like_pair/test.cpp
Towards #2917. Implements changes to [[pairs]](http://eel.is/c++draft/pairs) section.
The other goal of this PR is to move around some stuff, so that implementation of *`tuple-like`* concept is possible:
* Move `_Different_from` concept from `<xutility>` to `<utility>`,
* Move `_Is_subrange` variable template from `<ranges>` to `<utility>` and rename it to `_Is_subrange_v`,
* Move `_Is_std_array_v` variable from `<span>` to `<utility>`,
* Remove some redundant forward declarations.
> P2165R4: Compatibility Between `tuple`, `pair`, And tuple-like Objects (changes to `pair` only)

- stl/inc/vector
- tests/std/tests/GH_000625_vector_bool_optimization/test.cpp
On 32-bit platforms, the following program currently behaves incorrectly with MSVC STL - assertions fail (but pass on 64-bit platforms). [Godbolt link](https://godbolt.org/z/5bqYv1G6h).
```C++
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <memory>
template <class T>
struct huge_allocator {
huge_allocator() = default;
template <class U>
constexpr huge_allocator(const huge_allocator<U>) noexcept {}
using value_type      = T;
using size_type       = std::uint64_t;
using difference_type = std::int64_t;
T* allocate(std::uint64_t n) {
return std::allocator<T>{}.allocate(static_cast<std::size_t>(n));
}
void deallocate(T* p, std::uint64_t n) {
std::allocator<T>{}.deallocate(p, static_cast<std::size_t>(n));
}
};
int main() {
constexpr …
```
> Fix the behavior of `vector<bool, HugeAlloc>` whose size overflows `uint32_t`

- stl/inc/format
- stl/inc/xstring
- tests/libcxx/expected_results.txt
- tests/libcxx/skipped_tests.txt
- tests/std/tests/P0220R1_string_view/test.cpp
- tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
Fixes #3336.
The involved constructor of `basic_string_view` is introduced in C++23, so this PR also fixes the issue in C++20 mode in an alternative way.
Also updates references to working darft in `<format>` to WG21-N4928.
> Speculatively implement LWG-3857

- tests/std/tests/P0896R4_views_elements/test.cpp
This PR:
* Removes workarounds for VSO-1243263,
* Adds tests for `view_interface::cbegin` and `view_interface::cend`.
> Improve `views::elements` tests

- tests/libcxx/expected_results.txt
- tests/libcxx/magic_comments.txt
- tests/libcxx/skipped_tests.txt
- tests/libcxx/usual_matrix.lst
- tests/utils/stl/test/features.py
Update SHA and skip list(s), and some other changes:
* Tell `features.py` that we support `ja_JP.UTF-8`. Some of the libcxx `<format>`/`chronat` tests use that locale.
* Build libcxx tests with `/utf-8`. They write tests with the expectation that the source and execution character sets are both UTF-8, we should make it so to avoid failures.
* Build libcxx tests with [C6262 "Excessive stack size"](https://learn.microsoft.com/en-us/cpp/code-quality/c6262?view=msvc-170) disabled. A few tests use a ton of stack, and run just fine. It's not product code, and IMO not worth our time or theirs to rewrite such tests.
> Update LLVM submodule

- tests/libcxx/expected_results.txt
- tests/libcxx/skipped_tests.txt
The libcxx test `visit_format_arg.pass.cpp` is "unexpectedly passing" due to a stealth merge conflict:
* #3344 added this test, marked as a known failure
* #3348 fixed the bug that was causing this test to fail
MSVC-internal PR/CI runs aren't affected because they completely skip things in `skipped_tests.txt`. However, the GitHub CI noticed that the test was marked as `FAIL` yet was passing.
(I sometimes create GitHub PRs for testing purposes when merging a big stack of PRs, but didn't do so this time, which is how I missed it.)
> Fix XPASSing `visit_format_arg.pass.cpp`

- stl/CMakeLists.txt
- stl/modules/modules.json
This is a reverse mirror of MSVC-PR-445938. The goal is for the MSVC toolset to communicate to the IDE, MSBuild, and CMake where the Standard Library Modules are located, and the simple dependency relationship between them, so that `import std;` can automatically work with as little user effort as possible. (There will be more changes in the MSVC and VS repos to add properties and environment variables to communicate where this file is located.)
`modules.json` is JSON without comments, because multiple tools will need to read this file, and some might not support JSON-with-comments. (Accordingly, it lacks our usual banners.)
I've verified that `modules.json` is copied to the output directory (e.g. to `D:\GitHub\STL\out\x64\out\modules\modules.json`).
> Standard Library Modules: Add `modules/modules.json`

- stl/inc/__msvc_iter_core.hpp
- stl/inc/ranges
- tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
- tests/std/tests/P0896R4_views_transform/test.cpp
- tests/std/tests/P2441R2_views_join_with/test.cpp
Fixes #3228.
Also updates references to working draft in `<ranges>` and `P0896R4_ranges_iterator_machinery/test.cpp` to WG21-N4928.
Not all changes in LWG-3798 are implemented in this PR.
> Implement LWG-3798 Rvalue reference and `iterator_category`

- stl/inc/algorithm
- tests/libcxx/expected_results.txt
- tests/libcxx/skipped_tests.txt
- tests/std/tests/P0896R4_ranges_alg_minmax/test.cpp
Fixes #2900 
After https://github.com/microsoft/STL/pull/2958 the original repro works, but the issue still exists.
I also found that if we have only one element we also have the issue.
> `<algorithm>`: `ranges::minmax` should dereference iterators only once

- stl/inc/syncstream
- tests/std/tests/GH_001858_iostream_exception/test.cpp
> Speculatively implement LWG-3867

- stl/inc/ctime
- stl/modules/std.ixx
* Technically a bugfix: `module;` must appear first, although MSVC doesn't enforce this rule yet.
* Mark `<ctime>` workarounds as `inline`. This isn't necessary, but was recommended by @cdacamar.
* Update citation: DevCom-1126857 was "closed as lower priority" but OS-33790456 "`static inline` functions cannot be called when using modules" remains active.
> Minor modules modifications

- stl/inc/atomic
This mirrors Ben Niu's internal MSVC-PR-449792 "Re-implement `std::atomic` acquire/release/seqcst load/store using `__load_acquire`/`__stlr`" as of iteration 15. Note that this PR is targeted at the internal branch `prod/be`, thus there will be temporary divergence between GitHub and our usual branch `prod/fe`.
This relies on new compiler intrinsics, thus it won't be immediately active on GitHub until the necessary compiler and VCRuntime changes ship in a public Preview. Ben's benchmarking indicates **massive** performance improvements for load-acquire and store-release (around 14.1x to 23.8x speedups for officially supported chips - yes, times not percent) and significant performance improvements for sequentially consistent stores (1.58x speedups).
Ben has sworn a solemn oath on a basket …
> `<atomic>`: Improve ARM64 performance

- stl/inc/system_error
Currently `<system_error>` header uses non-reserved identifiers `clang` and `require_constant_initialization` which is incorrect (see #2645):
```console
PS D:\stl-playground> type .\clang_rci.cpp
// Non-reserved identifiers
#define clang
#define require_constant_initialization
#include <system_error> // Whoops!
PS D:\stl-playground> clang .\clang_rci.cpp
In file included from .\clang_rci.cpp:5:
D:\stl\out\build\x64\out\inc\system_error:646:7: error: expected ']'
[[clang::require_constant_initialization]] static _Ty _Static;
^
1 error generated.
```
This PR simply uglifies this attribute.
> `<system_error>`: Use uglified `[[clang::require_constant_initialization]]` attribute

- stl/inc/algorithm
The fix for #2900 in #3366 did not take advantage of the fact that the minimum and maximum elements of a range are always distinct except when the range has only one element. It couldn't easily do so due to the way `ranges::minmax` and `ranges::minmax_element` share the common backend `ranges::_Minmax_element_unchecked`.
This PR introduces a new backend for `ranges::minmax` (`ranges::_Minmax_fn::_Minmax_fwd_unchecked`) and makes `ranges::_Minmax_element_unchecked` the private member `ranges::_Minmax_element_fn::_Minmax_element_fwd_unchecked`. Since the two are distinct, `_Minmax_fwd_unchecked` can deal in values instead of iterators, and we can unroll the first loop iteration to detect the single-element case naturally. Since no additional branch is needed, we can enable the fix for #2900 …
> Refactor ranges::minmax and ranges::minmax_element

- stl/inc/xutility
Towards #2866
Reportedly, VSO-1488938 is not reproducible.
> Infinite range find algorithm: update transition comment for memchr optimization for ARM64

- tests/std/tests/P0088R3_variant/test.cpp
DevCom-10111923 and DevCom-10112408 (mistakenly treated as duplicate of the former) are reported as fixed in 17.4. I've tried to test the relative cases (added in #2971), but the tests still failed.
With some local tests, I'm sure that DevCom-10111923 is fixed in 17.4, but DevCom-10112408 is still not fixed (the posted example still fails to compile).
> Unmention DevCom-10111923 in test `P0088R3_variant`

- stl/src/atomic_wait.cpp
- stl/src/excptptr.cpp
- stl/src/memory_resource.cpp
- stl/src/multprec.cpp
- stl/src/parallel_algorithms.cpp
- stl/src/special_math.cpp
- stl/src/syncstream.cpp
- stl/src/syserror_import_lib.cpp
- stl/src/tzdb.cpp
- stl/src/xmath.hpp
- tests/std/tests/P2321R2_views_zip/test.cpp
> Change `_NODISCARD` in source and test files to `[[nodiscard]]`

- stl/inc/condition_variable
- stl/inc/mutex
- stl/inc/shared_mutex
- stl/inc/thread
- tests/libcxx/expected_results.txt
- tests/libcxx/skipped_tests.txt
- tests/std/tests/Dev11_1150223_shared_mutex/test.cpp
- tests/std/tests/P0156R2_scoped_lock/test.cpp
- tests/std/tests/VSO_0000000_condition_variable_any_exceptions/test.cpp
Fixes #3324. Towards #363.
These functions are made `noexcept`.
- `_Mutex_base::try_lock` (i.e. `mutex::try_lock`) (analysis: https://github.com/microsoft/STL/issues/3324#issuecomment-1422178980)
- `notify_all_at_thread_exit`
- `condition_variable`'s default constructor, `native_handle`, and `wait`
- `recursive_mutex`'s default constructor
- all `adopt_lock_t` constructors
Also make some special member functions defaulted.
- `thread::id`'s default constructor
- `unique_lock`'s default constructor
- `scoped_lock<>`'s default constructor and destructor, also strengthening exception specification
- `timed_mutex`, `recursive_timed_mutex`, and `shared_timed_mutex`'s default constructors, keeping exception specification strengthened (some comments were missing before, although IMO we don't need …
> Strengthen exception specifications for [thread] types

- .github/workflows/assign-new-prs.yml
Add a workflow to automatically assign a newly opened pull request to "Code Reviews" project.
This problem arose from https://github.com/microsoft/STL/pull/3390, where the `/pr` commands were used without the pull request being in the project.
Tested with https://github.com/sam20908/STL-PR-Workflow/pull/5.
> Assign new pull requests to Code Review

- stl/CMakeLists.txt
Our `ASM_MASM` options were being ignored (!) because they appeared after `add_library()`. This was visible in the output because `/nologo` was missing, we just didn't notice. (See output below.) This regression happened in #2780.
To fix this and prevent any recurrence, I'm slightly reorganizing this file. First, I'm introducing 3 prominent box comments, dividing the file into clear sections. The actual fix is to move `add_compile_options()` up. Finally, I'm moving `add_compile_definitions()` down slightly, so that the compile definitions, compile options, and include directories are grouped together.
I've additionally verified the fix by looking at the verbose build output; our desired options are now being passed to MASM.
```
D:\GitHub\STL>ninja -C out\x64
ninja: Entering directory …
```
> `stl/CMakeLists.txt`: Fix `add_compile_options()` ordering

- stl/inc/format
Fixes #1926.
The (current) cause of the issue is that currently `_Parse_format_string<char, _Format_handler<char>>` and its `wchar_t` variant are instantiated in `vformat_to` overloads (I'm not sure whether it's a bug of MSVC), and thus corresponding specializations of `visit_format_arg` are instantiated, so are `_Fmt_write` and eventually `use_facet` which touches `locale::id`.
I don't know how to write the test case for this...
----
It seems the MSVC STL implementation (or current standard specification?) is so type-erasing that we must pay the overhead for `locale::id` even when using `locale`-free `format` overloads.
> `<format>`: Make instantiation used by `vformat_to` lazier

- stl/inc/ranges
- tests/std/tests/P2442R1_views_slide/test.cpp
This PR adds `base` accessor to `ranges::slide_view` implemented in #2670.
Fixes #3409.
> LWG-3848: `slide_view` missing `base` accessor

- stl/inc/format
- tests/std/tests/P0645R10_text_formatting_args/test.cpp
> LWG-3810: CTAD for `basic_format_args`

- stl/inc/ranges
- tests/std/tests/P2278R4_views_as_const/test.cpp
> LWG-3850: `views::as_const` on `empty_view<T>` should return `empty_view<const T>`

- stl/inc/ranges
- stl/inc/yvals_core.h
- tests/libcxx/expected_results.txt
- tests/libcxx/skipped_tests.txt
> Implement P2711R1 Making Multi-Param Constructors Of Views `explicit`

- stl/inc/__msvc_chrono.hpp
- stl/inc/chrono
- stl/inc/xstring
- tests/std/tests/P0092R1_polishing_chrono/test.cpp
- tests/std/tests/P1522R1_difference_type/test.cpp
[CWG-2521](https://cplusplus.github.io/CWG/issues/2521.html) is recently accepted. It deprecates such form of literal operators.
Although such deprecation is not yet implemented as far, I think we can get rid of such form now.
> Eliminate spaces in `operator"" name()`

- stl/inc/yvals_core.h
- tests/libcxx/expected_results.txt
- tests/libcxx/skipped_tests.txt
- tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
No lines in `<barrier>` were actually touched.
I have verified that we have no test coverage on guarantees we eliminate.
Resolves #3440
> `<barrier>`: Declare victory!

- stl/inc/xutility
We implemented an earlier version of the resolution, this is the final version approved by WG21.
Fixes #3458
> LWG-3769 `basic_const_iterator::operator==` causes infinite constraint recursion

- stl/inc/deque
- stl/inc/queue
- stl/inc/syncstream
- stl/inc/xstring
- stl/inc/xutility
- stl/inc/yvals_core.h
- tests/std/tests/P0220R1_string_view/test.cpp
- tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Covers:
* LWG-3085
* LWG-3664
* LWG-3723
* LWG-3742
* LWG-3807
* LWG-3857
* LWG-3867
I've verified that we completely implement the resolutions of these issues.
Drive-by: remove extraneous `()` in the constraints on `basic_string_view`'s range constructor.
> Uncomment resolutions of applied LWG issues

- stl/inc/ranges
- stl/inc/tuple
Enforce the precondition when `_CONTAINER_DEBUG_LEVEL > 0`.
Drive-by: Fix conditional noexcept on the constructor, which requires adding conditional noexcept to `make_from_tuple`.
> LWG-3772 repeat_view's piecewise constructor is missing Postconditions

- tests/libcxx/expected_results.txt
- tests/libcxx/skipped_tests.txt
* All "libc++ doesn't implement (some proposal or LWG issue)" comments should be in the "ISSUES REPORTED/KNOWN UPSTREAM" section: libc++ knows what work WG21 has approved as well as we do.
* Strike noise word "yet" from all comments (e.g., "not yet implemented", "not yet analyzed")
* order "MISSING STL FEATURES" by proposal number
> Reorganize libc++ skips

- README.md
- azure-devops/create-1es-hosted-pool.ps1
- azure-devops/provision-image.ps1
- azure-pipelines.yml
* February 2023 Patch Tuesday.
* VS 2022 17.5 Preview 6.
* Python 3.11.2.
* Prepared with PowerShell 7.3.2.
Finally, we need to ask `Get-AzADServicePrincipal` to return the first result - we want `System.String` instead of `System.Object[]`. (I'm not sure when this breaking change appeared - if it was an update to Azure PowerShell, or if 1ES just started returning new results.)
> Toolset update: VS 2022 17.5 Preview 6

- stl/inc/xutility
- tests/std/tests/P2278R4_basic_const_iterator/test.cpp
> LWG-3853: `basic_const_iterator<volatile int*>::operator->` is ill-formed

- stl/modules/modules.json
@olgaark has requested that `modules.json` follow a new format before VS 2022 17.6 ships. This simply lists the source files for the Standard Library Modules in an array; the build system will discover what modules they provide, and their dependency relationship. As this has not yet shipped to users for General Availablity, the version number is still specified as 1.0.
> Finalize `modules.json` format

- CMakeLists.txt
- README.md
- azure-pipelines.yml
- benchmarks/CMakeLists.txt
- stl/CMakeLists.txt
- stl/inc/type_traits
- stl/inc/yvals_core.h
- tests/libcxx/expected_results.txt
- tools/CMakeLists.txt
- tools/format/CMakeLists.txt
- tools/validate/CMakeLists.txt
+ Updated build compiler to VS 2022 17.6 Preview 1 (now required).
+ Updated CMake to 3.25.2 (now required).
+ MSVC-PR-436582 updated C1XX's `__is_aggregate` for LWG-3823.
+ We can enable a couple of libcxx tests that were marked as FAILing for MSVC.
* CMake 3.25.2 fixed CMake-24249, so we can enable the [`CMP0141` policy](https://cmake.org/cmake/help/latest/policy/CMP0141.html).
+ Then, we need to set [`CMAKE_MSVC_DEBUG_INFORMATION_FORMAT`](https://cmake.org/cmake/help/latest/variable/CMAKE_MSVC_DEBUG_INFORMATION_FORMAT.html) to `Embedded`. This will pass the correct options to MSVC and MASM, avoiding `cl : Command line warning D9025 : overriding '/Zi' with '/Z7'`.
> Toolset update: VS 2022 17.6 Preview 1

- stl/inc/xiosbase
- tests/std/tests/P2467R1_exclusive_mode_fstreams/test.cpp
Fixes #3401 
If I understand correctly we can't change types of the variables but we can add operators.
> `ios_base` constants should have bitmask types

- stl/inc/mutex
Fixes #75. Fixes #3407.
----
This PR is currently subject to further changes, but decision is probably needed.
1. In the description of LWG-2309, SG1 suggested that `resource_deadlock_would_occur` should be thrown in the UB case; [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_lock.html) specifies `EAGAIN` (corresponding to `resource_unavailable_try_again`) on ownership level overflowing. While @BillyONeal preferred `abort()` for UB, and mentioned that SG1 suggested `terminate()` for overflowing (which, however, needs another LWG issue).
2. When implementing this, I strongly felt that it'd be better to divorce `mutex::lock` and `recursive_mutex::lock` because they have entirely different failing cases (same for `try_lock`). I guess they should be different …
> Implement LWG-2309 `mutex::lock()` should not throw `device_or_resource_busy`

- stl/inc/xutility
- tests/std/tests/P2278R4_basic_const_iterator/env.lst
- tests/std/tests/P2278R4_basic_const_iterator/test.cpp
> LWG-3872: `basic_const_iterator` should have custom `iter_move`

- stl/inc/xutility
- tests/std/tests/P2278R4_ranges_const_iterator_machinery/test.compile.pass.cpp
Closes #3428. Also improves test coverage for `common_type`.
> LWG-3862: `basic_const_iterator`'s `common_type` specialization is underconstrained

- stl/inc/format
Remove specialization `template<size_t N> struct formatter<const charT[N], charT>`
Fixes https://github.com/microsoft/STL/issues/3426
> LWG-3833 Remove specialization `template<size_t N> struct formatter<const charT[N], charT>`

- stl/inc/ranges
Adds extra constraints on type_Container that it can't be cv-qualified
Fixes #3417
Note: This is just a best guess attempt at a solution. I'm expecting I missed somethings here and will need to update
> LWG-3847 `ranges::to` can still return views

- stl/inc/xutility
- tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
> Implement LWG-3860 `range_common_reference_t` is missing

- stl/inc/ranges
- stl/inc/xutility
- tests/std/tests/P0323R12_expected/test.cpp
* `<ranges>`: wrap `zip_transform_view`'s constraints in a named concept so we can redeclare the class template, e.g., in a `friend` declaration. Repetitions of atomic constraints with equal expressions do not subsume, and Clang 16 is enforcing this rule more strictly.
* `<xutility>`: allow clang-format to format some more code, add some parens to keep it from going wild. Define a `_Store_size` helper concept for `subrange` instead of using a `static constexpr bool` class member as a perma-workaround for LLVM-60868.
* `tests/std/tests/P0323R12_expected`: Don't reference a local variable in a local class definition. (Clang 16 refuses to compile this; I suspect current compilers should as well.)
These changes don't make all tests pass with Clang 16, but should suffice to enable it to use …
> Workaround some Clang-16-rc2 regressions

- stl/inc/ranges
- tests/std/tests/P2474R2_views_repeat/test.cpp
> LWG-3875: `ranges::repeat_view<T, IntegerClass>::iterator` may be ill-formed

- stl/inc/charconv
- stl/inc/system_error
Same as #3478 but not from a microsoft/STL branch.
Link to internal codeql bugs:
* [VSO-1746341](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1746341)
* [VSO-1746390](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1746390)
I'm still not sure if we should have these, and I'm unsure how to test these changes.
> fix codeql warnings

- stl/inc/iterator
- stl/inc/ranges
- tests/std/include/range_algorithm_support.hpp
- tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
- tests/std/tests/P0896R4_views_elements/test.cpp
- tests/std/tests/P0896R4_views_join/test.cpp
- tests/std/tests/P0896R4_views_transform/test.cpp
- tests/std/tests/P2441R2_views_join_with/test.cpp
Fixes #3014.
Library parts affected by this issue:
* `move_sentinel<S>` (two constructors),
* `transform_view<R, F>::_Iterator`,
* `join_view<R>::_Iterator`,
* `join_with_view<R, P>::_Iterator` (two constructors),
* `join_with_view<R, P>::_Sentinel`
* `elements_view<R, N>::_Iterator`.
> `<ranges>`: Fix misused list-initializations

- stl/inc/regex
- tests/std/tests/Dev09_173612_tr1_regex_leak/test.cpp
> Implement LWG-3204 `sub_match::swap` only swaps the base class

- stl/inc/type_traits
- tests/std/tests/P2136R3_invoke_r/test.cpp
> Implement LWG-3655: The `INVOKE` operation and `union` types

- stl/inc/ranges
- tests/std/tests/P1206R7_ranges_to_misc/test.cpp
> Implement LWG-3733 `ranges::to` misuses `cpp17-input-iterator`

- stl/inc/bitset
- tests/std/tests/Dev08_576265_list_remove/test.cpp
- tests/std/tests/Dev11_0437519_container_behavior/test.cpp
- tests/std/tests/GH_002488_promise_not_default_constructible_types/test.cpp
- tests/std/tests/P0220R1_any/test.cpp
- tests/std/tests/P0220R1_optional/test.cpp
- tests/std/tests/P0608R3_improved_variant_converting_constructor/test.cpp
- tests/std/tests/P0674R1_make_shared_for_arrays/test.cpp
- tests/std/tests/P0784R7_library_support_for_more_constexpr_containers/test.cpp
- tests/std/tests/P0896R4_views_join/test.cpp
- tests/std/tests/P2231R1_complete_constexpr_optional_variant/test.cpp
@JonCavesMSFT just implemented a new off-by-default warning for VS 2022 17.7 Preview 1 (internal MSVC-PR-452406) that some internal teams are very interested in using. This warns about the deprecated case in WG21-N4928 [\[class.copy.ctor\]/6](https://eel.is/c++draft/class.copy.ctor#6) (emphasis mine):
> If the class definition does not explicitly declare a copy constructor, a non-explicit one is declared implicitly. If the class definition declares a move constructor or move assignment operator, the implicitly declared copy constructor is defined as deleted; otherwise, it is defaulted (9.5). **The latter case is deprecated** if the class has a user-declared copy assignment operator or a user-declared destructor (D.8).
and [\[class.copy.assign\]/2](https://eel.is/c++draft/class.copy.assign# …
> Avoid new warning C5267 for deprecated implicit copy ctor/assign

- stl/inc/mdspan
* Renames:
* `_Lhs` -> `_Left`,
* `_Rhs` -> `_Right`,
* `indexes` -> `indices` (part of several identifiers),
* `i` -> `_Ix` (unreserved identifier),
* `result` -> `_Result` (also unreserved identifier).
* Style:
* `explicit(...) constexpr` -> `constexpr explicit(...)` (looks like clang-format gives better result with the latter),
* Remove double empty lines,
* Always add empty line between functions,
* Reorder `span` and `const array&` constructors of `std::extents` to match the synopsis (see [[mdspan.extents]](http://eel.is/c++draft/mdspan.extents)),
* Add `_Get_dynamic_indices` function to `_Mdspan_extent_type` to avoid IIFE.
> `<mdspan>`: Various cleanups

- stl/inc/atomic
* `_ATOMIC_LOAD_VERIFY_MEMORY_ORDER` is not a good name, as it is an optional  memory barrier, not just a debug check
* move "these macros are _not_ always safe" above all unsafe macros
* preprocessor block comment as discussed in #351
> `<atomic>`: improve code documentation

- stl/inc/memory
- tests/std/tests/P1132R7_out_ptr/test.cpp
Fixes #3413.
I encountered a regressive bug in 17.6 Preview 1 and reported it as DevCom-10291456.
> Implement LWG-3734 Inconsistency in `inout_ptr` and `out_ptr` for empty case

- stl/inc/expected
- tests/std/tests/P2505R5_monadic_functions_for_std_expected/test.cpp
> Implement LWG-3877 Incorrect constraints on `const`-qualified monadic overloads for `std::expected`

- stl/inc/utility
- stl/inc/xmemory
- tests/std/tests/P0475R1_P0591R4_uses_allocator_construction/test.cpp
Fixes #3415.
LWG-3821 patches [P2165R4](https://wg21.link/p2165r4), so it should only be applied to C++23 mode. I think the overload added by LWG-3821 can be merged with the one added by LWG-3525.
> Implement LWG-3821 `uses_allocator_construction_args` should have overload for `pair-like`

- stl/inc/memory_resource
- tests/std/tests/P0220R1_polymorphic_memory_resources/test.cpp
... even when less than `_Default_next_capacity`.
Fixes #3408
> pool resources: respect `max_blocks_per_chunk`

- stl/inc/format
- tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
- tests/std/tests/P0645R10_text_formatting_parse_contexts/test.cpp
> Implement LWG-3720 Restrict the valid types of arg-id for width and precision in std-format-spec

- stl/inc/concepts
- stl/inc/type_traits
- stl/inc/yvals_core.h
- tests/std/tests/VSO_0000000_type_traits/test.cpp
- tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Fixes #3444.
I think the changes should be applied to C++20 mode as [this documentation](https://github.com/cplusplus/SG9/blob/main/2022-Telecons.md) said P2655 is possibly a DR.
Also
- moves `convertible_to` from `<concepts>` to `<type_traits>` for convenience,
- drops section numbers in `<type_traits>` (towards #182), and
- updates references to WD to WG21-N4928 in `<type_traits>` and `VSO_0000000_type_traits/test.cpp`.
> Implement P2655R3 `common_reference_t` Of `reference_wrapper` Should Be A Reference Type

- stl/inc/ranges
- stl/inc/yvals_core.h
- tests/std/test.lst
- tests/std/tests/P2164R9_views_enumerate/test.cpp
- tests/std/tests/P2321R2_views_adjacent/env.lst
- tests/std/tests/P2321R2_views_adjacent/test.cpp
Towards #2252. Implemented features:
* [\[range.adjacent\]](http://eel.is/c++draft/range.adjacent),
* Relevant parts of LWG-3848,
* Drive-by: add extra comment and remove unused using declaration in `views::enumerate`'s tests (my previous PR: #3472).
> P2321R2: `views::adjacent`, `views::pairwise`

- stl/inc/ranges
- tests/std/tests/P2442R1_views_chunk/env.lst
- tests/std/tests/P2442R1_views_chunk/test.cpp
- tests/std/tests/P2442R1_views_chunk_death/env.lst
> LWG-3851: `chunk_view::inner-iterator` missing custom `iter_move` and `iter_swap`

- stl/inc/__msvc_chrono.hpp
- stl/inc/bit
- stl/inc/limits
- stl/inc/tuple
- stl/inc/utility
- stl/inc/xmemory
For C++17's parallel algorithms, where we separately declare and define many of them, we developed a convention where the declaration is ` = 0` and the definition is `/* = 0 */`. This is a reminder that while the default template argument can't be repeated, we haven't simply forgotten it:
https://github.com/microsoft/STL/blob/994f94199c561a38a4a8e15584030160095bc25a/stl/inc/algorithm#L1124-L1125
https://github.com/microsoft/STL/blob/994f94199c561a38a4a8e15584030160095bc25a/stl/inc/execution#L1119-L1120
Thanks to Michael Grier for noticing that we've accumulated inconsistency elsewhere, with relics of an older convention where we'd name the template parameter in the definition `_Enabled`. That older convention was less clear and doesn't really provide new information (as we're already …
> Cleanups: Consistently comment `enable_if_t` definitions

- stl/inc/bit
Coalesce `_Byteswap_meow` and `byteswap`, follow Standard order - see WG21-N4928 [\[bit.syn\]](https://eel.is/c++draft/bit.syn).
Programmer archaeology: This was introduced by #2235, where we simply didn't mention Standard order while reviewing. It appears that the rationale for separating the helpers was that this grouped Standard functions together. These days, we prefer to follow Standard order unless there's a strong reason not to, and we're comfortable with interleaving helpers along the way (this makes it easier to see what the helpers are doing).
Note: There will be a trivial merge conflict between this PR's code movement and #3539 editing `countl_zero`'s adjacent definition.
> Cleanups: Follow Standard order for `byteswap` in `<bit>`

- stl/inc/bitset
- stl/inc/exception
- stl/inc/filesystem
- stl/inc/ranges
- stl/inc/xlocale
* When granting friendship to `bitset`, use its injected-class-name.
* In `<ranges>`, consistently grant access to the parent `meow_view`. This avoids needing forward declarations.
+ `join_view` is being updated by #3466, so I'm not changing it here.
+ This takes advantage of a C++ rule: nested classes are members of their parent class, so they have the same access rights as any other member. This means that if `Nested1` grants friendship to its `Parent`, then `Nested2` can now access `Nested1`'s internals.
+ Several other views/iterators are already using this scheme, so this increases consistency. It does widen the scope of friendship, but that doesn't really matter - a view and its iterators/sentinels are tightly coupled, so it's okay for the different parts to have access to one …
> Cleanups: Friendship is magic

- stl/inc/algorithm
- stl/inc/memory
- stl/inc/numeric
- stl/inc/xutility
While we love `const` and use it almost everywhere possible, we conventionally omit it in one place. Top-level `const` on value parameters in function declarations is immediately ignored by the language/compiler and serves no purpose (it makes no difference to callers).
I noticed that we accumulated several occurrences of this in our declarations of parallel algorithms, so I audited all of our `_ExPo&&` functions. I also noticed one more occurrence in `_Buffered_inplace_merge_unchecked()`. This is pretty hard to search for, so I don't claim that this is an exhaustive cleanup.
> Cleanups: Drop top-level `const` on value params in declarations

- stl/inc/xstring
- stl/src/ppltasks.cpp
- stl/src/taskscheduler.cpp
- tests/std/tests/Dev11_0235721_async_and_packaged_task/test.cpp
- tests/std/tests/P0019R8_atomic_ref/test.cpp
- tests/std/tests/VSO_0000000_list_iterator_debugging/test.cpp
- tests/std/tests/VSO_0961751_hash_range_erase/test.cpp
There are a few cases where we prefer to spend extra lines for clarity. (Examples: In modern code we strongly prefer to avoid packing too many side-effects into an expression, we avoid defining multiple variables on a single line, and we usually prefer to avoid elaborate conditional operators.)
One such case is simultaneously defining a type and an object. We prefer to do this separately, because they happen in different "domains". (Only lambdas get to be special!)
We accumulated a few occurrences throughput the codebase, which I tracked down. I consider this convention important enough (and the transformation simple enough) to be worth updating `tests/std`.
> Cleanups: Split type and object definitions

- tests/std/tests/Dev09_056375_locale_cleanup/test.cpp
- tests/std/tests/Dev09_192736_tr1_prngs_not_copyconstructible/test.cpp
- tests/std/tests/P2321R2_views_zip/test.cpp
* `P2321R2_views_zip` was using `ranges` as an identifier. :scream_cat: Rename this to `rngs`, avoiding confusion.
* `Dev09_192736_tr1_prngs_not_copyconstructible`, written a billion years ago, also had `ranges`. While this isn't *really* a problem, let's add a `d` suffix (also to the following `weights`), which is consistent with the preceding and following `vector<float> rangesf` and `vector<long double> rangesl`.
* `Dev09_056375_locale_cleanup`, written a trillion years ago, could use some extremely minor cleanups:
+ Add preprocessor comments.
+ Drop a totally unnecessary `using`-directive.
- In general, we should be wary of changing tests in ways that could disturb what they were testing, but there is *no way* that this had any effect, being scoped to `main()`.
+ Change a C cast to …
> Cleanups: Test code using `ranges` as an identifier, plus more

- stl/inc/__msvc_int128.hpp
- tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
- tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
- tests/std/tests/P0896R4_views_transform/test.cpp
- tests/std/tests/P1522R1_difference_type/test.cpp
- tests/std/tests/P2321R2_views_zip/test.cpp
We conventionally avoid the pattern `auto variable = Type{args};` because it is strictly more complicated than `Type variable{args};`. Following this convention reserves `auto` for the cases where it's doing real work to deduce a type.
We've accumulated a few cases which I'm cleaning up here. (There are a few more cases which I am reluctantly not changing, because `auto` results in code lining up nicely. I thought about it, though.)
In `P2321R2_views_zip`, I'm also performing some renames. We can name the parameters `single_element_container` and `three_element_container`, as that's relevant to the caller. Then we can rename the local copy to just `writable`, which avoids wrapping lines.
In `<__msvc_int128.hpp>`, I'm using `static_cast`. MSVC emits a signed/unsigned warning if we attempt …
> Cleanups: Avoid almost always `auto`

- stl/inc/numeric
- stl/src/fiopen.cpp
- stl/src/ppltasks.cpp
* Drop `break;` after `return true;` in `ppltasks.cpp`.
+ This was the deadest of dead code. :zombie: :brain:
* In `gcd()`, fuse `break` followed by `return`.
+ There's no other way out of this infinite loop, and no clarity advantage to having the `return` further away.
* In `fiopen.cpp`, change `ios_base::openmode atendflag` to `const bool at_end`.
+ We don't modify it, and it's simpler to immediately boil it down to a `bool`.
> Cleanups: Very minor logic changes

- stl/inc/condition_variable
- stl/inc/mutex
- stl/inc/thread
- stl/inc/xthreads.h
- stl/inc/xtimec.h
- stl/src/thread0.cpp
- stl/src/xtime.cpp
This PR contains fairly simple logic transformations - they aren't exactly trivial (as one must consult other code to verify their correctness), but they're far from complicated. There's no behavioral impact, no changes to dllexports, and no interaction with the "unlocked" state of the redist.
* First, `_Xtime_diff_to_millis()` is unused. We can drop its declaration in `inc/xtimec.h` and mark its definition in `src/xtime.cpp` as preserved for bincompat. When doing this, all we need to do is verify that the declaration and the definition contain all of the same annotations (in particular, `_CRTIMP2_PURE` controls dllexporting).
* Simplify `thread::detach()`, part 1.
+ `inc/xthreads.h` provided an `inline` helper `_Check_C_return()`. Originally, it may have been used widely, but now there's …
> Cleanups: Simplify `thread` and `condition_variable`, identify unused dllexports

- stl/inc/memory
> Remove unneeded check `if (this != _STD addressof(_Right))`

- stl/inc/xmemory
- stl/inc/yvals_core.h
- tests/libcxx/expected_results.txt
- tests/std/tests/P0401R6_allocate_at_least/env.lst
- tests/std/tests/P0401R6_allocate_at_least/test.cpp
- tests/std/tests/VSO_0000000_fancy_pointers/test.compile.pass.cpp
Fixes #3443. Also enables support and test coverage for EDG.
Upgrades `allocator_traits::allocate_at_least` to `_NODISCARD_RAW_PTR_ALLOC`.
I've filed DevCom-10301073 to request compiler support for this. Given compilers are already required to reject `initializer_list` specialization declarations, I think it's reasonable to do the same thing for `allocator_traits`.
> Implement P2652R2 Disallowing User Specialization Of `allocator_traits`

- stl/inc/mdspan
- tests/std/tests/P0009R18_mdspan/env.lst
- tests/std/tests/P0009R18_mdspan/test.cpp
This PR makes concepts mandatory for `<mdspan>`.
* Replace SFINAE with concepts in `std::extents` class,
* Address @StephanTLavavej's comments from my previous PR (#3535):
* `extends` -> `extents` (obvious typo)
* Improve `static_assert` messages (https://github.com/microsoft/STL/pull/3535#discussion_r1125485604).
I'm going to replace the rest of uses of SFINAE with concepts in follow-up PR.
> `<mdspan>`: Require concepts

- stl/inc/mdspan
* Drop `_STD` qualification for `make_index_sequence`.
* Remove dead `_Multiply()`. Also, `_X` and `_Y` were macro-like.
* All shall love `_EXPORT_STD` and despair. :elf_woman:
> `<mdspan>`: Add `_EXPORT_STD`, tiny cleanups

- stl/inc/algorithm
- stl/inc/xutility
... for all range algorithms operating on `forward_range`s.
> Use `_Rewrap_iterator` consistently

- stl/inc/algorithm
- tests/std/tests/P0896R4_ranges_alg_equal/test.cpp
> `<ranges>`: Fix `ranges::equal` for ranges with integer-class `range_difference_t`

- tests/std/tests/P0896R4_istream_view/test.cpp
- tests/std/tests/P0896R4_views_empty/test.cpp
- tests/std/tests/P0896R4_views_iota/test.cpp
- tests/std/tests/P0896R4_views_single/test.cpp
- tests/std/tests/P2474R2_views_repeat/test.cpp
Towards #3391.
This PR adds extra tests for `c(begin|end)` members of C++ range factories ([[range.factories]](http://eel.is/c++draft/range.factories)):
* `views::empty`,
* `views::single`,
* `views::iota`,
* `views::repeat`,
* `views::istream`.
> `<ranges>`: Test `c(begin|end)` members of range factories

- stl/inc/ranges
Implement LWG-3880:
* Remove outdated comment,
* Close #3434,
* Fix #2995.
> LWG-3880: Clarify `operator+=` complexity for `{chunk,stride}_view::iterator`

- stl/inc/mdspan
- tests/std/tests/P0009R18_mdspan/test.cpp
* Replace (almost) all uses of `enable_if` with `concepts`,
* Add missing `mdspan` deduction guides.
Drive-by:
* Remove unnecessary includes,
* Remove 2 non-standard constructors (one from `layout_stride::mapping` and one from `mdspan`),
* Improve some comments,
> `<mdspan>`: Use concepts everywhere and add `mdspan` deduction guides

- stl/inc/xutility
... so as not to require `_Prevent_inheriting_unwrap`; the intent of the unwrapping design is that `_Prevent_inheriting_unwrap` is optional.
I'm willing to be convinced that `_Prevent_inheriting_unwrap` should be made mandatory, in which case we should still accept this change and also make changes to `_Allow_inheriting_unwrap_v` to maintain consistency between Ranges and non-Ranges unwrapping machinery.
> `_Weakly_unwrappable` should use `_Allow_inheriting_unwrap_v`

- stl/inc/mdspan
- tests/std/test.lst
- tests/std/tests/P0009R18_mdspan_default_accessor/env.lst
- tests/std/tests/P0009R18_mdspan_default_accessor/test.cpp
- tests/std/tests/P0009R18_mdspan_extents/env.lst
- tests/std/tests/P0009R18_mdspan_extents/test.cpp
Short motivation:
* Separate tests are easier to read and maintain,
* We avoid files with 1000 lines of code.
That said, this PR adds:
* Add separate tests for `extents` and `default_accessor` (I'll introduce the rest of the tests in other PR),
* Drive-by: restore `<type_traits>` include in `<mdspan>` (see https://github.com/microsoft/STL/pull/3564#discussion_r1134606987).
`P0009R18_mdspan_extents/test.cpp` tests have two `FIXME` comment, as there *might* be a bug in `extents` implementation
> `<mdspan>`: Add separate tests for `extents` and `default_accessor`

- stl/inc/deque
- stl/inc/vector
We can avoid doing the addition ourselves when we do this.
> Prefer fill_n over fill where applicable

- stl/inc/compare
- tests/std/tests/P0768R1_spaceship_operator/test.cpp
LLVM has an issue: https://github.com/llvm/llvm-project/issues/43670
That issue marked as `libc++` but actually every C++ standard library affected , and MSVC STL and libstdc++.
```c++
#include <compare>
auto b = 1 <=> 2 < 0;
int main() {}
```
```
clang-cl /std:c++20 -Wzero-as-null-pointer-constant main.cpp
main.cpp(3,20): warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
auto b = 1 <=> 2 < 0;
^
nullptr
1 warning generated.
```
I also created: https://reviews.llvm.org/D146372
Yes, after that patch we accept 
```c++
auto b = 1 <=> 2 < (1-1);
```
but probably this is fine because the behavior is undefined. At least we don't warn on valid code.
> Don't warn when using operator<=> with 0

- stl/inc/xbit_ops.h
- stl/inc/xtimec.h
- stl/src/cond.cpp
- stl/src/cthread.cpp
- stl/src/mutex.cpp
- stl/src/vector_algorithms.cpp
- stl/src/xtime.cpp
Part 1: #3489
CodeQL is emitting more warnings in the STL's separately compiled sources, resulting in the automatic creation of high-priority bugs in the internal database.
This PR introduces no behavioral changes, nor does it affect the STL's dllexports.
`xtime_get`
===
* Fix `xtime_get` CodeQL warnings.
+ Bugs: VSO-1773907, VSO-1773908, VSO-1773909, VSO-1773910
+ This is the `[cpp/conditionallyuninitializedvariable]` warning:
> The status of this call to `xtime_get` is not checked, potentially leaving `now` uninitialized.
This is the most interesting one. We never documented or supported the non-Standard `xtime` API (and we really should get rid of these non-Standard identifiers someday). All of our calls to `xtime_get` are in `src`, and all of them are exactly `xtime_get(&now, …
> Fix CodeQL warnings, part 2

- index.html
- package-lock.json
- package.json
- src/status_chart.ts
- src/weekly_table.ts
- src_gather/gather_stats.ts
- src_gather/video_table.ts
Another month of manually collected data and dependency updates, plus a small change to extend the range of the Merged PRs chart up to 90, since we went into a merge frenzy! :smirk_cat:
As this now updates TypeScript to 5.0.2, we need a small code change for its improved type checking. :magic_wand: In `gather_stats.ts`, each `Row` contains a `date: DateTime;` and a bunch of `number` values. The `should_emit_data_point()` function, which makes lines vanish when they fall to `0`, takes a `key` and inspects the `number` value. TypeScript 5.0 correctly notices that this `key` could be the `date`, and it doesn't make sense to compare a `DateTime` with `0`. As we do in `status_chart.ts`, the fix is to use `Exclude<keyof Row, 'date'>` for both the parameter type and the array of keys that we …
> Status Chart: Weekly updates, TypeScript 5.0, Merged PRs range

- tests/std/include/test_header_units_and_modules.hpp
This mirrors the library test changes from @JonCavesMSFT's MSVC-PR-460102.
In the header units and named modules test, I was unintentionally being a bad kitty :smirk_cat: and was exercising an accepts-invalid codepath in the MSVC compiler, which is now being fixed. Specifically, WG21-N4928 \[expr.const\]/12.2:
> A *constant expression* is either a glvalue core constant expression that refers to an entity that is a permitted result of a constant expression (as defined below), or a prvalue core constant expression whose value satisfies the following constraints:
> [...]
> if the value is of pointer type, it contains the address of an object with static storage duration, the address past the end of such an object (7.6.6), the address of a non-immediate function, or a null pointer value,
In …
> Fix modules test by using `static constexpr` arrays

- stl/inc/mdspan
- tests/std/test.lst
- tests/std/tests/P0009R18_mdspan/test.cpp
- tests/std/tests/P0009R18_mdspan_extents/test.cpp
- tests/std/tests/P0009R18_mdspan_extents_death/env.lst
- tests/std/tests/P0009R18_mdspan_extents_death/test.cpp
Changes to `std::extents`:
* Get rid of `_Mdspan_extent_type` base type,
* Prefer named functions instead of internal names (e.g. `sizeof...(_Extents)` -> `rank()`, `_Static_extents[_Idx]` -> `static_extent(_Idx)`),
* Fix `_EXPORT_STD` placement (only for `extents` and `dextents`),
* Implement preconditions:
* Those preconditions are unconditional for now (Should I guard them with `_CONTAINER_DEBUG_LEVEL` macro?),
* Some preconditions are checked only if type of inspected value satisfies `integral`,
* Preconditions use `std::cmp_` functions from C++20 to avoid signed/unsigned comparison warnings,
* Add `_death` tests,
* Reimplement deduction guide with workaround for not-yet reported MSVC ICE,
* Reimplement `dextents` - get rid of IILE,
* Fix some bugs and enable previously failing tests …
> `<mdspan>`: Completely rework `std::extents`

- stl/inc/mdspan
- stl/inc/yvals_core.h
- tests/std/tests/P0009R18_mdspan_extents/test.cpp
- tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
* Fix feature test macro - it should be guarded with `__cpp_lib_concepts`,
* Fix various typos,
* Cleanup `_EXPORT_STD` - it should be on the same line as the class,
* Update working draft revision to N4944 and add missing citations,
* Prefer type aliases instead of _Ugly names (e.g. `_Extents` -> `extents_type`),
* Replace `_Mysomething` names with `_Something`.
> `<mdspan>`: Various cleanups (mostly renames)

- stl/inc/functional
- tests/std/test.lst
- tests/std/tests/GH_000952_bind_constraints/env.lst
- tests/std/tests/GH_000952_bind_constraints/test.compile.pass.cpp
Fixes #952.
The issue is probably because of that some functions used by `bind` are not well constrained.
- `_Invoker_ret<_Rx>::_Call` ("backported `invoke_r`") is not constrained at all.
- the return types of some `_Select_fixer<...>::_Fix`/`_Apply` rely on `std::get` for `tuple`, which is not constrained.
Driven-by changes: use direct `if constexpr` and `invoke` in the internal functions used by `function` and `move_only_function` (similar to the use in `invoke_r`), which may slightly improve compiler throughput.
> `<functional>`: Constrain functions used by `std::bind`

- stl/inc/__msvc_tzdb.hpp
- stl/inc/chrono
- stl/src/msvcp_atomic_wait.src
- stl/src/tzdb.cpp
... by only retrieving necessary information.
This makes `to_local` 3x faster on my machine (although it's still hundreds times slower than `localtime`).
> `<chrono>`: Optimize `to_sys` and `to_local`

- stl/inc/chrono
- stl/inc/compare
- stl/inc/ranges
- stl/inc/source_location
- stl/inc/utility
- stl/inc/xutility
- stl/inc/yvals_core.h
- tests/std/tests/P1208R6_source_location/header.h
- tests/std/tests/P1208R6_source_location/test.cpp
- tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
And enable support for `source_location` for Clang.
I've observed that there're already some unprotected uses of `consteval` in C++20/23 modes, which should have proved that `consteval` gets well with MSVC and Clang. EDG is not well tested, but it is [claimed](https://docs.google.com/spreadsheets/d/1H-aqjzVI2a-XQKGtw0xaS0tyjD0FcoQP8ttJI9JZQTc) that immediate functions are supported since 5.1. So I think `consteval` is also well supported.
I think `_CONSTEVAL` is still useful since there may be some other candidate functions for `_CONSTEVAL` that are needed for pre-C++20.
After this change, there'll be only one occurrence of `_CONSTEVAL`, which is in `<random>`:
https://github.com/microsoft/STL/blob/5116678ea11245b232a6e43824aad25fb60b9c6e/stl/inc/random#L1002
----
Edit:
- It seems that …
> Prefer `consteval` to `_CONSTEVAL`, enable `<source_location>` for Clang

- stl/inc/yvals_core.h
- tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
The change has been adoped into the C++ Working Draft by commit https://github.com/cplusplus/draft/commit/6e7fd98b684a92405934de981abf01414a67ddbd. However, it isn't contained in WG21-N4944. A newer WD (and perhaps the published C++23 Standard?) will contain it.
Driven-by change: concept dependency of `allocator_at_least` was removed by #3542, so the feature-test macro should also be enabled even if the concept support is absent.
> Implement LWG-3887 Version macro for `allocate_at_least`

- README.md
Updated working draft from N4928 to N4944 in README.md. Fixes #3590
> Update working draft from N4928 to N4944

- stl/inc/__msvc_chrono.hpp
- stl/inc/condition_variable
- stl/inc/mutex
- stl/inc/shared_mutex
- stl/inc/thread
- stl/inc/xthreads.h
- stl/inc/xtimec.h
- stl/src/cond.cpp
- stl/src/cthread.cpp
- stl/src/mutex.cpp
- stl/src/xtime.cpp
- tests/std/test.lst
- tests/std/tests/GH_002206_unreserved_names/env.lst
- tests/std/tests/GH_002206_unreserved_names/test.compile.pass.cpp
- tests/std/tests/VSO_0226079_mutex/test.cpp
This PR is currently trying to replace uses of `xtime` with `_timespec64`, because `_timespec64` is
- of a reserved name, and
- having the same member names as the standard `timespec`, and
- already available in all modes via `<time.h>`, and
- layout-compatible with `xtime`.
Definition of `_timespec64` (not available in this repo):
```C++
struct _timespec64
{
__time64_t tv_sec;
long       tv_nsec;
};
```
Definition of `xtime`:
https://github.com/microsoft/STL/blob/5e603826ea2f4bfbe3d72b33967193b2edf75ce5/stl/inc/xtimec.h#L23-L26
Working towards #2206.
Every function in MSVC STL that has external linkage and involves `xtime` is either `extern "C"` or inline, so I think this PR doesn't break ABI.
~I'm also trying to change the name of every function, except for constructor, involving …
> Eliminate `xtime` and its member `sec`, `nsec`

- stl/inc/mdspan
- tests/std/include/test_mdspan_support.hpp
- tests/std/test.lst
- tests/std/tests/P0009R18_mdspan_extents/test.cpp
- tests/std/tests/P0009R18_mdspan_layout_left/env.lst
- tests/std/tests/P0009R18_mdspan_layout_left/test.cpp
- tests/std/tests/P0009R18_mdspan_layout_left_death/env.lst
- tests/std/tests/P0009R18_mdspan_layout_left_death/test.cpp
`<mdspan>`:
* Implement `layout_left::mapping`'s preconditions,
* Fix `is_(unique/exhaustive/strided)` functions - they should be `static`,
* Add exposition-only public member *`_Fwd_prod_of_extents`* to `extents`,
* Fix some issues with signed-unsigned conversions,
* Fix `mdspan`'s constructor constraints,
* Address https://github.com/microsoft/STL/pull/3593#discussion_r1148923347.
Testing:
* Introduce `test_mdspan_support.hpp` header,
* Add separate tests for `layout_left`: regular tests and death tests.
> `<mdspan>`: `layout_left` improvements

- stl/inc/mdspan
- tests/std/test.lst
- tests/std/tests/P0009R18_mdspan_layout_left/test.cpp
- tests/std/tests/P0009R18_mdspan_layout_right/env.lst
- tests/std/tests/P0009R18_mdspan_layout_right/test.cpp
- tests/std/tests/P0009R18_mdspan_layout_right_death/env.lst
- tests/std/tests/P0009R18_mdspan_layout_right_death/test.cpp
`layout_right`:
* Implement preconditions (checked unconditionally for now),
* Fix `is_(unique/exhaustive/strided)` functions - all three should be `static`,
* Implement *`rev-prod-of-extents`* function in `extents`,
* Add separate regular tests and death tests.
`layout_left`:
* Fix incorrect preconditions in constructor from `layout_stride`,
* Fix tests and add extra coverage.
Testing:
* Get rid of `CanInvokeCallOperatorOfMapping` concept and use already defined in helper header `CheckCallOperatorOfLayoutMapping` concept.
> `<mdspan>`: `layout_right` improvements

- stl/inc/mdspan
- tests/std/include/test_mdspan_support.hpp
- tests/std/tests/P0009R18_mdspan_default_accessor/test.cpp
`default_accessor`:
* Implement requirements: [[mdspan.accessor.default.overview]/2](http://eel.is/c++draft/mdspan.accessor.default.overview#2).
Testing:
* Hide internal functions and concepts from `test_mdspan_support.hpp` header in `detail` namespace,
* Implement checking for accessor policy requirements ([\[mdspan.accessor.reqmts\]](http://eel.is/c++draft/mdspan.accessor.reqmts)),
* Check those requirements for `default_accessor`.
> `<mdspan>`: Improve accessor testing

- stl/CMakeLists.txt
- stl/msbuild/stl_base/msvcp.settings.targets
- stl/src/ppltasks.cpp
This is a clean revert (no manual changes) of #2654 and the following #3255 (in reverse order). #3255 was a targeted fix (partial revert) for an incredibly disruptive bincompat bug, but #2654 has caused even more trouble. This full revert:
* Fixes #3257, where the newly added dependency on `ole32.dll` was disruptive to certain exotic scenarios, and
* Fixes a "sandboxed process" scenario for the XStore team (reported by @vaboca), also disrupted by `ole32.dll`.
+ Don't ask me to explain this in any more detail, I don't know what's going on here. :exploding_head: That's the whole problem with this change - nobody fully understood the implications - and that's why we need to fully revert it, not mess around with it more.
By performing a full revert, we no longer need the partial revert. This …
> Revert the ppltasks change that introduced an `ole32.dll` dependency

- stl/inc/mdspan
- tests/std/tests/P0009R18_mdspan_layout_right/test.cpp
This small PR removes workaround for `extents`'s deduction guide ICE. It looks like the code was incorrect anyway (meaning it is ICE on invalid) and Clang incorrectly accepts it.
Here is a minimal repro: https://godbolt.org/z/Wdjq5boG3, feel free to report it to both LLVM and MSVC (and maybe to GCC, this error message is awful).
Drive-by: address [comment](https://github.com/microsoft/STL/pull/3615#discussion_r1156571002) from previous PR.
> `<mdspan>`: Cleanup `extents`'s deduction guide

- stl/inc/typeindex
Currently, when two referenced `type_info` are not equal, `type_index::operator<=>` needs to call `__std_type_info_compare` twice (both in `type_info::operator==` and `type_info::before`) to determine the relative order.
I think we can optimize `type_index::operator<=>` by calling the comparison function at most once. However, it is currently necessary to touch the implementation details of `type_info` and `__std_type_info_compare` in VCRuntime. This PR is essentially mirroring the implementation of `__std_type_info_compare` now.
I've filed DevCom-10326599 to request a stable interface for ordering.
> `type_index::operator<=>` should not call the comparison function twice

- stl/inc/ranges
Class template argument deduction for `std::tuple` does not always result in a `tuple` of the arguments (e.g. when the first argument is a `pair`). This PR adds the template parameters to ensure that these uses of `tuple` behave as expected in pathological cases.
<details>
<summary>example</summary>
```c++
#include <ranges>
#include <utility>
struct Tag {};
using Sent = std::pair<Tag, int>;
bool operator==(int*, Sent);
std::ptrdiff_t operator-(int*, Sent);
std::ptrdiff_t operator-(Sent, int*);
struct Rng {
int* begin();
Sent end();
};
int main() {
auto x  = std::views::cartesian_product(Rng{});
(void) (x.begin() - std::default_sentinel); // `operator-` calls `_It._Distance_from(_It._End_tuple(...))`
// Before: `_End_tuple` returns a `tuple<Tag, int>`, which results in an error in …
```
> `<ranges>`: Explicitly specify the template parameters for `tuple`

- tests/std/tests/P0896R4_ranges_ref_view/test.cpp
- tests/std/tests/P0896R4_ranges_subrange/test.compile.pass.cpp
- tests/std/tests/P0896R4_views_common/test.cpp
- tests/std/tests/P0896R4_views_filter/test.cpp
- tests/std/tests/P0896R4_views_join/test.cpp
- tests/std/tests/P0896R4_views_reverse/test.cpp
- tests/std/tests/P0896R4_views_transform/test.cpp
> Testing: Check `c(begin|end)` members of C++20 ranges

- stl/src/vector_algorithms.cpp
- tests/std/include/test_min_max_element_support.hpp
- tests/std/test.lst
- tests/std/tests/GH_003617_vectorized_meow_element/env.lst
- tests/std/tests/GH_003617_vectorized_meow_element/test.cpp
- tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
Fixes #3617.
* Fix truncation by adding `static_cast<size_t>`.
+ The bug was lurking in the expression `_Base + _V_pos * 16 + _H_pos`, where `_Base` was `const char *`, `_V_pos` was `unsigned int`, and `_H_pos` was `unsigned long`.
* Pre-existing: `test_various_containers` as we disable instructions.
+ This was an oversight in #804 on 2020-07-27.
* Extract `test_min_max_element_support.hpp`.
* Add `GH_003617_vectorized_meow_element`.
+ This uses the `fast_matrix.lst` (one configuration, optimized) because it takes a while and consumes a ton of memory if the usual matrix is used. (I originally tried to fuse it into `VSO_0000000_vector_algorithms` but that was infeasible.)
> Fix silent bad codegen for vectorized `meow_element()` above 4 GB

- stl/inc/optional
- stl/inc/variant
Separated from #3623.
`std::variant` and `std::optional` forbid using an array type as component, so it's unnecessary to include `<xmemory>` to obtain `_Destroy_in_place`.
~I think it's OK to write `<xutility>` for short. Several other headers, including conditionally included `<compare>`, are already handled in `<xutility>`.~ Edit: dropping this due to review comments.
Edit: I also need to reduce the `numeric_limits` depedency (needed for EDG?). I expect that the current approach is transient.
> Don't include `<xmemory>` in `<optional>` and `<variant>`

- stl/inc/regex
- stl/inc/xstring
- tests/std/tests/GH_000431_equal_memcmp_is_safe/test.compile.pass.cpp
- tests/std/tests/GH_000431_lex_compare_memcmp_classify/test.compile.pass.cpp
As these functors are only used in `<regex>`. Separated from #3623.
> Move `_Char_traits_eq` and `_Char_traits_lt` from `<xstring>` to `<regex>`

- stl/inc/chrono
Separated from #3623. Towards #3599.
It seems to me that we don't need to use `transform` for `tzdb_list`. `emplace_back` in loop looks better.
> Don't include `<algorithm>` in `<chrono>`

- stl/inc/compare
- stl/inc/format
- stl/inc/type_traits
- stl/inc/xutility
Separated from #3623. Towards #3599.
Once `<compare>` doesn't include `<bit>`, `<format>` needs to include `<bit>` directly. I think it's better to use the standard `std::bit_cast` in `<format>`.
~I have no good idea how to move `std::bit_cast` to another header. So currently this PR uses the `__builtin_bit_cast` intrinsic.~
The current decision is moving `_Bit_cast` from `<xutility>` to `<type_traits>` and using it in `<compare>`.
> Don't include `<bit>` in `<compare>`

- stl/src/vector_algorithms.cpp
> `vector_algorithms.cpp`: Add `vzeroupper`, so that it is there even in `/Od`

- index.html
- package-lock.json
- package.json
- src/status_chart.ts
- src/weekly_table.ts
- src_gather/video_table.ts
- usernames_maintainers.txt
* Weekly updates.
* Dependency updates.
* `index.html`: Drop es-module-shims.
+ Import maps are now supported by the latest versions of all major browsers (and the Status Chart makes no attempt to support older versions).
* Hide 'Combined Wait' by default.
+ This line was an interesting idea, but it's more distracting than useful (in my opinion).
* Update `usernames_maintainers.txt`.
As usual, this contains a "DROP BEFORE MERGING: Regen files." commit to make the live preview work.
===
> Status Chart: Weekly updates, drop es-module-shims, hide Combined Wait

- stl/inc/format
- stl/inc/yvals_core.h
- tests/std/tests/P0645R10_text_formatting_legacy_text_encoding/test.cpp
- tests/std/tests/P0645R10_text_formatting_parsing/test.cpp
- tests/std/tests/P0645R10_text_formatting_utf8/test.cpp
MSVC STL already allows multi-code-unit fill characters, but it does not check if a Unicode code unit sequence corresponds to a [Unicode scalar value](https://www.unicode.org/glossary/#unicode_scalar_value). This PR adds the check.
~~I'm not a fan of out parameters, but they get the job done here.~~
Fixes #3439.
> Implement P2572R1 `std::format()` fill character allowances

- stl/inc/numbers
- tests/std/tests/P0631R8_numbers_math_constants/test.cpp
In recent PR #3623 I noticed that the implementation of `<numbers>` when concepts are unavailable didn't seem correct enough. These variable templates are required to support possibly cv-qualified floating-point types due to `std::floating_point`, but the current concept-free implementation only supports cv-unqualified FP types.
This PR is adding test coverage for cv-qualified FP types, and rewriting the concept-free implementation. Technically, only the primary template is used, but I believe that the difference from the standard wording is unobservable.
Warning [C4197](https://learn.microsoft.com/sv-se/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4197?view=msvc-140) was encountered during local test. I think it's OK to only suppress that warning in testing, because …
> `<numbers>`: Rework the implementation when concepts are missing

- stl/inc/system_error
Hello, from a conversation that occurred on the STL Discord server, I noted that a call to ctor of the internal class `_System_error` appeared to take some extra unnecessary steps when the error message was empty.
As suggested by Stephan I opened a pull request in an attempt to simplify the code.
The goal of this pull request is to skip entirely the call to the internal function `_Makestr` since it would have no effect on an empty string. I think my pull request does not have any unintended consequences. This is also my first contribution so please let me know if I messed something up. I have been lurking on the activity on this repo for a while and on the Discord server so I tried my best to follow the code conventions 😄
> `<system_error>`: Optimize internal class `_System_error`

- stl/inc/ranges
> `<ranges>`: Cleanup for `_CONSTEVAL`

- stl/inc/yvals_core.h
> Update `yvals_core.h` to April 2023

- stl/inc/memory
- tests/std/tests/P1614R2_spaceship/test.cpp
Fixes #3646.
I think similar handling for `unique_ptr` is definitely wanted, but it seems that we can't achieve a complete workaround for `unique_ptr` due to the arbitrability of `unique_ptr::pointer`.
> `<memory>`: Workaround for MSVC bug on `operator<=>` (`shared_ptr` only)

- docs/cgmanifest.json
https://github.com/boostorg/math/releases/tag/boost-1.82.0
> Update boost-math to 1.82

- stl/inc/map
- stl/inc/unordered_map
- tests/std/tests/Dev11_0437519_container_requirements/test.compile.pass.cpp
One of the changes that I pushed to #2436 was damaging - while map-like types can't tolerate references as key types, using references as mapped types appears to be permitted (by the Standard, libstdc++, and libc++), and there are 4 projects across vcpkg and Real World Code that are doing this.
Fortunately, we can fix this before changes stop flowing into VS 2022 17.7 Preview 2, so users will never be affected. I'm removing my bad `static_assert`s, and adding test coverage to minimally verify that this scenario compiles.
(I suppose we could instead assert that the mapped types aren't function types or void types, but I'd rather just drop it entirely. Such usage is extremely unlikely and will still be rejected, just with lengthy diagnostics.)
> `<map>`, `<unordered_map>`: Allow `MapLike<K, V&>` again

- stl/inc/mdspan
* Use direct-non-list initialization in constructors (as standard says),
* Reorder members to match [[mdspan.layout.stride]](http://eel.is/c++draft/mdspan.layout.stride),
* Strengthen some member functions.
> `<mdspan>`: Cleanup `mdspan` class a little bit

- stl/inc/valarray
I don't know if whatever compile is supposed to compile this will notice, but this is the only place where this structure appears, so it seems best that the incrementation be done within the loop.
> Ensure _Idx is only worked on if it has to be.

- stl/inc/optional
- tests/std/tests/P0798R8_monadic_operations_for_std_optional/test.cpp
> `<optional>`: Fix exception specification for `optional`'s transform-construction

- stl/inc/typeinfo
- tests/std/include/test_header_units_and_modules.hpp
@cdacamar explained that in this case, the MSVC compiler looks for the True Name of `type_info` in the global namespace, so we need to export it as a special exception.
I'm adding test coverage for this scenario. The `using namespace std;` in this test doesn't actually affect the repro, so I didn't bother to remove it.
Fixes DevCom-10349749 and internal VSO-1810086 / AB#1810086 .
> `<typeinfo>`: Error with `import std;` and `typeid(T).name()`

- stl/inc/mdspan
- tests/std/include/test_mdspan_support.hpp
- tests/std/tests/P0009R18_mdspan_extents/test.cpp
- tests/std/tests/P0009R18_mdspan_layout_left/test.cpp
- tests/std/tests/P0009R18_mdspan_layout_right/test.cpp
- tests/std/tests/P0009R18_mdspan_layout_stride/test.cpp
* Improve tests of `extents` and layout mappings:
* Check all 10 standard signed and unsigned integer types,
* Check various combinations of static and dynamic extents.
* Fix integral conversions in `layout_stride::mapping`.
> `<mdspan>`: Diversify integer types used in tests

- stl/inc/mdspan
- tests/std/tests/P0009R18_mdspan_layout_stride/test.cpp
* Document DevCom-10360833 workaround,
* Add test coverage in `P0009R18_mdspan_layout_stride/test.cpp`,
* Test coverage is also in old test suite `P0009R18_mdspan/test.cpp`.
> `<mdspan>`: Document CTAD workaround

- stl/inc/mdspan
Comparison between N4944 and N4950: https://github.com/cplusplus/draft/compare/n4944...n4950#diff-3b5851f7056b7c68cb3ba2ab51cf0b75a780c6a11e5e181770067700454ace7b.
> `<mdspan>`: Cite N4950 instead of N4944

- stl/inc/mdspan
- tests/std/tests/P0009R18_mdspan_layout_left/test.cpp
- tests/std/tests/P0009R18_mdspan_layout_left_death/test.cpp
- tests/std/tests/P0009R18_mdspan_layout_right/test.cpp
- tests/std/tests/P0009R18_mdspan_layout_right_death/test.cpp
- tests/std/tests/P0009R18_mdspan_layout_stride_death/test.cpp
* Currently not guarded (https://github.com/microsoft/STL/pull/3586#discussion_r1148075895),
* Fix bug in `P0009R18_mdspan_layout_left/test.cpp`,
* Drive-by: in #3690 I've missed one warning, reduce it here.
> `<mdspan>`: Add new debug checks to layout mappings

- stl/msbuild/stl_1/xmd/dirs.proj
- stl/msbuild/stl_2/xmd/dirs.proj
- stl/msbuild/stl_atomic_wait/xmd/dirs.proj
- stl/msbuild/stl_base/dirs.proj
- stl/msbuild/stl_base/xmd/dirs.proj
- stl/msbuild/stl_base/xmt/dirs.proj
- stl/msbuild/stl_codecvt_ids/xmd/dirs.proj
- stl/msbuild/stl_post/xmd/dirs.proj
Port STL changes from MSVC-PR-471952.
tldr; the `SpectreBuildDebug` isn't being used now or in the future, so remove it.
> Remove SpectreBuildDebug flag from MSBuild

- stl/inc/ranges
- stl/inc/xutility
- tests/std/test.lst
- tests/std/tests/P2374R4_checked_arithmetic_operations/env.lst
- tests/std/tests/P2374R4_checked_arithmetic_operations/test.cpp
* Rename `_(Add|Multiply)_with_overflow_check` to `_Add_overflow` and `_Mul_overflow` for simplicity,
* This matches naming of Clang's builtins (`__builtin_add_overflow` and `__builtin_mul_overflow`),
* Move both functions to `<xutility>`,
* Both functions are going to be used in `<mdspan>` implementation,
* Add separate tests, which detected two bugs:
* When both arguments to `_Mul_overflow` are equal to `numeric_limits<uint16_t>::max()`, then signed integer overflow occurs,
* There were missing `static_cast`s in `_Mul_overflow`'s LLVM-based branch,
* Both bugs are fixed in this PR.
> Improve `_(Add|Multiply)_with_overflow_check`

- stl/inc/xlocnum
- tests/libcxx/expected_results.txt
- tests/std/test.lst
- tests/std/tests/GH_001277_num_get_bad_grouping/env.lst
- tests/std/tests/GH_001277_num_get_bad_grouping/test.cpp
- tests/std/tests/LWG2381_num_get_floating_point/test.cpp
Fixes #1277.
Unblocking one libcxx test:
- `std/localization/locale.categories/category.numeric/locale.num.get/facet.num.get.members/get_long.pass.cpp`
Also moves the test for non-ending unlimited grouping to the new test file.
I'm not sure when the grouping string is `"\0"s` which means grouping is not limited:
- whether `"17,,29"` can be parsed without setting `failbit`, and
- whether `"0,x1729"` should be parsed as a whole...
> `<xlocnum>`: Fix grouping for `num_get`

- stl/inc/__msvc_chrono.hpp
Part of #1588.
`_Xtime_get_ticks` and `system_clock::now` would no longer be equal after a future leap second when #1520 is eventually fixed. This PR changes the clock used in `_To_timespec64_sys_10_day_clamped` to be consistent with code that consumes its result, e.g. `target` in https://github.com/microsoft/STL/blob/091cad2eaaa5bc25873eb7261cae57ab123592f3/stl/src/cond.cpp#L72-L80
@BillyONeal pointed out (on Discord) that this PR could break (already somewhat broken) timed wait ABI:
> `_To_xtime_10_day_clamped`, used by `condition_variable::wait_for`, `this_thread::sleep_for`, etc., calls `system_clock::now()` internally to compute a value interpreted as `GetSystemTimeAsFileTime + offset` by another component. My understanding is that if the linker picks the old version of …
> `<__msvc_chrono.hpp>`: Use `_Xtime_get_ticks` in `_To_timespec64_sys_10_day_clamped` for consistency

- stl/inc/xhash
- tests/std/test.lst
- tests/std/tests/GH_000732_hash_reserve/env.lst
- tests/std/tests/GH_000732_hash_reserve/test.cpp
> `<xhash>`: Use ceiling instead of rounding when calculating number of buckets

- stl/inc/__msvc_iter_core.hpp
- stl/inc/chrono
- stl/inc/type_traits
- stl/inc/utility
- stl/inc/xlocnum
- stl/inc/xloctime
- stl/inc/yvals.h
- tests/tr1/tests/type_traits1/test.cpp
- tests/tr1/tests/utility/test.cpp
1. Move `_MAX_*` macros from `<yvals.h>` to `<xlocnum>` so that they can be `#undef`'d in the same header. Also demacroize `_MAX_INT_DIG` and rename it to `_Max_int_dig`, because it is used in multiple headers.
2. Move `integer_sequence` and its friends from `<type_traits>` to `<utility>` where the standard provides them.
3. Move `allocator_arg`, `uses_allocator` and their friends from `<utility>` to `<__msvc_iter_core.hpp>` where suitable. Although they are unrelated to iterators.
> Move some components from upstream headers to downstream

- stl/inc/deque
- tests/std/tests/GH_002769_handle_deque_block_pointers/test.cpp
> Cleanup elements when `resize` fails in `deque(n)`

- stl/inc/ranges
- stl/inc/xutility
- tests/std/tests/P1208R6_source_location/test.cpp
- tests/std/tests/P1522R1_difference_type/test.cpp
LLVM-47414, LLVM-51580, LLVM-55945, and LLVM-56379 should have been fixed in Clang16. Let's remove the workarounds.
> Remove some workaround for Clang

- stl/inc/iomanip
- tests/std/tests/VSO_0000000_instantiate_iterators_misc/test.compile.pass.cpp
> remove `operator>>` for `istream >> setfill(c)`

- stl/inc/ranges
- tests/std/test.lst
- tests/std/tests/P0896R4_views_iota_death/env.lst
- tests/std/tests/P0896R4_views_iota_death/test.cpp
And add death test for `iota_view`.
> `<ranges>`: Diagnose the precondition added by LWG-3597

- stl/inc/ranges
- tests/std/tests/P2374R4_views_cartesian_product/test.cpp
Per [[range.cartesian.view]/9-10](http://eel.is/c++draft/range.cartesian.view):
> Let *p* be the product of the sizes of all the ranges in bases_.
> *Preconditions*: *p* can be represented by the return type.
Currently `cartesian_product_view::size` may fail when *p* can be represented by return type:
```c++
#include <ranges>
int main() {
const auto r1 = views::repeat(0, (numeric_limits<ptrdiff_t>::max)());
const auto r2 = views::repeat(1, 0);
(void)views::cartesian_product(r1, r1, r1, r2).size(); // FAIL!
}
```
Obviously `0` can be represented by any unsigned integral type. This PR fixes this bug.
> `<ranges>`: Fix `cartesian_product_view::size` in debug mode

- stl/inc/charconv
- stl/inc/exception
- stl/inc/format
- stl/inc/future
- stl/inc/ios
- stl/inc/istream
- stl/inc/list
- stl/inc/ostream
- stl/inc/regex
- stl/inc/streambuf
- stl/inc/xiosbase
- stl/inc/xlocale
- stl/src/atomic.cpp
- stl/src/excptptr.cpp
- stl/src/ppltasks.cpp
- stl/src/primitives.hpp
- stl/src/sharedmutex.cpp
- stl/src/winapisupp.cpp
- stl/src/xstol.cpp
- stl/src/xstoll.cpp
The MSVC-internal repo is making another push to enable and clean up static analysis warnings in the build. The STL was previously unaffected as we've built our tests with plain `/analyze` for 3000 years, but now additional rulesets are being enabled and the STL is emitting warnings.
* Add empty braces to fix warning C26495 "Variable 'MEOW' is uninitialized. Always initialize a member variable (type.6)."
+ This is safe because Zero Is A Strict Subset Of Garbage.
* Permanently silence warning C26495 (uninitialized member variable) for `_Big_integer_flt::_Mydata`.
+ As the big comment explains, leaving this uninitialized is important for performance.
* Fix warning C28252 "Inconsistent annotation for `'RtlCaptureStackBackTrace'`: return/function has `'SAL_success(return!=0)'` on the prior …
> Fix static analysis warnings

- .clang-format
- stl/inc/format
Also avoid writing the `#if _HAS_CXX23`-`#endif` pair in several places.
> `<format>`: Restore the indent after adding `inline namespace __p2286`

- stl/inc/charconv
- stl/inc/memory_resource
- stl/inc/xlocale
Followup to #3734.
I've filed a tracking bug VSO-1828677 "False positive warning C26450 (arithmetic overflow) in charconv and memory_resource" for the static analysis team to investigate, and @dmitrykobets-msft has added fully reduced repros there. Our code is correct, so we need to silence this warning until the compiler is fixed.
For `locale::_Ptr`, attempting to initialize it will break the STL catastrophically. I'm permanently suppressing the warning, with an explanation of the squirrelly :chipmunk: behavior involved. In theory, this is not ABI-sensitive since `classic_locale` is isolated to the locale0.cpp TU, but iostreams is extremely complicated and fragile and I am not eager to mess with this logic at this time unless absolutely forced to.
> Silence 3 static analysis warnings

- stl/inc/mdspan
- tests/std/include/test_mdspan_support.hpp
- tests/std/test.lst
- tests/std/tests/P0009R18_mdspan/test.cpp
- tests/std/tests/P0009R18_mdspan_layout_left/test.cpp
- tests/std/tests/P0009R18_mdspan_layout_right/test.cpp
- tests/std/tests/P0009R18_mdspan_layout_stride/test.cpp
- tests/std/tests/P0009R18_mdspan_mdspan/env.lst
- tests/std/tests/P0009R18_mdspan_mdspan/test.cpp
* Add separate file with `mdspan`'s tests,
* Remove `clang-format (on/off)`s from `test_mdspan_support.hpp`,
* Address comments from #3689:
* https://github.com/microsoft/STL/pull/3689#discussion_r1204729493,
* https://github.com/microsoft/STL/pull/3689#discussion_r1204731766,
* Use `#ifdef __cpp_multidimensional_subscript` instead of `#ifdef __clang__` in tests too,
* Fix `mdspan::operator[](array/span)`,
* Fix construction of `mdspan<Args1...>` from `mdspan<Args2...>`.
> `<mdspan>`: Test `mdspan`

- README.md
- azure-devops/cmake-configure-build.yml
- azure-devops/create-1es-hosted-pool.ps1
- azure-devops/cross-build.yml
- azure-devops/native-build-test.yml
- azure-devops/provision-image.ps1
- azure-devops/run-tests.yml
- azure-pipelines.yml
- stl/inc/memory
- stl/inc/ranges
- stl/inc/xutility
* Updated build compiler to VS 2022 17.7 Preview 2.
* Updated Python to 3.11.4.
* Switched our VM SKU to Standard_D32ads_v5, which 1ES has already been doing for us behind the scenes.
* Updated our VM pool, also containing June's Patch Tuesday.
* Removed compiler bug workarounds:
+ VSO-1292293 "EDG incorrectly rejects defaulted `noexcept` dtor when a data member has a throwing dtor".
+ VSO-1222776 "EDG doesn't know that `noexcept`-specifiers of hidden friend functions are complete-class contexts".
* Reduce timeouts. It looks like the new pool doesn't avoid the timeouts we've been suffering recently, but this will waste less time.
+ `azure-pipelines.yml`:
- Reduce the timeout for Code Format Validation from 20 min to 5 min. This is still a ~5x safety margin as it takes ~56 seconds total.
+ …
> Toolset update: VS 2022 17.7 Preview 2

- stl/inc/__msvc_chrono.hpp
- stl/inc/chrono
- tests/std/test.lst
- tests/std/tests/GH_003676_format_large_hh_mm_ss_values/env.lst
- tests/std/tests/GH_003676_format_large_hh_mm_ss_values/test.cpp
- tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp
- Remove explicit assertion that prevents formatting `hh_mm_ss`s >= 1 day
- Change `hh_mm_ss`' formatting implementation to use the hours and minutes explicitly (`put_time` does not deal with hours >= 24, which is desired behavior)
- Remove `_Hh_mm_ss_part_underflow_to_zero` and instead cast every `duration` to be formatted this way to `hh_mm_ss` directly (this is the `format("{:%T}", some_duration) == "00:00:00"` bug discussed in the original issue (not the same bug, but closely related ;))
- Simplified `abs` for `duration`s slightly.
- Added custom `%H` format override.
Fixes #3676
> Fix `hh_mm_ss` formatting for values >= 1 day

- stl/inc/expected
- tests/libcxx/expected_results.txt
- tests/std/tests/P0323R12_expected/test.cpp
Per LWG-3843, `std::expected<int, std::unique_ptr<int>>{}.value()` needs to be rejected. But currently MSVC and Clang incorrectly accept it (DevCom-1638273 and LLVM-53224).
We also need to ensure that the `value() &` overload also treats `_Err` as a const lvalue on copy.
The mandating is missing in the standard wording in [[expected.void.obs]](https://eel.is/c++draft/expected.void.obs) currently, which is likely another LWG issue. I've mailed LWG chair for this.
Edit: the issue is now LWG-3940.
> Implement LWG-3843 `std::expected<T,E>::value() &` assumes `E` is copy constructible

- stl/inc/format
- tests/std/tests/P0645R10_text_formatting_args/test.cpp
- tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp
Also make formerly exposition only constructors private. As a result, several class templates are forward declared.
Add test coverage for construction of `handle` and inaccessibility of exposition only constructor(s). Note that construction of `handle` from a const rvalue is still possible since a `const T` rvalue can be bound to `const T&`.
Per @cpplearner's discovery on Discord, I decided to ensure that `TQ` (~`_Qual_for_handle<_Ty>`~`_Tq`  in this PR) never drops const-qualifier from `T` (`_Ty`).
Fixes #3460.
> Implement LWG-3631 `basic_format_arg(T&&)` should use `remove_cvref_t<T>` throughout 

- stl/inc/array
- stl/inc/bitset
- stl/inc/deque
- stl/inc/vector
For example, `void _Xran() const` ~> `static void _Xran()`.
> Add static for some `_Xxxx()` member functions

- stl/inc/future
`_Associated_state::_Ready_at_thread_exit` is always-false and has no real effect(#3740). This pr removes all relevant non-functional logics.
`_State_manager::_Get_only_once` may have similar issues, but I'm not too confident now so it is kept untouched.
> Cleanups for `<future>`

- stl/inc/mutex
- stl/inc/shared_mutex
- Removes `condition_variable::_Wait_until1(...const _timespec64*...)`, which is not called anywhere.
- Fuses some ugly methods like `timed_mutex::_Try_lock_until`.
> Cleanups for `<mutex>`  etc.

- stl/inc/memory
- stl/inc/system_error
- stl/inc/type_traits
- stl/inc/utility
- stl/inc/xtr1common
- stl/inc/xutility
- tests/std/tests/GH_002206_unreserved_names/test.compile.pass.cpp
This PR is trying to push and pop these attribute tokens like `new`. Considering `[[msvc::lifetimebound]]` which is about to be used (#3754).
Fixes #2645.
> Workaround for non-_Ugly attribute tokens

- stl/inc/condition_variable
- tests/std/tests/GH_000685_condition_variable_any/test.cpp
> `<condition_variable>`: Fixes bad timeout in wait_until with unsigned rep

- stl/inc/ranges
One non-defaulted move constructor for `_Defaultabox` is currently _never_ `noexcept`, which is probably a bug. ~So I decided not to add `// strengthened` to that move constructor. Some similar constructors are made conditionally `noexcept`, and I think `// strengthened` is suitable for them.~
`_Defaultabox` is used for `join_view::_Iterator` and `lazy_split_view`, while the standard wording uses `optional` and _`non-propagating-cache`_ respectively. And thus I'm afraid that the exception specifications are not yet strong enough for `lazy_split_view`. But further strengthening seems dangerous.
> `<ranges>`: Strengthen exception specification for `_Defaultabox`

- stl/inc/deque
- stl/inc/forward_list
- stl/inc/list
- stl/inc/vector
- stl/inc/xhash
- stl/inc/xstring
- stl/inc/xtree
Removes `_Reference` and `_Const_reference` for `_[List/Deque/Tree/Vec/String/Flist]_iter_types`.
> Remove redundant template parameters for `_XX_iter_types`

- stl/inc/__msvc_iter_core.hpp
- stl/inc/algorithm
- stl/inc/chrono
- stl/inc/execution
- stl/inc/expected
- stl/inc/memory
- stl/inc/ranges
- stl/inc/tuple
- stl/inc/utility
- stl/inc/xmemory
- stl/inc/xutility
- tests/std/tests/P0896R4_common_iterator/test.cpp
- tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
- tests/std/tests/P1899R3_views_stride/test.cpp
- tests/std/tests/P2164R9_views_enumerate/test.cpp
- tests/std/tests/P2374R4_views_cartesian_product/test.cpp
- tests/std/tests/P2387R3_pipe_support_for_user_defined_range_adaptors/test.cpp
clang-format 16 doesn't need these anymore, and in fact they often make things _worse_. Note that "I don't like how clang formats this" isn't enough reason to mess with the formatting; the threshold for using annotations is "the code without annotations is so bad that having noise from annotations is an improvement."
> Remove some unnecessary clang-format hacks

- stl/inc/xstring
- tests/std/tests/P0220R1_string_view/test.cpp
As discovered in #3735, both
- `basic_string_view`'s constructor from a `const _Elem*` (strengthened) and
- the `basic_string_view::compare` overload for two `basic_string_view`s (mandatory)
are already `noexcept`, so `basic_string_view::compare` for a `basic_string_view` and a `const _Elem*` should also be `noexcept`.
The exception specification strengthening is already done for `basic_string`.
https://github.com/microsoft/STL/blob/a62109595b6d89e08172fdf4beb75a2670fe0cc9/stl/inc/xstring#L4646-L4649
The message in the `static_assert` "(this is bad, char_traits)" no longer holds, since the exception specifications of all `char_traits::compare` in MSVC STL are already strengthened.
----
Driven-by changes: make `basic_string::_Eos`, `basic_string::_Swap_proxy_and_iterators`, and …
> `<xstring>`: Strengthen exception specification for `sv.compare("NTBS")`

- stl/inc/semaphore
See [[thread.sema.cnt]/2](https://eel.is/c++draft/thread.sema.cnt#2).
Also change the precondition check for `release` into the form in standard wording ([[thread.sema.cnt]/8](https://eel.is/c++draft/thread.sema.cnt#8)).
Also make the internal function `_Wait` private.
Fixes #3746. Thank you @achabense!
> `<semaphore>`: Add missed mandates for `counting_semaphore`

- stl/inc/barrier
> Enhance `_STL_VERIFY` for `std::barrier`

- stl/CMakeLists.txt
- stl/inc/mutex
- stl/msbuild/stl_base/libcp.settings.targets
- stl/msbuild/stl_base/msvcp.settings.targets
- stl/src/cond.cpp
- stl/src/mutex.cpp
- stl/src/primitives.hpp
`<mutex>` doesn't need to know the layout of the critical section member. Specifying the layout is both unnecessary and error-prone (if we ever decide to change `stl_critical_section_win7`).
This also makes it possible to verify that `_Critical_section_size` matches `stl_critical_section_max_size`.
This fixes a bug on UWP where locking a `mutex` could throw a bogus exception.
> `<mutex>`: Make `_Mtx_internal_imp_mirror` more closely match `_Mtx_internal_imp_t`

- stl/inc/mdspan
- tests/std/include/test_mdspan_support.hpp
- tests/std/tests/P0009R18_mdspan_extents_death/test.cpp
* Guard `_STL_VERIFY` with `#if _CONTAINER_DEBUG_LEVEL > 0` (towards https://github.com/microsoft/STL/pull/3586#discussion_r1148075895). I believe that this is the best solution, because:
* The checks are cheap,
* The checks don't require ABI-changing bookkeeping.
* Improve `extents`' constructors:
* `extents(other extents)` constructor avoids using `for` loop and uses `index_sequence` instead,
* `extents(exts...)` constructor avoids creating temporary arrays and using `for` loop. Instead, it puts `exts...` in a tuple and then constructs `_Dynamic_extents` array directly,
* `extents(exts...)` now always checks elements in `exts` when it is possible. Previously it checked element when all elements were "checkable" (were `integral`),
* `extents(span/array)` is more efficient.
* Add extra …
> `<mdspan>`: `extents` improvements

- stl/inc/__msvc_bit_utils.hpp
- stl/inc/complex
- stl/inc/deque
- stl/inc/mutex
- stl/inc/random
- stl/inc/regex
ICU previously macroized these reserved names. This was fixed by https://github.com/unicode-org/icu/pull/1555 on 2021-02-01, but old versions of ICU are still being used by various projects. Let's avoid these names for now. I haven't added test coverage because the UCRT uses some of these reserved names (which it's getting away with, due to the specific order in which headers are being included).
Fixes VSO-1837381 "\[RWC\]\[prod/fe\]\[Regression\] PDFium failed with error C2209: `'std::_Aligned_storage_t<64,8>'`: aliases cannot be used in constructor declarations".
* `_Cs` => `_Cs_storage`
+ This introduces a slight but acceptable asymmetry with `mutex.cpp`.
+ This is the actual fix for the regression introduced by #3763. We were getting away with the others.
* `_No` => `_Nope`
+ This …
> Avoid evil macros

- stl/inc/xutility
Towards #3599.
#832 doesn't seem completely fixed now due to #3678. This PR tries to remove inclusion of `<limits>` in `<xutility>`.
> Don't include `<limits>` in `<xutility>`

- stl/inc/ranges
- tests/std/tests/P0896R4_views_lazy_split/test.cpp
> Implement LWG-3904 `lazy_split_view::outer-iterator`'s `const`-converting constructor isn't setting `trailing_empty_`

- stl/inc/ranges
> Documentation Fix for #3780

- stl/inc/expected
- tests/libcxx/expected_results.txt
Fix [#3779](https://github.com/microsoft/STL/issues/3779)
> Documentation fix for #3779

- stl/inc/format
- tests/std/tests/P0645R10_text_formatting_args/test.cpp
Also fix a small bug on visiting `0`. As the visitor always visits a cv-unqualified `basic_format_arg` lvalue, it's incorrect to use `_STD forward<_Visitor>(_Vis)(0)` which takes an `int` prvalue and can result in non-conforming ill-formedness.
IMO this PR will make it simpler to implement WG21-P2637R3. Unfortunately, we're perhaps unable to implement that paper at this moment.
> `<format>`: Move the major part of `visit_format_arg` into a member function of `basic_format_arg`

- stl/inc/flat_set
- tests/std/tests/P1222R4_flat_set/test.cpp
As noticed by @achabense on Discord, the former use of the scope guards always cleared the containers, which was wrong.
Also fix the return type which may be different from `size_t`. I choose to spell the return type in a shorter form.
Also use `addressof` to avoid ADL-hijacking `operator&`.
Also remove one redundant `inline`.
> `<flat_set>`: Fix `erase_if` for `flat_set`/`flat_multiset`

- stl/inc/mdspan
- tests/std/include/test_mdspan_support.hpp
- tests/std/test.lst
- tests/std/tests/P0009R18_mdspan_extents_death/test.cpp
- tests/std/tests/P0009R18_mdspan_layout_left/test.cpp
- tests/std/tests/P0009R18_mdspan_layout_left_death/test.cpp
- tests/std/tests/P0009R18_mdspan_layout_right/test.cpp
- tests/std/tests/P0009R18_mdspan_layout_right_death/test.cpp
- tests/std/tests/P0009R18_mdspan_layout_stride_death/test.cpp
- tests/std/tests/P0009R18_mdspan_mdspan_death/env.lst
- tests/std/tests/P0009R18_mdspan_mdspan_death/test.cpp
* Guard all existing debug checks with `#if _CONTAINER_DEBUG_LEVEL > 0` (addresses https://github.com/microsoft/STL/pull/3586#discussion_r1148075895),
* `extents`:
* Make `_Static_extents` array public and use it when possible,
* Add new `_Multidim_index_space_size_is_always_zero` static member variable,
* Split `_Is_index_space_size_representable` into two functions: `_Is_static_multidim_index_space_size_representable` and `_Is_dynamic_multidim_index_space_size_representable`,
* Report DevCom-10398426 and silence it,
* Improve debug check in `extents(_OtherIndexTypes... _Exts)` constructor,
* `layout_(left|right|stride)`
* Implement missing debug checks,
* Replace scary looking immediately invoked lambda expressions with simple `for` loops (`layout_(left|right)`'s constructors from …
> `<mdspan>`: Improve debug checks

- tests/std/include/test_mdspan_support.hpp
- tests/std/tests/P0009R18_mdspan_layout_stride/test.cpp
Drive-by: fix `get_mapping_properties` when `Mapping::extents_type::rank() == 0`.
> `<mdspan>`: Finish `layout_stride`'s tests

- stl/inc/mdspan
- tests/std/tests/P0009R18_mdspan_extents/test.cpp
* Introduce `_Calculate_rank_dynamic` template variable for easier `rank_dynamic()` computations,
* Introduce `_Maybe_empty_array` - a base class for `std::extents` and (in the future) for `std::layout_stride::mapping`,
* Remove `extents::_Static_extents_only` and `extents::_Dynamic_extents`,
* Add tests.
> `<mdspan>`: Make `extents` truly empty when `rank_dynamic() == 0`

- stl/inc/mdspan
- tests/std/tests/GH_002206_unreserved_names/test.compile.pass.cpp
- tests/std/tests/P0009R18_mdspan_default_accessor/test.cpp
- tests/std/tests/P0009R18_mdspan_layout_left/test.cpp
- tests/std/tests/P0009R18_mdspan_layout_right/test.cpp
- tests/std/tests/P0009R18_mdspan_layout_stride/test.cpp
- tests/std/tests/P0009R18_mdspan_mdspan/test.cpp
* Add new base classes required for EBO implementation:
* `_Maybe_fully_static_extents` - EBO for `layout_left::mapping`,`layout_right::mapping` and `layout_stride::mapping`,
* `_Mdspan_mapping_base` - EBO for `mdspan` (`_Map` member only),
* `_Mdspan_accessor_base` - EBO for `mdspan` (`_Acc` member only),
* Add `/* [[no_unique_address]] */` comments when EBO cannot be applied.
* Ideally we would get rid of those base classes and just use this attribute (see #1364).
* Drive-by: address comment from #3825 (`static_cast<size_t>` in `_Calculate_rank_dynamic`).
* Add tests.
> `<mdspan>`: More EBO

- stl/inc/mdspan
- tests/std/include/test_mdspan_support.hpp
- tests/std/tests/GH_002206_unreserved_names/test.compile.pass.cpp
- tests/std/tests/P0009R18_mdspan_extents_death/test.cpp
- tests/std/tests/P0009R18_mdspan_layout_left/test.cpp
- tests/std/tests/P0009R18_mdspan_layout_right/test.cpp
- tests/std/tests/P0009R18_mdspan_layout_stride_death/test.cpp
- tests/std/tests/P0009R18_mdspan_mdspan/test.cpp
- tests/std/tests/P0009R18_mdspan_mdspan_death/test.cpp
* Privatize implementation-defined constructors,
* Strengthen various functions,
* Address comments from previous PRs:
* https://github.com/microsoft/STL/pull/3829,
* https://github.com/microsoft/STL/pull/3847,
* Add extra `_STL_INTERNAL_STATIC_ASSERT` in various places,
* Simplify `_Make_dynamic_indices_inv` and fix size of `_Dynamic_indices_inv` array,
* Make `check_members_with_various_extents` test less heavy.
After this PR `<mdspan>` will be ready for final review 😸
> `<mdspan>`: Final cleanups

- .github/workflows/compile-typescript.yml
- README.md
- package-lock.json
- package.json
- src_gather/gather_stats.ts
The Status Chart's automated daily update started failing with "error TS2590: Expression produces a union type that is too complex to represent." This is because we've accumulated so many days of history that TypeScript's advanced type inference is reaching internal limits.
The fix is very simple. When generating our `DailyRow[]` table, add `as DailyRow` type assertions to each element. This avoids making TypeScript deduce what each element could be, because we already know what type we ultimately want.
This PR also contains unrelated housekeeping - minor dependency updates, and increasing the mentioned Node.js version to 20.4.0 (I've gone back and forth on this; I think we should be a bit more diligent about keeping this updated).
Finally, this contains a "DROP BEFORE MERGING" commit to …
> Status Chart: Fix error TS2590

- tests/std/tests/P0218R1_filesystem/test.cpp
I _think_ LWG-2682 has been implemented (see https://github.com/microsoft/STL/issues/71#issuecomment-1455398683). So I just add test coverage for it.
Fixes #71.
> Test coverage for LWG-2682 `filesystem::copy()` won't create a symlink to a directory

- stl/inc/algorithm
- stl/inc/yvals_core.h
- tests/std/lit.site.cfg.in
- tests/std/rulesets/stl.ruleset
- tests/std/test.lst
- tests/std/tests/GH_002094_cpp_core_guidelines/env.lst
- tests/std/tests/GH_002094_cpp_core_guidelines/test.compile.pass.cpp
- tests/utils/stl/test/format.py
- tests/utils/stl/test/tests.py
Works towards #3754. Works towards #2094.
This PR adds `[[msvc::lifetimebound]]` to `std::minmax` and `std::ranges::minmax`, which are more error-prone than `std::min`/`std::max` but not as widely used.
`#define _SILENCE_LIFETIMEBOUND_WARNING` to suppress the warning.
```
C:\Users\He\source\repos\STL\out>type test.cpp
```
```cpp
#include <algorithm>
int square(int x) {
return x * x;
}
int square_diff(int x, int y) {
const auto [min, max] = std::minmax(square(x), square(y));
return max - min;
}
```
```
C:\Users\He\source\repos\STL\out>clang -Wall -Wextra -std=c++17 -c test.cpp
test.cpp:8:41: warning: temporary whose address is used as value of local variable '[min, max]' will be destroyed at the
end of the full-expression [-Wdangling]
const auto [min, max] = std::minmax(square(x), …
```
> Add `[[msvc::lifetimebound]]` to `minmax`

- stl/inc/yvals_core.h
- tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp
Fixes #3793. Fixes #3794. Fixes #3795.
(But we may need to reopen these issues and #2914 in future once freestanding mode is added. See #1289.)
It seems to me that hosted implementations are required to provide all of these macros (see "Rejected alternatives" in WG21-P2198R7). I think it makes more sense to define them in older modes when the corresponding feature/header is available.
Possibly related question: should we leave feature-test macros for non-core components not defined when `_ENFORCE_ONLY_CORE_HEADERS` is defined?
> C++26 freestanding feature-test macros

- stl/inc/functional
- tests/std/tests/Dev11_0535636_functional_overhaul/test.cpp
> `<functional>`: Make `function::target` return null function pointers without cast

- stl/inc/array
- tests/libcxx/expected_results.txt
- tests/std/tests/Dev11_1074023_constexpr/test.cpp
- tests/tr1/tests/array/test.cpp
... which shouldn't even be there, but can't be removed because ABI.
Fixes DevCom-10299275 / VSO-1759562 / AB#1759562.
Notably this will fail with `T`'s that cannot be `{}`-initialized, e.g., types with explicit default constructors. We could work around that in C++17-and-later by initializing the array with `{T()}`, but I didn't want to obfuscate the code and I feel these two corner cases are incredibly unlikely to occur together.
> Initialize array<T, 0>'s single element

- stl/inc/deque
- stl/inc/sstream
- stl/inc/syncstream
- stl/inc/vector
- stl/inc/xmemory
- stl/inc/xstring
- tests/std/test.lst
- tests/std/tests/GH_003570_allocate_at_least/env.lst
- tests/std/tests/GH_003570_allocate_at_least/test.cpp
This reverts the reversion of #3712 from #3819. It also detects allocators publicly derived from `std::allocator`, and refuses to use `allocate_at_least` in such a case to avoid potential mismatch between a user's `deallocate` and the default `allocate_at_least`.
I expect we'll squash merge this, but I've kept it as two separate commits for ease of review: one that reverts the revert, and one that implements the fix.
> Reallocate at least

- stl/inc/functional
- tests/libcxx/expected_results.txt
- tests/std/tests/GH_000952_bind_constraints/test.compile.pass.cpp
The deleted overloads prevent overload resolution flowing into another unintended overload when the invocation should be (SFINAE-friendlily) ill-formed.
Since the `operator()` overloads are constrained in default template arguments now, I think it would be better to use `decltype(auto)` to specify the return types.
There seems to be something wrong with modules when using traditional SFINAE, so I'm changing to use `requires` when possible.
~Unblock one libc++ test:~
- ~`std/utilities/function.objects/func.bind_front/bind_front.pass.cpp`~
The test seemly requires `bind_front` to be SFINAE-friendly, while the Standard uses "_Mandates_:"... As a result, I decided to copy some parts of that file into MSVC STL's test file.
Driven-by: `_STD`-qualify the internal calling helpers.
> `<functional>`: Deleted `operator()` overloads for return types of `bind`, `bind_front`, and `bind_back`

- stl/inc/xlocale
- tests/std/tests/Dev09_056375_locale_cleanup/test.cpp
I think that LWG issue is actually already implemented, and thus just add test coverage and precondition checking.
Driven-by change: mark the `noexcept` checking (added in #3250) as `// strengthened`.
Fixes #3463.
> Test coverage and precondition checking for LWG-2295 Locale name when the provided `Facet` is a `nullptr`

- stl/inc/format
- (Cleanup) Remove two redundant parameters in a `requires` expression.
They were meant for `_Parse_align_callbacks`(which is already checked).
- Avoid usage of `visit_format_arg` in `_Estimate_required_capacity`.
This change makes the method a lot more light-weight.
- Avoid usage of `toupper` in `_Buffer_to_uppercase` and another place.
I believe we don't need locale awareness in these places, and `toupper` cannot be inlined.
- Avoid calling `_Buffer_to_uppercase` in `_Write_integral` when `_Specs._Type` is `'B'`.
In this case there are no letters in the buffer.
> Optimizations for `<format>`

- benchmarks/CMakeLists.txt
- benchmarks/src/bitset_to_string.cpp
- stl/inc/bitset
- simplifies `bool operator[](size_t) const`.
- makes some public `_Members` private.
- optimizes `to_string`.
<details>
<summary>Benchmark</summary>
```cpp
#include <bitset>
#include "benchmark/benchmark.h"
template <class _Char = char, size_t _N>
auto _to_string_bef(const std::bitset<_N>& _Bset, const _Char _Elem0 = '0',
const _Char _Elem1 = '1') {
return _Bset.to_string(_Elem0, _Elem1);
}
template <class _Char = char, size_t _N>
auto _to_string_now(const std::bitset<_N>& _Bset, const _Char _Elem0 = '0',
const _Char _Elem1 = '1') {
std::basic_string<_Char> _Str(_N, _Elem0);
for (size_t _Idx = 0; _Idx < _N; ++_Idx) {
if (_Bset[_N - 1 - _Idx]) {
_Str[_Idx] = _Elem1;
}
}
return _Str;
}
template <class _Char, size_t N>
void BM_bef(benchmark::State& state) {
std::bitset<N> …
```
> Enhancements for `<bitset>`

- stl/inc/xlocale
- stl/inc/xlocmes
- stl/inc/xlocmon
- stl/inc/xloctime
- tests/std/tests/Dev09_056375_locale_cleanup/test.cpp
Also make `messages_base` implicitly default constructible, which seems to be implied by the standard wording.
Also add some "TRANSITION, ABI" comments because it seems that these base types shouldn't be derived from `locale::facet`.
> Strengthen exception specification for some facet base types

- stl/src/cthread.cpp
- stl/src/mutex.cpp
- stl/src/ppltasks.cpp
They are: `_Thrd_abort`, `_Thrd_exit` and `_ReportUnobservedException`.
> Add `[[noreturn]]` for some functions

- stl/inc/xlocnum
- tests/std/test.lst
- tests/std/tests/GH_003867_output_nan/env.lst
- tests/std/tests/GH_003867_output_nan/test.cpp
> fix writing NaN to the output stream with a set locale

- stl/inc/filesystem
`_Current_path` is wrongly marked as `noexcept`, which will cause the program to terminate if `resize` throws.
https://github.com/microsoft/STL/blob/2261f7edb760eb3fe0726187c818b796dc7ea798/stl/inc/filesystem#L4045-L4046
This pr fixes it by merging the function into throwable `path current_path(error_code&)`.
> `<filesystem>`: fix dangerous `noexcept` specification of `_Current_path`

- stl/inc/xlocnum
- tests/libcxx/expected_results.txt
- tests/std/tests/Dev11_0496153_locale_ctor/test.cpp
- tests/std/tests/GH_003867_output_nan/test.cpp
> Fix iostreams with imbued locales to print INFs correctly

- benchmarks/src/path_lexically_normal.cpp
- stl/inc/filesystem
- Fix another problematic `noexcept` signature for `_Read_symlink`
https://github.com/microsoft/STL/blob/f51733ca5352c712165e46fdbc5d0d395971f0e7/stl/inc/filesystem#L3233
- Merge `_Absolute` into `absolute`, as it's simple enough
- Nitpicks for my previous prs: add a missed `// for exception safety` comment; make benchmark cases look better; make the vector reserve slightly more space in `lexically_normal`
> Follow-up enhancements for `<filesystem>`

- stl/inc/xmemory
- tests/std/tests/GH_003570_allocate_at_least/test.cpp
... to avoid DevCom-10419218, a C1XX bug in the non-requires-expression detection.
Fixes VSO-1852860 / AB#1852860
> Detect allocate_at_least with a concept

- stl/inc/cmath
- stl/inc/random
- stl/inc/valarray
- stl/src/xlgamma.cpp
- tests/libcxx/expected_results.txt
- tests/std/tests/GH_000940_missing_valarray_copy/test.cpp
Adding unconditional `noexcept` to suitable functions in `<cmath>`, `<random>`, and `<valarray>`.
(Conditional `noexcept` may be suitable for many functions in `<random>`...)
Currently only test for `<valarray>` is added. I hope we can add the test coverage to a new test suit for MS-specific properties and extensions in the future (see #502).
A bug of MSVC (DevCom-10416247) is discovered during testing.
> Strengthen exception specification for numeric operations

- stl/inc/filesystem
- stl/inc/format
- stl/inc/xfilesystem_abi.h
- Remove all unnecessary `typename`s for `<format>` header (#3718).
- (Also, move `_Is_slash_oper & _Is_slash` downstream from `<xfilesystem_abi.h>` to `<filesystem>` as it is only needed there.)
> Remove unnecessary `typename`s for `<format>`

- stl/inc/compare
- stl/inc/coroutine
- stl/inc/numbers
- stl/inc/ranges
- stl/inc/stacktrace
- stl/inc/syncstream
The headers newly introduced in C++20 are:
```
<bit>
<compare>
<concepts>
<coroutine>
<format>
<numbers>
<ranges>
<source_location>
<span>
<syncstream>
<version>
<barrier>
<latch>
<semaphore>
<stop_token>
```
The headers that contain `typename` are:
```
<compare>: Removes two `typename` in `using` clauses; one left as necessary.
<concepts>: All necessary.
<coroutine>: X(Removes one in `using` clause; one left as necessary) update: kept unchanged
<format>: Tackled in last pr.
<numbers>: Removes the only one.
<ranges>: Removes those in `using` clause; the rest(a lot) are necessary.
<span>: All necessary.
<syncstream>: Removes those in `using` clause; one left as necessary.
```
Also removes all `typename` in `<stacktrace>`
Works towards #3718.
> Remove unnecessary `typename`s for all standard headers introduced in C++20

- stl/inc/atomic
- stl/inc/chrono
- stl/inc/deque
- stl/inc/forward_list
- stl/inc/functional
- stl/inc/list
- stl/inc/map
- stl/inc/memory
- stl/inc/regex
- stl/inc/set
- stl/inc/spanstream
- stl/inc/tuple
- stl/inc/type_traits
- stl/inc/unordered_map
- stl/inc/unordered_set
- stl/inc/vector
- stl/inc/xhash
- stl/inc/xmemory
- stl/inc/xstring
- stl/inc/xutility
Followup to #3892 and #3893. Works towards #3718 - I believe this finishes the product code, but we're open to cleaning up the test code here.
Reported VSO-1854035 "C++20 Down With Typename is confused by fully qualified names".
> Remove unnecessary `typename`s in all remaining headers

- stl/inc/condition_variable
- stl/inc/mutex
- stl/inc/thread
- stl/inc/xthreads.h
- stl/src/cond.cpp
- stl/src/cthread.cpp
- stl/src/mutex.cpp
- stl/src/thread0.cpp
I was briefly investigating #292 again due to a related user report, where it turned out that that specific problem was fixed by #3721. For the general problem of defending the STL against *all* unconstrained operator overloads, it's unclear whether we can practically solve it, or whether we should devote significant effort towards doing so (considering that it isn't a regression, and that plenty of UCRT/VCRuntime/PPLTasks headers are also affected). I note this because I *don't* want to encourage a bunch of follow-up PRs in this area.
However, I noticed that `<xthreads.h>` uses an unnamed, unscoped enumeration for its result codes, which are returned as `int`. This came to my attention because it leads to `int`s being compared to these enumerators (hence this can be hijacked by …
> `<xthreads.h>`: Use `enum class _Thrd_result` for type safety

- tests/std/tests/P0608R3_improved_variant_converting_constructor/test.cpp
- tests/std/tests/P0718R2_atomic_smart_ptrs/test.cpp
- tests/std/tests/P2321R2_proxy_reference/test.cpp
* Use lvalue references for the LHS of `is_assignable_v` and `is_nothrow_assignable_v` for `variant` and `atomic<shared_ptr>`.
+ We expect lvalues even though it technically works with rvalues.
* Check const rvalues and const lvalues in `P2321R2_proxy_reference`.
+ This is a "nice to have" expansion of test coverage, as both work, and this makes it clear that we didn't test them unintentionally.
* Cite LWG-3661 with the usual syntax.
> Fix `is_assignable` test coverage

- stl/inc/functional
- stl/inc/future
- stl/inc/xutility
> Cleanups for `don't-call` functions

- stl/inc/flat_set
> `<flat_set>`: Drop `#pragma once`

- stl/inc/algorithm
- stl/inc/execution
- stl/inc/numeric
- stl/inc/xutility
Fixes #2985.
Notes:
- This PR is introducing `_REQUIRE_CPP17_MUTABLE_BIDIRECTIONAL_ITERATOR` and `_REQUIRE_CPP17_MUTABLE_RANDOM_ACCESS_ITERATOR`, which require mutable iterators to be _Cpp17BidirectionalIterator_ and _Cpp17RandomAccessIterator_ respectively.
- If a parallel algorithm calls another parallel overload, then the checking is only made in the other overload.
- `reverse_copy` is specially handled, since it requires the source iterators to be bidirectional.
It seems that the checking also make sense for non-parallel (non-`ranges`) algorithms, but we can do this in another PR.
> Consistent iterator type checking for parallel algorithms

- stl/inc/exception
- stl/inc/thread
Towards #3888
Will talk about `std::terminate()` in `ppltasks.cpp` later.
> Justify `terminate()` calls

- stl/src/ppltasks.cpp
Towards #3888
Changes:
* In the preprocessor condition, added pre-Win8 check. Starting in Windows8, `__fastfail` is always available. Mostly added as a reminder that this should be cleaned up further when dropping pre-Win8.
* Changed `terminate` to `abort` as discussed in https://github.com/microsoft/STL/issues/3888#issuecomment-1654482314
* Restructured the flow to avoid calling `abort()` if always calling `__fastfail`. IMO, the compiler should make the assumption that `__fastfail` does not return by itself, added DevCom-10425806.
> Avoid unnecessary handling in `_ReportUnobservedException`

- stl/debugger/STL.natvis
The `locking_thread_id` and `ownership_levels` can be represented by named members now, so I believe we can simplify its visualization.
I've verified that the outputs are unchanged for `std::recursive_mutex` with every combination of MSVC/Clang, x64/x86, and Debug/Release.
> `STL.natvis`: Simplify visualization for `mutex`/`recursive_mutex`

- stl/src/stacktrace.cpp
[C23 WP N3096](https://open-std.org/JTC1/SC22/WG14/www/docs/n3096.pdf) 7.23.6.5 "The `snprintf` function"/2:
> The `snprintf` function is equivalent to `fprintf`, except that the output is written into an array (specified by argument `s`) rather than to a stream. If `n` is zero, nothing is written, and `s` may be a null pointer. Otherwise, output characters beyond the `n`-1<sup>st</sup> are discarded rather than being written to the array, and a null character is written at the end of the characters actually written into the array.
In English, `n` should be the buffer size, **INCLUDING** room for a null terminator.
`stacktrace.cpp` consistently said `sizeof("meow") - 1`, which excludes the null terminator. This was a mistake.
So far I haven't seen actual misbehavior caused by this.
> `stacktrace.cpp`: Fix `snprintf()` usage

- tools/validate/validate.cpp
This PR replaces uses of `fwprintf` with calls to `print(ln)`.
> Modernize `validate.cpp`: Use `<print>` instead of `<cstdio>`

- tests/std/tests/P0009R18_mdspan_default_accessor/test.cpp
- tests/std/tests/P0009R18_mdspan_extents/test.cpp
* Remove superfluous `std::`, the tests do `using namespace std;`
* Cast `bool` to `size_t` explicitly
* Check the correct constructor
> mdspan STL's review comments - easy part

- README.md
- azure-devops/provision-image.ps1
- azure-pipelines.yml
- tests/std/include/range_algorithm_support.hpp
- tests/std/tests/P0019R8_atomic_ref/test.cpp
- tests/std/tests/P0040R3_extending_memory_management_tools/test.cpp
- tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp
- tests/std/tests/P0660R10_stop_token/test.cpp
- tests/std/tests/P1135R6_atomic_flag_test/test.cpp
This updates the pool for VS 2022 17.8 Preview 1, including August's Patch Tuesday.
We're not yet able to require 17.8 because the internal build is still starting with 17.6 (!). No changes to CMake/Ninja/Clang versions.
Update to PowerShell 7.3.6 when building the pool.
We're able to remove a couple of compiler bug workarounds:
* Remove workaround for VSO-1659408 "`/clr` `alignas` emits error C2711 "this function cannot be compiled as managed" instead of falling back to native codegen"
+ Validated internally.
+ One workaround had to be retained due to an apparently different bug that has now been revealed. I filed VSO-1867037 "`/clr` C++20 System.AccessViolationException with ranges uninitialized algorithms".
+ Two more workarounds had to be retained due to VSO-1659695 "`/clr` x86 …
> Toolset update: VS 2022 17.8 Preview 1

- stl/src/StlCompareStringA.cpp
- stl/src/StlCompareStringW.cpp
- stl/src/StlLCMapStringA.cpp
- stl/src/StlLCMapStringW.cpp
- stl/src/xmtx.cpp
- stl/src/xmtx.hpp
We should have export specifiers on both function declaration **and** definition.
This is because after some future changes the declaration may be gone - either entirely, or header be no longer included.
By repeating export specifiers we make sure the function type and its impact on export surface stays the same.
See https://github.com/microsoft/STL/pull/3912#issuecomment-1661423190
Additionally, this simplifies the declarations in `stl/src/xmtx.hpp` to match the definitions (the declarations are functionally unchanged).
> Repeat export specifiers on definitions, so that they stay if the declarations are gone

- stl/src/winapisupp.cpp
Resolve #3926
Mostly a red change
Also repeat `_CRTIMP2` on `__crtGetSystemTimePreciseAsFileTime` -- see #3927
> Remove unused functions from `winapisupp.cpp`

- stl/inc/sstream
- stl/inc/xstring
- tests/std/tests/Dev09_181509_tr1_inf_loop_uniform_int_ull/env.lst
- tests/std/tests/Dev09_181509_tr1_inf_loop_uniform_int_ull/test.cpp
- tests/std/tests/VSO_0000000_allocator_propagation/test.cpp
This is a reorganized version of #3830.
- Various logic cleanups to make `basic_string` easier to maintain.
- Fixes a bug in `operator=(const&)` which will break invariant.
Thanks to @StephanTLavavej, @fsb4000 and @frederick-vs-ja for review in the original pr!
> Logic cleanups for `basic_string`

- stl/inc/bitset
- stl/inc/xstring
Towards #3858.
> * @AlexGuteniev suggested using `basic_string::resize_and_overwrite`, creating an `_Ugly` version for unconditional use internally. (We generally avoid adding totally novel secret machinery to Standard classes as it can become a maintenance burden, but simply having `_Ugly` names to access Future Technology is easy and common.)
This is what was addressed
> * @AlexGuteniev also suggested investigating whether branchless codegen for assigning `_Elem0` vs. `_Elem1` would be superior. (Note: we cannot assume that their values are consecutive, they could be `'M'` and `'E'`.)
This is confirmed to be non applicable. Before the change it was `cmovne` to set `'1'`. After it became `setne al` to set to 0 or 1, then `add al, '0'`. Both are branchless. I think, the compiler will be …
> Use `string::resize_and_overwrite` in `bitset` to avoid buffer initialization

- tests/std/tests/P1899R3_views_stride/test.cpp
- tests/std/tests/P2278R4_views_as_const/test.cpp
- tests/std/tests/P2321R2_views_zip/test.cpp
Towards #3391.
I've encountered some compiler issues with other C++23 range adaptors, so this PR only covers 3 of them.
> Testing: check `c(begin|end)` members of some C++23 ranges

- README.md
#3730 changes the current directory from `C:\Dev\STL\out\build\x64` to `C:\Dev\STL\out\x64`, so one less level of `..` is needed to reach the test directory.
> Fix README.md Examples

- CMakePresets.json
#3732 has added support for building the STL for the ARM64EC platform. This PR makes it easier to build for ARM64EC using the presets.
> `CMakePresets.json`: Add ARM64EC

- stl/inc/xtr1common
This is a very simple modification. The original _Is_any_of_v produces a lot of bloated unrolling. Using fold-expression is a better alternative. Because the change was so simple, I didn't issue it, and the tests were fine.
> update stl/inc/xtr1common: _Is_any_of_v

- tests/std/tests/Dev09_199123_tr1_mem_fun_abstract_classes/test.cpp
- tests/std/tests/Dev10_654977_655012_shared_ptr_move/test.cpp
- tests/std/tests/Dev10_847656_shared_ptr_is_convertible/test.cpp
- tests/std/tests/Dev11_0496153_locale_ctor/test.cpp
- tests/std/tests/Dev11_0535636_functional_overhaul/test.cpp
- tests/std/tests/Dev11_1066589_shared_ptr_atomic_deadlock/test.cpp
- tests/std/tests/P0220R1_polymorphic_memory_resources/test.cpp
- tests/std/tests/P0476R2_bit_cast/test.cpp
- tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
- tests/tr1/tests/future1/test.cpp
- tests/tr1/tests/locale1/test.cpp
- tests/tr1/tests/locale2/test.cpp
- tests/tr1/tests/locale3/test.cpp
- tests/tr1/tests/locale4/test.cpp
- tests/tr1/tests/memory1/test.cpp
- tests/tr1/tests/streambuf1/test.cpp
- tests/tr1/tests/streambuf2/test.cpp
As a general rule, we avoid significant cleanups of test code. This is partly because some tests are deliberately doing strange things to exercise weird corners of the product, and "cleaning up" the strangeness could affect test coverage. It's also because test code is much less important for long-term maintainability - if the tests keep passing, we generally don't care about them after they've been written.
However, we do try to enforce some basic conventions across the entire codebase including the tests. In the product code, we now follow a convention of saying only `override`. This avoids redundancy and allows `virtual` and `override` to serve different purposes (now when we see `virtual` we know we're introducing a new virtual member function). And using `override` is *much* safer …
> Consistently use `override` in tests

- tests/std/tests/P0009R18_mdspan_extents/test.cpp
- tests/std/tests/P0009R18_mdspan_extents_death/test.cpp
- tests/std/tests/P0009R18_mdspan_layout_left/test.cpp
- tests/std/tests/P0009R18_mdspan_layout_right/test.cpp
- tests/std/tests/P0009R18_mdspan_layout_stride/test.cpp
- tests/std/tests/P0009R18_mdspan_layout_stride_death/test.cpp
- tests/std/tests/P0009R18_mdspan_mdspan/test.cpp
* Include `<utility>` for `make_index_sequence`.
* Use `bool` underlying types when we call `to_underlying()` later.
* `Mdspan` => `mdspan` in comments.
* Rename an `array` from `s` to `a`.
+ The nearby comment is intentionally unchanged.
* Mark `ActionTracker` observers as `[[nodiscard]]`.
* Use `M1` typedef. Rename `m2` => `m1` to avoid looking weird.
* Extract `Mapping` typedef, like the block immediately above, and the `layout_right` test.
* `LyingLayout` inherits from `layout_left::mapping<Extents>`; use that for `is_always_exhaustive()`.
* Drop repeated line; `span<int>` is inherently symmetry-breaking here.
* Construct `layout_stride::mapping` without an extra `span`, matching `P0009R18_mdspan_layout_right`.
* In `P0009R18_mdspan_layout_right`, …
> Final `mdspan` test fixes

- stl/inc/mdspan
* Unconditionally strengthen `mdspan::is_always_MEOW()`.
+ They return `mapping_type::is_always_MEOW()` which is required to be a constant expression of type `bool` (N4950 \[mdspan.mdspan.overview\]/3, \[mdspan.layout.policy.reqmts\]/1, \[mdspan.layout.reqmts\]/22,24,26). The Standard should simply be enhanced to say `noexcept` here.
+ Also introduce `constexpr bool _Result` to make this extra clear and improve debug codegen.
* Drop strengthened comment; `_Access_impl()` is `_Ugly`.
* Follow N4950 \[mdspan.mdspan.cons\]/8.1 by saying `const _OtherIndexType&` in this constraint.
* In `default_accessor`, define `access()` before `offset()` to follow the order of N4950 \[mdspan.accessor.default.overview\].
* `layout_stride::template mapping` is unnecessary; `layout_stride` is not a template. …
> `<mdspan>`: Product code review

- stl/inc/system_error
- stl/src/excptptr.cpp
Towards #351.
I'm not sure which is really TRANSITION,
so I want this reviewed separately.
> Update `#else` transition comment

- stl/inc/xstring
- tests/std/tests/GH_002030_asan_annotate_string/test.cpp
Fixes #3955 / VSO-1854254 / AB#1854254 (fix string's self-assignment with offset via pointers under ASan)
Fixes VSO-1854245 / AB#1854245 "ASan issue in `basic_string::assign(pointer)`"
Fixes VSO-1854251 / AB#1854251 "ASan issue in `basic_string::assign(iterator, iterator)`"
Fixes VSO-1854242 / AB#1854242 "ASan issue in `tests/std/P0980R1_constexpr_strings` [`basic_string::resize_and_overwrite`]"
Drive-by: In `resize_and_overwrite`, compare the converted result size so we need not suppress the "comparing signed and unsigned" warning.
Test coverage for the latter three fixes will be in the ASan test coverage that's incoming in the near future.
> Fix `string::assign` and `::resize_and_overwrite` under ASan

- stl/inc/__msvc_chrono.hpp
Resolve #3929
I'm sorry I accidentally close the origin pull request... I upload it again. thank you.
> Replace if with if constexpr

- tests/tr1/tests/algorithm/test.cpp
These two `is_permutation(first, last, x)` calls violate the precondition that `[x, x + (last - first))` is a valid range.
Fixes VSO-1854237 / AB#1854237
> Fix bad tr1/algorithm test cases

- docs/cgmanifest.json
https://github.com/boostorg/math/releases/tag/boost-1.83.0
> Update boost-math to 1.83

- stl/inc/algorithm
- stl/inc/ranges
- tests/libcxx/expected_results.txt
Unblocks one libcxx test for MSVC.
I found that DevCom-1559808 is fixed during working on `_STD`-/`_RANGES`-qualifying _Ugly function names.
(And I've realized that structured bindings for `pair`/`subrange` involve ADL, so I'm planning changing the return type of `_Partition_by_median_guess_common` to something like `meow_result`).
Edit: I was wrong. DevCom-1559808 isn't totally fixed.
Edit: I've filed DevCom-10452846 "Customized structured binding of subrange that refers to dynamic buffer incorrectly causes constant evaluation failure" for the remain issue.
> Partially remove workaround for DevCom-1559808

- stl/inc/algorithm
- tests/std/tests/P0896R4_ranges_alg_lexicographical_compare/test.cpp
... even with two potentially-infinite ranges. 
Drive by: Pull non-dependent test cases out of the `instantiator::call` template magic in `tests/P0896R4_ranges_alg_lexicographical_compare`.
Fixes VSO-1854238 / AB#1854238
> Don't `memcmp(x, y, -1)` from `ranges::lexicographical_compare`
