tests/tr1/tests/regex3/test.cpp

This test constructs a `regex_iterator` and a `regex_token_iterator` with invalid character ranges. The first occurrence is benign - the test never directs the library to examine the bogus part of the range - but the second case ventures into the land of pure undefined behavior. Caught by ASan.
Fixes VSO-1854241 / AB#1854241

Don't violate preconditions in tr1/regex3

---

stl/inc/xlocnum
tests/std/tests/LWG2381_num_get_floating_point/test.cpp

Fixes #3980 / DevCom-10450662 / VSO-1876474 / AB#1876474
Also fixes DevCom-10445082 / VSO-1873604 / AB#1873604.
Likely fixes VSO-1874745 / AB#1874745.
Likely fixes VSO-1876601 / AB#1876601.

Fix `num_get`'s float-parsing problem

---

tests/std/include/range_algorithm_support.hpp
tests/std/include/test_atomic_wait.hpp
tests/std/tests/P0019R8_atomic_ref/test.cpp
tests/std/tests/P0024R2_parallel_algorithms_equal/test.cpp
tests/std/tests/P0024R2_parallel_algorithms_for_each/test.cpp
tests/std/tests/P0024R2_parallel_algorithms_inclusive_scan/test.cpp
tests/std/tests/P0024R2_parallel_algorithms_mismatch/test.cpp
tests/std/tests/P0024R2_parallel_algorithms_reduce/test.cpp
tests/std/tests/P0024R2_parallel_algorithms_replace/test.cpp
tests/std/tests/P0024R2_parallel_algorithms_transform_inclusive_scan/test.cpp
tests/std/tests/P0024R2_parallel_algorithms_transform_reduce/test.cpp
tests/std/tests/P0896R4_ranges_alg_equal/test.cpp
tests/std/tests/P0896R4_views_drop/test.cpp
tests/std/tests/P0896R4_views_elements/test.cpp
tests/std/tests/P0896R4_views_iota/test.cpp
tests/std/tests/P0896R4_views_take/test.cpp
tests/std/tests/P1135R6_atomic_flag_test/test.cpp
tests/std/tests/P1522R1_difference_type/test.cpp

Thanks to Shayne Hiet-Block's wonderful internal MSVC-PR-487530, we can remove numerous test workarounds for the following internal bugs:
* VSO-1658184 `/clr` silent bad codegen with `std::_Signed128` multiplication
* VSO-1659489 `/clr` System.AccessViolationException with parallel `std::mismatch`
* VSO-1659695 `/clr` x86 runtime assertions/crashes with parallel algorithms
* VSO-1665654 `/clr` C++20 x86 System.AccessViolationException with `atomic<shared_ptr>`
* VSO-1666180 `/clr` C++20 x64 System.AccessViolationException with `views::iota` and `views::transform`
* VSO-1867037 `/clr` C++20 System.AccessViolationException with ranges uninitialized algorithms
I had to report and add a highly targeted workaround for one remaining bug:
* VSO-1881472 `/clr` C++20 x86 …

Remove `/clr` test workarounds

---

stl/inc/expected
tests/std/tests/P0323R12_expected/test.cpp

Make `expected<any, ...>` and `expected<void, any>` copyable

---

stl/inc/flat_set
tests/std/tests/P1222R4_flat_set/test.cpp

Works towards #2912.
Replace #3985; the commits are reorganized for ease of review.
Major changes are:
1. Fix usage of `_Compressed_pair`; the implementation was erroneously trying to compress the container instead of `key_compare`.
2. Implement LWG-3884 (`flat_meow(flat_meow&&, al)`).
3. Implement missing `insert(initializer_list)`, and make `operator=(initializer_list)` available for users of `flat_meow`.
4. Fix `emplace[_hint]` and `insert([hint,]val)` functions.
4.1. Some functions couldn't compile, including `insert(const key&)` and hint functions.
4.2. Some function signatures were non-conformant.
4.3. The bound searching algorithm in `_Emplace_hint` was wrong. `flat_set` must find `lower_bound` for correctness, and `flat_multiset` should find `upper_bound` for efficiency and …

Various bugfixes / enhancements for `<flat_set>`

---

stl/inc/__msvc_filebuf.hpp
stl/inc/fstream
stl/src/fiopen.cpp

Removes `open(const unsigned short*,...)` functions from the library.
These functions are defined in `_CRTBLD` blocks, and are not used elsewhere in the library.
The project can build successfully after their removal (or `=delete` them). The `xxx.dll` and `msvcprt(d).lib` files are unchanged.
Works towards #3941.

Remove some functions defined in `_CRTBLD` blocks

---

stl/inc/istream
stl/inc/ostream
stl/inc/yvals_core.h

I found that these functions were present in some early prehistoric working drafts but removed before C++98 (see [WG21-N0794](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/1995/N0794.pdf) for rationale). I think it's helpful to say `sentry` classes should be used instead.

`<istream>`, `<ostream>`: Deprecate pre-Standard `ipfx`, `isfx`, `opfx`, and `osfx` functions

---

stl/inc/__msvc_iter_core.hpp
stl/inc/ranges
stl/inc/type_traits
stl/inc/utility
tests/std/tests/P2321R2_views_zip_transform/test.cpp

I tested with LLVM 17.0.0-rc4 and found a couple of issues / regressions:
* Instead of fixing the friend declaration issues as we expected, they get worse in Clang 17. I relabeled the workaround in `<ranges>` with LLVM-61763 and added another similar workaround for `zip_transform_view`.
* Clang seems to be confused by the deduced return type of our implementation of `forward_like` (LLVM-64029)

Prepare for impending LLVM 17 release

---

stl/src/cthread.cpp
stl/src/dllmain.cpp
stl/src/primitives.hpp
stl/src/taskscheduler.cpp
stl/src/winapinls.cpp
stl/src/winapisupp.cpp
stl/src/xalloc.cpp
stl/src/xdateord.cpp
stl/src/xgetwctype.cpp
stl/src/xmtx.cpp
stl/src/xonce.cpp

Remove unnecessary #include "awint.hpp"

---

stl/inc/yvals_core.h

Fixes #4009 
It looks like this in the IDE:

use only `static_assert` for `_EMIT_STL_ERROR`

---

stl/inc/stacktrace
stl/inc/yvals_core.h

Works towards DevCom-10368801 / VSO-1822115 "compiling `std.ixx` causes compiler warnings, even with `/external:anglebrackets` and `/external:W0`". (Additional changes are needed in the MSVC-internal repo: MSVC-PR-497556)
We don't attempt to be `/Wall` clean in general, but users are experiencing this as a regression due to the addition of the automatic build of the Standard Library Modules. Only a few warnings are being emitted so we can just clean them up. While this is motivated by the Modules, the changes are not modules-related.
I'm dealing with two warnings in this PR. First, I reported VSO-1885306 "warning C5039 shouldn't be emitted when an `extern "C"` function is marked `noexcept(false)`". `<stacktrace>` is correctly using `noexcept(false)`, so we should suppress this warning in …

Silence a couple of `/Wall` warnings

---

CMakeLists.txt
README.md
azure-devops/provision-image.ps1
azure-pipelines.yml
benchmarks/CMakeLists.txt
stl/inc/mdspan
tools/CMakeLists.txt
tools/format/CMakeLists.txt
tools/validate/CMakeLists.txt

+ Updated build compiler to VS 2022 17.8 Preview 2.
+ Updated CMake to 3.27 (now required).
+ Updated Python to 3.11.5.
+ VSO-1852021, VSO-1852030, and DevCom-10398426 affected `<mdspan>`.

Toolset update: VS 2022 17.8 Preview 2

---

stl/inc/flat_set
tests/std/tests/P1222R4_flat_set/test.cpp

This pr is separated from #4019 and contains all (and only) the bugfixes in it. Contents in this pr:
1. (Not strictly a bug) Fix `signed/unsigned` mismatch in `count` and `_Erase`.
2. Fix missed comp in `_Emplace_hint` (my mistake :(
3. Fix `erase(auto&&)`'s constraint. (Thanks to @cpplearner for sharing the link about [heterogeneous erasure](https://wg21.link/P2077R3#whyfwd)!

More bugfixes for `flat_set`

---

stl/inc/flat_set

Reopened for the remaining enhancements.
<hr>
Contents in this pr:
1. Enable `rbegin/...` for non-reversible containers.
2. Add debug check for comparisions (`_DEBUG_LT_PRED`), and avoid copying the comparator when passing to algorithm functions (`_Pass_fn`)
3. Replace some `_Keys_equal` with single comparision, and optimize `flat_set.count/erase(const key&)`.
4. Some other cleanups.
<hr>
Some remaining problems in `flat_set`:
1. https://github.com/microsoft/STL/commit/1ce8fc666d67abe4e727d0c099c91afe1042f2fb This commit tries to copy construct `comp` in move construction as suggested in [this comment](https://github.com/microsoft/STL/pull/3993#issuecomment-1712213203). I find it hard to decide whether to make a push. The standard says `priority_queue(&&,const alloc&)` should …

More enhancements for `<flat_set>`

---

stl/inc/latch
stl/inc/mutex
stl/inc/semaphore

Simplifies ~~, and fixes some minor problems in~~ `condition_variable`'s waiting functions. The correctness can be confirmed by looking through commits in order.
Works towards #718; after this change it will be much easier to fix `condition_variable`'s clock-awareness problem.
`condition_variable_any` are not effected by this pr.

Cleanups for `condition_variable`'s waiting functions

---

stl/inc/deque
tests/std/tests/GH_003570_allocate_at_least/test.cpp

`deque::_Mapsize()` should always be power of 2. Therefore, in `deque::_Growmap`, `_Allocate_at_least_helper` should not have chance to change `_Newsize` directly.

Fix `deque`'s usage of `_Allocate_at_least_helper`

---

azure-devops/format-validation.yml
azure-pipelines.yml

To avoid duplication if and when we add other pipelines in the future.
* [Test run demonstrating the new template works](https://dev.azure.com/vclibs/STL/_build/results?buildId=15045&view=results)
* [Test run demonstrating that validation failures are still handled properly](https://dev.azure.com/vclibs/STL/_build/results?buildId=15048&view=results)
* [Test run demonstrating that formatting failures are still handled properly](https://dev.azure.com/vclibs/STL/_build/results?buildId=15046&view=results)

extract code format validation into a new template

---

stl/inc/xlocnum

https://github.com/microsoft/STL/blob/8f67ece4a654625220642c92fa029a5cfc77afa8/stl/inc/xlocnum#L615-L622
This was introduced by MSVC-PR-113746 on 2018-03-29.
In DevCom-10465513, a user has reported that this prevents compilation with the Intel compiler in 80-bit `long double` mode. We don't support the Intel compiler and we especially don't support 80-bit `long double`, but we have an unofficial policy of avoiding gratuitous breakage when doing so is easy. In this case, merely omitting the `static_assert` and explaining the assumption with a comment has no impact for MSVC/Clang users, and allows Intel 80-bit users to compile.
I checked the STL for other occurrences and this appears to be the only such `static_assert` about `long double`'s size in the product code.

Tolerate 80-bit `long double` in `<xlocnum>`

---

stl/inc/xutility

(Pardon my French!)
Fixes #4027

Document `_Ref_fn`'s *raison d'etre*

---

stl/inc/mdspan
tests/std/test.lst
tests/std/tests/GH_004023_mdspan_fwd_prod_overflow/env.lst
tests/std/tests/GH_004023_mdspan_fwd_prod_overflow/test.compile.pass.cpp

`<mdspan>`: Fixes signed overflow in `_Fwd_prod_of_extents`

---

stl/inc/ranges
stl/inc/yvals_core.h

The MSVC-internal toolset (i.e. the checked-in compiler binaries that build the compiler) has finally been updated, so we can begin requiring VS 2022 17.8, and we can remove a workaround for a compiler bug that was fixed in 17.7 Preview 1.

Require VS 2022 17.8, remove workaround

---

stl/inc/future

- replaces long trailing `decltype` return types with `decltype(auto)` in several places
- removes some redundant `_Packaged_state` constructors
- simplifies signatures of `_Packaged_state::_Get_fn`, and remove an extra copy construction around it
- makes some `using`s private in `packaged_task`
- removes some uncommon `forward` patterns

`<future>` cleanups

---

stl/inc/xstring

- Merge `_Memcpy_val_from` to its only caller.
- Simplify `basic_string(initializer_list)`
- Enhance exception guarantee for `basic_string(&&, off)`. The rvalue will be unchanged if exception is thrown from `_Alloc_proxy()`.
- `noexcept` enhancements, mainly for comparisons with c-string.
- Some other nitpicks.

Cleanups and enhancements for `basic_string`

---

stl/inc/xstring
tests/std/tests/VSO_0000000_allocator_propagation/test.cpp

Fixes #3997; also adds test coverages for non-trivial pointers.
---update---
Fixes another lifetime problem in `_Take_contents`. Hopefully fixes all the lifetime issue of `_Ptr` in `basic_string`. Possibly related to #3949.
Thanks to @frederick-vs-ja for suggesting adding test coverage for non-trivial pointers! Also thanks for implementing `VSO_0000000_fancy_pointers`, that test helps me a lot
---update (solved with workaround)---
The updated test meets another problem in `static_assert(test_sequence<vector>)`'s `test_sequence_move_ctor`... (see https://github.com/microsoft/STL/pull/4031#discussion_r1328413358)

Fix the `_Choose_pocca_v` branch in `basic_string::operator=(const&)`

---

stl/inc/deque

Contents of this pr:
1. `trivial relocations XXX`: The definition order of `deque`'s methods was highly chaotic; reorder them to roughly match with the standard.
2. `A&B`: some minor cleanups for push/insert functions
3. `C`: Let `_Construct[_n]` do proxy allocation to save some lines.
4. ~`D`: The usage of `_Allocate_at_least_helper` in `_Growmap` was problematic, as it can make `_Mapsize()` not power of 2 if `_Allocate_at_least_helper` changes `_Newsize`; restore to the old version.~ moved to pr 4017

Cleanups for `<deque>` part 1

---

stl/inc/vector

* `_IsSingleBlockDest` wasn't accounting for the fact that `_DestEnd` is past-the-end
* we sometimes don't realize we're done and read past the end of the input
Test coverage is forthcoming in my ASAN work. (I've run 1e7 iterations of the randomized test locally, FWIW.)

ASAN found _two_ bugs in `_Copy_vbool`!

---

stl/inc/flat_set
tests/std/tests/P1222R4_flat_set/test.cpp

- `2`: `insert_range` should not unconditionally rely on `append_range`.
- `4.1&4.2`: cleanups for debug checks.
- `5&6`: more test coverages. fix support for uncomparable types.
- `7`: enhance usage of scope guard. (implement invariant safety against exceptions for `operator=` and `replace`; `erase` and `insert` methods need further investigations)
- other improvements / cleanups.

🛠️ for `flat_set`

---

stl/inc/flat_set
tests/std/tests/P1222R4_flat_set/test.cpp

Contents in this pr:
- Drop `_Compressed_pair` optimization, using separate container and comparer.
~ I think it will be ok to drop this optimization, as the spatial gain is not significant, and it greatly complicates constructors and brings indirection when accessing members. The spatial optimization will become easily achievable (and without the `final` constraint) when `[[no_unique_address]]` becomes available. I notice that `mdspan` has already adopted this approach.
- Various refactorings, including some renamings, and giving separate definitions for `_Emplace[_hint]:_Multi/!_Multi`, for better clarity.
- Record some remaining issues in the current codebase (`// TRANSITION` ones). Some of them are really tough :|
- Fix a bug introduced by previous pr (my fault :( The problem is that …

Cleanups for `<flat_set>`

---

stl/inc/functional
stl/inc/yvals_core.h
tests/libcxx/expected_results.txt
tests/std/test.lst
tests/std/tests/P1169R4_static_call_operator/env.lst
tests/std/tests/P1169R4_static_call_operator/test.compile.pass.cpp

Fixes #2954.
This updates the STL's CTAD for `std::function` and `packaged_task` to work with a C++23 Core Language feature that was implemented in Clang 16 (which we began requiring in VS 2022 17.7). It will automatically "light up" when MSVC and EDG claim support by defining the feature-test macro.
* This alters the structure, but not the behavior, of the existing code by adding another layer. First, `_Deduce_signature` performs SFINAE for `&_Fx::operator()`, which needs to be well-formed for both the old and new cases. Then, we send `_Fx` (because the new path will need it) and `decltype(&_Fx::operator())` (so both paths don't need to recompute it) up to the layer `_Deduce_from_call_operator`.
* Without the new compiler feature, or with the new compiler feature but a classically …

P1169R4 `static` `operator()`

---

stl/inc/source_location
tests/std/include/test_header_units_and_modules.hpp
tests/std/tests/P1208R6_source_location/header.h
tests/std/tests/P1208R6_source_location/test.cpp

Fixes #3729.
After #3206 in VS 2022 17.6 made `source_location::function_name()` more detailed, some users experienced significant increases in binary size (see microsoft/cppwinrt#1337), because heavy usage generated lots of long strings which couldn't be folded away. microsoft/cppwinrt#1260 added an escape hatch for that project, but we should add one too, which fixes VSO-1893424 / AB#1893424 .
This uses [Clang's `__has_builtin`](https://clang.llvm.org/docs/LanguageExtensions.html#has-builtin) to detect the upcoming support. When supported, enabling the detailed function name by default is still the right design - it's *much* more useful.
```
C:\Temp>type meow.cpp
```
```cpp
#include <print>
#include <source_location>
void purr(source_location loc = …
```

`<source_location>`: Light up detailed `function_name()` for Clang 17, add escape hatch

---

stl/inc/execution
stl/inc/yvals_core.h

[warning C4868: compiler may not enforce left-to-right evaluation order in braced initializer list](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-c4868?view=msvc-170)
Office is seeing instances of C4868 being emitted inside of the STL. Example:
`xutility(5637) : warning C4868: compiler may not enforce left-to-right evaluation order in braced initializer list`
After discussing the issue with Stephan he suggested adding the supression to the STL itself:
```
You can non-intrusively add this to _STL_EXTRA_DISABLED_WARNINGS.
We would also consider a PR to add it to _STL_DISABLED_WARNINGS for
everyone (as we do globally suppress a number of /Wall warnings there).
We basically never have such ordering assumptions in the STL, so this
warning provides no …
```

Add C4868 to _STL_DISABLED_WARNINGS

---

stl/inc/deque
tests/std/tests/GH_002769_handle_deque_block_pointers/test.cpp

Currently we sometimes directly add a `size_type` value to a fancy pointer, which is not always supported. Also, the difference type of `pointer` and `_Mapptr` may be different (which is contrived though). I think we should `static_cast` to the correct difference type in iterator arithmetic.
The return value of `_Getblock` is always used in the subscipt, so I guess it's OK to change the return type to the difference type.
Driven-by: avoid seemingly redundant indirection in `operator[]` and `at`. (Perhaps we should also do this for `front` and `back`).

`<deque>`: Fix iterator arithmetic

---

stl/inc/functional
tests/std/tests/Dev11_0535636_functional_overhaul/test.cpp

Make the return type (`_Not_fn`) perfect forwarding call wrapper since C++20, which is a change in WG21-P0356R5. 
Currently this PR leaves `_Not_fn` as-is in C++17 mode, because the return type was nearly fully specified in C++17 ([N4659 [func.not_fn]/1](https://timsong-cpp.github.io/cppwp/n4659/func.not_fn#1)), which means that
1. due to the absence of deleted `operator()` overloads, an invocation to a non-const value of the return type might select a const overload, and
2. due to the use of `decltype(!declval<invoke_result_t<...>>())`, if the `operator!` takes a non-movable return type of `std::invoke(args...)` by value, the return type of `operator()` would be ill-formed, while `!std::invoke(args...)` being well-formed.
In C++20 the first case should be ill-formed (in an …

`<functional>`: Fixes around `not_fn`

---

stl/inc/random
tests/std/test.lst
tests/std/tests/LWG3561_discard_block_engine_counter/env.lst
tests/std/tests/LWG3561_discard_block_engine_counter/test.cpp
tests/tr1/tests/random4/test.cpp

By changing the base type of `discard_block_engine` when `_Px` is too large for `discard_block` to work. The changes will break ABI for some `discard_block_engine` specializations that didn't previously work.
I haven't come up with a portable way for testing, because what I had tried took a long while to run.
Also correct the types of static data members `block_size` and `used_block`.
Fixes #2250.

Implement LWG-3561 Issue with internal counter in `discard_block_engine`

---

azure-devops/asan-pipeline.yml
azure-devops/cmake-configure-build.yml
azure-devops/config.yml
azure-devops/cross-build.yml
azure-devops/native-build-test.yml
azure-devops/run-tests.yml
azure-pipelines.yml

* Extract common pipeline config into a new `azure-devops/config.yml` variable template so we don't need to repeat pool info and target directories in both pipelines.
* Improve the `displayName`s of all the pipeline stages.
* Use `trigger: none` so ASan pipeline runs don't trigger for pushes to _any_ branch. We _do_ want to schedule a daily build, so add `schedules`.
* `benchmarkBuildOutputLocationVar` was actually used to control building the benchmarks; replace with a boolean `buildBenchmarks`.
* We need to explicitly remove `asan-pipeline`'s second stage's dependency on the first with `dependsOn: []`.
* We never set `buildOutputLocationVar` to a non-default value; get rid of it.
* Make `litFlags` a defaulted parameter of `cmake-configure-build.yml` so we don't need to duplicate it.
+ …

build and test infra cleanup

---

stl/inc/deque
tests/std/tests/VSO_0000000_allocator_propagation/test.cpp

Fixes #2868.
Some changes are made for consistency, while they may be unnecessary as algorithms can unwrap checked iterators.
Driven-by changes:
- introduce the `_At` member functions to make `operator[]`, `at`, `front`, `back`, and `_Insert_n` clearer;
- fix `shrink_to_fit` - previously it didn't support non-default-constructible allocators and might use a wrong memory resource denoted by the default-constructed allocator.

`<deque>`: Use unchecked iterators

---

tests/libcxx/expected_results.txt

Originally, these `ctad.static.compile.pass.cpp` tests were marked as failing for all compilers. After #4053, they were marked as failing for MSVC only (configuration 0). After #4069 finished setting up the ASan-Daily-CI pipeline, these tests additionally need to be marked as failing for MSVC with ASAN (configuration 1).

Fix ASAN CI failure caused by stealth merge conflict

---

README.md
azure-devops/config.yml
azure-devops/provision-image.ps1
stl/inc/charconv
stl/inc/xutility
tests/CMakeLists.txt
tests/std/tests/VSO_0000000_instantiate_containers/test.compile.pass.cpp
tests/std/tests/VSO_0105317_expression_sfinae/test.cpp
tests/tr1/tests/memory1/test.cpp

+ Updated build compiler to VS 2022 17.8 Preview 3.
+ Updated Python to 3.12.0 (now required).
* Remove compiler bug workarounds:
+ Remove workaround for VSO-1826196 "False positive C26454 in charconv" as the internal toolset has been updated. Validated internally, we can resolve this bug when merging.
+ Drop TRANSITION comment about VSO-251998 "File issue for `cbegin` interaction with other std containers with only non-member `begin()` functions". This wasn't a compiler or STL bug; it was a reminder to maybe file an LWG issue someday, which never happened and isn't worth pursuing now.
+ VSO-1281038 "False C6287 for C++20 synthesized operators" was rightfully resolved as By Design. Permanently avoid it by separately asserting each expression, which is our preferred …

Toolset update: VS 2022 17.8 Preview 3

---

tests/utils/stl/test/format.py

Fixes #4082.
Currently, the test harness leaves behind the OBJ, EXE, etc. files that it builds. These are safely contained within the `out` subdirectory, and they're easily dealt with via `git clean`. However, this means that large test runs leave behind a *lot* of emitted files. After ASAN configurations were added to the matrix, I observed that a full test pass left behind ~200 GB of files on my local machine, causing my 1 TB SSD to run out of space. :scream_cat:
These emitted files are never useful to us. If we have to investigate a particular test, we always want to rebuild it by hand, and extracting the relevant command line from the logs is easy (for all except the header units test, and the emitted artifacts aren't any more helpful there). This is because the vast majority of our …

Clean up emitted files as the test harness runs

---

stl/inc/xstring
tests/std/tests/VSO_0000000_allocator_propagation/test.cpp

Resolves the comments [(1)](https://github.com/microsoft/STL/pull/4031#discussion_r1331063123) [(2)](https://github.com/microsoft/STL/pull/4031#issuecomment-1727571761) in pr 4031. Hope that is the last lifetime bug of `basic_string` using fancy pointers (`3.1.`).
<hr>
Sometimes the pointer's destruction and buffer's activation are dangerously separated into different functions, in an obscure way (mainly relevant to the usage of `_Tidy_init`).
This pr introduces a helper function `_String_val::_Bxty::_Switch_to_buf` to make the transition state (where both `_Ptr` and `_Buf` are inactive) invisible to `basic_string`'s ctors and methods.
<hr>
Remaining issue after this pr:
https://github.com/microsoft/STL/blob/48eedd369d6c88130fff4d15afb88f016fa6e648/stl/inc/xstring#L2282-L2284
As …

Lifetime cleanups for `basic_string`

---

stl/inc/xstring
tests/std/tests/P1206R7_string_from_range/test.cpp

Fixes #2901.
Criteria:
- the source element type is integral
- the target element type is an `EcharT` (encoded character type, i.e. `char`, `wchar_t`, `char8_t`, `char16_t`, `char32_t`)
- the source and target element types are the same size
- the target traits type is library-provided (thanks @CaseyCarter)
- the source iterator is a contiguous iterator which doesn't dereference to a volatile lvalue.
Perhaps we can extend the criteria to `move_iterator` and unscoped enumeration types later.
Clang's `__builtin_memcpy` doesn't work when copying a `char` array to a `char8_t` array in constant evaluation (nor does GCC's), so this PR isn't using it in the involved construction.
The test `P1206R7_string_from_range` is largely extended to cover some related contiguous ranges and character types. …

`<xstring>`: Use `memmove` in construction of `basic_string` when the source is a suitable contiguous range

---

stl/inc/format

This allows EDG to parse `<format>` when `__cpp_lib_concepts` is defined. (`__cpp_lib_concepts` must be defined in order for `<format>` to work.)
Currently, `__cpp_lib_concepts` is not defined when the compiler is EDG, but I expect this to change soon.
https://github.com/microsoft/STL/blob/f362f7d7bea87bd199c927a89718e929ed89b187/stl/inc/yvals_core.h#L1704-L1710

`<format>`: Guard one use of `_MSVC_EXECUTION_CHARACTER_SET`

---

README.md

This adds a status badge for the daily ASAN CI that @CaseyCarter finished implementing with #4069. It also updates our existing badge.
* The existing badge image was still mentioning `microsoft.STL`, so I suspect that the image was stale, i.e. it would appear green even if the newly renamed STL-CI was failing.
* I've generated/regenerated the badges and then further edited their Markdown. The way is to look at the pipeline, e.g. https://dev.azure.com/vclibs/STL/_build?definitionId=4&_a=summary , click on the vertical ellipsis at the upper right, click "Status badge", set the Branch to `main`, and then look at the Sample Markdown.
* It helps to be familiar with GitHub Flavored Markdown's image syntax: https://github.github.com/gfm/#images
* As suggested by @CaseyCarter, I'm using "CI …

README.md: Update Azure Pipelines status badges

---

README.md

Update Draft to N4964

---

stl/inc/algorithm
stl/inc/memory
stl/inc/numeric
stl/inc/ranges
stl/inc/xutility

The core language doesn't seem to be any closer to providing first-class overload sets, and we're starting to get "bug" reports (DevCom-10450794) since the other standard library implementations simply implement these as (semiregular?) function objects.
This change removes the type `std::_Not_quite_object`, promoting its member `_Construct_tag` to namespace scope since it is also used in the implementation of `join_view` and `join_with_view`.
Fixes #4097

Turn niebloids into function objects

---

tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp

* Drop extra spaces in `#error` messages.
* Mechanically simplify.
+ This test originally covered both the compiler and library feature-test macros, and was therefore extremely paranoid about checking the behavior of the preprocessor. We gave the compiler test coverage to the compiler team a long time ago, so we can simplify the library test coverage now. This commit is a 100% regex search-and-replace, from:
```cpp
#ifndef (__cpp_lib_\w+)
#error \1 is not defined
#elif \1 != (\d{6}L)
#error \1 is not \2
#else
STATIC_ASSERT\(\1 == \2\);
#endif
```
to:
```cpp
#ifdef $1
STATIC_ASSERT($1 == $2);
#else
#error $1 is not defined
#endif
```
except with `\n` between each line of the "from" and "to" (presented here on separate lines for clarity).
* Simplify `__cpp_lib_chrono` and …

Fix and simplify the feature-test macro test

---

README.md
stl/inc/algorithm
stl/inc/memory
stl/inc/numeric
stl/inc/ranges
stl/inc/thread
stl/inc/xthreads.h
stl/inc/xutility
stl/src/cthread.cpp
stl/src/sharedmutex.cpp
stl/src/vector_algorithms.cpp
tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp

This merges `main` to pick up #4103, then contains an additional commit to update the `__cpp_lib_flat_set` test accordingly. Note that it was damaged like `__cpp_lib_containers_ranges` previously was.

Merge `main` to `feature/flat_set`, fix `__cpp_lib_flat_set` test

---

stl/inc/xcall_once.h
stl/src/dllmain.cpp
stl/src/excptptr.cpp
stl/src/ppltasks.cpp
stl/src/xonce.cpp

* Revert #1318, #1356, and #1398 (`xonce.cpp` only) while preserving #1194's change to directly call `InitOnceExecuteOnce()`.
+ XFG is being removed from the toolset (see internal VSO-1726733, MSVC-PR-462377). Some things like ASan still need to handle XFG hashes, but things like the STL no longer need unusual contortions. I checked with @amyw-msft and she said this should be okay to remove.
* Drop `_Execute_once()` usage in `ppltasks.cpp`, and as an associated change, simplify `dllmain.cpp`.
+ See below.
* Use `call_once()` instead of `_Execute_once()` in `excptptr.cpp`.
+ After #3861, they're both declared by `xcall_once.h`, so we don't need to use the internal `_Execute_once()` (with a worse interface) anymore.
+ We're `using namespace std;` so we don't need qualification.
+ Because …

Cleanup `_Execute_once()`

---

stl/inc/__msvc_print.hpp
stl/inc/ostream
stl/inc/xcharconv.h
stl/inc/xcharconv_ryu.h
stl/inc/xcharconv_ryu_tables.h
stl/inc/xnode_handle.h
tests/std/tests/GH_001411_core_headers/test.cpp

`<__msvc_print.hpp>` was missing the Standard mode check that the rest of our internal headers perform. This one's a little special because it's included by `<format>` in C++20 Concepts mode, and by `<print>` in C++23 Concepts mode.
Without this check, the header is still rejected in C++14/17 mode, but with a less clear error about the usage of `consteval`:
https://github.com/microsoft/STL/blob/1c59a205787f4fdcd9c20decc8fa6dfa9096d394/stl/inc/__msvc_print.hpp#L58
Also, this moves the other Standard mode checks in `<xmeow.h>` as early as possible. The mode is available after including `<yvals_core.h>`, and if we're doomed, we should diagnose doom immediately. `<xcharconv_tables.h>` was already doing this.
Next, `<ostream>` was guarding its inclusion of `<__msvc_print.hpp>` with `#if …

Add a Standard mode check to `<__msvc_print.hpp>`

---

stl/src/vector_algorithms.cpp

Resolves #3963 
Also remove some stray newlines @CaseyCarter complained about.
Also drop some superfluous `typename`s.
Will conflict with #3928 , which I'll have to fix after either is merged.

inline internal function that are called only once in `vector_algorithms.cpp`

---

stl/inc/memory
stl/inc/system_error
stl/inc/xstring
stl/inc/xutility
stl/src/ppltasks.cpp
stl/src/stdthrow.cpp
stl/src/xgetwctype.cpp
stl/src/xlock.cpp

* Comments: Drop extra space.
* Comments: Add them to `#endif`.
* Comments: Drop "TRANSITION, requires expression support".
+ We use `_Resettable_pointer` twice; *requires-expression*s would be more verbose.
* Comments: Fix capitalization typo.
* Comments: Strengthen comment about `ole32.dll`.
+ See #3607 - we can't depend on `ole32.dll` anywhere.
* String literals: Space before wrapping.
+ There were only a few places that weren't following our usual convention.
* String literals: Unwrap.
+ This one was easier to read on a single line.

Various cleanups: Comments and strings

---

tests/std/tests/GH_002030_asan_annotate_string/test.cpp

I noticed that `GH_002030_asan_annotate_string` had a bunch of workarounds for DevCom-1527920 "\[ASAN\] Exceptions invalidate annotation of stack based buffer", but it no longer appears to repro. Let's see if we can activate this test coverage now. I'm isolating this into a separate PR in case something goes wrong.
The ASAN configurations are passing:
```
D:\GitHub\STL\out\x64>git status
On branch dry-cleaning-2-remove-test-workarounds
Your branch is up to date with 'stephan/dry-cleaning-2-remove-test-workarounds'.
nothing to commit, working tree clean
D:\GitHub\STL\out\x64>python tests\utils\stl-lit\stl-lit.py -o testing_x64.log  %STL%\tests\std\tests\GH_002030_asan_annotate_string
-- Testing: 46 tests, 32 workers --
PASS: std :: tests/GH_002030_asan_annotate_string:00 (1 of 46)
[...] …
```

Remove test workarounds for an ASAN bug

---

stl/inc/random
tests/tr1/tests/random1/test.cpp

* Conformance: `base_type` in `<random>` is a non-Standard typedef.
+ Remove it outright for Standard `discard_block_engine` (via the new base class `_Discard_block_base` introduced by #4066), `independent_bits_engine`, and `shuffle_order_engine`.
+ For `discard_block`, which is usually the base class for Standard `discard_block_engine`, we can guard the typedef with TR1's availability, and deprecate it. We should then avoid using it ourselves.
* Conformance: Add `_Engine&&` constructors to `discard_block` and `_Discard_block_base`.
+ `discard_block_engine` had an `_Engine&&` constructor but its base classes didn't, so it was always copying.

`<random>`: Fix minor conformance issues

---

stl/inc/exception
stl/inc/ios
stl/inc/random
stl/inc/xstring
stl/inc/xutility

* `<exception>`: `throw_with_nested()` no longer needs `_Glued` to defend against the preprocessor.
+ After #3973, `_With_nested_v2<_Uty>` doesn't contain commas.
* Simplify: `ios_base::_Iostate{}` => `ios_base::goodbit`
+ It's just zero.
* Simplify `_Copy_unchecked()`'s `#ifdef __cpp_lib_concepts` logic.
+ Here's a case where a negative test allows us to considerably simplify the code by avoiding the need for two `#ifdef __cpp_lib_concepts` regions (which was hard to follow). Now the code reads much more naturally - in concepts mode, we need to handle different iterator/sentinel types.
* `<random>`: `discard_block_engine` can use its `result_type` typedef for `min` and `max`.
+ A constructor above is already using this typedef.
* Style: Avoid using an assignment expression as an index in …

Various cleanups: Simplify product code

---

tests/std/include/range_algorithm_support.hpp
tests/std/include/test_mdspan_support.hpp
tests/std/tests/Dev09_174589_tr1_function_storing_pmf_called_with_reference_or_pointer/test.cpp
tests/std/tests/Dev10_646244_bad_alloc_message/test.cpp
tests/std/tests/Dev10_722102_shared_ptr_nullptr/test.cpp
tests/std/tests/Dev10_860421_deque_push_back_pop_front/test.cpp
tests/std/tests/Dev11_0485243_condition_variable_crash/test.cpp
tests/std/tests/Dev11_0836436_get_time/test.cpp
tests/std/tests/Dev11_0920385_list_sort_allocator/test.cpp
tests/std/tests/P0024R2_parallel_algorithms_find_first_of/test.cpp
tests/std/tests/P0024R2_parallel_algorithms_is_heap/test.cpp
tests/std/tests/P0083R3_splicing_maps_and_sets/test.cpp
tests/std/tests/P0088R3_variant/test.cpp
tests/std/tests/P0218R1_filesystem/test.cpp
tests/std/tests/P0220R1_polymorphic_memory_resources/test.cpp
tests/std/tests/P0288R9_move_only_function/test.cpp
tests/std/tests/P0323R12_expected/test.cpp
tests/std/tests/P0355R7_calendars_and_time_zones_zoned_time/test.cpp
tests/std/tests/P0811R3_midpoint_lerp/test.cpp
tests/std/tests/P0896R4_ranges_alg_find_end/test.cpp
tests/std/tests/P0896R4_ranges_alg_minmax/test.cpp
tests/std/tests/P0896R4_ranges_algorithm_machinery/test.compile.pass.cpp
tests/std/tests/P0898R3_concepts/test.cpp
tests/std/tests/P2136R3_invoke_r/test.cpp
tests/std/tests/P2441R2_views_join_with/test.cpp
tests/std/tests/VSO_0000000_type_traits/test.cpp
tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
tests/std/tests/VSO_0095837_current_exception_dtor/test.cpp
tests/utils/stl/test/format.py

Usual disclaimer about how we dislike grab-bag PRs as a general rule, *and* how we avoid large-scale cleanups of test code (low value, potentially disrupts the weird subtle things that the tests were trying to cover). The existence of this PR means that I think these cases are worth it for codebase consistency and that they're low-risk.
* `format.py`: `import copy` was unused.
+ Thanks to Pylance for finding this.
* Style: `constexpr friend` => `friend constexpr`
+ This was the only place that wasn't following our convention.
* Style: Nameless value parameter `const choose` => `choose`
* Drop unnecessary `static` for namespace-scope `permissive()`.
+ This one was easy to miss, because it's followed by a `static` member function.
* Test cleanup: Catch by const ref, even when unnamed.
+ …

Various cleanups: Test code

---

stl/src/tzdb.cpp
stl/src/winapisupp.cpp

`winapisupp.cpp`: Use separate function pointers with proper types, instead of enumerators into an array of `PVOID`.
This is within an unnamed namespace (after #2841 dramatically simplified the code), so we can freely modify this machinery.
Originally, the function pointer table's ordering seemed really important to us, and we were scared about adding/removing/reordering entries. #2841 showed that those fears were unfounded, but it was changing a ton of code so I didn't eliminate the table entirely at that time.
The table wasn't buying us anything - we were able to properly size it via `eMaxKernel32Function`, but we still had to mention every function to manually form the `eMeow` enumerators. By introducing `DEFINEFUNCTIONPOINTER`, we can spend the same number of lines to form separate …

Various cleanups: Store properly-typed function pointers in `winapisupp.cpp`

---

stl/src/stdhndlr.cpp
stl/src/xtime.cpp

(I recommend "ignore whitespace" while reviewing this.)
Over time, we've developed a convention of using unnamed namespaces in `stl/src` for internal machinery. This clearly separates TU-local code from functions that are accessed from other `stl/src` TUs, injected into the import lib, or dllexported. I noticed a couple of older TUs that could benefit from being cleaned up.
* `xtime.cpp`: The `_Epoch` and `_Nsec100_per_sec` constants can be function-local.
* `xtime.cpp`: Use an unnamed namespace, following our modern convention.
+ The `constexpr` variables and `static` functions had internal linkage, so this is unobservable to other TUs. We can drop `static` now.
* `stdhndlr.cpp`: Use an unnamed namespace, following our modern convention.
+ UCRT `<new.h>` declares `_set_new_handler`, …

Various cleanups: Use unnamed namespaces

---

stl/inc/xiosbase
stl/inc/xlocale

Using `static constexpr` is what allows the major improvement of dropping out-of-line definitions - see #3381 which made that change to `ios_base`'s base class `_Iosb`.
* The DLL's exports don't mention any of `_Dummy_enum`, `_Dummy_enum_val`, `_Stdio`, `_Openmode`, `_Openmask`, `_Seekdir`, `_Seekbeg`, `_Seekcur`, `_Seekend`, `_Openprot`. 
* Move retained enums to the bottom of `_Iosb` with an improved comment.
+ There's an internal MaxMPDCompat tool that notices the enum types and enumerators. With significant effort I think I could update the checked-in CompatibilityData baseline, but for now this is the easiest cleanup.
* We can drop `_Stdio` entirely (it's not an enumerator).
* We can simplify the definitions of the `meowfield` constants (I verified that this doesn't change them).
* …

Various cleanups: Simplify `ios_base` and `locale` constants

---

stl/inc/__msvc_tzdb.hpp
stl/inc/chrono
stl/inc/yvals.h
tests/std/tests/P0355R7_calendars_and_time_zones_clocks/test.cpp
tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp
tests/std/tests/P0355R7_calendars_and_time_zones_io/test.cpp
tests/std/tests/P0355R7_calendars_and_time_zones_time_zones/test.cpp

Fixes #1805 after 2.5 years. It's about time!
This is inherently a grab-bag PR (sorry) of various cleanups we identified during the rush to complete C++20. I've structured it into a series of fine-grained commits addressing each comment. Most are for the product code, with only a few changes to the test code. (We generally refrain from large-scale cleanups of test code, as it's low-value work and has the potential to disrupt what the tests were trying to do, but these changes are quite simple.) There are also a few cleanups I noticed myself along the way; I've included them here since they're pretty small.
* Make `_THROW` a variadic macro so we never need extra parens.
+ Something I noticed myself.
* Replace `decltype(tzdb::zones)` and `decltype(tzdb::links)` with their actual types.
+ …

Various cleanups: `<chrono>`

---

stl/inc/__msvc_sanitizer_annotate_container.hpp

#4106 marked `__sanitizer_annotate_contiguous_container` as `noexcept` because it's `extern "C"`. However, it has to match ASan's primary declaration, so we can't mark it.
This PR reverts this declaration to its original form, and adds a comment for future maintainers.

ASan: Remove `noexcept` from `__sanitizer_annotate_contiguous_container`

---

stl/inc/type_traits
stl/inc/yvals_core.h
tests/std/tests/Dev11_0535636_functional_overhaul/test.cpp

Resolves #4080 by replacing the _CONSTEXPR17 with constexpr for std::invoke.

Make invoke constexpr available in all modes

---

stl/inc/xhash

Select "Hide whitespace" to see how simple this change is.
We usually use our namespace macros when defining `stdext` machinery:
https://github.com/microsoft/STL/blob/f392449fb72d1a387ac5025d508e8442914477f9/stl/inc/iterator#L1468-L1470
This PR fixes the one inconsistency in our headers. (Right now, there's no difference between the macros and directly mentioning the namespace, but in the future the macros might be trickier.)

Various cleanups: Use `_STDEXT_BEGIN` and `_STDEXT_END`

---

stl/inc/atomic
stl/inc/memory
stl/inc/semaphore
stl/inc/xatomic_wait.h
stl/src/atomic_wait.cpp
stl/src/parallel_algorithms.cpp

One more round of cleanups resulting from my audit of things in the global namespace that aren't `extern "C"`.
* Move `_Atomic_wait_no_deadline` from `<xatomic_wait.h>` to `atomic_wait.cpp`.
+ Nothing else mentions this, obviously.
+ It's moving into the unnamed namespace for isolation, and dropping `_INLINE_VAR`.
* Rename `_Atomic_wait_no_timeout` => `__std_atomic_wait_no_timeout`
+ This is moving into `extern "C"` like `<xfilesystem_abi.h>`'s constants: https://github.com/microsoft/STL/blob/f392449fb72d1a387ac5025d508e8442914477f9/stl/inc/xfilesystem_abi.h#L21-L23
+ `<xatomic_wait.h>` can assume C++20 mode, so we can use `inline` variables unconditionally.
+ There will be a trivial merge conflict with #4143.

Various cleanups: `<xatomic_wait.h>` constants

---

stl/inc/flat_set
tests/std/tests/P1222R4_flat_set/test.cpp

Citation:
>For associative containers where the value type is the same as the key type, both iterator and const_iterator are constant iterators[.](https://eel.is/c++draft/container.requirements#associative.reqmts.general-6.sentence-2) It is unspecified whether or not iterator and const_iterator are the same type[.](https://eel.is/c++draft/container.requirements#associative.reqmts.general-6.sentence-3)
This pr makes `flat_(multi)set`'s `iterator` an alias for `const_iterator`.

`<flat_set>`: `flat_(multi)set`'s `iterator` type should be constant iterator

---

stl/inc/algorithm
stl/inc/atomic
stl/inc/execution
stl/inc/xutility
tests/std/test.lst
tests/std/tests/GH_001596_adl_proof_algorithms/env.lst
tests/std/tests/GH_001596_adl_proof_algorithms/test.compile.pass.cpp
tests/std/tests/P2538R1_adl_proof_std_projected/test.compile.pass.cpp

Towards #140 and #1596, separated from #4004.
The `std::search` overload taking a searcher is not yet handled. I'll created another PR for standard searchers.
- The modification of `_Adl_verify_range` is adopted from https://github.com/microsoft/STL/issues/1596#issuecomment-769841584 (thanks to @miscco).
- A single commit adding `_STD`, `_RANGES`, and `::`-qualifications.
- I decided to add `::` for `__std_meow` functions because `_CSTD __std_meow` looks very weird to me.
- A single commit removing ADL-dependent structured binding declarations (where the unnamed variables are `pair`s).
- I'm not sure whether we should avoid structured bindings or change the return type of `_Equal_rev_pred` to avoid ADL.
- A single commit speculatively implementing LWG-3969.
- A single commit for …

ADL-proof implementation of algorithms in [alg.nonmodifying]

---

stl/inc/ranges

Fixes GH-4141.
The standard says ([\[range.utility.conv.to\]](http://eel.is/c++draft/range.utility.conv.to)):
> - (2.1) If `C` does not satisfy `input_range` or `convertible_to<range_reference_t<R>, range_value_t<C>>` is `true`:
>     - [...]
> - (2.2) Otherwise, if `input_range<range_reference_t<R>>` is `true`:
>      ```
>      to<C>(r | views::transform([](auto&& elem) {
>          return to<range_value_t<C>>(std::forward<decltype(elem)>(elem));
>      }), std::forward<Args>(args)...);
>      ```
So `views::transform` shouldn't be used if `convertible_to<range_reference_t<R>, range_value_t<C>>` is `true`.
Notably, when step (2.2) recursively calls `ranges::to<C>`, it passes a `transform_view` whose `range_reference_t` is the same as `range_value_t<C>`. So in this case …

`<ranges>`: Avoid infinite recursion in `ranges::to` when the inner ranges match but the destination container is still not constructible

---

stl/inc/xutility

When no match is found, we `return {false, _It1 {}};` which implies that `_It1` must be a `forward_iterator `that can be default-constructed.

`<xutility>`: Fix inaccurate constraint of `_Equal_rev_pred`

---

stl/inc/xutility

I noticed this a while ago, but it's increasingly important due to modules. (This PR avoids the likely compiler bug VSO-1914077 "Modules: `extern "C++"` interferes with ADL".)
The `vector<bool>` algorithm optimizations (#879 #1131 #3353) detect `vector<bool>` iterators via an internal type trait, then dispatch to dedicated functions. We were defining those functions in `<vector>`, but were never declaring them before calling them in `<xutility>` (which is "higher up" in the dependency graph), so our calls were actually using ADL. That was squirrelly :chipmunk: since we never rely on ADL like this for internal functions.
This PR adds declarations (dropping `const` on value parameters as usual), then qualifies the calls for good measure (also aligning with our developing practice of …

Various cleanups: Declare `_Meow_vbool` to avoid ADL

---

.clang-format
stl/inc/cmath
stl/inc/cstddef
stl/inc/cstdlib
stl/inc/ctime
stl/inc/cwchar
stl/inc/xfilesystem_abi.h
stl/inc/xutility
stl/inc/yvals_core.h
tests/std/tests/P2465R3_standard_library_modules/custom_format.py
tests/std/tests/P2465R3_standard_library_modules/custombuild.pl
tests/std/tests/P2465R3_standard_library_modules/test.cpp
tests/std/tests/P2465R3_standard_library_modules/test3.cpp
tests/std/tests/P2465R3_standard_library_modules/test4.cpp

As my `<yvals_core.h>` comment here explains, `extern "C++"` allows named modules to work with classically separately compiled code, which we've been doing ever since #3108 implemented the Standard Library Modules. It can also allow named modules to work with classic includes in the same TU, in one specific order.
Originally, I thought that wrapping the STL in `extern "C++"` would involve changing every header. I discovered that while I needed to *audit* every header, the necessary changes were far less extensive. I did have to perform several restructurings in other PRs (see below), but after that, we've reached a point where only a few additional changes are necessary. This is because the vast majority of the STL's code is wrapped in the `_STD_BEGIN`/`_STD_END` macro pair, which can be …

Add `extern "C++"` as a temporary workaround for `#include`/`import` coexistence

---

stl/inc/flat_set
tests/std/tests/P1222R4_flat_set/test.cpp

None of allocator-extended constructors of `flat_meow` requires the adapted container to be allocator-aware. The container may be constructed in some other style than standard containers.
(Actually, `flat_meow` don't care whether an adapted container is allocator-aware anywhere.)
IIUC we should unconditionally use `std::make_obj_using_allocator` ([[allocator.uses.construction]/1](https://eel.is/c++draft/allocator.uses.construction#1)).
See also https://github.com/microsoft/STL/pull/4084#discussion_r1364824733.
---
For non-allocator-extended allocators, the adapted container is only constructed in 4 ways ([[flat.set.defn]](https://eel.is/c++draft/flat.set.defn), [[flat.multiset.defn]](https://eel.is/c++draft/flat.multiset.defn) [[flat.set.cons]](https://eel.is/c++draft/flat.set.cons), …

`<flat_set>`: Correct allocator-extended constructors for `flat_(multi)set`

---

stl/inc/flat_set

This PR restores the original inserting logic by using ~`insert` and `insert_range`~ `assign` and `assign_range` in certain allocator-extended constructors (per [[sequence.reqmts]](https://eel.is/c++draft/sequence.reqmts), they are required for all (adaptable) sequence containers).
Addresses @achabense's review comments in https://github.com/microsoft/STL/pull/4148#discussion_r1388010662.

`<flat_set>`: Restore insertion in `flat_(multi)set`'s iterator-pair/range constructors

---

README.md
azure-devops/config.yml
azure-devops/provision-image.ps1
stl/inc/stacktrace
stl/inc/yvals_core.h
tests/libcxx/expected_results.txt
tests/std/include/test_atomic_wait.hpp
tests/std/tests/P0226R1_math_special_functions/test.cpp
tests/std/tests/VSO_0000000_type_traits/test.cpp

+ VSO-1881472 "`/clr` C++20 x86 System.AccessViolationException with `atomic<with_padding_bits<8>>`".
+ VSO-1885306 "warning C5039 shouldn't be emitted when an `extern "C"` function is marked `noexcept(false)`".
- I manually verified this fix.
+ DevCom-10138792 VSO-1611566 "Bogus warning C4455: '`operator ""s`': literal suffix identifiers that do not start with an underscore are reserved".
- This bug remains active, but I notified the compiler dev it's assigned to that it appears to be fixed.
+ Remove libcxx skips for `std/containers/sequences/vector.bool/move.pass.cpp`.
- We never analyzed this failure, but a compiler bug was fixed, yay!
+ Remove an `_MSVC_INTERNAL_TESTING` workaround in `P0226R1_math_special_functions`.
- This test coverage was …

Toolset update: VS 2022 17.9 Preview 1

---

stl/inc/iterator
tests/std/tests/P0896R4_common_iterator/test.cpp

Implement LWG-3749 `common_iterator` should handle integer-class difference types

---

stl/inc/algorithm
stl/inc/format
stl/inc/iterator
stl/inc/optional
stl/inc/ranges
stl/inc/spanstream
stl/inc/xutility
tests/std/include/range_algorithm_support.hpp
tests/std/tests/P0896R4_P1614R2_comparisons/test.cpp
tests/std/tests/P0896R4_counted_iterator/test.cpp
tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp
tests/std/tests/P0896R4_ranges_range_machinery/test.cpp
tests/std/tests/P0896R4_ranges_subrange/test.compile.pass.cpp
tests/std/tests/P0896R4_views_drop/test.cpp
tests/std/tests/P0896R4_views_join/test.cpp
tests/std/tests/P0896R4_views_lazy_split/test.cpp
tests/std/tests/P0896R4_views_take/test.cpp
tests/std/tests/P0898R3_concepts/test.cpp
tests/std/tests/P1206R7_string_insert_range/test.cpp
tests/std/tests/P1206R7_string_replace_with_range/test.cpp
tests/std/tests/P1659R3_ranges_alg_ends_with/test.cpp
tests/std/tests/P2286R8_text_formatting_formattable/test.compile.pass.cpp
tests/std/tests/P2404R3_move_only_types_for_comparison_concepts/test.compile.pass.cpp

clang-format has significantly improved its handling of concepts, so this PR removes over a hundred suppressions (from 295 down to 173).
In general, we should suppress clang-format only when it would do something egregious, or when there's a significant advantage to manual formatting (e.g. custom alignment of a table, or staying similar to upstream code). I looked at each of these suppression removals, and I believe that they're all neutral or an improvement. (I refrained from removing suppressions where clang-format would damage whitespace around `&&`. I also refrained from removals that would impact a lot of code, even if I thought the impact was positive; those are candidates for future cleanups.)
I've structured this into a series of commits for easier review, listed below. There are …

Various cleanups: Enable more clang-format

---

tests/std/tests/Dev11_0863628_atomic_compare_exchange/test.cpp

Implement LWG-3949: `atomic<bool>`'s trivial destructor dropped in C++17 spec wording

---

stl/inc/iterator

Update return type of `iter_move` to `decltype(auto)`

---

stl/inc/memory
tests/std/tests/P1132R7_out_ptr/test.cpp

Implement LWG-3897 `inout_ptr` will not update raw pointer to null

---

stl/inc/xutility
stl/inc/yvals_core.h
tests/std/tests/P2278R4_basic_const_iterator/test.cpp
tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp

P2836R1: `basic_const_iterator` Should Follow Its Underlying Type's Convertibility

---

stl/inc/ranges
tests/std/tests/P0896R4_views_iota/test.cpp

Implement LWG-4001 `iota_view` should provide `empty`

---

stl/inc/random
tests/std/tests/Dev11_0577418_random_seed_0/test.cpp

Fixes #4162.
Also updates citations in the modified test file.

Implement LWG-3809 Is `subtract_with_carry_engine<uint16_t>` supposed to work?

---

stl/inc/ranges
tests/std/tests/P2321R2_views_adjacent_transform/test.cpp

Fixes #4165.
(The `base` overload seemed to be underconstrained before the change.)

Implement LWG-3947 Unexpected constraints on `adjacent_transform_view::base()`

---

stl/inc/yvals_core.h
tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp

Implement P2937R0 Freestanding Library: Remove strtok

---

stl/inc/chrono
stl/inc/format

Fixes #2785.
This alters the layout of `_Format_checker`, but since `_Format_checker` is only used at compile-time, I believe that it doesn't need to be renamed.
Do we have tests in the test suites for compile errors?

`<format>`: Reject dynamic width or precision of non-integral type

---

stl/inc/format
stl/inc/yvals_core.h
tests/std/tests/P0645R10_text_formatting_formatting/test.cpp
tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp

Implement P2909R4 Fix Formatting Of Code Units As Integers

---

azure-devops/config.yml

Azure Pipelines recently started auto-injecting CodeQL, which sometimes takes so long that it causes test runs to sporadically fail. We don't need CodeQL here because it also runs in the MSVC-internal repo.
This disables the auto-injection, based on the internal documentation at https://aka.ms/codeql3000 .

Disable CodeQL

---

stl/inc/ranges
tests/std/tests/P2387R3_pipe_support_for_user_defined_range_adaptors/test.cpp

Fixes #4153.
Notes:
1. IIRC `_Pipeline::operator()` overloads also need to return `decltype(auto)` per [[range.adaptor.object]/1](https://eel.is/c++draft/range.adaptor.object#1).
2. Deleted overloads are needed, see #4057 and [_Perfect forwarding call wrappers need `=delete`_](https://quuxplusone.github.io/blog/2021/07/30/perfect-forwarding-call-wrapper/).
3. There seems to be a bug of MSVC on cv-qualification in constraints, which is reported as DevCom-10519736.
4. I _think_ we don't need to guard anything for C++23 (but not 100% sure currently) - in C++20 the return types should always be controlled by the implementation and should always be cv-unqualified class types.

`<ranges>`: Fix the return types and overload resolution of range adaptor closure objects

---

stl/inc/xlocnum
tests/std/tests/GH_003867_output_nan/test.cpp

Fixes #4210.
This PR is a workaround for DevCom-10519861 and may be `affects redist` because it modifies dll-exported functions.

`<xlocnum>`: Drop `ios_base::showpoint` flag when printing non-finite values

---

stl/inc/mdspan
tests/std/tests/P0009R18_mdspan_mdspan_death/test.cpp

Closes #4166.
I believe the original implementation is conforming after LWG-3974, because the difference between _`index-cast`_ and `static_cast` can't be observed without UB (precondition violation). This PR intends to improve precondition checking.

`<mdspan>`: Check preconditions of `mdspan::operator[]` clarified by LWG-3974

---

stl/inc/deque
stl/inc/experimental/deque
stl/inc/experimental/forward_list
stl/inc/experimental/list
stl/inc/experimental/map
stl/inc/experimental/set
stl/inc/experimental/string
stl/inc/experimental/unordered_map
stl/inc/experimental/unordered_set
stl/inc/experimental/vector
stl/inc/forward_list
stl/inc/list
stl/inc/map
stl/inc/set
stl/inc/unordered_map
stl/inc/unordered_set
stl/inc/vector
stl/inc/xmemory
stl/inc/xstring
tests/std/tests/GH_001596_adl_proof_algorithms/test.compile.pass.cpp
tests/std/tests/VSO_0000000_instantiate_containers/test.compile.pass.cpp

Towards #140 and #1596. Note that there'll be a merge conflict with #4216.
`_STD`-qualification for internal functions should become complete for following headers:
- `experimental/deque`
- `experimental/forward_list`
- `experimental/list`
- `experimental/map`
- `experimental/set`
- `experimental/string`
- `experimental/unordered_map`
- `experimental/unordered_set`
- `experimental/vector`
Unfortunately, I failed to find how to test ADL-proofness for `std::(experimental::)erase`. Not sure whether this is possible.
Edit: Overloads for `flat_meow` also need to fixed, but perhaps this should be done after the `main` branch is updated.

ADL-proof implementation of `erase_if` and related algorithms

---

stl/inc/ranges
tests/std/tests/P1206R7_ranges_to_misc/test.cpp

I'm working on an llvm-project update, and `std/ranges/range.utility/range.utility.conv/to.pass.cpp` found this bug.
I'm extending `P1206R7_ranges_to_misc` to cover this scenario. I also searched for other occurrences and didn't find any.

`<ranges>`: Fix a correctness-damaging typo in `ranges::to`

---

stl/inc/sstream

I'm working on an llvm-project update, and it has an allocator with a custom size type that found this bug. In this PR, I'm not bothering to add any test coverage since llvm-project will provide so much.
Clang error:
```
sstream(263,39): error: no matching function for call to '_Allocate_at_least_helper'
```
MSVC error:
```
sstream(263): error C2664: 'wchar_t *std::_Allocate_at_least_helper<test_allocator<wchar_t>>(_Alloc &,unsigned int &)': cannot convert argument 2 from 'size_t' to 'unsigned int &'
```
This code was using `size_t` since the beginning of history, we just missed the type mismatch in #3712 / #3864.
Elsewhere we're already using `_Mysize_type`.

`<sstream>`: Pass the correct size type to `_Allocate_at_least_helper`

---

tests/std/tests/P1208R6_source_location/test.cpp

MSVC-internal MSVC-PR-512527 and MSVC-PR-512932 updated the `P1208R6_source_location` test without being properly mirrored to GitHub.
We'll need to add `_MSVC_INTERNAL_TESTING` logic until the fixed compiler ships. I've verified that this passes in both repos.

Update `P1208R6_source_location` after MSVC-internal changes

---

stl/inc/__msvc_bit_utils.hpp
stl/inc/__msvc_int128.hpp
stl/inc/atomic
stl/inc/bit
stl/inc/xatomic.h
stl/inc/xcharconv_ryu.h

This mirrors @mcfi's MSVC-PR-511288 as of Iteration 10, fixing VSO-1918426 which tracks the following issues reported internally by Geoffrey Antos:
1. `std::atomic<T>::load()` is still generating the original/slow `ldr`+barrier instructions and not the `lda[p]r` instructions intended by MSVC-PR-449792 / #3399.
2. Neither overload of `std::atomic<T>::load()` appears to guarantee sequential consistency when requested for ARM64 CHPE builds.
3. `std::atomic_thread_fence()` does not appear to guarantee the requested ordering for CHPE builds (other than for `std::memory_order_seq_cst`).
4. (Performance) On CHPE builds, `std::atomic<T>::exchange()`, `std::atomic<T>::compare_exchange_*()` and `std::atomic<T>::fetch_*()` appear to force sequentially consistent behavior.

`<atomic>`: Fix ARM64EC and CHPE codegen

---

.github/workflows/assign-new-prs.yml

As a Microsoft-owned repo, the default permissions for our `GITHUB_TOKEN` are going to change in the near future, so we need to begin explicitly granting what permissions we need.
After looking at the API calls in [srggrs/assign-one-project-github-action](https://github.com/srggrs/assign-one-project-github-action) and reading [GitHub's permissions documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions), I'm 70% confident that `repository-projects: write` is what we need. Note that I am unable to test this PR (because my fork doesn't have any Classic Projects and GitHub frustratingly won't let me create them anymore).
[`.github/workflows/move-ready-for-review-prs.yml`](https://github.com/microsoft/STL/blob/9f9ab8855c9bb5ac68f462fa540 …

Add permissions to the Assign New PR action

---

stl/inc/yvals_core.h

Close #4224
Update yvals_core.h file to December 2023.

Update yvals to December 2023

---

stl/inc/mdspan

Test coverage will be provided by the upcoming libcxx update, which complained:
```
mdspan(541,49): error: comparison of integers of different signs: 'index_type' (aka 'unsigned long long') and 'index_type' (aka 'int') [-Werror,-Wsign-compare]
```
Varying signedness is allowed by WG21-N4964 \[mdspan.extents.overview\]/1.1 "`IndexType` is a signed or unsigned integer type".

`<mdspan>`: Avoid `-Wsign-compare` warnings

---

stl/inc/sstream

Test coverage will be provided by the upcoming libcxx update, which has allocators with custom size types. #4219 fixed outright compiler errors, but there's still a compiler warning:
```
sstream(57): warning C4267: 'argument': conversion from 'size_t' to 'const unsigned int', possible loss of data
```
`_Convert_size` is our machinery for dealing with this.

`<sstream>`: Avoid truncation warnings in `basic_stringbuf`'s constructor

---

stl/inc/xutility
tests/std/tests/P0896R4_ranges_range_machinery/test.cpp

Fixes #4107.
Non-exception throwing specifier added in ```stl/inc/xutility:3357```
Besides, some improper fomats are changed in ```stl/inc/xutility```

Add Non-exception Throwing Specifier to `ranges::ssize`

---

stl/inc/random

Neither Clang nor MSVC is smart enough to optimize the previous code into the simple non-branching non-conditional move variant. (GCC actually is, but GCC does not matter in this context)
See
https://godbolt.org/z/T9GT7s5rG
https://godbolt.org/z/eE7q9G9W8
---------
**Comment on the PR instructions:**
I am working on custom distributions for Catch2, and implemented the range adjustment like this. Afterwards I went to check how the STLs do it and quick test showed that MSVC is better served with my implementation. Since this started as my original work, even though for different repo, I think that's fine.

`<random>`: Optimize range adjustment in `uniform_int`

---

stl/inc/algorithm
stl/inc/vector
stl/inc/xstring

Test coverage will be provided by `std/strings/basic.string/string.cons/from_range.pass.cpp`, `std/containers/unord/unord.multimap/unord.multimap.cnstr/from_range.pass.cpp`, and more in the upcoming libcxx update that I'm working on. They have allocators with custom size/difference types (e.g. 32-bit types even on 64-bit platforms) that reveal these issues.
When subtracting `string`/`vector` iterators, we can get truncation warnings like `xstring(1972): warning C4244: 'return': conversion from '__int64' to 'int', possible loss of data`. Because we're subtracting iterators into the same `string`/`vector`, casting to the allocator's `difference_type` is always safe.
In `_Is_permutation_sized` powering `ranges::is_permutation`, we can get `algorithm(940): warning C4244: 'argument': …

Fix truncation warnings in `string`/`vector` iterator subtraction and `ranges::is_permutation`

---

stl/inc/format

Fixes #4241. Test coverage will be provided by the upcoming libcxx update.
When `_First == _Last`, the iterator will compare equal to `default_sentinel_t` and the callsite `_Measure_string_prefix()` will do the right thing, we just need to avoid calling `_Decode_utf()` for an empty range. This will leave `_Next` as null, which is fine - we only need it when we increment the iterator.
`_Measure_string_prefix_iterator_legacy` already appears to handle empty ranges correctly.

`<format>`: Fix STL internal check when formatting empty strings

---

stl/inc/xlocale
stl/src/locale0.cpp

Found by `std/localization/locales/locale/locale.cons/char_pointer.pass.cpp` in the upcoming libcxx update:
```
D:\GitHub\STL\llvm-project\libcxx\test\std\localization\locales\locale\locale.cons\char_pointer.pass.cpp(92): error C2440: '<function-style-cast>': cannot convert from 'nullptr' to 'std::locale'
D:\GitHub\STL\llvm-project\libcxx\test\std\localization\locales\locale\locale.cons\char_pointer.pass.cpp(92): note: 'std::locale::locale': ambiguous call to overloaded function
D:\GitHub\STL\out\x64\out\inc\xlocale(304): note: could be 'std::locale::locale(const char *,std::locale::category)'
D:\GitHub\STL\out\x64\out\inc\xlocale(394): note: or       'std::locale::locale(std::locale::_Locimp *)'
D:\GitHub\STL\llvm-project\libcxx\test\std\localization\locales\locale\locale.cons\char_pointe …
```

Allow `locale{nullptr}` to compile

---

stl/inc/chrono
tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp

`<chrono>`: Make `format()` accept `%X` and `%EX` for `duration` and `hh_mm_ss`

---

stl/inc/memory

Found by `std/utilities/memory/util.smartptr/util.smartptr.shared/util.smartptr.shared.create/allocate_shared_for_overwrite.pass.cpp` in the upcoming libcxx update.
```
memory(2858): warning C4267: 'argument': conversion from 'size_t' to 'test_allocator<U>::size_type', possible loss of data
```
We need to `_Convert_size` when allocating, but if that succeeds, we can simply `static_cast` when deallocating.

Fix truncation warnings in `allocate_shared()`

---

stl/inc/regex

Found by `std/re/re.submatch/re.submatch.op/compare.pass.cpp` in the upcoming libcxx update.
This follows WG21-N4964 \[re.submatch.op\]/5:
```cpp
template<class BiIter, class ST, class SA>
auto operator<=>(
const sub_match<BiIter>& lhs,
const basic_string<typename iterator_traits<BiIter>::value_type, ST, SA>& rhs);
```
*Returns:*
```cpp
static_cast<SM-CAT(BiIter)>(lhs.compare(
typename sub_match<BiIter>::string_type(rhs.data(), rhs.size()))
<=> 0
)
```
without constructing a temporary. Our equality operators are already correct.

Fix `sub_match <=> basic_string` with custom traits/allocators

---

stl/inc/deque
stl/inc/forward_list
stl/inc/list
stl/inc/vector
stl/inc/xstring
tests/libcxx/expected_results.txt

Found by the upcoming libcxx update, where they test CTAD for `(Iter, Iter, BadAlloc)` and expect it to SFINAE away.
(The explicit deduction guides are already constrained to take only things that qualify as allocators. The issue is that every constructor generates an implicit guide, and those can lead to the container being instantiated with a BadAlloc unless we guard against that.)
It's actually unclear to me whether this is guaranteed by the Standard, but the defense is simple and we already do this in `basic_string`.

Defend sequence container constructors from bad CTAD

---

tests/std/tests/P0912R5_coroutine/test.cpp

Port changes from [MSVC-PR-516915](https://devdiv.visualstudio.com/DevDiv/_git/msvc/pullrequest/516915)

Suppress a PREfast warning in tests

---

tests/libcxx/expected_results.txt
tests/libcxx/lit.site.cfg.in
tests/std/lit.site.cfg.in
tests/std/tests/P0912R5_coroutine/test.cpp
tests/tr1/lit.site.cfg.in
tests/utils/stl/test/features.py
tests/utils/stl/test/tests.py

This picks up the llvm-project update #4263. It doesn't yet test `<flat_set>`, but switching between branches is really annoying when they have different submodules.

Merge `main` to `feature/flat_set`

---

tests/libcxx/expected_results.txt

Followup to #4263. In the zillions of times that I ran libcxx locally, and in GitHub PR checks, and for MSVC locally, and in MSVC-PR checks, everything was fine - then the very first post-merge GitHub CI encountered a sporadic failure in an inherently bogus detached-threads test. This needs to be SKIPPED because we don't know if it'll pass or fail.
Additionally, I'm recording llvm/llvm-project#75611 that @frederick-vs-ja reported, as mentioned in https://github.com/microsoft/STL/pull/4263#discussion_r1428011519.

Skip a sporadically failing libcxx test

---

stl/inc/xthreads.h

We change the size of critical sections based on `_CRT_WINDOWS`, but that macro is defined at build time only, and the size is relevant in our headers. We need to change the size based on `UNDOCKED_WINDOWS_UCRT` as well, which is defined in consumers. 
I've added a pragma detect mismatch as well, but as its own commit. If we don't want it we don't have to accept that commit.

Fix an issue in the special snowflake windows version of the STL

---

stl/inc/xthreads.h

Followup to #4294.
In theory, this `#pragma detect_mismatch` was a good thing. In practice, it causes ~200 directories to fail with linker errors in the Windows build. That's too many to feasibly deal with on short notice, even if we added an escape hatch, so we should simply drop this attempt to detect mismatch. (The change was originally tested in Windows in December without `detect_mismatch`.)
The net effect of #4294 and this PR is to make `_Critical_section_size` additionally sensitive to `UNDOCKED_WINDOWS_UCRT`. This should be a strict improvement, reducing mismatches between the headers and separately compiled code (we know for a fact that this was causing problems). If these ~200 directories are mixing TUs with varying settings of `UNDOCKED_WINDOWS_UCRT`, then depending on linker …

Drop `#pragma detect_mismatch` for `mutex` size

---

tests/libcxx/expected_results.txt

Followup to #4263.
* For some MSVC-specific failures, I forgot to mark both :0 (MSVC plain) and :1 (MSVC ASAN).
+ I ran ASAN several times while working on the llvm-project update, but forgot to run it at the very end.
* Mark x86-specific "AddressSanitizer: allocator is out of memory" issues as `:1 SKIPPED`.
+ The STL-ASan-CI had to find these, because I was unable to run whole x86 ASAN test runs (they would hang). However, I'm able to reliably reproduce these failures locally by running the individual directories.
* Comment why 2 tests in mem.poly.allocator.mem are marked for :0 (MSVC) only - it's static analysis warning C6011.
* Consistently comment when we're marking only :0 (MSVC) because :1 (ASAN) doesn't run static analysis.
* Enhance a comment to mention that :1 means ASAN.
In the …

Mark ASAN failures in libcxx

---

stl/inc/atomic
tests/libcxx/expected_results.txt

Per [[atomics.types.generic.general]](https://eel.is/c++draft/atomics.types.generic.general), [[atomics.types.int]](https://eel.is/c++draft/atomics.types.int), [[atomics.types.float]](https://eel.is/c++draft/atomics.types.float), and [[atomics.types.pointer]](https://eel.is/c++draft/atomics.types.pointer), this overload exists for all specializations.
Unblocks two libcxx tests:
- `std/atomics/atomics.types.generic/atomics.types.float/copy.compile.pass.cpp`
- `std/atomics/atomics.types.generic/copy_semantics_traits.pass.cpp`

`<atomic>`: Add missing `atomic& operator=(const atomic&) volatile = delete;` overload

---

azure-devops/asan-pipeline.yml

.... but set the UI to require a maintainer comment to trigger.

Enable STL-ASAN-CI on PRs

---

README.md

Updated working draft revision to N4971

---

docs/cgmanifest.json

https://github.com/boostorg/math/releases/tag/boost-1.84.0

Update boost-math to 1.84

---

azure-devops/config.yml

Today is Patch Tuesday, but due to the holidays there's no new VS Preview (and VS 2022 17.9 Preview 3 won't contain significant MSVC toolset changes anyways). As there are no other dependency updates, this is one line.
As usual, I verified that this actually picked up the Patch Tuesday OS, since occasionally there are delays in the VM image becoming available. (The wiki has a PowerShell incantation that reports whether Patch Tuesday is available as a VM image, then the script prints out `winver` to confirm what was picked up.)

Toolset update: Jan 2024 Patch Tuesday

---

stl/inc/execution
tests/std/tests/P0024R2_parallel_algorithms_transform_reduce/test.cpp

`<numeric>`: switch `transform_reduce` from direct list initialization to copy non-list initialization

---

stl/inc/vector
tests/libcxx/expected_results.txt

I've confirmed that @StephanTLavavej's analysis for the related test failure was correct.
> Possible STL bug, _Vb_reference derives from _Vb_iter_base and is adopted by the container, but _Orphan_range_unlocked assumes every child is a const_iterator.
This PR exposes `_Mybase` for the convenience of casting, and removes some unnecessary `_Difference_type` member type alias as driven-by changes. (It seems better to me to use `difference_type` whenever it's available.)
Unblocks one libcxx test:
- `std/containers/sequences/vector.bool/emplace_back.pass.cpp`

`<vector>`: Cast to the correct base type in `vector<bool, Alloc>::_Orphan_range_unlocked`

---

stl/inc/type_traits
tests/libcxx/expected_results.txt

The bug was not previously analyzed. I reduced the test case and reported DevCom-10543093.
Unblocks one libcxx test:
- `std/utilities/function.objects/func.invoke/invoke_constexpr.pass.cpp`

`<type_traits>`: Workaround for DevCom-10543093 (ICE with some uses of pointers to data members)

---

stl/inc/chrono
tests/std/test.lst
tests/std/tests/GH_004201_chrono_formatter/env.lst
tests/std/tests/GH_004201_chrono_formatter/test.cpp

Fixes #4201.
As has @cpplearner noted, `_Chrono_formatter::_Write()` calls and returns `_Write_aligned` before trying to check if a width is provided dynamically. The updated behavior is now similar to that of `_Formatter_base::format()`.

`<chrono>`: Fix `formatter` ignoring dynamically provided width

---

stl/inc/exception
stl/inc/istream
stl/inc/iterator
stl/inc/ostream
stl/inc/random
stl/inc/typeindex
stl/inc/typeinfo
stl/inc/yvals_core.h
tests/std/tests/GH_002206_unreserved_names/test.compile.pass.cpp

Towards #2206. The posted example should compile with the changes landed when pre-standard hash containers are disabled.
- Not sure how to test `stdext`, because `<__msvc_all_public_headers.hpp>` is currently including non-Standard `<hash_map>` & `<hash_set>`.
- `<arm64_neon.h>` (which is surprisingly heavy), `<ppltasks.h>`, and UCRT stuffs are not handled currently.
Some extensions may become conforming with deprecation warnings enabled, others are not yet because they're visible via SFINAE.

Mitigate non-conformance of extensions of non-reserved names by the `push_macro`/`pop_macro` mechanism

---

stl/src/atomic_wait.cpp

As _Api_level is not always accessed with sequential ordering, and _Level is thread-local, acq_rel is good enough for all compare_exchange successes. However, this means we need to explicitly mention acquire for the failure case.

All atomic exchanges with _Api_level should be acq_rel

---

stl/inc/memory
tests/libcxx/expected_results.txt

There are weird things in [[util.smartptr.shared.const]/3](https://eel.is/c++draft/util.smartptr.shared.const#3) and [[util.smartptr.shared.const]/9.1](https://eel.is/c++draft/util.smartptr.shared.const#9.1): `Y(*)[N]` or `Y(*)[]` is not necessary a valid type, e.g. when `Y` is `T[]` or a function type, which means that the constraints themselves can be sometimes ill-formed.
Presumably there should be substitution failures in such cases (instead of hard errors or UB/IFNDR). I've tried to submit an LWG issue for this.
`void_t<decltype(static_cast<_Yty (*)[]>(nullptr))>` works while `void_t<_Yty (*)[]>` doesn't for MSVC. Reported DevCom-10548086.
Unblocks 2 libcxx tests:
- `std/utilities/memory/util.smartptr/util.smartptr.shared/util.smartptr.shared.const/pointer.pass.cpp`
- …

`<memory>`: Fix constraints of `shared_ptr`'s constructors when the involved pointer type would be invalid

---

stl/inc/xcharconv_ryu.h

When I ported @ulfjack's amazing [Ryu and Ryu Printf](https://github.com/ulfjack/ryu) to MSVC `<charconv>` (making it compatible with MSVC and C++, adding buffer bounds checking, etc.), I extensively validated correctness and tried to improve performance for both x64 and x86, on both MSVC and Clang/LLVM. x64 had convenient, fast intrinsics, while x86 relied on plain old (bitwise) arithmetic. Life was simple.
Over time, our codebase was modified to support ARM, ARM64, and more exotic flavors like ARM64EC, but we've long lacked comprehensive runtime test coverage. Now that's beginning to change, and Andrew Dean from the MSVC compiler back-end team discovered runtime failures, indicated by an `_STL_INTERNAL_CHECK` in `__ryu_shiftright128`. If built without internal checks, the code would …

`<xcharconv_ryu.h>`: Fix `__ryu_shiftright128` for ARM64

---

stl/inc/flat_map
tests/std/tests/P0429R9_flat_map/env.lst
tests/std/tests/P0429R9_flat_map/test.cpp

Addresses #4056, towards #2910, enabling `flat_map` (and, possibly, yet-to-implement `flat_multimap`) for permissive modes.
Other cleanups in the product code:
- Changes the "true name" of iterator types from `type` to `_Iterator`, as they are not transforming type traits.
- Possibly enables NRVO in iterator arithmetic operators.
- Drops `_STD` for trait variable templates.
- Uses `auto` for iterators obtained from `begin()` etc..
- Uses `_STL_INTERNAL_STATIC_ASSERT` for invariants maintained by implementations that should never be violated.
Other cleanups in the test:
- Drops all redundant `std::`.
- Drops redundant `return 0;` in `main()`.
- Drops redundant constructor inheritance for comparators - only default constructors are used.
- Avoids dependency on internal …

`<flat_map>`: Remove `zip_view` dependency and other cleanups

---

tests/libcxx/expected_results.txt
tests/utils/stl/util.py

* Mark a sporadic failure in a threading test as SKIPPED.
+ Explain how libc++ speculatively implemented LWG-3343 (thanks @CaseyCarter).
* Print exit codes in both decimal and hex (thanks to Sir Walrus on Discord for the suggestion).
+ Verified that this prints `Exit Code: 3 (0x3)` for an `abort()` and `Exit Code: 3221225477 (0xC0000005)` for a null dereference.
* Cite #4268 now that @frederick-vs-ja has analyzed these failures.
* Explain how libc++ speculatively implemented an old proposed resolution for LWG-3645. According to the ultimately accepted wording, their test is bogus and MSVC's STL is behaving correctly here.

Minor test improvements

---

tests/utils/stl/test/format.py

This doesn't solve the underlying problem causing the failure but will hopefully provide enough info for us to analyze it.
Addresses #4308

Report as UNRESOLVED when exception is thrown in `execute`

---

stl/inc/ranges
tests/libcxx/expected_results.txt
tests/std/tests/P2474R2_views_repeat/test.cpp
tests/std/tests/P2474R2_views_repeat_death/test.cpp

`<ranges>`: Fix truncation warnings and improve overflow check for `repeat_view`

---

stl/inc/algorithm
stl/inc/execution
stl/inc/xutility
tests/std/tests/GH_001596_adl_proof_algorithms/test.compile.pass.cpp
tests/std/tests/P2538R1_adl_proof_std_projected/test.compile.pass.cpp

Split from #4004, towards #140 and #1596.
Fixes #4043 by `::`-qualifying all remaining `__std_meow` vectorizing functions (some are `_STD`-qualified in #4146).
Also adds `_Is_trivially_ranges_swappable(_v)` to handle triviality of swapping by `ranges::swap` (which gets rid of ADL for pointers and pointers-to-members), along with workaround for DevCom-10456445.

ADL-proof implementation of [alg.modifying.operations]

---

stl/inc/deque
stl/inc/forward_list
stl/inc/list
stl/inc/vector
stl/inc/xhash
stl/inc/xmemory
stl/inc/xstring
stl/inc/xtree
tests/libcxx/expected_results.txt
tests/std/tests/VSO_0000000_instantiate_containers/test.compile.pass.cpp

Towards #140. Some changes were already done in #4217.
Unblocks one libcxx test:
- `std/strings/basic.string/string.modifiers/robust_against_adl.pass.cpp`
Notes:
- There're some other internal function names qualified in changed functions.
- Occurences of `_Adl_verify_range` are consistently `_STD`-qualified in touched headers.

ADL-proof container operations for iterator pairs and comparators

---

stl/inc/filesystem
tests/libcxx/expected_results.txt

The goal of the implementation was to fix #4291.
Following tables should explain the behavior of the current implementation in comparison to the changed code:
| Case       | `filesystem::exists(...)` | current implementation           | this implementation 
| ------------- |:---:|:-------------:| :-----:|
| empty volume<br/>`\\?\Volume{ecab883f-c728-474b-9b40-e90cb2834b66}\` | `true` | `ERROR` :bug: | `true` | 
| not existing volume<br/>`\\?\Volume{ecab883f-c728-474b-9b40-e90cb2834b65}\` | `false` | `ERROR` | `ERROR` | 
| Case       | `filesystem::exists(...)` | current implementation           | this implementation 
| ------------- |:---:|:-------------:| :-----:|
| empty volume<br/>`\\?\Volume{ecab883f-c728-474b-9b40-e90cb2834b66}\` | `true` | `ERROR` :bug: | `empty` | 
| not existing …

Adjusted behavior of filesystem::is_empty and filesystem::directory_iterator to work with empty volumes

---

stl/inc/type_traits
tests/std/tests/P0758R1_is_nothrow_convertible/test.compile.pass.cpp

`<type_traits>`: Make `is_nothrow_convertible` a class template and ADL-proof

---

CMakeLists.txt
azure-devops/asan-pipeline.yml
azure-devops/cmake-configure-build.yml
azure-devops/native-build-test.yml
stl/CMakeLists.txt
tests/libcxx/lit.site.cfg.in
tests/libcxx/usual_matrix.lst
tests/std/include/force_include.hpp
tests/std/include/vso1913897.hpp
tests/std/tests/GH_002030_asan_annotate_string/env.lst
tests/std/tests/GH_002030_asan_annotate_vector/env.lst
tests/utils/stl/test/tests.py

Add support for instrumenting the STL with ASan by setting the `STL_ASAN_BUILD` cmake option and enable this support in the STL-ASan-CI pipeline. This lets us run "full ASan" tests with coverage of the header-only code and binary libraries. For now that requires client programs to be ASan instrumented since they statically link with either the entire STL (`/MT` or `/MTd`) or the contents of the import library (`/MD` or `/MDd`). 
This includes a fairly icky workaround for an initialization ordering bug (VSO-1913897) which injects a dynamically-initialized `thread_local` into each test TU. It's a matter of opinion whether it's more horrible to have ASan and non-ASan test coverage diverge by using this workaround only for ASan testing, or more horrible to have the ASan workaround affect …

Support instrumenting the STL with ASan

---

stl/inc/xcharconv_ryu.h

This mirrors @mcfi's MSVC-PR-522018.

`<xcharconv_ryu.h>`: `__umulh` is already an intrinsic for `_M_HYBRID_X86_ARM64`

---

stl/inc/expected
tests/std/tests/P0323R12_expected/test.cpp

The conditions for triviality should be consistent with `optional` and `variant` (see WG21-P0602R4). I've tried to submit an LWG issue for this, but I believe we can conformingly do this without changing the standard wording. Edit: the issue is now LWG-4026.
The changes are also being made in libc++, see LLVM-74768.
<details><summary>Old test coverage was a bit crazy</summary>
<p>
More than 1000 function template specializations are instantiated. But I have no good idea to reduce the instantiation.
<ul dir="auto">
<li>It was actually somehow bad, there're failures with "fatal error C1060: compiler is out of heap space".</li>
</ul>
</p>
</details>
Edit: reduced the cases from 32×32 to 6×6.

`<expected>`: Make copy/move assignment operators of `expected` propagate triviality

---

stl/inc/random
stl/inc/yvals_core.h
tests/std/tests/VSO_0000000_instantiate_iterators_misc/test.compile.pass.cpp
tests/tr1/tests/random1/test.cpp
tests/tr1/tests/random6/test.cpp

Towards #183 and #1002.
They are internally undeprecated when used as base classes. It seems that when `_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING` is defined, warning should still be suppressed.
~TODO: need to investigate how to reuse functions from base classes.~ DONE

`<random>`: Deprecate TR1 components in the `std` namespace

---

stl/inc/format
tests/std/tests/P0645R10_text_formatting_formatting/test.cpp

Fixes #4319
`libcxx\test\std\utilities\format\format.functions\locale-specific_form.pass.cpp` is still failing after this fix.
```
Format string   {:$<11.6Lg}
Expected output 1,234.57$$$
Actual output   1,234.57$$$$
```
I guess, it's a different bug, isn't it?

fix formatting floating-point values without type and precision provided

---

stl/inc/expected
stl/inc/optional
stl/inc/type_traits
stl/inc/xutility
tests/std/test.lst
tests/std/tests/GH_000140_adl_proof_comparison/env.lst
tests/std/tests/GH_000140_adl_proof_comparison/test.compile.pass.cpp
tests/std/tests/P0896R4_ranges_range_machinery/test.cpp

... by `_STD`-qualifying `_Fake_copy_init`. Towards #140.
While dealing with #4318, I found that most, if not all, occurrences of `_Fake_copy_init` in MSVC STL needed to be qualified.
Fixed components:
- "legacy" comparison function objects: `equal_to`, `not_equal_to`, `less`, `greater`, `less_equal`, and `greater_equal`
- iterator adaptors: `reverse_iterator`, `move_iterator` (together with `move_sentinel`), and `basic_const_iterator`
- `optional`
- `expected` (together with `unexpected`)
Views (in `<ranges>`) are not yet touched since I haven't come up with testing examples, but I think occurrences of `_Fake_copy_init` in views also need to be qualified.

Make implicit conversion to `bool` ADL-proof (except for views)

---

tests/libcxx/expected_results.txt

... and update links to point at upstream issues instead of VSOs which I closed as "duplicates" of those upstream issues.

Clarify some ASan-related libcxx FAILs

---

stl/inc/flat_map
tests/std/tests/P0429R9_flat_map/env.lst
tests/std/tests/P0429R9_flat_map/test.cpp

As mentioned in a [comment](https://github.com/microsoft/STL/commit/00c23249b9580512990722e3a0494fe61866c3fe#commitcomment-137907936), I've been testing out the `flat_map` implementation in my personal project but after the last commit I'm getting the following error:
`flat_map.h(1196,44): '_Key_equal': function was not declared in the template definition context and can be found only via argument-dependent lookup in the instantiation context`
Previous version compiled fine though.
It seems the `_Try_emplace` function here depends on the private `_Key_equal`. I moved that back to the base implementation similar to `_Erase_if`.
I've also moved `_Insert_exact` to the protected section as the `flat_multimap::_Emplace_key_mapped()` uses that function.

`<flat_map>` Fix compile errors

---

stl/inc/algorithm
stl/inc/execution
stl/inc/xmemory
stl/inc/xutility
tests/std/tests/GH_001596_adl_proof_algorithms/test.compile.pass.cpp
tests/std/tests/P2538R1_adl_proof_std_projected/test.compile.pass.cpp

Separated from #4004. Towards #140 and #1596.

ADL-proof implementation of [alg.merge], [alg.set.operations], [alg.heap.operations], and [alg.permutation.generators]

---

tests/libcxx/expected_results.txt
tools/scripts/check_libcxx_paths.py

I started by adding a script `check_libcxx_paths.py` to make LLVM updates easier. Then I figured I'd see how easy it was, and it only took me a day instead of a month.
llvm/llvm-project#79793 is still in flight, but the affected test is blocked by a suspected MSVC compiler bug with `constexpr`, so we don't need to wait.

llvm-project Mini-Update

---

stl/inc/generator

Mostly tiny adjustments to better match the standard.
Also implements LWG-3894 "`generator::promise_type::yield_value(ranges::elements_of<Rng, Alloc>)` should not be `noexcept`".
Works towards #2936.

`<generator>`: Mark strengthened noexcept (plus tiny drive-by changes)

---

tests/libcxx/expected_results.txt

Mark more libcxx tests as FAIL due to ASan oversized allocations

---

benchmarks/CMakeLists.txt
benchmarks/inc/udt.hpp
benchmarks/inc/utility.hpp
benchmarks/src/std/containers/sequences/vector.bool/copy/test.cpp
benchmarks/src/std/containers/sequences/vector.bool/copy_n/test.cpp
benchmarks/src/std/containers/sequences/vector.bool/move/test.cpp

Discovered while reviewing #3928, but this has been lurking since the addition of the benchmarks in #2780. No stealth merge conflicts - #3928's new benchmark has been fixed to be warning-clean.
* Enable warnings when building the benchmarks.
+ Start with the usual: `/diagnostics:caret /W4 /WX`
+ I'm enabling the same off-by-default warnings as the STL's build (C4265 (non-virtual dtor), C5038 (data member init order)) and adding C5262 (implicit fallthrough).
+ Finally, let's add `/utf-8` in case we ever benchmark `<format>`.
* Fix x86 `size_t` truncation warnings in the vector.bool benchmarks.
* `udt.hpp`: Rename template parameters from `Contained` to `Data`, avoiding REALLY confusing diagnostics.
* `utility.hpp`: Silence truncation warnings with a big comment.

Enable warnings for the benchmarks, and fix them

---

tests/utils/stl/util.py

Fixes #4308.
Followup to #2145, which added a two-step process for decoding compiler and test output. See [Python's Unicode documentation](https://docs.python.org/3/howto/unicode.html#the-string-type) and [`bytes.decode` documentation](https://docs.python.org/3/library/stdtypes.html#bytes.decode). Our `decodeOutput(bytes)` first tries `bytes.decode()`, i.e. `bytes.decode(encoding='utf-8', errors='strict')`, to handle EDG's UTF-8 output. `'strict'` asks it to throw a `UnicodeDecodeError` (derived from `UnicodeError`). If that happens, we assume we're looking at MSVC's output in the active codepage, so we fall back to locale-aware decoding.
The problem was that this fallback was still `'strict'`, so if the test emitted unrecognized characters, we'd get another `UnicodeDecodeError`, this …

Use Python `backslashreplace` to avoid UNRESOLVED tests

---

stl/inc/__msvc_filebuf.hpp
stl/inc/ostream
stl/inc/print
stl/inc/ranges
tests/std/tests/Dev11_0000000_tuple_cat/test.cpp
tests/std/tests/GH_000545_include_compare/test_stacktrace.cpp
tests/std/tests/GH_000690_overaligned_function/test.cpp
tests/std/tests/GH_001411_core_headers/test.cpp
tests/std/tests/P0769R2_shift_left_shift_right/test.cpp

From https://github.com/microsoft/STL/pull/4298#issuecomment-1923382041:
> in general, we prefer to test coarse-grained `_HAS_CXXnn` instead of fine-grained `__cpp_lib_MEOW`, once there are no compiler or mode dependencies.

Test coarse-grained `_HAS_CXXnn` instead of fine-grained `__cpp_lib_MEOW`

---

.github/workflows/update-status-chart.yml

Followup to #4223 where I said:
> `.github/workflows/update-status-chart.yml` mentions `github.token` for the GraphQL API, but all it needs is public read-only access, so I don't think that it'll need to be changed.
Wrong! It autonomously commits changes:
https://github.com/microsoft/STL/blob/1bc5ca60fcb41c2ed87a721d6ca2f77844cf6dc6/.github/workflows/update-status-chart.yml#L31-L37
So the workflow runs [started failing](https://github.com/microsoft/STL/actions/runs/7752540972/job/21142220750) with:
```
remote: Permission to microsoft/STL.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/microsoft/STL/': The requested URL returned error: 403
Error: Process completed with exit code 128.
```
I've verified in my fork that granting the `contents: write` permission …

Add permissions to the Update Status Chart action

---

stl/inc/flat_map
tests/std/include/test_header_units_and_modules.hpp
tests/std/tests/P0429R9_flat_map/env.lst
tests/std/tests/P0429R9_flat_map/test.cpp

Towards #2910. Addresses some comments in #4337.
Product code fixes for `<flat_map>`.
- Proper `_EXPORT_STD`.
- Simplify the template head of `_Flat_map_base`.
- `_NODISCARD` and `_NODISCARD_FRIEND`.
- Drop leading `typename` in the namespace scope.
- Re-enable `/permissive` mode by changing `_Insert_exact` calls.
- Perhaps we should change `_Insert_exact` in the future.
- Avoid double guarding in `_Erase_if`.
- Turn doubtful accociated constraints into `_STL_INTERNAL_STATIC_ASSERT`.
Test coverage for modules with `<flat_map>`.
Test coverage unique to `<flat_map>`.
- SCARY-ness test reforming.
- Proper `this->template` test coverage.
- Re-enable `/permissive`.

`<flat_map>`: Re-enable `/permissive` with miscellaneous fixes and test coverage

---

stl/inc/exception
stl/inc/new
stl/inc/typeinfo
stl/modules/std.ixx
tests/std/include/test_header_units_and_modules.hpp

Fixes #4350. Mirrored as MSVC-PR-527804 with VCRuntime changes.
The Standard has a rule WG21-N4971 \[module.interface\]/6: "A redeclaration of an entity *X* is implicitly exported if *X* was introduced by an exported declaration; otherwise it shall not be exported." followed by an example:
```cpp
export module M;
struct S { int n; };
typedef S S;
export typedef S S; // OK, does not redeclare an entity
export struct S;    // error: exported declaration follows non-exported declaration
```
[Clang enforces this rule](https://godbolt.org/z/bcG9b4hzv), but MSVC let me be a bad kitty :smirk_cat:, jumping up on the table where I'm not allowed, reported as VSO-1953157 "Modules: MSVC should emit an error when an exported declaration follows a non-exported declaration".
For types, we can export …

Export VCRuntime entities properly

---

stl/inc/ostream
tests/std/tests/GH_001858_iostream_exception/test.cpp

Fix rethrowing the caught exception from streambuf

---

stl/inc/vector
stl/inc/xmemory
tests/libcxx/expected_results.txt
tests/std/tests/VSO_0000000_instantiate_containers/test.compile.pass.cpp

By qualifying `_Ugly` calls in `vector::_Tidy`, `allocator`'s member functions, and `_Destroy_range` to avoid inadvertent ADL.
Fixes #3842

Properly destroy `vector<shared_ptr<uninstantiable>>`

---

stl/inc/memory
stl/inc/new
stl/inc/xmemory
tests/std/tests/GH_001596_adl_proof_algorithms/test.compile.pass.cpp
tests/std/tests/P2538R1_adl_proof_std_projected/test.compile.pass.cpp

Separated from #4004. Towards #140 and #1596.
There's a separated commit addressing cases noted in https://github.com/microsoft/STL/pull/4367#discussion_r1477975129. Note that EDG currently incorrectly thinks `Derived*` and `Base*` are subtractable under some conditions, which ~should be~ is reported as DevCom-10581519 and should be cited as VSO-XXXX.
Unfortunately, currently there doesn't seem possible to verify that `_Copy_memcpy_distance` and `_Copy_memcpy_count` calls are properly qualified, because the comparison between `tagged_derived<holder<incomplete>>*` and `unreachable_sentinel_t` is ill-formed due to ADL.
As a workaround for DevCom-10456452, the `__builtin_launder` call is qualified.
This PR changes one line `_Destroy_range` in the same way as #4373, which shouldn't raise …

ADL-proof implementation of uninitialized memory algorithms

---

stl/inc/functional
tests/std/tests/P0220R1_searchers/test.cpp

Separated from #4004. Towards #140.
This PR makes `default_searcher` ADL-proof and makes `boyer_moore_searcher` and `boyer_moore_horspool_searcher` accept ADL-incompatible functors.
Currently, internal function calls involving program-defined types and `std::swap` calls are `_STD`-qualified, while other internal functions (which only involve `void*` and integers) are not.
There're some difficulties in making `boyer_moore_searcher` and `boyer_moore_horspool_searcher` accept ADL-incompatible element types: see #4380.

`<functional>`: Make `default_searcher` ADL-proof

---

README.md

Fixes #4381
It seems htmlLabels are disabled by default now for some reason. But we can enable them.
It seems it works:
https://github.com/fsb4000/STL/tree/patch-1

README.md: allow htmlLabels inside flowchart

---

benchmarks/CMakeLists.txt
benchmarks/src/find_and_count.cpp

Ported from #2434 description, dropping unnecessary parts.

Add `find` / `count` benchmark

---

stl/inc/mutex
stl/inc/xthreads.h
stl/src/mutex.cpp

By simply removing `~_Mutex_base`. This destructor has been only a debug check since GH-3770. Losing the debug check is a small price to pay to elide the destructor call, doubly so for static storage duration mutexes that now won't need dynamic initializers to register with `at_exit`.
`_Mtx_destroy` and `_Mtx_destroy_in_situ` are only called by APIs preserved for binary compatibility, so mark them as also "preserved for binary compatibility".

Make `~mutex` trivial

---

stl/inc/execution
stl/inc/numeric
stl/inc/vector
stl/inc/xmemory
tests/std/tests/GH_001596_adl_proof_algorithms/test.compile.pass.cpp

Separated from #4004 (this is the last one). Towards #1596.
Some `begin()` calls are replaced with `data()` because the iterator operations are not ADL-proof.
- There're some other `begin()` calls on `_Parallel_vector` that are not dependent on user-defined types and thus are always safe. I'm not sure whether we should consistently use `data()` (which possibly improves debug performance).
After merging this PR, there're still a small number of unqualified `_Adl_verify_range` calls that possibly do evil (in `span` and `distance` etc.).
The remaining unqualified `_Adl_verify_range` calls looks "OK" to me as ADL-incompatible types don't seem required to be supported in those cases (where the acceptable value types are integer/character types).

ADL-proof implementation of numeric algorithms

---

tests/utils/stl/test/format.py

Fixes #4393.
@AlexGuteniev discovered that attempting to run tests with a drive letter of a different case would fail (see lowercase `d:`):
```
D:\GitHub\STL\out\x64>python tests\utils\stl-lit\stl-lit.py d:\GitHub\STL\tests\std\tests\VSO_0157762_feature_test_macros
stl-lit.py: D:\GitHub\STL\llvm-project\llvm\utils\lit\lit\discovery.py:276: warning: input 'd:\\GitHub\\STL\\tests\\std\\tests\\VSO_0157762_feature_test_macros' contained no tests
error: did not discover any tests for provided path(s)
```
Later, I discovered that case variation in the middle of the path would also fail (see uppercase `STD`):
```
D:\GitHub\STL\out\x64>python tests\utils\stl-lit\stl-lit.py D:\GitHub\STL\tests\STD\tests\VSO_0157762_feature_test_macros
stl-lit.py: …
```

Handle paths case-insensitively when running tests

---

stl/src/vector_algorithms.cpp

The possibility was realized when working on #4384. 
I observed that the compiler swaps branches to make the `_Minmax` loop more local.
Applying the same change to the `_Minmax_element` loop gives significant improvement: 1.6 or 1.8 times for some cases.
Also made that change to `_Minmax` loop to maintain consistency (with both its counterpart and how it being compiled).
<details>
<summary>Benchmark results</summary>
```
--------------------------------------------------------------------------------------------
Benchmark                              Old Time        Old CPU    New Time         New CPU  
--------------------------------------------------------------------------------------------
bm<uint8_t, 8021, Op::Min>              647 ns          642 ns      361 ns          361 ns …
```

`vector_algorithms.cpp`, `*minmax*`: invert the condition to improve `*_element` cases a bit more

---

stl/inc/mutex
stl/inc/span
stl/inc/xutility
tests/std/tests/Dev11_1114006_condition_variable_pred/test.cpp
tests/std/tests/P0122R7_span/test.cpp
tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp

Towards #140. Fixes #1596. IIUC remaining unqualified `_Adl_verify_range` calls after this PR are not supposed to involve ADL-incompatible iterators.
Affected components:
- `ranges::advance` (non-sized branch)
- `ranges::distance` (non-sized branch)
- `span` constructors
- `condition_variable::wait_for`
Notes:
- `_STD`-qualification is also made in `std::advance` and `std::distance` for consistency, but IIUC these code paths don't handle ADL-incompatible iterators.
- `_To_absolute_time` remains unqualified, because valid `_Rep` in `chrono::duration<_Rep, _Period>` requires `_Rep` to be "arithmetic-like" type (although the requirements are unclear), and thus must not be ADL-incompatible.
- Currently, `span<holder<incomplete>*>` can't be supported in C++23 mode because …

ADL-proof implementation of range verifying and functor passing components that involve arbitrary types

---

stl/inc/memory
stl/inc/xmemory
tests/std/tests/Dev10_445289_make_shared/test.cpp
tests/std/tests/P0718R2_atomic_smart_ptrs/test.cpp

Towards #140 and #3100.
Notes:
- `_Fill_memset` is `_STD`-qualified for consistency, although it seems that `_Fill_memset` is never used with "weird" types.
- All `_Make_shared_unbounded_array` and `_Allocate_shared_unbounded_array` overloads are consistently `_STD`-qualified even though some don't need.
- One `_Deallocate` call is `_STD`-qualified as drive-by since #4373 started to do this.
- The remaining unqualified `_Deallocate` call are all related to `function` and will be handled in a future PR.
- `_STD addressof(meow)` is used in some places instead of `&`. This seems necessary even if no ADL-incompatible type is involved, because an overloaded unary `operator&` can still do evil.
- In the test codes, `adl_proof_allocator` is invented. Because the equality comparison of …

`<memory>`: ADL-proof implementation of `shared_ptr` creation functions and atomic smart pointers

---

stl/inc/yvals.h
stl/src/stdhndlr.cpp

Towards #3521
After finally making both constructor of `std::mutex` `constexpr` and its destructor trivial, it is should be fine to use usual mutexes everywhere!

`<new>`: `SRWLOCK` to protect the `new` handler instead of an indexed `CRITICAL_SECTION`

---

stl/inc/yvals.h
stl/src/xlock.cpp
stl/src/xnotify.cpp

Towards #3521. Fixes #273.
After finally making mutex constructor and destructor constexpr, it is time that we start using usual mutexes!

`xnotify.cpp`: `SRWLOCK` to protect the at-thread-exit data instead of an indexed `CRITICAL_SECTION`

---

stl/inc/algorithm
stl/inc/xutility

Closes #4385 
This PR adds the top-level `const` to the `_Ty* _First, _Ty* _Last ` parameters for the following functions
`<algorithm>` : `__std_minmax_element`, `__std_minmax`
`<xutility>`: `__std_find_trivial_unsized`, `__std_min`, `__std_max`

<xutility>, <algorithm>: Add top level const on pointer parameters

---

stl/inc/ranges
tests/std/tests/P2321R2_views_zip_transform/test.cpp

Fixes #4414.
While there's DevCom-1603671 which directly results in the reported error, the library implementation is also currently somehow broken - the initializer of `_Enable_const_begin_end` may be ill-formed when the value is expected to be `false`, which can make `ranges::range<const ranges::zip_transform_view<...>>` ill-formed when it should be `false`.

`<ranges>`: Fix `zip_transform_view` by not using possibly ill-formed static data member

---

stl/inc/ranges
tests/std/include/test_header_units_and_modules.hpp

Fixes #4404 by working around VSO-1975579 "Standard Library Modules: fatal error C1116: unrecoverable error importing module `'std'`. Specialization of `'std::invoke_result_t'` with arguments `'_Fn, _Ty...'`".
I don't trust the behavior of pack expansions here until @cdacamar fixes the compiler, so I've chosen to use a classical countdown for the workaround.
I checked our other usage of `_Repeat_type` and it didn't appear to be affected, presumably because it doesn't involve `invoke_result_t`.

Modules workaround for `views::pairwise_transform`

---

stl/inc/format
tests/libcxx/expected_results.txt
tests/std/tests/P0645R10_text_formatting_formatting/test.cpp

Fix the incorrect width that occurred when formatting a floating number in the locale specific form

---

stl/inc/execution
stl/inc/xutility
stl/inc/yvals_core.h
tests/std/tests/P2374R4_views_cartesian_product/test.cpp

Fixes #4425.
This globally silences the warning because I don't think it's ever useful for the STL to emit it. If the user gives us a highly-aligned type, and we have to build another type with it, warning about padding is unlikely to be productive - presumably they had reasons for making their type highly-aligned, and it's not like they can change the layout of our type. (Yeah, in theory maybe they could request a different order of `tuple` elements or something, but most of the time it's not going to be actionable.) And if the warning is emitted purely from STL code, as in my test case, it's extremely annoying. Finally, this is just a performance warning - it has no impact on correctness.

Silence warning C4324: structure was padded due to alignment specifier

---

benchmarks/src/bitset_to_string.cpp
stl/src/vector_algorithms.cpp
tests/std/tests/VSO_0000000_vector_algorithms/test.cpp

Not sure if it worth merging due to complexity growth, and noticeable improvement only for larger bitsets
Turned out that the existing vectorization is fine for bitsets beyond 256 bits (32 bytes), and AVX2 upgrade is harmful.
For very large bitsets the improvement is noticeable.
```
Before:
------------------------------------------------------------------------------------
Benchmark                                          Time             CPU   Iterations
------------------------------------------------------------------------------------
BM_bitset_to_string<15, char>                    211 ns          206 ns      2800000
BM_bitset_to_string<64, char>                   2662 ns         2668 ns       263529
BM_bitset_to_string<512, char>                  3730 ns         3767 ns …
```

AVX2 vectorization for very large bitsets

---

stl/inc/functional
stl/inc/future
stl/inc/memory
stl/inc/optional
stl/inc/xmemory
tests/libcxx/expected_results.txt
tests/std/test.lst
tests/std/tests/GH_000140_adl_proof_construction/env.lst
tests/std/tests/GH_000140_adl_proof_construction/test.compile.pass.cpp
tests/std/tests/GH_001596_adl_proof_algorithms/test.compile.pass.cpp

Towards #140 and #3100.
Unblocks one libcxx test:
- `std/utilities/function.objects/func.wrap/func.wrap.func/robust_against_adl.pass.cpp`
Also contains some drive-by and previously missed changes.
- Handling for array destruction in algorithms (valid since C++20) was missed in #4374.
- `_STD`-qualification for one `shared_ptr`-related `_Unfancy` call (which is not strictly necessary).
- `_STD`-qualification for `_Deallocate` and `_Make_unique_alloc` calls (which are not strictly necessary IIUC).
- Moving `_Global_new` from `<xmemory>` to `<functional>` because it is only used for `function`.
Remaining unqualified `_Construct_in_place` and `_Destroy_in_place` calls after this PR are all in containers and `valarray`.

ADL-proof implementation of `function`, `move_only_function`, `packaged_task`, `promise`, and `optional`

---

stl/src/xdateord.cpp

Fixes #3346
1) I found out that the tests work on libc++. 
2) I looked how libc++ detect date_order. It has a some date and run `std::strftime(mbstr, sizeof(mbstr), "%x", std::localtime(&t));` and analyse its output.
3) I looked at `strftime` implementation. It creates `_LocaleUpdate` object. and passes `nullptr` to it.
`_LocaleUpdate` constructor looks like that (pseudo-code)
```C
if (locale)
{
_locale_pointers = *locale;
}
else if (is_it_C_locale())
{
_locale_pointers = some_predefined_values;
}
else
{
query runtime data to fill _locale_pointers from the current locale.
}
```
4) So  `std::strftime` uses `mdy` for "C" locale and we can do too. I found another places where we did a special case for "C" locale.
https://github.com/microsoft/STL/blob/8b081e26ba016970ce3338cb483ff10f2ade30a5/s …

Enforce `std::time_base::mdy` for "C" locale

---

stl/inc/random

Fixes #4434.
Notes:
- Extended unsigned integer types are not supported (through the whole MSVC STL).
- `char32_t` is excluded because it's not an "unsigned integer type" in the core language.
- `remove_cv_t` is used, which is related to CWG-251 (still open).
- `_Iter_value_t` is intentionally not used, see #4436.

`<random>`: Implement Mandates for `seed_seq::generate`

---

stl/inc/xmemory

Currently, both `_Allocate` and `_Deallocate` have multiple overloads that are dispatched by SFINAE.
It seems that we should dispatch overaligned and normal branches with `if constexpr` instead (see #189).

`<xmemory>`: Unify overloads of `_Allocate` and `_Deallocate` with `if constexpr`

---

stl/inc/compare
stl/inc/concepts
stl/inc/ranges
stl/inc/tuple
stl/inc/xutility
stl/inc/yvals_core.h
tests/std/tests/GH_000431_equal_memcmp_is_safe/test.compile.pass.cpp
tests/std/tests/P0088R3_variant/test.cpp
tests/std/tests/P0220R1_optional/test.cpp
tests/std/tests/P0896R4_ranges_algorithm_machinery/test.compile.pass.cpp
tests/std/tests/P0896R4_ranges_range_machinery/test.cpp

* Fix comment typos.
* Drop comment `// inspected by GSL, do not remove`.
+ This is no longer necessary after microsoft/GSL#822.
* Comments: `C++23 / C++20` => `_HAS_CXX23 / !_HAS_CXX23`
+ This is more conventional and more accurately descriptive.
* Comments: Replace weird `_HAS_CXX23` comments with conventional ones.
* Comments: Replace weird `^^ real test / vv workaround` comments with conventional ones.
* Comments: In `yvals_core.h`, drop most comments around "macros with language mode sensitivity".
+ This eliminates one last occurrence of `^^^ C++23 / C++20 vvv`. We were pretty inconsistent about the patterns here, and these comments were distracting from the actually useful paper citations. The regions here are all single line, so it's okay to skip preprocessor comments. The only …

Comment cleanups

---

tests/std/include/is_permissive.hpp
tests/std/include/range_algorithm_support.hpp
tests/std/include/test_mdspan_support.hpp
tests/std/tests/P0645R10_text_formatting_args/test.cpp
tests/std/tests/P0896R4_ranges_algorithm_machinery/test.compile.pass.cpp
tests/std/tests/P0898R3_concepts/test.cpp
tests/std/tests/P2136R3_invoke_r/test.cpp
tests/std/tests/VSO_0000000_type_traits/test.cpp

We've accumulated a bunch of test files copy-pasting the machinery used to detect `/permissive` mode. Let's centralize it.
This is based on `test_mdspan_support.hpp`, with `namespace details` renamed to `namespace detail` (see below). Its `PermissiveTestBase` and `PermissiveTest` were nicely named, and it was using `inline constexpr bool`. Also add `is_permissive_v<T>`, when we need it to be dependent on a template parameter. We need to include `<yvals_core.h>` for `_INLINE_VAR`, since there's some C++14 usage.
`test_mdspan_support.hpp`: Drive-by change, this file had both `namespace details` and `namespace detail`. Standardize on the latter, as it's used everywhere else.
`P2136R3_invoke_r`: `// TRANSITION, DevCom-1457457` is repeated where `is_permissive` is used, so we can drop the one …

Tests: Extract `is_permissive.hpp`

---

benchmarks/inc/utility.hpp
benchmarks/inc/xoshiro.hpp
tests/std/tests/Dev09_172497_tr1_mem_fn_const_correctness/test.cpp
tests/std/tests/Dev09_174589_tr1_function_storing_pmf_called_with_reference_or_pointer/test.cpp
tests/std/tests/P0088R3_variant/test.cpp

* Overhaul FDIS citation and extend test coverage for `std::function` PMFs/PMDs.
+ FDIS citations were so old, they escaped our scans for outdated WPs. We don't need to quote `INVOKE`'s Standardese at length, we just need to summarize it. It used to be really confusing, now it's easy mode.
+ A couple of things have changed: derived values are now covered by the Standardese, and `reference_wrapper` support was added. This is tested elsewhere, e.g. in `Dev11_0535636_functional_overhaul`, but we can easily add comprehensive test coverage here.
+ I chose `f1x` and `g1x` to avoid renumbering everything.
* Update FDIS citations and add test coverage for `mem_fn` typedefs.
+ These typedefs were deprecated in C++17 and removed in C++20, so I'm citing WG21-N4659, the C++17 WP.
+ We were also …

Expand old test coverage

---

stl/inc/__msvc_bit_utils.hpp
stl/inc/algorithm
stl/inc/xutility
stl/inc/yvals_core.h

* In `_Popcount_fallback()`, after `if constexpr ... return` add `else` to avoid dead code.
+ We always follow this convention for `if constexpr`.
* Remove unnecessary `_STD` qualification on types, variable templates, and alias templates.
+ This became possible after my #4146 moved these functions into `namespace std`.
* `yvals_core.h`: Improve "error STL1003: Unexpected compiler, expected C++ compiler." like #4020.
+ Then we can move `_STL_STRINGIZE` down to its point of use, near our other macros.
+ Result:
```
D:\GitHub\STL\out\x64>type woof.c
D:\GitHub\STL\out\x64>cl /EHsc /nologo /W4 /c woof.c
woof.c
D:\GitHub\STL\out\x64\out\inc\yvals_core.h(23): fatal error C1189: #error:  error STL1003: Unexpected compiler, expected C++ compiler.
```

Various cleanups: product code

---

stl/src/ppltasks.cpp

I've validated this with an internal build and test run. I know there's not a lot of value in cleaning up old `src` files, but this eliminates some complexity and I believe it's safe.
* `RtlCaptureStackBackTrace` is universally available.
+ It might not have been when this was originally implemented, but it's now [documented](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-rtlcapturestackbacktrace) as "Target Platform: Universal", and this aligns with its actual declaration.
* Move `GUID` into `Concurrency::details` within `#if defined(_CRT_APP) || defined(UNDOCKED_WINDOWS_UCRT)`.
+ It's `static`, so there's no ABI impact.
* We don't need `<mutex>` - only `<functional>` for `std::function` and `<stdexcept>` for `std::runtime_error`.
* Drop "ASYNC TODO" …

Various cleanups: `ppltasks.cpp`

---

stl/src/vector_algorithms.cpp
tests/std/tests/VSO_0000000_vector_algorithms/test.cpp

Fixes #4449.
For unsized `ranges::find`, `vector_algorithms.cpp` reads elements "before the beginning", although (hopefully) not in a way that annoys memory page protection or ASAN. Then we "we mask out matches that don't belong to the range", pretending that they weren't there. This allows us to use vectorized loads for the entire unbounded loop, instead of starting with classic scalar code until we get to a nicely-aligned boundary.
However, we had a control flow bug. We started with "load" a vector chunk, "mask" away matches before the beginning, "check" if we found anything (and return if so). Then we started our infinite loop: `for (;;) { load; check; advance; }`. But this repeated the initial load and check, *without the mask!* It was also unnecessary extra work.
A minimal …

Fix vectorized `ranges::find` with `unreachable_sentinel` to properly mask the beginning and handle unaligned pointers

---

stl/inc/regex

In general, the STL cannot avoid all stack overflows. (We don't know how much stack has been consumed when the user calls us, so thinking *any* thoughts might be too much.) However, `<regex>` tries to throw exceptions instead of stack overflowing due to excessive recursion. We've had a long-standing struggle with exactly where to set this threshold during matching; right now our threshold detects most potential overflows before they happen, but not all.
However, we don't do anything during regex *construction*. It turns out that requesting an excessive number of capture groups can easily trigger a stack overflow. We even had commented-out legacy code, indicating that our predecessors thought about this scenario somewhat. This PR adds a hardcoded limit arbitrarily set at 1000, which is …

`<regex>`: Limit capture groups

---

stl/inc/generator
stl/inc/ranges
tests/std/tests/P2502R2_generator/test.cpp

Towards #2936.
Per the synopsis in [[coro.generator.class]](https://eel.is/c++draft/coro.generator.class), the _`iterator`_ and `promise_type` types are non-template classes, so they should be ADL-proof even if the enclosing `generator` specialization is ADL-incompatible. `_Nested_awaitable` is also changed to a nested non-template class to make `generator<holder<incomplete>*>` yieldable.
`_Promise_allocator` is currently unchanged because _Cpp17Allocator_ essentially requires allocator types to be ADL-compatible. Perhaps we should change it to a member marked with `[[msvc::no_unique_address]]` later.
Drive-by change: make the default template arguments of `elements_of` and its deduction guide conditionally present, which is consistent with `polymorphic_allocator`. …

`<generator>`: Make nested types of `generator` ADL-proof

---

stl/inc/coroutine
stl/inc/generator
tests/std/tests/P2502R2_generator/test.cpp

My apologies for the grab-bag PR (slightly excusable for a feature branch).
This starts with trivial followups to #4464, then addresses pre-existing issues that I found:
* `std::` => `_STD`
* Include `<cstddef>` for `std::nullptr_t`.
* Extract a verbose immediately-invoked lambda for clarity.
* Bugfix: Use `__stdcall` to make `<generator>` immune to default calling conventions.
+ We must always do this when mentioning function pointer types in headers.
* Scalar `constexpr size_t _Align` doesn't need to be `static`.
* Fix unintentional move from `const _Alloc&`.
+ This is now consistent with the other occurrence of `auto& _Stored_al`.
* Consistently use `_RANGES`.
* `_Promise` => `_CoroPromise` to avoid intolerable shadowing of `<future>`.
+ I clearly missed this in the shipping …

`<generator>`: Various fixes and cleanups

---

stl/inc/flat_map
tests/std/include/test_header_units_and_modules.hpp
tests/std/tests/P0429R9_flat_map/test.cpp

Towards #2910. Addresses review comments in #4337 and #4386.
Style cleanups:
- Eliminate redundant parentheses.
- Use `it[-1]` instead of `*(it - 1)`.
- Add some `const`. Not yet to iterators due to moving.
- Eliminate most `if {/*...*/ return; } else {/*...*/}`, except when returning `end()`/`cend()` in `else`.
Bug fixes:
- Use direct-non-list-initialization.
- Avoid calling `distance` on non-forward input iterators.
- Fix iterator dereferencing in insertion.
Drive-by consistency changes:
- Make the default (template) arguments of deduction guides relying on `allocator<byte>` conditionally present, which is consistent with `polymorphic_allocator`. The behavior should be unchanged (modulo the existence of `byte`) when `__cpp_lib_byte` is not defined.
Performance improvements:
- …

`<flat_map>`: Various cleanups and bug fixes

---

stl/CMakeLists.txt
stl/inc/__msvc_chrono.hpp
stl/inc/__msvc_threads_core.hpp
stl/inc/condition_variable
stl/inc/header-units.json
stl/inc/mutex
stl/inc/thread
stl/inc/xthreads.h
stl/src/cond.cpp
stl/src/mutex.cpp
stl/src/primitives.hpp
stl/src/sharedmutex.cpp
tests/std/tests/GH_001411_core_headers/test.cpp

Fix #718
Possibly create chaos (I hope not).
I made new core header, since making `<xthreads.h>` non-core looked hard.
Thanks @achabense for the first step in this direction.

Wait on condition variables independently on system time

---

stl/inc/format

We've been enabling compiler-time format string checking for self-synchronizing execution character sets (see #2221 and #2493). 
However, when the character type is `wchar_t`, the checking may also be skipped for certain execution character sets ([Godbolt link](https://godbolt.org/z/oh1K3fPcq)), although, IIUC, the supported execution _wide_ character set should always be Unicode and MSVC STL only supports `wchar_t` of the UTF-16 encoding.
This PR unconditionally enables compiler-time format string checking when the character type is `wchar_t` (or is not `char`, if formatting for `charN_t` is supported in the future).

`<format>`: Always enable compile-time format string checking for `wchar_t`

---

stl/inc/format

Fixes #4202.
Also adds `static_assert` messages in the constructor body of `basic_format_arg::handle`, and moves the `static_assert`s into the lambda body.
Currently, Clang emits 2 `static_assert` failures for such an error, one in `make_(w)format_args`, one in the `handle` ctor. Because lack of `formatter` specialization or `const` on `format` can trigger `static_assert` failure in the constructor body of `basic_format_arg::handle` now.
This PR slightly worsens the error messages for Clang (2 similar `static_assert` messages will be emitted). However, it seems that cleaner error messages can be achieved by conditional compilation (skipping `static_assert`s in `make_(w)format_args` for Clang).

`<format>`: Conditionally emit special diagnostic message for lack of `const`

---

stl/inc/ranges

`<ranges>`: Drop one superfluous `_Fake_copy_init<bool>` where the argument type is always `bool`

---

tools/unicode_properties_parse/download_unicode_data_files.py

Followup to #4435, addressing @tahonermann's https://github.com/microsoft/STL/pull/4435#discussion_r1518638817.
Usage examples:
```
D:\GitHub\STL\tools\unicode_properties_parse>python download_unicode_data_files.py
Usage: python download_unicode_data_files.py [latest|<VERSION LIKE 15.0.0>]
D:\GitHub\STL\tools\unicode_properties_parse>python download_unicode_data_files.py x y
Usage: python download_unicode_data_files.py [latest|<VERSION LIKE 15.0.0>]
D:\GitHub\STL\tools\unicode_properties_parse>python download_unicode_data_files.py latest
Base URL: https://unicode.org/Public/UCD/latest/
Downloading: https://unicode.org/Public/UCD/latest/ucd/DerivedCoreProperties.txt
Downloading: https://unicode.org/Public/UCD/latest/ucd/extracted/DerivedGeneralCategory.txt
Downloading: …
```

`download_unicode_data_files.py`: Select latest or a specific version

---

stl/inc/xstring

... to silence `-d1initall`'s complaint.
Fixes #4473

Initialize pointer in `basic_string::_Allocate_for_capacity`

---

stl/inc/yvals.h

This fixes DevCom-10610863 "Importing module std warns on signed/unsigned mismatch" (internal VSO-1992367 / AB#1992367 ).
The problem was that the [`/ZI` compiler option](https://learn.microsoft.com/en-us/cpp/build/reference/z7-zi-zi-debug-information-format?view=msvc-170) (debug info for Edit and Continue) messes with `__LINE__`, making it a variable of type `long` instead of an integer literal. This variable can emit sign conversion warnings when passed to functions taking unsigned types (whereas integer literals don't, regardless of their type, because the compiler can directly see that the value is unaffected).
The fix is to `static_cast<unsigned int>`, matching what [`_invalid_parameter()`][invalid_parameter_and_invoke_watson] takes.
[invalid_parameter_and_invoke_watson]: …

Standard Library Modules: Fix warning C4365 (signed/unsigned mismatch) with `/ZI`

---

stl/inc/tuple
stl/inc/utility
tests/std/tests/Dev11_0000000_tuple_cat/test.cpp

Towards #140. These functions are made ADL-proof:
- `pair`'s piecewise constructor,
- `tuple_cat`,
- `apply`, and
- `make_from_tuple`.
Drive-by change:
- Include `<cstddef>` for `size_t` in `Dev11_0000000_tuple_cat/test.cpp` (the use of `size_t` is pre-existing).
There're some `tuple`-related unqualified internal function calls in `<ranges>`. I'll do the cleanup in another PR.
This PR also largely reorganizes `Dev11_0000000_tuple_cat/test.cpp` (by splitting the original `main` into several functions) to test `constexpr`-friendliness.

`<tuple>`, `<utility>`: Make `tuple`-related functions ADL-proof

---

stl/inc/format
tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp

Notes:
- `handle`'s constructor is exposition only and private in the standard wording ([[format.arg]/10](https://eel.is/c++draft/format.arg#10)), so at least the constructor shouldn't be callable from user code. Removing `static_assert` messages due to this.
- ~~The standard wording seemingly leaves special member functions of `basic_format_context` implicitly declared ([[format.context]](https://eel.is/c++draft/format.context)), which means that its default constructor should be declared and defaulted.~~
- Internal non-Standard constructors of `basic_format_context` are changed to take references to avoid double copy/move.
- Now constructions of `basic_format_arg`, `handle`, and `basic_format_context` are consistently performed by `_Make_from` static member functions, and `_Make_from` …

`<format>`: Make non-Standard constructors of `basic_format_arg::handle` and `basic_format_context` private

---

stl/src/vector_algorithms.cpp

Use `else` instead of early return

`vector_algorithms.cpp`: clearer control flow in `bitset::to_string`

---

tests/libcxx/expected_results.txt

Followup to the VS 2022 17.10 Preview 2 toolset update #4475.
This toolset fixed VSO-1875597 "\[ASAN\]\[STL\] Interception breaks strtol: TEST 'libc++ std/strings/string.conversions/stol.pass.cpp:1' FAILED". @CaseyCarter explained the bug:
> The implementation of `std::stol` expects `::strtol` to set `errno` to `ERANGE` when given an unrepresentable input, which it does normally, but not with ASAN
We can now un-skip the affected test.
(We missed a few opportunities to discover this during the toolset update; I should have run ASAN, etc. I'll try to improve our development practices in the future.)

libcxx `stol.pass.cpp` is now passing for ASAN

---

stl/inc/generator
tests/std/test.lst
tests/std/tests/P2502R2_generator_promise/env.lst
tests/std/tests/P2502R2_generator_promise/test.cpp

* Add tests for `generator::promise_type`
* Fix issues detected by new tests:
* `generator::promise_type::initial_suspend` should be marked with `const`
* Add missing `generator::yielded` type alias
* Ad hoc: add `static_cast`s in `_Promise_allocator` since custom allocator's `size_type` might be smaller than `size_t`

`<generator>`: Test `generator::promise_type`

---

stl/inc/xstring
tests/std/tests/P0220R1_string_view/test.cpp

Fixes #4500.
Tests whether `std::type_identity_t` is exactly used, see #4249.

Implement LWG-3950 `std::basic_string_view` comparison operators are overspecified

---

stl/inc/ranges
tests/std/tests/P2164R9_views_enumerate/test.cpp

Implement LWG-3919 `enumerate_view` may invoke UB for sized common non-forward underlying ranges

---

stl/inc/yvals_core.h
tests/std/test.lst
tests/std/tests/GH_004477_mdspan_warning_5246/env.lst
tests/std/tests/GH_004477_mdspan_warning_5246/test.compile.pass.cpp

Add an STL-wide suppression for C5246

---

stl/inc/ranges
tests/std/tests/P0896R4_views_common/test.cpp

Implement LWG-4012 `common_view::begin`/`end` are missing the `simple-view` check

---

stl/inc/xpolymorphic_allocator.h
stl/inc/yvals_core.h
tests/std/tests/P0220R1_polymorphic_memory_resources/test.cpp

Fixes #4521. Also makes MSVC STL's `polymorphic_allocator::destroy` reject arrays (which is implicitly required by the standard wording).

Implement P2875R4 Undeprecate `polymorphic_allocator::destroy`

---

stl/src/vector_algorithms.cpp

Followup to #4495.
The usage of `_Avx2_tail_mask_32()` is always guarded by `#ifndef _M_ARM64EC`, and we need to do the same for the definition. (It's still within an unnamed namespace.)
I'm adding a newline to make the preprocessor structure of the file clearer.

`vector_algorithms.cpp`: Fix ARM64EC build break

---

azure-devops/create-1es-hosted-pool.ps1

This mirrors MSVC-PR-539935, which @joemmett will be merging into MSVC `main`.
New codebase scanning tools are hissing at how `create-1es-hosted-pool.ps1` builds up a plaintext password before converting it into a `SecureString` with `ConvertTo-SecureString`.
Jonathan's fix is to start with a `SecureString` and build it up character-by-character. Of course, this still leaves each character in normal memory for a fraction of a nanosecond, but that's unavoidable. This avoids mentioning `ConvertTo-SecureString`, thereby making the tools happy. Later in this script, we redact the generated password from appearing in any console output (my innovation back in #1577), and we discard it entirely after creating the pool, so we're touching it as little as possible.
I verified that the updated …

`create-1es-hosted-pool.ps1`: Avoid `ConvertTo-SecureString`

---

tests/std/test.lst
tests/std/tests/P2502R2_generator_death/env.lst
tests/std/tests/P2502R2_generator_death/test.cpp

`<generator>`: Add death tests

---

stl/inc/ranges
tests/std/tests/P1206R7_ranges_to_misc/test.cpp

Fixes #4504.
Notes:
- the call to `ranges::for_each` in the proposed resolution is "manually inlined" to avoid inclusion dependency;
- the Standard requires `<ranges>` to include `<concepts>`, so the test code doesn't explicitly include it.

Implement LWG-4016 `container-insertable` checks do not match what `container-inserter` does

---

stl/inc/ranges
tests/std/tests/P2474R2_views_repeat/test.cpp

Fixes #4508.
Drive-by changes: add previously missing titles of GH/LWG issues to comments.

Implement LWG-4054 Repeating a `repeat_view` should repeat the view

---

stl/inc/ranges
tests/std/tests/P1206R7_ranges_to_sequence/test.cpp

Implement LWG-3984 `ranges::to`'s recursion branch may be ill-formed

---

stl/inc/algorithm
stl/inc/xutility
stl/src/vector_algorithms.cpp

Resolves #4531
(See somewhat-related #4453.)

Standardize vector algorithms dispatch

---

stl/inc/__msvc_threads_core.hpp
stl/inc/condition_variable
stl/inc/mutex
stl/src/cond.cpp
stl/src/primitives.hpp
stl/src/sharedmutex.cpp

Followup to https://github.com/microsoft/STL/pull/4457#issuecomment-1995780996. I performed this as a series of well-structured commits.
`primitives.hpp`: Include `__msvc_threads_core.hpp`.
This will allow us to move the definition of `_Cnd_internal_imp_t` into `__msvc_threads_core.hpp`.
This is a safe transformation because only 3 files include `primitives.hpp` and they already drag in `__msvc_threads_core.hpp` (`sharedmutex.cpp` directly; `cond.cpp` and `mutex.cpp` via `xthreads.h`).
---
In `_Cnd_internal_imp_t`, rename its `_Aligned_storage_t` data member `cv` to `_Cv_storage`.
This will allow us to move the definition into `stl/inc/__msvc_threads_core.hpp`.
The new name is consistent with how `_Mtx_internal_imp_t` names its `_Aligned_storage_t` data member `_Cs_storage`.
---
Change …

`<condition_variable>`: Avoid squirrelly forward declaration of `_Cnd_internal_imp_t`

---

stl/src/vector_algorithms.cpp

Resolves #4536
Also checked and improved where can take advantage of new assumptions:
* `_mm_set1_epi8` replaced with `_mm_shuffle_epi8` with zero input, slight improvement for 1-byte elements `find` and `count`
* Simplified and improved `__std_bitset_to_string_*`
* Used `_mm_shuffle_epi8` to populate a `__m128i` variable instead of the sequence
* Used `_mm_blendv_epi8` to avoid `xor`
Didn't measure the results. If measured on a modern machine, that would be artificial to alter `__isa_enabled`, and still not relevant.
Also removed SSE level of instructions from comments. Kept `__popcnt` comment though.

Manually vectorize for at least SSE4.2

---

stl/inc/ranges
tests/std/test.lst
tests/std/tests/P0896R4_views_drop_death/env.lst
tests/std/tests/P0896R4_views_drop_death/test.cpp
tests/std/tests/P0896R4_views_take_death/env.lst
tests/std/tests/P0896R4_views_take_death/test.cpp

`<ranges>`: Check and test preconditions for `take_view` and `drop_view`'s constructors

---

benchmarks/src/replace.cpp
stl/inc/algorithm
stl/inc/xutility
stl/src/vector_algorithms.cpp
tests/std/tests/VSO_0000000_vector_algorithms/test.cpp

AVX2 masks only
Before
```
---------------------------------------------------------------
Benchmark                     Time             CPU   Iterations
---------------------------------------------------------------
r<std::uint32_t>           2005 ns         1086 ns      1280000
r<std::uint64_t>           2107 ns         1247 ns       814545
```
After
```
---------------------------------------------------------------
Benchmark                     Time             CPU   Iterations
---------------------------------------------------------------
r<std::uint32_t>            173 ns         73.8 ns     19063830
r<std::uint64_t>            441 ns          178 ns      7466667
```

vectorize `replace` 🎭

---

stl/src/vector_algorithms.cpp
tests/std/tests/VSO_0000000_vector_algorithms/test.cpp

In benchmark results only the last line changed:
before
```
-----------------------------------------------------------------
Benchmark                       Time             CPU   Iterations
-----------------------------------------------------------------
bm<uint8_t, 2, 3>            2.70 ns         2.35 ns    597333333
bm<uint16_t, 2, 3>           2.71 ns         2.13 ns    689230769
bm<uint8_t, 7, 4>            14.1 ns         10.9 ns    112000000
bm<uint16_t, 7, 4>           12.4 ns         10.6 ns    100000000
bm<uint8_t, 9, 3>            9.77 ns         7.70 ns    190638298
bm<uint16_t, 9, 3>           10.4 ns         8.06 ns    162909091
bm<uint8_t, 22, 5>           10.1 ns         8.02 ns    208372093
bm<uint16_t, 22, 5>          11.0 ns         8.64 ns    151864407
bm<uint8_t, …
```

vectorize `find_first_of` for long needle 🪡

---

stl/inc/mdspan
tests/std/include/test_mdspan_support.hpp

* Use `conjunction_v` instead of fold expressions
* Drive-by: remove unnecessary lambda in `test_mdspan_support.hpp`

`<mdspan>`: Throughput improvements

---

stl/inc/algorithm
tests/std/tests/Dev11_0316853_find_memchr_optimization/env.lst
tests/std/tests/Dev11_0316853_find_memchr_optimization/test.cpp

Fix #4553
Add coverage, so that the test would fail without the fix.

Check if `find_last` can find anything

---

benchmarks/src/find_first_of.cpp
stl/inc/algorithm

Look for `/325/1` lines in the result:
Before:
```
---------------------------------------------------------------
Benchmark                     Time             CPU   Iterations
---------------------------------------------------------------
bm<uint8_t>/2/3            3.58 ns         2.47 ns    640000000
bm<uint8_t>/7/4            13.8 ns         11.8 ns     99555556
bm<uint8_t>/9/3            9.76 ns         7.25 ns    213333333
bm<uint8_t>/22/5           10.1 ns         8.79 ns    186666667
bm<uint8_t>/58/2           11.4 ns         10.2 ns    100000000
bm<uint8_t>/102/4          13.4 ns         11.9 ns    100000000
bm<uint8_t>/325/1          33.0 ns         27.6 ns     49777778
bm<uint8_t>/1011/11        94.6 ns         79.4 ns     19478261
bm<uint8_t>/3056/7          276 ns …
```

Optimize `find_first_of` for one element needle

---

azure-devops/config.yml

An unnecessary new script (we don't ship from this repository, so the checks in the Microsoft-internal repo suffice) auto-injected into our pipeline causing problems.

Skip Component Governance autodetection

---

stl/inc/queue
stl/inc/stack
stl/inc/stacktrace
stl/inc/yvals_core.h

As `flat_meow`s enter, the container-ness makes even less sense to distinguish nodiscard messages.

`<yvals_core.h>`: avoid using the 'container' word for something that has `empty()` member in `[[nodiscard]]` messages

---

stl/inc/__msvc_iter_core.hpp
stl/inc/tuple
stl/inc/variant

Fixes #4575 by aborting recursive instantiation using `if constexpr`.
Also reuses `_Meta_find_unique_index` for overloads for `tuple`.

`<tuple>`, `<variant>`: Make error messages from get-by-type functions clearer

---

tests/std/tests/P0429R9_flat_map/test.cpp

* construction from `sorted_equivalent`
* `test_erase_if`
* `test_pointer_to_incomplete_type`

`<flat_map>`: more `flat_multimap` coverage copied from `flat_map`

---

tests/std/include/test_generator_support.hpp
tests/std/test.lst
tests/std/tests/P2502R2_generator/test.cpp
tests/std/tests/P2502R2_generator_iterator/env.lst
tests/std/tests/P2502R2_generator_iterator/test.cpp
tests/std/tests/P2502R2_generator_promise/test.cpp

* Add tests for `generator`'s iterator type in separate `P2502R2_generator_iterator/test.cpp` file
* Add `test_generator_support.hpp` header
* Move
```c++
static_assert(sizeof(ranges::iterator_t<G>) == sizeof(void*));
```
test from `P2502R2_generator/test.cpp` to the new file.

`<generator>`: Test `generator::iterator`

---

stl/src/vector_algorithms.cpp

missed `vzeroupper` in `mismatch` and `replace`

---

stl/inc/__msvc_chrono.hpp
stl/inc/condition_variable
stl/inc/future
stl/inc/mutex
stl/inc/shared_mutex
stl/inc/thread

This PR generalizes #1687 to C++14/17 modes and reimplements `is_clock_v` with a `requires`-expression. Towards #602.
In [N4659 [time.point]/1](https://timsong-cpp.github.io/cppwp/n4659/time.point#1), the `Clock` template parameter was required to meet the Clock (_Cpp17Clock_ now) requirements. The requirement was changed by WG21-P0355R7 in C++20 and removed by WG21-P2212R2 in C++23.
All involved thread functions take a `time_point` parameter, so it was already invalid (probably UB) in C++11 to use these functions with an invalid `time_point` type. Static checking seems OK to me as we've been statically asserting `is_standard_layout_v` and `is_trivial_v` for `basic_string`.

Check `is_clock_v` for thread utilities before C++20

---

benchmarks/src/find_first_of.cpp
stl/inc/algorithm
stl/src/vector_algorithms.cpp

The specialized approach shuffles the needle so that every element is on every place and compares it with the haystack part. Then `or`s all comparison results to find the lowest index match, then if there's a match returns it.
The generic approach finds a haystack element in the needle, it is like `find` with reversed haystack/needle, but instead of `vpmovmskb` and checking that index and computing offset, we have `vptest`, as we don't need the index.
Looks like we will have way better results if specialized approach is generalized,, instead of having different and simpler generic approach. But the complexity would grow.
If only the generic approach is used, the complexity would be reduced, but the performance for small needles would be worse, the generic approach for small needles and …

Vectorize `find_first_of` for 4 and 8 byte elements

---

benchmarks/CMakeLists.txt
benchmarks/src/swap_ranges.cpp

```
-----------------------------------------------------------
Benchmark                 Time             CPU   Iterations
-----------------------------------------------------------
bm<uint8_t>/1          1.95 ns        0.854 ns    640000000
bm<uint8_t>/5          2.96 ns         1.44 ns    640000000
bm<uint8_t>/15         4.40 ns         2.00 ns    320000000
bm<uint8_t>/26         2.93 ns         1.26 ns    448000000
bm<uint8_t>/38         3.90 ns         1.59 ns    373333333
bm<uint8_t>/60         4.21 ns         1.96 ns    446008889
bm<uint8_t>/125        5.31 ns         2.51 ns    373333333
bm<uint8_t>/800        15.5 ns         6.70 ns     95573333
bm<uint8_t>/3000       75.1 ns         36.8 ns     18666667
bm<uint8_t>/9000        140 ns         69.8 ns     11200000
```
I actually …

`swap_ranges` benchmark

---

stl/inc/type_traits
tests/std/tests/Dev09_158457_tr1_mem_fn_calling_conventions/test.cpp
tests/std/tests/P0898R3_concepts/test.cpp

The documentation says "On ARM64EC, `__vectorcall` is unsupported and rejected by the compiler." I'm not sure why our usage isn't being rejected, but we have confirmation from the compiler team that ARM64 doesn't currently accept `__vectorcall` so we should avoid it.
Fixes #4596

Avoid `__vectorcall` on ARM64EC

---

stl/inc/yvals_core.h

There are three Microsoft extensions that we've deprecated, with the intent of eventually removing them:
* VS 2022 17.8: #3818
+ Patched by #3924
* VS 2022 17.9: #4006
* VS 2022 17.10: #4284
Currently, these deprecations are activated by C++17 mode, but there's no real justification for that. It was *practically* convenient, because leaving C++14 mode unaffected limited the source-breaking impact on legacy codebases that we immediately had to deal with. However, if we really want to remove this machinery, we need to warn C++14 users. Fortunately, some ecosystem cleanup has already occurred (e.g. Qt stopped using `stdext::checked_array_iterator` and backported that to their various release branches) since usage of C++17 and later is somewhat popular. Deprecating and removing things always …

Emit 'MS extension' deprecation warnings in all Standard modes

---

stl/inc/xhash
stl/inc/yvals_core.h
tests/tr1/tests/hash_map/test.cpp
tests/tr1/tests/hash_set/test.cpp

These member functions were unconditionally deprecated by MSVC-PR-181971 on 2019-05-23.
It's been *almost 5 years*, so it's time to remove this machinery now. Note that there is no loss of functionality - as the deprecation warnings advised, any calls can be exactly converted into `find()` or `equal_range()`.
We can remove the tr1 test coverage because we already have exactly equivalent coverage of `find()` and `equal_range()`.

Remove `lower_bound()`/`upper_bound()` from `hash_meow`/`unordered_meow`

---

stl/inc/ranges

- Extract the uses of `_Ref_converts` from the helper concepts.
- This matches the structure of [\[range.utility.conv.to\]/2](http://eel.is/c++draft/range.utility.conv.to#2).
- Provide more detailed error messages.
Closes #4562

`<ranges>`: Refactor `ranges::to`

---

stl/inc/ostream
stl/inc/print
stl/inc/yvals_core.h
tests/std/include/test_header_units_and_modules.hpp
tests/std/tests/P2093R14_formatted_output/test.cpp

Implements:  https://wg21.link/P3142R0 (Fixes GH-4524)
Applied retroactively as DR:
https://github.com/orgs/microsoft/projects/1143?pane=issue&itemId=57457187

P3142R0: Printing Blank Lines with `println`

---

stl/inc/xstring

As specified in [[char.traits.specializations]](https://eel.is/c++draft/char.traits.specializations), `char_traits::assign` should just perform assignments. #1502 made these functions also start lifetime of elements since C++20, but this is possibly wrong as the difference is theoretically observable due to lack of constant evaluation failure. This PR reverts changes of `char_traits::assign`.
Notes:
- #3334 (and following-up PR #4047) correctly made `basic_string` start lifetime of elements when required.
- After the changes, Clang behaves correctly but MSVC doesn't. DevCom-10642767 is reported for this.

`<xstring>`: Make `char_traits::assign` not start lifetime of elements

---

stl/src/vector_algorithms.cpp
tests/std/tests/VSO_0000000_vector_algorithms/test.cpp

Somewhat better in a long run, some pessimization for a short one.
Before:
```
----------------------------------------------------------------------------
Benchmark                                  Time             CPU   Iterations
----------------------------------------------------------------------------
bm<uint8_t, Op::Count>/8021/3056        97.4 ns         95.3 ns     10000000
bm<uint8_t, Op::Count>/63/62            3.86 ns         3.13 ns    194782609
bm<uint8_t, Op::Count>/31/30            9.98 ns         8.89 ns     89600000
bm<uint8_t, Op::Count>/15/14            5.00 ns         4.97 ns    144516129
bm<uint8_t, Op::Count>/7/6              3.08 ns         3.14 ns    248888889
bm<uint16_t, Op::Count>/8021/3056        198 ns          193 ns      3733333
bm<uint16_t, …
```

Improve `count` vectorization: replace `popcnt` implementation with vector counting

---

stl/inc/cmath
stl/inc/complex
stl/inc/numeric
stl/inc/type_traits
stl/inc/xutility

Towards #3599.
- Move `_Float_abs_bits`, `_Float_abs`, `_Is_nan`, and `_Is_finite` to `<type_traits>` to avoid including `<xutility>` in `<cmath>`.
- However, throughput may be slightly damaged when `<cmath>` is not included.
- Move `_Is_signaling_nan` and `_Is_inf` to `<complex>` as they are not used elsewhere.
- Remove `_Float_copysign` as it's unused.
- Reimplement `_Floating_max` and `_Floating_min` in a consistent way.

Move `_Floating_type_traits`-related functions

---

stl/inc/ranges
tests/std/tests/P0896R4_views_iota_death/test.cpp

Fixes #4586.
Also completes precondition checking for [[range.iota.view]/10](https://eel.is/c++draft/range.iota.view#10), and adds some previous missed comments `// _CONTAINER_DEBUG_LEVEL > 0`.

`<ranges>`: Consistently check preconditions for `iota_view` and `_Counted_fn`

---

stl/src/vector_algorithms.cpp

Before:
```
---------------------------------------------------------------
Benchmark                     Time             CPU   Iterations
---------------------------------------------------------------
bm<uint32_t>/2/3           3.11 ns         2.12 ns    640000000
bm<uint32_t>/7/4           13.8 ns         10.3 ns    154482759
bm<uint32_t>/9/3           4.29 ns         3.07 ns    448000000
bm<uint32_t>/22/5          8.13 ns         5.90 ns    235789474
bm<uint32_t>/58/2          5.70 ns         4.01 ns    358400000
bm<uint32_t>/102/4         12.3 ns         8.57 ns    165925926
bm<uint32_t>/325/1         26.8 ns         19.5 ns     68923077
bm<uint32_t>/1011/11       1035 ns          643 ns      2357895
bm<uint32_t>/3056/7         542 ns          337 ns      3895652
bm<uint64_t>/2/3 …
```

`find_first_of` vectorized: generalize fast approach for 4 and 8 bytes elements

---

stl/inc/algorithm
stl/inc/bit
stl/inc/chrono
stl/inc/compare
stl/inc/functional
stl/inc/ranges
stl/inc/tuple
stl/inc/variant
stl/inc/vector
stl/inc/xlocnum
stl/inc/xmemory
stl/inc/xutility

Followup to #4591.
This was prompted by VSO-2045281 "\[RWC\]\[prod/fe\]\[Regression\] Taichi and Root failed with error G030630B7: static assertion failed: Unexpected size", although it doesn't attempt to completely fix those failures in our Real World Code test suite. (It appears that these projects are using unsupported compilers - i.e. non-MSVC/Clang/CUDA/IntelliSense - to parse our STL headers, and these compilers haven't implemented CWG-2518.)
Some occurrences of `static_assert(false, "message")` are enforcing requirements for users, providing nice messages (ideally with Standard citations). However, many occurrences were checking for "can't happen" scenarios, i.e. damaged logic in the STL itself. We should use `_STL_INTERNAL_STATIC_ASSERT` for such checks, as this clearly …

Use `_STL_INTERNAL_STATIC_ASSERT(false)` when appropriate

---

stl/inc/exception
stl/modules/std.ixx

Fixes DevCom-10643328 VSO-2045649 "VS17.10-preview4 C++ Modules `import std;` fails to compile if `boost::unordered::unordered_hash_map` member of type also imported" which emitted:
```
[...]\emmintrin.h(298): error C2733: '_mm_cmpeq_epi8': you cannot overload a function with 'extern "C"' linkage
```
The root cause was that the STL drags in `<intrin.h>` (in whole or in part), and it defines a few types outside of `extern "C"` or `extern "C++"`. This causes them to be attached to the `std` module, which we don't want. (I missed this in #4154.) The fix is to include `<intrin.h>` in the Global Module Fragment.
* I've manually verified the fix with the provided Boost-powered repro. This resisted my attempts at reduction, so I think manual testing with a source comment is sufficient.
* To …

Fix `import std;` interaction with `<intrin.h>` emitting bogus error C2733

---

stl/inc/algorithm

As the use of `_Iter_value_t` appeared within the implementation details of C++20 `ranges::stable_sort`, it should be replaced with `iter_value_t`.
See also https://github.com/microsoft/STL/issues/4436#issuecomment-1981978127 - this should be the only occurence of `_Iter_value_t` that "Should always be C++20 `iter_value_t`".

`<ranges>`: Replace one improper use of `_Iter_value_t` with `iter_value_t` in `_Stable_sort_fn`

---

stl/inc/exception

In #4626, I was a greedy kitty and added a one-line throughput improvement to make `<exception>` stop dragging in `<malloc.h>`, which it totally doesn't need.
Unfortunately, as `<exception>` is an ancient header, many projects have grown to assume this inclusion (over 15 found in our Real World Code test suite alone as reported by VSO-2048380; other codebases like Windows and Office are presumably similarly affected). That's too many for me to submit upstream fixes for, at least right now, and I didn't have a pressing need to make this change (unlike, say, increased deprecations where we're working towards removal). I did create chriskohlhoff/asio#1472 to fix Boost.Asio, though.
I want to revert this drive-by cleanup before 17.11 Preview 2 branches for release, so that no customers will …

Restore `<exception>`'s inclusion of `<malloc.h>`

---

stl/inc/generator
stl/inc/ranges
stl/inc/xmemory

This improves inclusion time of `<generator>`.
`generator.cpp`:
```c++
#include <generator>
```
Before:
```term
PS D:\stl-playground> cl /std:c++latest /Bt /nologo .\generator.cpp /Zs
generator.cpp
time(C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.40.33721\bin\HostX64\x64\c1xx.dll)=0.514s
```
After:
```term
PS D:\stl-playground> cl /std:c++latest /Bt /nologo .\generator.cpp /Zs
generator.cpp
time(C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.40.33721\bin\HostX64\x64\c1xx.dll)=0.257s
```

`<generator>`: Don't include `<ranges>`

---

stl/inc/generator
tests/std/tests/P2502R2_generator_promise/test.cpp

`_Promise_allocator<void>`'s `operator new(size_t)` is specified to allocate memory with `allocator<_Aligned_block>` (see [[coro.generator.promise]/17](http://eel.is/c++draft/coro.generator#promise-17)), which internally uses `::operator new`, not `::operator new[]` (see [[allocator.members]/5](http://eel.is/c++draft/default.allocator#allocator.members-5)).

`<generator>`: Don't use `operator new[]` and `operator delete[]`

---

stl/inc/generator
tests/std/tests/P2502R2_generator/test.cpp

Merge `promise_type::_Top` and `promise_type::_Info` into single `promise_type::_Data` member of type `uintptr_t`.

`<generator>`: An attempt to merge `_Top` and `_Info`

---

stl/inc/flat_map
tests/std/tests/P0429R9_flat_map/test.cpp

Also
- move-construct underlying iterators in the constructors of `flat_(multi)map`'s iterators;
- fix and test `flat_(multi)map`'s comparison;
- remove possibly pessimizing `reserve`, with signedness adjusted; and
- simply `vector<T, allocator<T>>` to `vector<T>`.
Address review comments in #4468; towards #2910.

`<flat_map>`: Unwrap `flat_(multi)map`'s iterators

---

stl/inc/format
tests/std/tests/P2286R8_text_formatting_escaping_legacy_text_encoding/test.cpp
tests/std/tests/P2286R8_text_formatting_escaping_utf8/test.cpp
tests/std/tests/P2286R8_text_formatting_tuple/test.cpp

Currently, the tuple formatter uses `static_cast<int>(_Tmp_buf.size())` to compute the width of output (in order to determine the number of fill characters to insert). This gives the wrong width if
1. The output contains multibyte Unicode characters, or
1. `_Tmp_buf.size()` is larger than `INT_MAX` (see #4479).
Both problems can be avoided by using [`_Measure_string_prefix`](https://github.com/microsoft/STL/blob/0515a05b394596de92d08cb0f352614479a2a883/stl/inc/format#L3343-L3383), which computes the display width and clamps the result to `INT_MAX` (which means no fill character will be inserted).
Closes #4479
While working on this, I noticed that the tuple formatter test uses `\u00d6` which cannot be represented in some legacy text encodings. This PR adjusted the test to make it …

Measure display width in tuple formatter

---

stl/inc/__msvc_int128.hpp
stl/inc/algorithm
stl/inc/bitset
stl/inc/chrono
stl/inc/deque
stl/inc/execution
stl/inc/filesystem
stl/inc/format
stl/inc/forward_list
stl/inc/functional
stl/inc/istream
stl/inc/limits
stl/inc/list
stl/inc/mdspan
stl/inc/regex
stl/inc/semaphore
stl/inc/spanstream
stl/inc/utility
stl/inc/vector
stl/inc/xhash
stl/inc/xlocnum
stl/inc/xmemory
stl/inc/xstring
stl/inc/xtr1common
stl/inc/xtree
stl/inc/xutility
tests/libcxx/expected_results.txt

Based on #4627 fixup that extracts `_In_range`.
This also makes some place directly using `_In_range`, but mostly `_Max_limit` is used.

Refactor `<limits>` usage

---

stl/inc/algorithm
stl/inc/bit
stl/inc/chrono
stl/inc/cmath
stl/inc/compare
stl/inc/functional
stl/inc/memory
stl/inc/numeric
stl/inc/span
stl/inc/sstream
stl/inc/stop_token
stl/inc/thread
stl/inc/type_traits
stl/inc/xmemory
stl/inc/xutility

Notes:
- Helper concepts are introduced to avoid constraints mismatch in forward declarations.
- `is_same_v` is not replaced with `same_as` since the latter checks twice.
- Containers, `tuple`, `pair`, and `zoned_time` are not yet touched. I think they should handled in concentrated following-up PRs.
MSVC is buggy on detection of forming an invalid reference type to a cv-/ref-qualified function type in a `requires`-expression. Reported DevCom-10648215.
Towards #602.

Use `requires`-clauses and concepts for miscellaneous C++20/23 components

---

stl/inc/format
tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp

Fixes #4636. Also fixes the runtime behavior - both output line in the reported example should be `arg-id: 1, arg-id: 3`.
I've verified that the example posted in #4078 still fails to compile (when using `/utf-8` or a `wchar_t` variant). But I don't know how to test such error in the test suits of MSVC STL.

`<format>`: Fix handling of replacement field when format-spec is absent

---

benchmarks/src/iota.cpp
stl/inc/numeric

Help the compiler vectorize `ranges::iota`

---

tests/std/tests/Dev09_056375_locale_cleanup/test.cpp

Avoid triggering VSO-2046190 in `Dev09_056375_locale_cleanup` by leaving the DLL loaded in ASan instrumented statically-linked configs.
This test is failing with 17.10p5 and current dev compilers, I suspect due to a change in the ASan runtime's interception of `memcpy`. Recall that `memcpy` is part of VCRuntime, so statically-linked configs of this test have a copy of `memcpy` linked to the program and another copy of `memcpy` linked into the DLL. When the program unloads the DLL, I believe the ASan runtime's "pointer to actual memcpy" is left pointing into unallocated space where the DLL's copy used to be.
I'm going to disable unloading the DLL for this case to avoid the problem until we can implement and ship a fix.

Avoid triggering ASan bug in `Dev09_056375_locale_cleanup`

---

stl/inc/yvals_core.h

Fix #4645 Update _MSVC_STL_UPDATE to May 2024

Update _MSVC_STL_UPDATE to May 2024

---

tests/std/tests/VSO_0000000_vector_algorithms/test.cpp

Before this change the mismatch and lex compare test consumed more time than all other tests in vector algorithms test combined.
Done the following:
* Reused lgk mismatch result in lgk lex compare
* Reduced the number of random mismatches

Reduce `mismatch` test run time

---

stl/src/vector_algorithms.cpp

This: piece
https://github.com/microsoft/STL/blob/8dc4faadafb52e3e0a627e046b41258032d9bc6a/stl/src/vector_algorithms.cpp#L1116-L1123
works around the oddity of not having `_mm_cvtsi128_si64` on 32-bit x86
It has been problematic:
* An internal bug was reported; fixed by #2821 
* A compiler bug was caught, it blocked #3922
I have discovered a nicer workaround!
If we spill the reg into the stack, the spill will optimize away. 
On 32-bit with at least `/arch:SSE2` it even produces better code than the existing workaround.
Demo: https://godbolt.org/z/ErGWz8GYT
It still does the actual spill on `/arch:IA32`. But given that this path is executed only once per function call (there are no intermediate reductions for 64-bit elements), and there's a plan to lift to `/arch:SSE2`, I think that's …

`vector_algorithms.cpp`: `minmax` for 64-bit elements: replace ugly x86 workaround with a nice one

---

benchmarks/src/std_copy.cpp

See
https://google.github.io/benchmark/user_guide.html#templated-benchmarks
>  C++11 or newer, you can use the BENCHMARK macro with template parameters:
Related issue #4592

Use `BENCHMARK` macro for template benchmarks

---

stl/inc/expected
tests/std/tests/P0323R12_expected/test.cpp

Works around DevCom-10655311. The reason of the issue seems to be that MSVC cannot recognize the injected-class-name as a template name in associated constraints in inherited constructors.
The workaround seemingly works with `/permissive` so there wouldn't be stealing conflicts with #4658, AFAIK.

`<expected>`: Workaround for DevCom-10655311 "Class derived from `std::expected` can't be constructed with `bool` value type"

---

stl/inc/ranges
tests/std/tests/P2474R2_views_repeat/test.cpp

Fix #4507: LWG-4053 Unary call to std::views::repeat does not decay the argument

---

stl/inc/atomic
tests/std/tests/Dev11_0863628_atomic_compare_exchange/test.cpp
tests/std/tests/P0019R8_atomic_ref/test.cpp

Fixes #4688.
It seems intentional that `atomic(_ref)<T*>` are SFINAE-friendly on atomic pointer arithmetic. So this PR adds another mediate base class to avoid breaking the SFINAE-friendliness.
Also updates the comments in `Dev11_0863628_atomic_compare_exchange/test.cpp` to cite WG21-N4981.

`<atomic>`: Add member `difference_type` to `atomic<void*>` and its friends

---

tests/libcxx/expected_results.txt

- `std/atomics/atomics.types.operations/atomics.types.operations.wait/atomic_notify_all.pass.cpp`
- The timing assumption has been removed by https://github.com/llvm/llvm-project/commit/b3b611fe1a2f41e3e3ccf294c3fd9b1316e70c4d and https://github.com/llvm/llvm-project/commit/e98195f318375978e3e0b153cade8bb3a05029bb.
- `std/thread/thread.mutex/thread.lock/thread.lock.guard/adopt_lock.pass.cpp`
- The timing assumption has been removed by https://github.com/llvm/llvm-project/commit/a675c1dee483129611794f37e0867f565181827b.
- `std/thread/thread.mutex/thread.lock/thread.lock.guard/mutex.pass.cpp`
- The timing assumption has been removed by https://github.com/llvm/llvm-project/commit/a675c1dee483129611794f37e0867f565181827b.
- `std/thread/thread.threads/thread.thread.class/thread.thread.destr/dto …

Tests: un-skip a few libc++ tests that were believed to have timing assumptions

---

tests/libcxx/expected_results.txt
tests/libcxx/magic_comments.txt
tests/std/tests/P0088R3_variant/test.cpp
tests/utils/stl/test/features.py
tests/utils/stl/test/tests.py

* This updates our llvm-project submodule for the first time in 4 months. Previously:
+ #4263
+ #4348
* To make this possible, I had to fix the following things upstream:
+ llvm/llvm-project#93255
+ llvm/llvm-project#93257
+ llvm/llvm-project#93259
* Tons of things have been fixed upstream, allowing us to remove many expected failures and update comments:
+ llvm/llvm-project#77948
+ llvm/llvm-project#79978
+ llvm/llvm-project#79856
+ llvm/llvm-project#83734
+ llvm/llvm-project#74534
+ llvm/llvm-project#88669
+ llvm/llvm-project#90981
+ llvm/llvm-project#88998
+ llvm/llvm-project#74630
+ llvm/llvm-project#79793
* libcxx replaced old Features with 'has-1024-bit-atomics' (and unconditional Features should be defined in features.py instead of tests.py):
+ llvm/llvm-project#75553
+ …

llvm-project Meso-Update

---

tests/std/include/test_generator_support.hpp
tests/std/tests/P2502R2_generator/test.cpp
tests/std/tests/P2502R2_generator_iterator/test.cpp
tests/std/tests/P2502R2_generator_promise/test.cpp

* Add `using namespace std`
* Rename some functions (e.g. `zip` -> `co_zip`, `meow` -> `co_upto`)
* Add missing includes
* Other minor changes (see commit messages)

`<generator>`: Cleanup `P2502R2_generator/test.cpp`

---

CMakePresets.json

Fixes #4639 
I didn't test ARM command prompts.

Block building STL in wrong command prompt

---

stl/inc/chrono
stl/inc/format
stl/inc/regex
stl/inc/xlocmon
stl/inc/xloctime
tests/std/rulesets/stl.ruleset
tests/std/tests/GH_002094_cpp_core_guidelines/test.compile.pass.cpp

Fixes DevCom-10670613 VSO-2081258 / AB#2081258.
In general, we haven't attempted to be clean with respect to Core Guidelines warnings, as many of them are noisy and/or inappropriate for Standard Library code. However, warning C26818 "Switch statement does not cover all cases. Consider adding a 'default' label ([es.79][])." aligns with our conventions. We always like to have a `default` as a reminder to think about what happens when none of the `case`s are selected (this is one of the relatively few scenarios where we like to write code that isn't necessary). The only exception to this convention is when we're switching on an enum and we've handled all of the enumerators (it can still be okay to have a "can't happen" `default`, but sometimes we don't bother), which fortunately this warning …

Fix warning C26818 about `switch` statements needing `default` cases

---

tests/utils/stl-lit/stl-lit.in

Block building Tests in wrong command prompt

---

stl/inc/__msvc_threads_core.hpp
stl/inc/condition_variable
stl/inc/mutex
stl/inc/xthreads.h
stl/src/cond.cpp
stl/src/cthread.cpp
stl/src/mutex.cpp
stl/src/primitives.hpp
stl/src/sharedmutex.cpp
tests/libcxx/expected_results.txt

This improves how we initialize `condition_variable` and `condition_variable_any`. It also eliminates layers of confusing machinery like `Concurrency::details::stl_condition_variable_win7`. I've been careful to preserve bincompat at each step. (All of the other `Concurrency::details` machinery was dllexported, but not this one.) This also respects the escape hatch macro `_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR`, for users who aren't following our documented binary compatibility requirements and are mixing new STL headers with a very old STL DLL (older than VS 2022 17.8), so it doesn't affect that situation any further.
mutex.cpp doesn't use anything from primitives.hpp.
---
primitives.hpp doesn't need `<type_traits>`.
---
Stop calling no-op `_Cnd_destroy_in_situ()`.
`~condition_variable()` …

Overhaul `condition_variable`

---

stl/inc/ranges

This removes redundant `_HAS_CXX23` guards around `_Compile_time_max_size` specializations, for views that are already guarded for C++23.
Note that these changes are very low risk because the primary template for `_Compile_time_max_size` is guarded for C++23. If we attempted to specialize it in C++20 mode, we'd get instant errors:
https://github.com/microsoft/STL/blob/e36ee6c2b9bc6f5b1f70776c18cf5d3a93a69798/stl/inc/ranges#L44-L55
This also adds a couple of `#endif` comments; they aren't strictly necessary but they helped me ripgrep for the redundant guards.
Noticed while reviewing #4707.

`<ranges>`: Remove redundant `_HAS_CXX23` guards

---

tests/libcxx/expected_results.txt

After merging #4721, two CI runs sporadically failed with:
```
Assertion failed: test1 == 0, file D:\a\_work\1\s\llvm-project\libcxx\test\std\thread\thread.condition\thread.condition.condvar\notify_all.pass.cpp, line 35
Assertion failed: test2 == 0, file D:\a\_work\1\s\llvm-project\libcxx\test\std\thread\thread.condition\thread.condition.condvar\notify_all.pass.cpp, line 45
```
This test is bogus, so I've reported https://github.com/llvm/llvm-project/issues/95944 upstream. It appears to be the only affected test.

Re-skip a condvar test

---

stl/inc/__msvc_bit_utils.hpp

As mentioned in #4683, VS 2022 17.11 Preview 1 added ARM64 support for `__popcnt64` etc. intrinsics. When merging #4695, everything seemed to be okay during MSVC-internal PR checks, but post-merge CI noticed that the MSVC-internal build starts with a checked-in 17.10p4, which is too old to know about the new intrinsics.
I missed this because I forgot that MSVC-internal PR checks don't build ARM64 (only the CI does) and I didn't build ARM64 locally.
The workaround is to check the compiler version. I'll be able to remove this after we update the internal toolset, which should happen very soon.

Add MSVC-internal workaround for ARM64 `popcount` intrinsics

---

stl/src/vector_algorithms.cpp

After merging #4659, the MSVC-internal "selfbuild" CI (where the freshly built compiler is used to build itself again) failed. I've reported VSO-2093761 "amd64chk vect_opcode.cpp assertion `entryIsaRequirement <= isaRequirement` when compiling the STL's vectorized minmax".
Thanks to @AlexGuteniev for suggesting [`#pragma loop(no_vector)`](https://learn.microsoft.com/en-us/cpp/preprocessor/loop?view=msvc-170) as a workaround. (The problem involves the optimizer getting confused by manually vectorized code followed by auto-vectorized code.)

Work around a compiler back-end assertion in vectorized minmax

---

CMakeLists.txt
tests/std/tests/GH_002431_byte_range_find_with_unreachable_sentinel/test.cpp
tests/std/tests/VSO_0000000_vector_algorithms/test.cpp
tests/std/tests/floating_point_model_matrix.lst
tests/utils/stl/test/features.py
tests/utils/stl/test/tests.py

Fixes #3118. Fixes #3922. See [`/arch` (x86)](https://learn.microsoft.com/en-us/cpp/build/reference/arch-x86?view=msvc-170) on Microsoft Learn.
On x86, the STL (and indeed the entire VCRedist) was historically built with `/arch:IA32` because it had to be capable of running on ancient OSes and potato chips. Now, Win7 / Server 2008 R2 are unsupported and no longer receiving security updates - but before they reached end-of-life, even they were patched to require SSE2. That was [KB4103718](https://support.microsoft.com/en-us/topic/may-8-2018-kb4103718-monthly-rollup-c4c01989-faca-af5f-46f4-2bdc2d0171fd) in May 2018, **over 6 years ago**. (Note: I am well aware of the single exception that paid security updates for the highly obscure Windows Embedded POSReady 7 will end in Oct 2024. More on …

Build the x86 STL with `/arch:SSE2` instead of `/arch:IA32`

---

stl/inc/deque
stl/inc/forward_list
stl/inc/hash_map
stl/inc/hash_set
stl/inc/list
stl/inc/map
stl/inc/queue
stl/inc/set
stl/inc/sstream
stl/inc/stack
stl/inc/unordered_map
stl/inc/unordered_set
stl/inc/vector
stl/inc/xhash
stl/inc/xstring
stl/inc/xtree
stl/inc/xutility

Towards #602.
New internal concepts `_Iterator_for_container`, `_Allocator_for_container`, and `_Hasher_for_container` are mainly added for plain disambiguating constraints (as required by the standard).
Edit: desired changes for `priority_queue` didn't work since MSVC and Clang haven't implemented CWG-2369 ([Godbolt link](https://godbolt.org/z/G8j83qx9b)).
Edit: reduced the bug of EDG - DevCom-10678753.

Use `requires`-clauses and concepts for container-like components since C++20

---

stl/inc/atomic
tests/std/tests/P0019R8_atomic_ref/test.cpp

Fixes #4728.
For `!_ATOMIC_HAS_DCAS`:
* If we're `is_always_lock_free` (power of two, at most 1 pointer), return true.
* Otherwise, we have to be `_Is_potentially_lock_free` (power of two, at most 2 pointers) and have cmpxchg16b.

Fix `atomic_ref::is_lock_free()` on x64

---

stl/inc/yvals_core.h
tests/libcxx/expected_results.txt
tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp

Fixes #4172. Fixes #4177.
Blocked libcxx tests:
- `std/language.support/support.limits/support.limits.general/array.version.compile.pass.cpp`
- `std/language.support/support.limits/support.limits.general/expected.version.compile.pass.cpp`
- `std/language.support/support.limits/support.limits.general/mdspan.version.compile.pass.cpp`
- `std/language.support/support.limits/support.limits.general/optional.version.compile.pass.cpp`
- `std/language.support/support.limits/support.limits.general/string_view.version.compile.pass.cpp`
Some related tests are already marked `FAIL` for other reasons.

C++26 freestanding feature-test macros: Partial Classes and `inout` `expected` `span`

---

stl/inc/format
tests/libcxx/expected_results.txt
tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp

See LWG-4061 and WG21-P3341R0.
Blocked libcxx test
- `std/utilities/format/format.functions/bug_81590.compile.pass.cpp`

Implement LWG-4061 Should `std::basic_format_context` be default-constructible/copyable/movable?

---

tests/std/tests/P2474R2_views_repeat/test.cpp

LWG-4053 was correctly implemented in #4685. However, the test cases merely tested LWG-4054.
Actually, LWG-4054 rendered LWG-4053 affect CTAD only. So this PR tests CTAD for `repeat_view`, although the divergence between CTAD and `views::repeat` indicates that users should always use the latter.

Properly test the resolution of LWG-4053

---

stl/inc/xtree

Towards #2307.
Also drops an `if`-statement and reuses `_Newroot` since `_Scary->_Myhead->_Isnil` is always `true`. Closes #1913.

`<xtree>`: Use scope guard for node copy failure

---

stl/inc/xutility

It is used only once after #4654

Inline `_Memcmp_ranges` that is used only once

---

stl/inc/yvals_core.h

Updated _MSVC_STL_UPDATE to July 2024

---

stl/inc/algorithm
stl/inc/xutility

Inspect unwrapped iterators by `_Prefer_iterator_copies`

---

stl/inc/tuple
stl/inc/utility
stl/inc/yvals_core.h

As requested moved  class deinition of _Ignore and ignore to the utility header file
removed the /* strengthened */ comment from the operator=, and
added the // P2968R2 Make std::ignore A First-Class Object comment to <yvals_core.h> 
Fixes #4756

P2968R2 Make std::ignore A First-Class Object

---

stl/inc/__msvc_int128.hpp
stl/inc/__msvc_ranges_to.hpp
stl/inc/__msvc_string_view.hpp
stl/inc/array
stl/inc/charconv
stl/inc/compare
stl/inc/deque
stl/inc/exception
stl/inc/expected
stl/inc/filesystem
stl/inc/functional
stl/inc/iosfwd
stl/inc/iterator
stl/inc/mdspan
stl/inc/random
stl/inc/ranges
stl/inc/span
stl/inc/stacktrace
stl/inc/stop_token
stl/inc/system_error
stl/inc/tuple
stl/inc/valarray
stl/inc/vector
stl/inc/xcharconv.h
stl/inc/xhash
stl/inc/xpolymorphic_allocator.h
stl/inc/xstring
stl/inc/xutility
stl/inc/yvals_core.h

Fixes #4104 
I believe the workaround is not needed since CUDA 11.3.0: https://gcc.godbolt.org/z/bPh1av5f9
```
C:\Dev\STL\playground>type main.cpp
template<int>
struct test {
int i;
[[nodiscard]] friend bool operator==(const test& lhs, const test& rhs) {
return lhs.i == rhs.i;
}
};
int main() {
test<1> t1{1};
test<1> t2{1};
t1 == t2;
}
C:\Dev\STL\playground>nvcc main.cpp
main.cpp
main.cpp(12): warning C4834: discarding return value of function with [[nodiscard]] attribute
C:\Dev\STL\playground>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Feb_27_16:28:36_Pacific_Standard_Time_2024
Cuda compilation tools, release 12.4, V12.4.99
Build cuda_12.4.r12.4/compiler.33961263_0
```
I used this version Cuda 12.4.0: …

Remove `_NODISCARD_FRIEND` workaround

---

stl/inc/__msvc_formatter.hpp
tests/std/tests/P2286R8_text_formatting_formattable/test.compile.pass.cpp

Fixes #4760.
I guess resulted error messages (e.g. in the case of `std::format("L{}", "")`, pre-existing for `std::format("{}", L"")`) still need to be improved, which can be done in another PR.

Implement LWG-3944 Formatters converting sequences of `char` to sequences of `wchar_t`

---

stl/inc/ranges
tests/std/tests/P0896R4_views_iota/test.cpp

Implement LWG-4096 `views::iota(views::iota(0))` should be rejected

---

stl/inc/format
tests/libcxx/expected_results.txt
tests/std/tests/P0645R10_text_formatting_custom_formatting/test.cpp

See LWG-4106 and WG21-P3341R0.
Blocked libcxx tests
- `std/utilities/format/format.arguments/format.args/ctor.pass.cpp`
- `std/utilities/format/format.arguments/format.args/get.pass.cpp`

Implement LWG-4106 `basic_format_args` should not be default-constructible

---

stl/inc/atomic
stl/inc/yvals.h
stl/inc/yvals_core.h
stl/src/atomic_wait.cpp
tests/std/tests/P0019R8_atomic_ref/env.lst
tests/std/tests/P0019R8_atomic_ref/test.cpp

Fixes #4481.
The cmpxchg16b instruction (aka the `_InterlockedCompareExchange128` intrinsic) was missing from the earliest x64 processors, but was quickly added and is now required by all modern OSes. This intrinsic (emitting an equivalent instruction sequence) has always been supported by ARM64.
Our implementation of C++11 `atomic` didn't attempt to take advantage of the then-fairly-new cmpxchg16b instruction. By the time our ABI was frozen in VS 2015, cmpxchg16b was more widespread, but we were still learning about concurrency and hadn't realized the potential for optimization here. Shortly after the ABI freeze, we added some (highly unusual for our conventions) preprocessor-disabled logic, indicating how we could take advantage of cmpxchg16b when we could break ABI, which still hasn't …

Always use cmpxchg16b on x64 for `atomic_ref<16 bytes>`

---

stl/inc/flat_map
tests/std/tests/P0429R9_flat_map/test.cpp

`_Flat_map_base::insert` overloads were hidden because of the additional `insert` overloads defined in the children classes.
Use `using _Mybase::insert` to make them visible.
Also add test cases.

Fix insert for flat_map and flat_multimap

---

stl/inc/flat_map
tests/std/tests/P0429R9_flat_map/test.cpp

Addresses the FIXME in #4778. Fixes #4779.
For insertion, WG21-N4981 [associative.reqmts.general]/68 and /72 are fully specifying the order of results. So `insert` without hint should insert at the upper bound, and three-way comparison result should be used in hinted insertion to determine whether `lower_bound` or `upper_bound` should be used.
In construction, the `_Other` is cast to references to `_Flat_map_base` to retrieve the correct access control.
Drive-by: remove occurrences of the `_NODISCARD_FRIEND` workaround, following up #4782.

`<flat_map>`: Fix ordering in insertion and access control in construction

---

CMakeLists.txt
README.md
azure-devops/config.yml
azure-devops/create-1es-hosted-pool.ps1
azure-devops/provision-image.ps1
benchmarks/CMakeLists.txt
stl/inc/__msvc_bit_utils.hpp
stl/inc/yvals_core.h
tools/CMakeLists.txt
tools/format/CMakeLists.txt
tools/validate/CMakeLists.txt

* Updated dependencies. [#4824](https://github.com/microsoft/STL/pull/4824)
+ Updated build compiler to VS 2022 17.11 Preview 3 (now required).
+ Updated CMake to 3.29 (now required).
* PowerShell 7.4.3.
* Move to eastus2.
+ This is required for 1ES Hosted Pools quota.
* VS 2022 17.11 Preview 3, now required.
* CMake 3.29, now required.
* Remove workaround for the MSVC-internal toolset.
* New pool.

Toolset update: VS 2022 17.11 Preview 3

---

stl/inc/numeric
stl/inc/utility
stl/inc/xutility
tests/std/tests/P0295R0_gcd_lcm/test.compile.pass.cpp

In compile time or in debug.
Fixes #2300

`<numeric>`: check for gcd / lcm overflows

---

stl/inc/ranges
tests/std/tests/P2446R2_views_as_rvalue/test.cpp

Fixes #4762.
Reported a related EDG bug: DevCom-10698021.

Implement LWG-4083 `views::as_rvalue` should reject non-input ranges

---

stl/inc/ranges
tests/std/tests/P2441R2_views_join_with/test.cpp

Implement LWG-4074 `compatible-joinable-ranges` is underconstrained

---

stl/inc/ranges
tests/std/tests/P2321R2_views_adjacent/test.cpp
tests/std/tests/P2321R2_views_adjacent_transform/test.cpp

Fixes #4764.
Also slight cleanups tests `P2321R2_views_adjacent/test.cpp` and `P2321R2_views_adjacent_transform/test.cpp`. Now meaningful tests are made to only handle forward ranges.

Implement LWG-4098 `views::adjacent<0>` should reject non-forward ranges

---

stl/inc/xutility
stl/inc/yvals_core.h
tests/libcxx/expected_results.txt
tests/std/tests/P0896R4_ranges_algorithm_machinery/test.compile.pass.cpp
tests/std/tests/VSO_0157762_feature_test_macros/test.compile.pass.cpp

As a DR against C++20. Fixes #4771.
Blocked libcxx tests:
- `std/iterators/iterator.requirements/indirectcallable/indirectinvocable/indirect_binary_predicate.compile.pass.cpp`
- `std/iterators/iterator.requirements/indirectcallable/indirectinvocable/indirect_equivalence_relation.compile.pass.cpp`
- `std/iterators/iterator.requirements/indirectcallable/indirectinvocable/indirect_strict_weak_order.compile.pass.cpp`
- `std/iterators/iterator.requirements/indirectcallable/indirectinvocable/indirect_unary_predicate.compile.pass.cpp`
- `std/iterators/iterator.requirements/indirectcallable/indirectinvocable/indirectly_regular_unary_invocable.compile.pass.cpp`
- `std/iterators/iterator.requirements/indirectcallable/indirectinvocable/indirectly_unary_invocable.compile.pass.cpp`

Implement P2997R1 Removing The Common Reference Requirement From The Indirectly Invocable Concepts

---

benchmarks/src/bitset_to_string.cpp

I see more things to do with `bitset` regarding performance, but first let's fix the current benchmark.
Fortunately, the discovered issues didn't have impact on results, and on performance decisions.
Should use this to prevent compiler making the benchmarked function or its part constant.
Currently the compiler doesn't do this, but it might improve in the future
Small cases were initialized with `uint64_t` which was not enough to initialize 512 bit bitset.
The 512 rows in the benchmark improved, but it is gooseberries vs watermelons: small cases have inner loop whereas large doesn't. 
(The loop in small cases is to defeat branch prediction for the cases of branchy implementation activation. It is not needed for larger bitsets, as these would be vectorized, and if they wouldn't, the amount …

Fix `<bitset>` benchmark correctness

---

stl/inc/bitset

The value of 128 bytes is arbitrary, could be greater if we are brave.
I kept variable `_Len` as opposer to `_Bits` constant, as constant propagation apparently engages a very harmful optimization.
Didn't benchmark precisely output to stream, I think if falls under "definitely good" category; if not, I can add, but then will need to wait for #4817

Fewer allocations to put smaller bitset to stream

---

stl/inc/expected
stl/inc/tuple
stl/inc/utility

Towards #602. Also unconditionally uses `is_swappable<T>::value` workaround for `expected` as suggested in https://github.com/microsoft/STL/pull/4658#discussion_r1601027519.
Notes:
- some occurences of `conjunction_v` are preserved for `tuple` because fold expressions are not yet decomposed for associated constraints until C++26 (and thus doesn't short-circuit, see WG21-P2963R2);
- changes for `tuple` constructors were attempted but are currently given up due to LLVM-59827.

Use `requires`-clauses for `pair` and `tuple` since C++20 

---

stl/inc/xfilesystem_abi.h
tests/std/tests/P0218R1_filesystem/test.cpp

We have a regression test for DevCom-538510 (internal VSO-850856) "`std::filesystem::weakly_canonical` erroneously throws an exception":
https://github.com/microsoft/STL/blob/ecbc1efa09936f4ef5af529e770a95a29a4290d3/tests/std/tests/P0218R1_filesystem/test.cpp#L3233-L3237
This has regressed on the upcoming Win11 24H2, where we throw an exception (again). The relevant code is:
https://github.com/microsoft/STL/blob/ecbc1efa09936f4ef5af529e770a95a29a4290d3/stl/inc/filesystem#L4127-L4144
After calling `_Canonical()`, anything other than `_Err == __std_win_error::_Success` or `__std_is_file_not_found(_Err)` is considered a hard error (which will cause the non-`error_code` overload to throw a `filesystem_error`).
In current OSes, the `fileWithSuffix` scenario results in `_Invalid_name` here. …

Fix `filesystem::weakly_canonical()` on Win11 24H2

---

tests/libcxx/expected_results.txt

* Update llvm-project.
+ This is high priority, to pick up llvm/llvm-project#98161 which solved llvm/llvm-project#96121.
* llvm/llvm-project#83575 was merged.
* llvm/llvm-project#90070 was merged.
* llvm/llvm-project#94122 was merged.
* llvm/llvm-project#94907 was merged.
* llvm/llvm-project#96319 was merged.
* llvm/llvm-project#97250 implemented LWG-4106.
* llvm/llvm-project#97251 implemented LWG-4061.
* llvm/llvm-project#97622 solved llvm/llvm-project#95944.
* llvm/llvm-project#98817 implemented WG21-P2997R1.
* Reported llvm/llvm-project#100498.
* Reported llvm/llvm-project#100502.
* Reported llvm/llvm-project#100504.
* Reported llvm/llvm-project#100506.
* Clang solved llvm/llvm-project#95311, but we don't have that yet, or an equivalent product code workaround.
* Categorize …

llvm-project Mid-Year Update

---

stl/inc/atomic
stl/inc/xatomic.h

This mirrors @mcfi's MSVC-PR-567635 "Leverage clang builtins `__atomic_load_n`/`__atomic_store_n` for more efficient acquired loads and released stores on Arm64" as of Iteration 13. His description:
> Clang doesn't support `__load_acquire`/`__ldar`/`__stlr` intrinsics, so applications built with clang still generate full barriers for acquired loads and released stores. This PR changes the STL code to leverage clang builtins `__atomic_load_n`/`__atomic_store_n` to generate more efficient `ldar`/`stlr` for acquired loads and released stores.
This improved a benchmark score by ~2.8% on real hardware.
Resolves https://github.com/llvm/llvm-project/issues/62103 because we're going to use Clang's builtins now.
Works towards #1133.

Improve ARM64 atomics for Clang

---

stl/inc/generator
stl/inc/yvals_core.h
tests/std/tests/P2502R2_generator/test.cpp

Towards #2936. Makes `pmr::generator` available when `__cpp_lib_byte` is defined (i.e. when `polymorphic_allocator<>` is itself valid).
Test coverage is initially added. Perhaps more stateful-allocator-related stuffs should be tested later.

Implement P2787R1 `pmr::generator`

---

stl/debugger/STL.natvis

Fixes #4830 
Actually I tested it and I think `std::ranges::view_interface` natvis may be useless.
My test code:
```
#include <ranges>
#include <sstream>
template<class T, class A>
class VectorView : public std::ranges::view_interface<VectorView<T, A>>
{
public:
VectorView() = default;
VectorView(const std::vector<T, A>& vec) :
m_begin(vec.cbegin()), m_end(vec.cend())
{}
auto begin() const { return m_begin; }
auto end() const { return m_end; }
private:
typename std::vector<T, A>::const_iterator m_begin{}, m_end{};
};
int main()
{
std::vector<int> v = { 1, 4, 9, 16 };
VectorView view1{ v };
view1.size();
view1.front();
view1.empty();
view1.back();
view1.data();
auto words = std::istringstream{ "today is yesterday’s tomorrow" };
auto istream_view = …
```

Remove `std::ranges::view_interface` visualizer.

---

stl/debugger/STL.natvis

Fixes #4829
Test code:
```c++
#include <iterator>
int main()
{
std::vector<std::string> v{ "This", "_", "is", "_", "an", "_", "example" };
auto begin = std::make_move_iterator(v.begin());
return 0;
}
```
Result:

`move_iterator` visualizer should use `_Current`

---

stl/inc/expected
tests/std/tests/P0323R12_expected/test.cpp

Fixes #4279.
Some test cases are skipped for EDG, due to the bug which is probably VSO-1601179 (encountered in #3057 previously).

`<expected>`: Add deleted copy function overloads

---

stl/inc/algorithm
stl/inc/utility
stl/inc/xutility

Works towards #3754.
Reported CI ICE as DevCom-10702457.

Add `[[msvc::lifetimebound]]` to more min/max functions

---

stl/inc/xloctime
tests/std/tests/Dev11_0836436_get_time/test.cpp

Fixes #4820. The test case also verifies the situation where an invalid specifier is given when a modifier is being used. For example "%E% some text"
This is my first PR, so sorry if something is wrong in formatting or ABI terms.

Fix `put_time()` crash on invalid format specifier

---

stl/inc/vector

Use `_CONTAINER_DEBUG_LEVEL > 0` instead of `_ITERATOR_DEBUG_LEVEL == 2` in `vector::pop_back`. The former seems to be the better choice considering that there are no iterators involved here.

Verify in vector::pop_back if _CONTAINER_DEBUG_LEVEL > 0

---

stl/inc/random
tests/std/tests/P0952R2_new_generate_canonical/test.cpp

Avoid using wider types in `generate_canonical` when the range of the random generator is a power of 2

---

stl/inc/array
stl/inc/mdspan
tests/libcxx/expected_results.txt
tests/std/include/test_mdspan_support.hpp
tests/std/test.lst
tests/std/tests/P0009R18_mdspan_extents_death/test.cpp
tests/std/tests/P0009R18_mdspan_layout_left/test.cpp
tests/std/tests/P0009R18_mdspan_layout_left_death/test.cpp
tests/std/tests/P0009R18_mdspan_layout_right/test.cpp
tests/std/tests/P0009R18_mdspan_layout_right_death/test.cpp
tests/std/tests/P0009R18_mdspan_layout_stride/test.cpp
tests/std/tests/P0009R18_mdspan_layout_stride_death/test.cpp
tests/std/tests/P0218R1_filesystem/test.cpp
tests/std/tests/P2321R2_views_adjacent/test.cpp
tests/std/tests/P2321R2_views_adjacent_transform/test.cpp
tests/std/tests/VSO_1804139_static_analysis_warning_with_single_element_array/env.lst
tests/std/tests/VSO_1804139_static_analysis_warning_with_single_element_array/test.compile.pass.cpp

Fixes DevCom-10342063 VSO-1804139 "False positive C28020 iterating over single element `std::array`". Thanks to Hwi-sung Im from the static analysis team for explaining how to fix this with `_Ret_range_(==, _Size)`.
The issue is that we had SAL annotations on `array::operator[]` explaining its precondition, but static analysis didn't know that `array<T, N>::size()` always returns `N`. (By design, it doesn't do interprocedural analysis.) Adding a return annotation allows `/analyze` to understand loops that are guarded by `arr.size()`.
Updating `array` then revealed that `<mdspan>` (which uses `array` extensively) should be updated accordingly.
* Update product code.
+ Mark `array::size()` with `_Ret_range_(==, _Size)`, which is what fixes the reported bug.
+ As a cleanup, replace …

Fix and improve `array` and `mdspan` static analysis warnings

---

README.md

`README.md`: Add instructions for building ARM and ARM64.

---

stl/inc/algorithm

Explicit casting of the result of `ranges::size` is too verbose; simply comparing the values ​​of `ranges::distance` is sufficient as they are guaranteed to be signed integers.
This aligns with the implementation in `ranges::is_permutation`:
https://github.com/microsoft/STL/blob/8657d15b3ddfacb121e88e307f9a18b3fa379185/stl/inc/algorithm#L1084-L1088

Simplify the comparison of sizes of different ranges

---

stl/inc/yvals_core.h

resolves #4871, change  to `202408L`

Update _MSVC_STL_UPDATE to August 2024

---

stl/inc/__msvc_string_view.hpp

__builtin_wmemcmp and __builtin_wmemchr are simply lowered to wchar-by-wchar loops by MSVC backend, which may perform poorly than vectorized CRT wmemcmp and wmemchr. Therefore, for non-constexpr cases in string view, we call CRT functions instead of the builtins.

Call CRT `wmemcmp`/`wmemchr` when possible in `char_traits` for better performance

---

stl/inc/xutility

Enforce [alg.three.way]/2 mandate

---

benchmarks/CMakeLists.txt
stl/CMakeLists.txt
tools/validate/CMakeLists.txt
tools/validate/validate.cpp

[`/std:c++latest`][] implies [`/permissive-`][] but not [`/Zc:preprocessor`][], so we have to manually enable it.
[`/std:c++latest`]: https://learn.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=msvc-170
[`/permissive-`]: https://learn.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=msvc-170
[`/Zc:preprocessor`]: https://learn.microsoft.com/en-us/cpp/build/reference/zc-preprocessor?view=msvc-170
* Build the STL, benchmarks, and validator with the conformant preprocessor.
+ I've verified that the compiler option is active in each directory.
* Drop "we use SAL annotations" comment.
+ This was added by #2671 on 2022-05-01, then `_Printf_format_string_` was removed by #3919 on 2023-08-03.
+ We can keep using `/analyze`, though. …

Build with the conformant preprocessor, improve validator

---

tests/libcxx/expected_results.txt

These tests are all annotated with `ALLOW_RETRIES: n` comments, indicating that sporadic failures due to timing assumptions are expected. We don't tolerate sporadic failures, so let's disable these tests locally.

Skip libcxx tests with timing assumptions

---

README.md
azure-devops/config.yml
azure-devops/provision-image.ps1
stl/inc/type_traits
stl/src/vector_algorithms.cpp
tests/libcxx/expected_results.txt

+ Updated build compiler to VS 2022 17.12 Preview 1.
+ Updated Ninja to 1.12.1.
+ Updated Python to 3.12.5.
* PowerShell 7.4.4.
* Python 3.12.5.
* New pool.
* VS 2022 17.12 Preview 1.
+ Not yet required, because the MSVC-internal build is still using 17.11.
* Ninja 1.12.1.
* Remove workaround for DevCom-10648215 VSO-2048353.
* Remove workaround for VSO-2093761.
* Add workaround for VSO-2164191 "\[ASAN\]\[STL\] Interception breaks strtoll".
+ [AddressSanitizer-PR-566123](https://devdiv.visualstudio.com/DevDiv/_git/AddressSanitizer/pullrequest/566123) and MSVC-PR-566126 are fixing this, likely in VS 2022 17.12 Preview 3. (Thanks, @dmitrykobets-msft!)
+ This is very similar to …

Toolset update: VS 2022 17.12 Preview 1

---

tools/format/CMakeLists.txt

Our CMake machinery for clang-format is awesome, but it's remained largely unchanged since being added by #2671 on 2022-05-01. Thanks to @TheStormN for bringing my attention to issues here.
The first problem is that we're looking for the clang-format executable in a hardcoded path. That's easily broken if a contributor has installed VS Preview to a non-default location.
Second, during configuration of the STL build, we're simply warning about clang-format being missing. This isn't really helpful - to be successful, contributors really need to have both Clang installed (for testing) and clang-format (to make all but the most trivial source changes without over-relying on PR checks).
Third, we weren't validating what version of clang-format we're picking up. clang-format routinely changes …

Overhaul how we search for clang-format

---

tests/std/tests/P1206R7_ranges_to_mappish/test.cpp
tests/std/tests/P1206R7_ranges_to_misc/test.cpp
tests/std/tests/P1206R7_ranges_to_sequence/test.cpp
tests/std/tests/P1206R7_ranges_to_settish/test.cpp

There's a regression in the latest Intellisense compiler, we'll avoid the problem until it's fixed. Tracked as VSO-2208356.
This mirrors the STL portion of MSVC-PR-571275.

Workaround Intellisense bug in some `ranges::to` tests

---

stl/inc/xutility
stl/src/vector_algorithms.cpp

Follow up on #4873 
I didn't measure the effect. I expect it to be negative currently, until @mcfi changes are picked up.
I changed the compatibility part too, as it was meant to optimize originally, why shouldn't save it, if possible.

Use `wmemchr` in optimizations

---

tests/std/include/range_algorithm_support.hpp
tests/std/test.lst
tests/std/tests/LWG4105_ranges_ends_with_and_integer_class/env.lst
tests/std/tests/LWG4105_ranges_ends_with_and_integer_class/test.cpp

Closes #4765.
This PR confirms that the resolution is effectively implemented at first by testing two ranges with difference types being an integer type and an integer-class type repectively.
- I'd like to add `redifference_iterator`/`redifference_sentinel` to `<range_algorithm_support.hpp>` because I think they will be useful for addressing many difference-type-related issues.
- A new test file is created because the test coverage is unexpectedly heavy for compilation.

Test LWG-4105 `ranges::ends_with`'s Returns misses difference casting

---

stl/inc/__msvc_iter_core.hpp
stl/inc/forward_list
stl/inc/list
stl/inc/ranges
stl/inc/span
stl/inc/utility
tests/std/tests/P0323R12_expected/test.cpp

A grab bag of minor changes broken down for quick-and-easy commit-wise review:
* `<ranges>`: simplify `zip_view::_Size_closure` by making it a `static constexpr` data member instead of a function
* Use conventional LLVM issue linking style
* Simplify `_Tuple_like` metaprogramming: implements `_Tuple_like_impl` as a variable template with four partial specializations instead of as a disjunction of four other variable template specializations. Consequently, each evaluation of `_Tuple_like` causes the compiler to memoize one constexpr variable instead of five.
* Don't return a decayed *boolean-testable* since the exposition-only concept doesn't allow for construction of an object of decayed type from a model of *boolean-testable*. Note that the changes in `erase_if(forward_list, pred)` and …

Casey's accumulated miscellaneous changes

---

stl/inc/chrono
tests/std/tests/P0355R7_calendars_and_time_zones_clocks/test.cpp

LWG-4139 indicated constraint recursion in the current specification of the `operator<=>` for `leap_second` and `sys_time`, which is not yet revealed due to the bugs in MSVC and (old versions of) Clang.
Although the proposed resolution is not shown in the LWG issue, I think the necessary changes are clear enough - just moving the operator functions from the synopsis of `<chrono>` to that of `std::chrono::leap_second` and adding `friend`.
This has been done in libstdc++ years ago (https://github.com/gcc-mirror/gcc/commit/1736bf5a61c7364c5da6fa52e5e2bfdbc9507c97), and recently in libc++ via LLVM-104713.

Speculatively implement LWG-4139 [time.zone.leap] recursive constraint in `<=>`

---

stl/inc/variant
tests/std/tests/P0088R3_variant_msvc/test.cpp

Fixes #4901. The workaround doesn't seem to affect conformance, as the destructor of derived classes and `variant` are always `noexcept`.

`<variant>`: Workaround for LLVM-59854 in the case of destructor of `variant`

---

tests/std/run.pl
tests/tr1/run.pl

Followup to #2830 merged on 2022-06-28, mirrored as MSVC-PR-407767 "Enable memory stressing in std/tr1 test suites".
That PR attempted to add an environment variable `PM_CL_MSVC` to our internal test harness, allowing the MSVC-only compiler option `/d1db178,179` (which stresses compiler memory somehow) to be added without affecting Clang (which wouldn't understand it).
Unfortunately, this never took effect, and we didn't notice for two years! Our compiler back-end dev Andrew Dean recently discovered this while attempting to use the mechanism to investigate sporadic compiler crashes (which, as an aside, we now have good reason to believe are being caused by bitflips in flaky hardware :scream_cat:).
The fix is simple: we need to update the `PM_CL` variable, which contains the set of …

Fix MSVC-only compiler options for the internal test harness

---

stl/inc/__msvc_int128.hpp
tests/std/include/test_header_units_and_modules.hpp

Fixes #4899 by adding workarounds for DevCom-10729775.
I slightly reduced the test case from `uniform_real_distribution`, then verified that the `generate_canonical` test coverage fails without the workaround (for both Standard Library Modules and Standard Library Header Units), before passing with the workaround.
`_Signed128` has the same code pattern, and I was able to craft a highly contrived repro demonstrating that it needs the same workaround. I don't think we need to add automated test coverage for it, though.
<details><summary>Click to expand bonus repro:</summary>
```
C:\Temp>"C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Auxiliary\Build\vcvarsall.bat" x64
**********************************************************************
** Visual Studio 2022 Developer Command …
```

Standard Library Modules: Add compiler workarounds for `<random>`

---

stl/inc/ranges

The Visual Studio IDE has an "inline parameter hint" feature which will show the parameter names inline.  The STL generally has nice descriptive names which can make this feature helpful.
When I went to use `views::iota` I forgot if the second arg is a count or not, I was hoping the parameter names would save me a trip to cppreference, but alas, I was greeted with useless names.
`views::repeat` has the same issue (which is my fault; I just copied and pasted iota)
I also have a [feature request](https://developercommunity.visualstudio.com/t/De-uglify-STL-identifiers-in-inline-hint/10697009) to de-uglify them (might make another to not show the type information for these views, or I guess more generally, long nested templated types)

`<ranges>`: rename `views::iota` and `views::repeat` parameters

---

tests/std/tests/P0088R3_variant/test.cpp
tests/std/tests/P2136R3_invoke_r/test.cpp

Update some noexcept tests in variant and invoke to remove old permissive behavior. This is guarded in a check for an as-yet unreleased MSVC compiler.
This mirrors the STL portion of MSVC-PR-566073.

Adjust tests relying on CWG-1351 noexcept behavior

---

stl/src/locale0.cpp

locale0.cpp has a global static linked list: 
https://github.com/microsoft/STL/blob/8af2cc499c94271c8d12baeb45e840f7160e082d/stl/src/locale0.cpp#L52
whose memory is released when another global variable,
https://github.com/microsoft/STL/blob/8af2cc499c94271c8d12baeb45e840f7160e082d/stl/src/locale0.cpp#L64
, is destructed: 
https://github.com/microsoft/STL/blob/8af2cc499c94271c8d12baeb45e840f7160e082d/stl/src/locale0.cpp#L54-L62
This is fine, except when `new` and `delete` are replaced globally by application code. In our application code (a fairly old codebase that is hard to refactor), we replace `new` and `delete` operators globally and use our private custom heap to manage the memory. The problem is `_Fac_node` linked list's memory is allocated on our private heap, but when the …

`locale0.cpp`: Protect memory integrity of `_Fac_node`

---

tests/tr1/tests/algorithm/test.cpp
tests/tr1/tests/memory2/test.cpp

Our bosses and boss-like entities heard that [`rand()` is considered harmful](https://learn.microsoft.com/en-us/shows/goingnative-2013/rand-considered-harmful) and are starting a push to avoid unnecessary use.
Almost all of our mentions of `rand` are Standard-mandated (or Standard stable name citations), but I found a few unnecessary uses in our legacy `tr1` test suite. We avoid cleaning up its code unless there's a specific reason to mess with it, and this easily qualifies.
* `tr1/tests/algorithm`
+ Give `rand_gen` an `mt19937` data member. (Default construction is fine; we weren't attempting to seed `rand()` before.) This is purely masking bits with `& 0xfffff`, so there's no need for a `uniform_int_distribution`.
+ Replace the `frand()` wrapper with an `rng_func` lambda. To avoid …

Avoid `rand()` in the legacy `tr1` test suite

---

stl/inc/memory

Per suggestion of Howard Hinnant on the LWG reflector. We initialize `unique_ptr`'s stored `pointer` with the result of calling `release()` on the `auto_ptr`. `release()` has type `U*`, so the correct constraint is to require `U*` to be convertible to `pointer`.
STL will probably laugh himself to tears before rejecting this PR, but it's probably the only chance I'll ever get to fix an `auto_ptr`-related bug so here it is =)

Fix constraint on `unique_ptr<T, D>(auto_ptr<U>&&)`

---

stl/inc/algorithm
tests/std/tests/P0896R4_ranges_alg_inplace_merge/test.cpp

Fixes #4863.
----
I _guess_ it would be better to require `const&` for the checking in `std::sortable` to make `ranges::inplace_merge` able to use `ranges::upper_bound` like this:
```C++
template<dereferenceable I>
struct const_lvalue_adaptor { // exposition only
const iter_reference_t<I>& operator*(); // not defined
};
template<class I, class R = ranges::less, class P = identity>
concept sortable =
permutable<I> &&
indirect_strict_weak_order<R, const_lvalue_adaptor<projected<I, P>>>;
```
But at this moment I decide just not to require `const&` for internal checking.

`<algorithm>`: Relax const-ness requirements on `ranges::_Meow_bound_unchecked`

---

benchmarks/CMakeLists.txt

google/benchmark#1450 was fixed by google/benchmark#1470 on 2022-08-18.

Remove google/benchmark workaround

---

stl/inc/algorithm

Resolves #4660
(Turns out that #4660 is completely orthogonal to #4453.  Initially I thought that the "prefer values" branch is inherently vectorization friendly or can be made such, but it is not true. as that branch reduces comparisons number, whereas vectoriztion-friendly loop should be naive)

Vectorize `minmax` on each code path

---

stl/src/filesystem.cpp

We have an extremely squirrelly line of code that's `memcpy`ing two consecutive `DWORD`s into the beginning of a buffer. There's no reason for this weirdness - it isn't perf-critical, and the optimizer should understand `memcpy`. Now, code analysis tools (specifically CodeQL) are noticing that this code is a :chipmunk: read overrun. Let's avoid this by splitting it up into two separate reads.
For the destination, `_Id` points to [`FILE_ID_INFO`][]. Its `FileId` is [`FILE_ID_128`][], which contains `BYTE Identifier[16];`.
For the source, `_Info` is [`BY_HANDLE_FILE_INFORMATION`][]:
```cpp
typedef struct _BY_HANDLE_FILE_INFORMATION {
DWORD    dwFileAttributes;
FILETIME ftCreationTime;
FILETIME ftLastAccessTime;
FILETIME ftLastWriteTime;
DWORD    dwVolumeSerialNumber;
DWORD    nFileSizeHigh; …
```

Avoid squirrelly `memcpy()` call in `filesystem.cpp`

---

stl/inc/future

https://en.cppreference.com/w/cpp/thread/packaged_task/packaged_task
https://en.cppreference.com/w/cpp/thread/packaged_task/operator%3D
Cppref states that the move constructor and move assignment operator of packaged_task are noexcept, so I think there should be a noexcept specifier here.

Explicitly spell the noexcept-specifier of the move constructor and move assignment operator of packaged_task

---

stl/inc/__msvc_string_view.hpp
stl/inc/charconv
stl/inc/xutility
stl/src/StlLCMapStringA.cpp

* "Unclear validation of array index" silenced by `// lgtm [cpp/unclear-array-index-validation]`
+ `__msvc_string_view.hpp` 668: We have `bool _Matches[256]` and the index is cast to `unsigned char`.
+ `__msvc_string_view.hpp` 1334: `basic_string_view::operator[]` has optional validation controlled by `_CONTAINER_DEBUG_LEVEL` and intentionally doesn't validate by default.
+ `charconv`: `_Digit_from_byte` has 256 elements (enforced by `_STL_INTERNAL_STATIC_ASSERT`) and the index is cast to `unsigned char`.
* "Cast from `char*` to `wchar_t*`" silenced by `// lgtm [cpp/incorrect-string-type-conversion]`
+ `xutility`: `_Copy_memmove()` is correctly bypassing pointer arithmetic for performance.
+ `StlLCMapStringA.cpp`: This function has [`LCMapStringA`][]'s narrow interface, but implements …

Silence CodeQL false positive warnings

---

tests/std/tests/P1206R7_ranges_to_mappish/test.cpp
tests/std/tests/P1206R7_ranges_to_misc/test.cpp
tests/std/tests/P1206R7_ranges_to_sequence/test.cpp
tests/std/tests/P1206R7_ranges_to_settish/test.cpp

VSO-2208356 has been fixed internally. Disable the workaround internally, and mark the workaround for cleanup when VS 17.12p3 releases.
This mirrors MSVC-PR-577053.

Begin removing EDG workaround from `ranges::to` tests

---

stl/inc/generator
tests/std/include/test_generator_support.hpp
tests/std/tests/P2502R2_generator/test.cpp
tests/std/tests/P2502R2_generator_death/test.cpp
tests/std/tests/P2502R2_generator_iterator/test.cpp
tests/std/tests/P2502R2_generator_promise/test.cpp

This should complete the `generator` feature branch and get it ready to merge. There are very few product code changes here, it's mostly expanded test coverage with some cleanup and reorganization. There's also some documentation of the "stack of coroutines" and the memory layout of allocations that will make it easier for folks to get up to speed on how the code works under the covers.
It's broken down nicely by commit for ease of review; I'll replicate the commit messages here as an overview. Comments without specific context refer to `P2502R2_generator` where most changes were made. The `P2502R2_generator_iterator` and `P2502R2_generator_promise` tests were already very nicely complete.
* Update `generator` template argument mandates
* Update citations to WG21-N4988
* Reorder checks to …

Polish `std::generator`

---

stl/msbuild/stl_1/xmd/dirs.proj
stl/msbuild/stl_2/xmd/dirs.proj
stl/msbuild/stl_atomic_wait/xmd/dirs.proj
stl/msbuild/stl_base/dirs.proj
stl/msbuild/stl_base/xmd/dirs.proj
stl/msbuild/stl_base/xmt/dirs.proj
stl/msbuild/stl_codecvt_ids/xmd/dirs.proj
stl/msbuild/stl_post/xmd/dirs.proj

Historically, /Qspectre was only supported in optimized code so spectre-mitigated debug builds were disabled. This is now supported, so this PR enables the build path. Spectre-mitigated debug libraries are useful primarily to reduce friction for customers that would like to release debug versions of their binaries, but have policies preventing production or publication of binaries that are not spectre-mitigated.
Mirrored as MSVC-PR-569343.

Allow spectre build of debug libraries

---

stl/inc/deque
tests/std/tests/GH_002769_handle_deque_block_pointers/test.cpp

Fixes #4954.
In #4091, `_First_used_block_idx` was incorrectly unmasked. In some problematic cases, `_First_used_block_idx` can become larger than `_Mask`, which could render the loop infinite.

`<deque>`: Add missed masking of `_First_used_block_idx` in `deque::shrink_to_fit` to correctly end the loop

---

stl/inc/optional
tests/libcxx/expected_results.txt

This avoids interfering with pathological initializations like the one in `std/utilities/optional/optional.object/optional.object.ctor/gh_101960_internal_ctor.compile.pass.cpp`.

Make `optional`'s secret constructor private

---

stl/inc/deque
stl/inc/forward_list
stl/inc/list
stl/inc/queue
stl/inc/stack
stl/inc/vector
stl/inc/xmemory
tests/std/test.lst
tests/std/tests/VSO_2252142_wrong_C5046/env.lst
tests/std/tests/VSO_2252142_wrong_C5046/test.compile.pass.cpp

The instantiation used to deduce the return types of template functions with placeholders in their declared return type happens outside the immediate context of any other template instantiation. Notably, that means the body of such an instantiation isn't an unevaluated context. 
Switching to concrete return types will:
1. Avoid return type deduction, correcting the problem described in DevCom-10745303, and
2. Correct the ODR problem described in #4962.
Fixes DevCom-10745303 / VSO-2252142 / AB#2252142

Don't deduce the return type of `emplace`{,`_back`,`_front`}

---

stl/inc/variant
tests/std/tests/P0088R3_variant_msvc/test.cpp

`variant`'s converting constructor and assignment operator templates are constrained to reject arguments of the `variant`'s type. In such a case, the templates instantiated to check the constructibility constraint might be ill-formed outside the immediate context of template instantiation causing a hard error. We should split the constraints into multiple `enable_if_t`s to enable short-circuiting of later constraints when the earlier constraints fail.
Fixes #4959.

Short-circuit some `variant` constraints

---

stl/inc/bitset
tests/std/tests/GH_004930_char_traits_user_specialization/test.cpp

Use `char_traits` in streaming `operator>>` of `bitset`

---

tests/std/tests/VSO_0226079_mutex/test.cpp

_Can I tell you only one solution to this problem? Ditch the second clock!_
Fixes #1472
With the series of PRs ended with #4755 we should be fine with this change.

Use `steady_clock` in timed mutex test

---

stl/inc/forward_list
stl/inc/list
stl/inc/xmemory

fixes #4968. It's similar to #4963.

Do not deduce the return type of `unique,remove[_if]` of `[forward_]list`

---

stl/inc/utility
tests/std/tests/VSO_0000000_more_pair_tuple_sfinae/test.cpp

In #4961 we made an internal secret constructor private. It's arguably conforming to leave the internal constructor of `pair` public, because it must be called with 4 arguments, and no Standard constructor would be selected in such a call. However, it's possibly better to prevent accident calls to implementation details.
~Also move the deleted `operator=` overload to the private section for consistency, which should affect nothing.~ Edit: reverted.

`<utility>`: Privatize `pair`'s internal non-Standard constructor

---

stl/inc/queue
stl/inc/stack
stl/inc/xmemory
tests/std/tests/VSO_2252142_wrong_C5046/test.compile.pass.cpp

Followup to #4963. Fixes VSO-2261359 / AB#2261359 "\[VCPKG\] rocksdb installation failed with error C2440":
```
stack(125): error C2440: 'return': cannot convert from 'void' to 'rocksdb::TransactionBaseImpl::SavePoint &'
```
As the container adaptors are required to use `decltype(auto)` in C++17, the "warning C5046: Symbol involving type with internal linkage not defined" in the `convertible_to_any` scenario and the ODR violation when mixing C++14 and C++17 TUs are unavoidable.
In `<xmemory>`, I'm lexicographically sorting `_ADAPTOR_EMPLACE_RETURN` before `_CONTAINER_EMPLACE_RETURN`, which will avoid an adjacent-add conflict with #4975 adding `_LIST_REMOVE_RETURN` (also in lex order).

Deduce the return type of `queue::emplace` and `stack::emplace`

---

stl/inc/__msvc_string_view.hpp
stl/inc/charconv
stl/inc/system_error
stl/inc/xbit_ops.h
stl/inc/xutility
stl/src/StlLCMapStringA.cpp
stl/src/vector_algorithms.cpp

Our internal infrastructure that periodically runs CodeQL and creates automated bug reports is changing how it accepts warning suppressions.
The suppression comments that we've been using, of the form `// lgtm [cpp/too-many-puppies]`, are now rejected with:
> cpp/policy/alert-suppression-without-justification
> \[SM03936\] Alert Suppression Without Justification
> A legacy (LGTM) CodeQL suppression comment without a justification was detected.
The new form that we must use is:
```cpp
// CodeQL [OpaqueID] Justification consisting of 25 or more characters
```
This comment can appear on the affected line, or immediately above it.
Note that the opaque ID SM03936 for Alert Suppression Without Justification isn't what we ever want to use - we need to use the opaque ID for the underlying …

Update CodeQL warning suppressions

---

stl/inc/__msvc_iter_core.hpp
stl/inc/tuple
stl/inc/utility
stl/inc/xmemory
stl/inc/xutility

Effectively mirrors LLVM-85206.
In the current standard wording, the "_`pair-like`_ but not `subrange`" pattern is used more often than plain _`pair-like`_. So it's probably worthwhile to carve out the `_Pair_like_non_subrange` concept. `_Tuple_like_non_subrange` seems less worthwhile, but it should be helpful in the constructors of  `tuple`.
Moreover, with `_Pair_like_non_subrange` carved out, we can put the definitions of `_Pair_like` in C++20 & 23 modes together in `<xutility>`.
`_Pair_like_non_subrange` should be also helpful for extracting the key object from pair-like construction argument via
`_In_place_key_extract_map` (since C++23). I think this can be done in a future PR.
Other changes: Renaming the template parameter of `subrange`'s conversion function to `_PairLike`, making …

Refactoring around `tuple-like`, `pair-like`, and `subrange`

---

stl/inc/xlocmon
stl/inc/xlocnum
stl/inc/xloctime

Use `if constexpr` in locale facets

---

README.md
azure-devops/config.yml
azure-devops/provision-image.ps1
stl/inc/chrono
stl/inc/format
stl/inc/yvals_core.h
tests/CMakeLists.txt
tests/libcxx/expected_results.txt
tests/std/tests/P0088R3_variant/test.cpp
tests/std/tests/P1206R7_ranges_to_mappish/test.cpp
tests/std/tests/P1206R7_ranges_to_misc/test.cpp
tests/std/tests/P1206R7_ranges_to_sequence/test.cpp
tests/std/tests/P1206R7_ranges_to_settish/test.cpp
tests/std/tests/P2136R3_invoke_r/test.cpp

+ Updated build compiler to VS 2022 17.12 Preview 3 (now required).
+ Updated Python to 3.13.0 (now required).

Toolset update: VS 2022 17.12 Preview 3, Python 3.13.0

---

stl/inc/__msvc_ranges_to.hpp
stl/inc/__msvc_ranges_tuple_formatter.hpp
stl/inc/algorithm
stl/inc/array
stl/inc/execution
stl/inc/format
stl/inc/print
stl/inc/ranges
stl/inc/xmemory
stl/inc/xutility
tests/std/include/range_algorithm_support.hpp
tests/std/tests/GH_004109_iter_value_t_direct_initialization/test.compile.pass.cpp
tests/std/tests/P1502R1_standard_library_header_units/env.lst
tests/std/tests/P2165R4_tuple_like_operations/test.compile.pass.cpp
tests/std/tests/P2165R4_tuple_like_relational_operators/test.compile.pass.cpp
tests/std/tests/P2502R2_generator/test.cpp

Nice bite-sized commits:
* Improve formatting of `_Default_allocate_traits`; define a new macro instead of conditionally inserting `_CONSTEXPR20`. Drive-by: Combine nested conditionals.
* Fix `TRANSITION` comment for disabled EDG config in `P1502R1_standard_library_header_units`.
* Annotate workaround for Clang constrained-friends issue with `TRANSITION, Clang 19`. I discovered this has been fixed in 19.1.0 after reducing a repro to file, didn't try to dig up the fix.
* Remove extraneous `constexpr` in `P2502R2_generator`
* Simplify `unreachable_sentinel_t`. We had to workaround the fact that hidden friends aren't hidden in permissive mode by stuffing `unreachable_sentinel_t`'s `operator==` into a detail namespace. Now that the changes to C++20 relational expressions are implemented, we …

Casey's miscellaneous changes, definitive edition

---

stl/inc/__msvc_iter_core.hpp
stl/inc/algorithm
stl/inc/memory
stl/inc/xutility
tests/libcxx/expected_results.txt

This completes the last bits of the iterator unwrapping design for Ranges algorithms.
Detailed commit-wise description:
* Expand `_Idl_distance` design for Ranges
* Add `_Distance_unbounded` to represent the distance between an iterator and `unreachable_sentinel`.
* `_Idl_distance` takes iterator/sentinel pairs in C++20 mode.
* Add `_RANGES _Idl_distance(range)`, equivalent to `_STD _Idl_distance` but for `sized_range` instead of `sized_sentinel_for`.
* Support integer-class counts in `_Get_unwrapped_n`.
* Simplify `ranges::destroy_n`. Now that `_Get_unwrapped_n` supports integer-class counts, we don't need to apply `_Algorithm_int_t` to `_Count`.
* Update operations on `_Idl_distance`s
* Refactor `_Idl_dist_add`:
* Use `if constexpr` dispatch instead of overloading.
* …

Unwrapping output iterators in range algorithms

---

stl/inc/algorithm
stl/inc/xutility
tests/libcxx/expected_results.txt

* Split `_Idl_distance` into Ranges and pre-Ranges flavors. Who put their Ranges in my peanut butter??!?
* Move `_STD _Idl_dist_min` into `ranges` for consistency.
Fixes VSO-2285862 and VSO-2285916. (Currently validating.)
This is a mirror of MSVC-PR-586447. (I created the mirror PR early so I can verify this fixes things that #5015 broke in RWC.)

Don't throw arbitrary iterators at `sized_sentinel_for`

---

stl/debugger/STL.natvis

Adds a visualizer for `std::chrono::system_clock::time_point`. To compute the date representation, it uses the same algorithm as [`_Civil_from_days`](https://github.com/microsoft/STL/blob/faccf0084ed9b8b58df103358174537233b178c7/stl/inc/chrono#L823-L959) (with the same "variables" as https://howardhinnant.github.io/date_algorithms.html#civil_from_days).
The time is displayed as hh:mm:ss.ssssss. Additionally, the visualizer shows `ns/100` (the actual value of the time-point), `us`, `ms`, and `s`.
Unfortunately, the [format specifiers](https://learn.microsoft.com/en-us/visualstudio/debugger/format-specifiers-in-cpp?view=vs-2022#BKMK_Visual_Studio_2012_format_specifiers) don't provide a way of formatting numbers with padding, so they're formatted "manually" (e.g. a 2-digit `v` is formatted …

Add visualizer for `std::chrono::system_clock::time_point`

---

stl/src/vector_algorithms.cpp

Not an optimization, rather maintenance change.
Experience with bitset from string and others has shown that while traits-based approach is a bit harder to read, it is less error prone.
The benchmark results are within the same.
The only semantic change is that now `memcpy` is always used for tail, instead of just one specific case where tail can be long.

Generalize vectorized `bitset::to_string` implementation

---

stl/src/vector_algorithms.cpp

Work around DevCom-10767462
Looks fragile (how can we be sure that the compiler won't misplace another `vzeroupper` too?) but seems to work.
Alternative to #5010

Fix floating `minmax` performance

---

stl/inc/list
stl/inc/xtree

Update list to remove bogus strengthened comment

---

stl/inc/regex

Fixes #4993 
updated line 502 in regex.cpp
from : "contained an invalid range in a { expression }."
to : "contained an invalid range in a {} expression."

`<regex>`: Fix goofy message for `error_badbrace`

---

tests/utils/stl/test/params.py

To control test process priority. Defaults to `IDLE_PRIORITY_CLASS`. Has no effect without `pip install psutil`.

Add LIT parameter `priority`

---

stl/inc/__msvc_threads_core.hpp

For ages, we've had an "optimization" in the machinery for `mutex` and `condition_variable`, reducing their bloated sizes for Windows-internal builds. This is a relic of when we switched between different implementations for XP, Vista, and Win7; the largest size consumption was for the ConcRT-powered XP implementation. Windows could always assume it was the latest Windows, so it never needed that switching.
Unfortunately, the world is not as simple as we believed it to be. We thought that Windows was built consistently with a macro identifying it as Windows-internal, and that such object files were never mixed with ordinary object files (built with public VS). First, the macro scheme either changed or we didn't fully understand it in the first place (`_CRT_WINDOWS` vs. …

Abandon Windows-internal size optimizations for `mutex` and `condition_variable`

---

.mailmap

Git will use this file to determine a canonical name and email address for each committer and/or author email address to display in the output of `git log` and `git blame`. This is useful when people change names or emails or if someone wants to map their different accounts to a single canonical set of info.
See https://git-scm.com/docs/gitmailmap for details.

Add `.mailmap` file

---

stl/inc/algorithm
stl/src/vector_algorithms.cpp

Re-try of #4943 
Reverts #5041 and fixes the bug that triggered ASan.
We do SSE4.2 checks that search for up to 16 bytes sequence in a 16 bytes sequence. Such search can result in a match if it is a full match, or if it is a match of the beginning, and can be a match or mismatch when looking into further bytes.
We have two different code branches for needles within 16 bytes and longer needles. The bug is in the longer needles branch.
The 16 or less bytes branch can have SSE4.2 match as confirmed, when the needle fits fully, or a match that needs further confirmation when beginning of the needle matched. 
The search starts from the 16 bytes before the end, to have data for the first SSE4.2 instruction.
The whole haystack is split into three parts:
1. The last part, that is 16 bytes closest …

Vectorize `find_end`, make sure ASan passes

---

stl/inc/__msvc_string_view.hpp
stl/inc/chrono
stl/inc/regex

Towards #602.
Drive-by: Simply `sub_match` by reusing `_Get_comparison_category_t`.

`requires` for `chrono::parse` and comparison category detection

---

stl/inc/algorithm
stl/inc/xutility
tests/std/tests/GH_000431_copy_move_family/test.cpp

* BUG: `_Copy_memmove_n` adds a `size_t` directly to an iterator.
* BUG: `ranges::copy_n` converts `n` to `size_t` without verifying it is non-negative.
* There's a redundant recalculation of `n` in our existing implementation of `_Copy_memmove_n` which calls `_Copy_memmove`. Eliminate that redundancy by extracting the commonality into a new function `_Copy_memmove_tail` called by both `_Copy_memmove` and `_Copy_memmove_n`. 
* `_Copy_n_unchecked4` should verify its precondition that `n >= 0`. Drive-by: We can unconditionally `_STL_INTERNAL_STATIC_ASSERT(_Integer_like<_SizeTy>)` since #5015 defined `_Integer_like` in pre-20 modes

Refactor `_Copy_memmove` and `_Copy_memmove_n`

---

tests/std/tests/P1502R1_standard_library_header_units/custombuild.pl

While working on internal MSVC-PRs, including mirroring GitHub changes, I noticed something curious. The Standard Library Header Units test appeared to be ICEing, but it wasn't related to any of the PR changes. What happened is that our internal "chk" compiler (with assertions enabled) had begun ICEing in this test. (We weren't seeing it on GitHub because either the shipping "ret" compiler was less severely affected, or because recent changes that intensified the problem hadn't yet shipped. I didn't care enough to investigate which was the case.) The mysterious thing was why this ICE wasn't blocking our internal PR/CI checks. While the ICE had a different underlying cause (internal VSO-2293247 "`/Zc:preprocessor` does not terminate macro definitions properly", which @cdacamar just fixed …

Fix internal Perl script for Standard Library Header Units test coverage

---

stl/inc/regex
tests/std/tests/GH_000431_equal_memcmp_is_safe/test.compile.pass.cpp
tests/std/tests/GH_000431_lex_compare_memcmp_classify/test.compile.pass.cpp
tests/std/tests/VSO_0000000_regex_use/test.cpp

1. Simply overly generalized traits and algorithms, which are actually specific to `std::char_traits` and `sub_match`.
2. Add `const` to some `operator()`. A (non-static, non-explicit-parameter) `operator()` without `const` usually implies the status of the function can be modified, which is not the case for the touched functors.
3. Use `= default;` and default member initializers for some classes.
4. Strengthend exception specifications for some funcitons.
Maybe in a future PR: Moving some function bodies into class bodies. Separation doesn't seem necessary to me, but the change is a bit large.

`<regex>`: Small cleanups

---

stl/inc/numeric
stl/inc/yvals_core.h

Followup to #4958.
Fixes VSO-2295101 "\[RWC\]\[prod/fe\]\[Regression\] Cutlass failed with error C2146: syntax error: missing `')'` before identifier `'_Dest'`". It appears that CUDA 12.4 doesn't understand `__restrict`, so when it attempts to split code between the device (GPU) and host (MSVC) compilers, it mangles what's sent to MSVC.
Apparently this is only an issue when the template is instantiated, which is why it wasn't found by our CUDA test coverage (that includes all headers and does nothing with them). It was only encountered in our Real World Code test suite where we wisely harnessed NVIDIA's Cutlass project.
I am slightly nervous that bad kitties have grabbed `_RESTRICT` but we're following that form for `_LIKELY` etc. and I don't want to pre-emptively avoid issues when we …

Guard `__restrict` usage for CUDA

---

stl/inc/optional

Clarify `optional::swap` conditions

---

stl/inc/locale
stl/inc/xlocale
stl/src/locale.cpp
stl/src/locale0.cpp
stl/src/wlocale.cpp
stl/src/xlocale.cpp
tests/std/tests/Dev09_056375_locale_cleanup/test.cpp

The non-Standard constructor and conversion function are likely to change the behavior of overload resolution, so perhaps they should be eliminated. But they're currently appearing in the DLL interface and thus can't be removed until vNext.
This PR attempts to make them only exist when building the STL. The newly added Standard default constructor and `_Get_index` function are templates to avoid alternating DLL interface. (I'm still unsure whether this is sufficient or necessary.)

`<locale>`: Hide some non-Standard functions of `locale::id`

---

stl/inc/xfilesystem_abi.h
tests/std/tests/P0218R1_filesystem/test.cpp

After upgrading to Win11 24H2, I observed a very sporadic failure in `P0218R1_filesystem`. (#4844 was also a behavioral change in 24H2, but that one was consistent.) Eventually I was able to reproduce this with focused testing:
<details><summary>Click to expand reduced test case:</summary>
```
D:\GitHub\STL\out\x64>type meow.cpp
```
```cpp
#include <cassert>
#include <exception>
#include <filesystem>
#include <random>
#include <system_error>
using namespace std::filesystem;
bool good(const error_code& ec) {
bool overall = true;
if (ec.value() != 0) {
wcout << L"Unexpected error " << ec.value() << L" " << ec.message().c_str() << L"\n";
overall = false;
}
if (ec.category() != system_category()) {
wcout << L"Unexpected category " << …
```

Fix `filesystem::directory_entry::refresh` on Win11 24H2

---

CMakeLists.txt
README.md
azure-devops/config.yml
azure-devops/create-1es-hosted-pool.ps1
azure-devops/provision-image.ps1
benchmarks/CMakeLists.txt
tools/CMakeLists.txt
tools/format/CMakeLists.txt
tools/validate/CMakeLists.txt

+ Updated build compiler to VS 2022 17.13 Preview 1.
+ Updated CMake to 3.30 (now required).
+ Updated the PR/CI system to Windows Server 2025.
* Updated PowerShell to 7.4.6.
* VS 2022 17.13 is not yet required because the MSVC-internal build is still using 17.12.
* We last updated the OS in #2496, from Win11 21H2 to Windows Server 2022.
* I've updated the [Checklist for Toolset Updates](https://github.com/microsoft/STL/wiki/Checklist-for-Toolset-Updates) for Windows Server 2025.
* [STL-ASan-CI passed.](https://dev.azure.com/vclibs/STL/_build/results?buildId=17870&view=results)

Toolset update: VS 2022 17.13 Preview 1, Windows Server 2025

---

stl/inc/regex

Windows encountered internal OS-50456631 "\[CodeQL:Warning\]: SM02323: cpp/infiniteloop (in packages/\[...\]/regex)", reported to me by @DefaultRyan. According to the [internal doc](https://liquid.microsoft.com/Web/Object/Read/scanningtoolwarnings/Requirements/CodeQL.SM02323#Zguide), this is:
> \[SM02323\] Comparison of narrow type with wide type in loop condition
> Comparisons between types of different widths in a loop condition can cause the loop to fail to terminate.
In this case, the warning is a false positive, and my suppression comment explains why.
Alternatively, we could widen the `unsigned int` to `size_t`, either with a `static_cast` or a named variable, but that'd be unusual enough to still merit a comment, so I chose the less invasive approach.

`<regex>`: Silence CodeQL false positive warning

---

stl/inc/xutility

When `three_way_comparable_with<const _Elem1&, const _Elem2&>` is satisfied, `_Synth_three_way` behaves same as `compare_three_way`. So we should also consider three-way comparison via `_Synth_three_way` to be vectorizable.
The change is expected to make more comparisons between contiguous containers vectorized.
I _think_ existing test coverages are sufficient.

`<xutility>`: Extend vectorization condition for `_Synth_three_way`

---

stl/inc/yvals_core.h

Followup to #4958 and #5061.
According to [CUDA's documentation](https://docs.nvidia.com/cuda/cuda-c-programming-guide/#restrict), CUDA recognizes `__restrict__`, so I think we can use that spelling for CUDA.

Use `__restrict__` for CUDA

---

stl/inc/yvals_core.h

#5079 was a nice try, but it doesn't work. We need to revert this before 17.13 Preview 3 branches for release.
It broke NVIDIA's Cutlass again. @CaseyCarter observed:
> In both the old and new preprocessed repros, our `_RESTRICT`s in the declaration of `_Adjacent_difference_no_overlap` are being expanded to plain `restrict`. If I had to guess, I'd say that CUDA is replacing `__restrict__` with `restrict` under the expectation that `__restrict__` is only used in C mode.
Fixes VSO-2295101 / AB#2295101 again.

Don't use `__restrict__` for CUDA

---

stl/inc/deque
stl/inc/forward_list
stl/inc/list
stl/inc/vector

Resolves #5076 by statically asserting the mandates for the sequence containers `deque`, `forward_list`, `list`, and `vector`.
`basic_string` also defines a function `assign_range()`, but I did not add a static assert to it: `basic_string` includes its own specification of `assign_range()` which does not provide for any *Mandates* ([\[string.assign\]/16](https://eel.is/c++draft/strings#string.assign-16)).  Besides, the standard doesn't list `basic_string` among the sequence containers in [\[sequence.reqmts\]/1](https://eel.is/c++draft/sequence.reqmts#1), so it appears to me that [\[sequence.reqmts\]/60](https://eel.is/c++draft/sequence.reqmts#60) doesn't apply directly to `basic_string`.

Enforce `assign_range()` mandates for sequence containers

---

benchmarks/src/find_and_count.cpp
stl/inc/__msvc_string_view.hpp
stl/inc/algorithm
stl/inc/xutility
tests/std/tests/VSO_0000000_vector_algorithms/test.cpp

Towards #5036 
Benchmark                                                                  |    main  |     this | comment
---------------------------------------------------------------------------|----------|----------|-----
`bm<uint8_t, not_highly_aligned_allocator, Op::FindSized>/8021/3056`       | 37.2 ns  |  45.8 ns | random variation
`bm<uint8_t, not_highly_aligned_allocator, Op::FindSized>/63/62`           | 3.86 ns  |  3.30 ns |
`bm<uint8_t, not_highly_aligned_allocator, Op::FindSized>/31/30`           | 6.91 ns  |  8.26 ns |
`bm<uint8_t, not_highly_aligned_allocator, Op::FindSized>/15/14`           | 6.05 ns  |  6.15 ns |
`bm<uint8_t, not_highly_aligned_allocator, Op::FindSized>/7/6`             | 2.76 ns  |  3.05 ns |
`bm<uint8_t, highly_aligned_allocator, …

Vectorize `basic_string::rfind` (the single character overload)

---

stl/inc/algorithm
tests/std/include/range_algorithm_support.hpp
tests/std/test.lst
tests/std/tests/GH_002885_stable_sort_difference_type/env.lst
tests/std/tests/GH_002885_stable_sort_difference_type/test.cpp

By using `ptrdiff_t` when the related value is guaranteed to be small enough and/or used in pointer arithmetic. Fixes #2885.

`<algorithm>`: Fix bogus pointer arithmetic with integer-class

---

stl/inc/__msvc_chrono.hpp
stl/inc/chrono
stl/inc/experimental/filesystem

After #4457 removed `_To_timespec64_sys_10_day_clamped`, `<mutex>` and friends no longer depend on `system_clock`, so `system_clock` can be moved back to `<chrono>`.
This PR also moves `high_resolution_clock` and `chrono_literals` to `<chrono>` since they are not used in STL headers.

Move `system_clock` from `<__msvc_chrono.hpp>` to `<chrono>`

---

stl/inc/__msvc_string_view.hpp
tests/std/tests/VSO_0000000_vector_algorithms/test.cpp

Resolves #5036
**⚠️ Need to decide whether this CRT replacing vectorization is needed ⚠️** 
`basic_string::find` is already vectorized for 8 and 16 bit characters via calling `memchr` and `wmemchr`
`memchr` shows good results for smaller positions, but if the distance from the beginning to the result is long the `memchr` results are noticeably worse. There's strong indication that such a results are due to not using AVX in `memchr`.
`wmemchr` is not fast at all. It was promised to be fast in a new CRT in #4873 though.
For larger characters the vectorization is novel, there's no CRT implementation, but these characters are rare anyway.
Benchmark                                                              |      main    |       this …

Vectorize `basic_string::find`

---

stl/src/syserror_import_lib.cpp

Fixes #3254, a regression introduced by #2669 in VS 2022 17.3.
Thanks to:
* @cppdev123, who first reported the regression and whose PR #3260 inspired this alternative approach,
* @fsb4000 for noting an issue with that PR (in https://github.com/microsoft/STL/pull/3260#issuecomment-1336299026),
* @sylveon for suggesting the US English approach (in https://github.com/microsoft/STL/pull/3260#issuecomment-1336337294),
* @davemcincork for providing an extra-simple repro (in https://github.com/microsoft/STL/issues/3254#issuecomment-1991532148),
* @muellerj2 and @TheStormN for checking single-language OS installations,
* and everyone else who commented on these issues and PRs.
The original (pre-#2669) strategy of using language ID 0 to request [`FormatMessageA`'s multi-step …

Prefer US English for `system_category()` messages, fall back to system locale, then ID 0

---

stl/inc/atomic
tests/std/tests/Dev11_0863628_atomic_compare_exchange/test.cpp

Fixes #5123.
Perhaps this should be backported to old modes as we backported WG21-P0883R2.

Implement LWG-4169 `std::atomic<T>`'s default constructor should be constrained

---

stl/inc/bitset
stl/inc/vector
tests/std/tests/Dev10_860410_bitset_ctors/test.cpp
tests/std/tests/Dev11_0437519_container_requirements/test.compile.pass.cpp

Implement LWG-4140 Useless default constructors for bit reference types

---

stl/inc/filesystem
stl/inc/xfilesystem_abi.h
stl/src/filesys.cpp
stl/src/filesystem.cpp

Fixes #3571 for `<filesystem>` and `<experimental/filesystem>`.
The fix for `<experimental/filesystem>` affects the redist because it changes the implementation of `_Equivalent` in `filesys.cpp` that is exported by msvcp140.dll.
There is no additional test coverage because a reliable test for this issue would involve setting up a drive commonly producing such transient file IDs. But I verified manually with a drive shared by Remote Desktop that (a) false positives by `std::filesystem::equivalent` and `std::experimental::filesystem::equivalent` are present without this PR and (b) are gone with it. I also added comments at the top of `_Equivalent` and `__std_fs_equivalent` that reference #3571 and serve as a reminder why the file handles can't be closed before file IDs for both files have …

Fix false positives by `filesystem::equivalent` on file systems with transient file IDs

---

stl/inc/random
tests/std/tests/Dev11_0577418_random_seed_0/test.cpp

Fixes #5133.
The behavior change was indicated by changes in the test file. LWG-4014 restores the old behavior, which can be indicated by reverting of the change in that line in the test file.

Implement LWG-4014 LWG-3809 changes behavior of some existing `std::subtract_with_carry_engine` code

---

stl/inc/execution
stl/inc/memory
stl/inc/xmemory
tests/std/tests/P0040R3_extending_memory_management_tools/test.cpp
tests/std/tests/P0784R7_library_machinery/test.cpp

Also implements guaranteed copy elision in `std::uninitialized_copy/_n`, which has been implicitly required since C++17 without DR.
Corresponding `ranges` algorithms might also need to perform guaranteed copy elision, but that fix wouldn't affect well-formedness (for, IIUC, it would merely reduce moving when initializing constructor arguments). Perhaps we can do that in another PR.
Fixes #5113.

Implement LWG-3918 `std::uninitialized_move/_n` and guaranteed copy elision

---

stl/inc/xlocnum
tests/std/test.lst
tests/std/tests/LWG4084_iostream_uppercase_inf_nan/env.lst
tests/std/tests/LWG4084_iostream_uppercase_inf_nan/test.cpp

Fixes #5120.
It seems that the outputting Inf/NaN with `uppercase` was never tested before.

Implement LWG-4084 `std::fixed` ignores `std::uppercase`

---

stl/inc/ranges
tests/libcxx/expected_results.txt
tests/std/tests/P0896R4_views_filter/test.cpp
tests/std/tests/P0896R4_views_join/test.cpp

Fixes #5116. This affects `filter_view` & `join_view`'s iterators.
Skipped libcxx test:
- `std/ranges/range.adaptors/range.join/range.join.iterator/arrow.pass.cpp`

Implement LWG-4112 `has-arrow` should require `operator->()` to be `const`-qualified

---

stl/inc/chrono
tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp

Fixes #5121.
The default to `%F %T %Z` specification for _`locale-time-format-t`_ seems already implemented and tested when chronat was initially implemented.

Implement LWG-4124 Cannot format `zoned_time` with resolution coarser than seconds

---

stl/inc/chrono
tests/std/tests/P0355R7_calendars_and_time_zones_dates/test.cpp

Avoid arithmetic overflow in the constructors of `weekday`

---

stl/inc/valarray
tests/std/tests/GH_000140_adl_proof_construction/test.compile.pass.cpp

Towards #140 and #3100.
IMO it's quite insane to use an ADL-incompatible type with `valarray` (or any numeric utility that expects overloaded operators). However, LWG-3133 relaxed the requirements for "[numeric types](https://en.cppreference.com/w/cpp/named_req/NumericType)" so much that ADL-bombs became acceptable. This PR also arguably implements LWG-3133 (by using `std::addressof` instead of `operator&`).

`<valarray>`: Make `valarray` ADL-proof as required

---

stl/inc/regex
tests/libcxx/expected_results.txt
tests/std/include/test_regex_support.hpp
tests/std/tests/VSO_0000000_regex_use/test.cpp

Fixes #4995.
Unblocks libcxx test `std/re/re.regex/re.regex.construct/bad_range.pass.cpp`.
Note that I did not add test coverage for regular expressions like `[[.a.]-e]`: After this change, this regex is rejected as well (rather than parsed incorrectly). However, such regular expressions should actually be accepted (!), because `[.xxx.]` is not a set of characters, but (kind of) a single character if `xxx` is the name of a valid collating element. But support of collating symbols is currently so terribly broken that it is basically guaranteed to produce wrong results (see https://github.com/microsoft/STL/issues/994#issuecomment-1603697429), so I think it would be a major disservice to users if we actually accepted this regex without a major overhaul of collation support in the …

`<regex>`: Always reject character ranges with set limits

---

stl/inc/regex
tests/std/tests/VSO_0000000_regex_use/test.cpp

Partially addresses #992 (or, from a different perspective, fixes the issue exposed by the provided test case).
After this change, class escapes are handled correctly when they appear outside character class definitions, but not when they are used inside them. So regular expressions like `\S` or `\D` do work correctly now, but `[\S]`, `[\D]` or `[0\D]` still show the defective behavior.
The fix uses the observation that `\A` for some negated character class A is equivalent to the class definition `[^\a]` and `[^\a]` is handled correctly by parser and matcher.
Drive-by change: Removes useless boolean parameter from `_Parser::_ClassEscape`.

`<regex>`: Repair character class escapes outside character class definitions

---

stl/inc/yvals_core.h

This is a new warning MSVC is adding to steer users away from attempting to specialize the type traits as forbidden by N4993 [meta.rqmts]/4. Since MSVC implements many of the type traits in the compiler, such specializations are generally ignored to the confusion of users who trigger the UB.
This is a mirror of the STL portion of MSVC-PR-596210.

Globally suppress C5278

---

README.md
azure-devops/config.yml
azure-devops/create-1es-hosted-pool.ps1
azure-devops/provision-image.ps1
tests/std/tests/Dev09_056375_locale_cleanup/test.cpp
tests/std/tests/P0323R12_expected/test.cpp
tests/std/tests/P1502R1_standard_library_header_units/custom_format.py
tests/std/tests/P2502R2_generator/test.cpp

+ Updated build compiler to VS 2022 17.13 Preview 2.
+ Updated Python to 3.13.1.
+ Updated VMs to compute-optimized [F32as_v6](https://learn.microsoft.com/en-us/azure/virtual-machines/sizes/compute-optimized/fasv6-series).
* Remove workarounds for:
+ VSO-2188364 "EDG assertion failed in `conversion_for_direct_reference_binding_possible`".
+ VSO-2254804 "EDG ICE in `cpfe.dll!make_coroutine_result_expression` with C++23 `<generator>` test".
+ VSO-2046190 "\[CI-NIGHTLY\]\[Libs-ASan-amd64\] `src\vctools\crt\github\tests\std\tests\Dev09_056375_locale_cleanup` failed due to ERROR: AddressSanitizer: access-violation on unknown address".
* Add `/shallowScan` to work around VSO-2293247 …

Toolset update: VS 2022 17.13 Preview 2, F32as_v6

---

stl/inc/queue
stl/inc/stack

The standard requires checking that `c.append_range(std​::​forward<R>(rg))` is well-formed, so this fix pedantically conforms to the standard.
Although it doesn't make sense for some containers' `append_range` to only accept the rvalue range, there's nothing wrong with being completely consistent with the standard.

`<stack>`, `<queue>`: Add `std::forward` for `append_range`

---

stl/inc/xmemory
tests/std/test.lst
tests/std/tests/VSO_2318081_bogus_const_overloading/env.lst
tests/std/tests/VSO_2318081_bogus_const_overloading/test.compile.pass.cpp

* Followup to #5135.
* Reported llvm/llvm-project#119084.
* Fixes VSO-2318081 / AB#2318081 "\[RWC\]\[prod/fe\]\[Regression\] 4 projects failed with error C2440: 'initializing': cannot convert from `'const llvm::Value *'` to `'_Ty'`".
In an ideal world with infinite capacity, we would push through RWC fixes as we did with #5105. However:
* :santa:
* These fixes will be more intrusive than adding `#include <chrono>`.
* I suspect that a fair amount of code will be affected and LLVM is just the first canary, even though `uninitialized_meow()` is relatively obscure.

`<xmemory>`: Tolerate bogus const-overloading in iterators passed to `uninitialized_meow()`

---

stl/inc/__msvc_ranges_to.hpp
tests/std/tests/P1206R7_ranges_to_misc/test.cpp

In #4539, the `ranges::for_each` call in the resolution of LWG-4016 was "manually inlined" to reduce inclusion dependency. However, the inlining was not always correct, because builtin-in range-`for` may just stop and fail when a deleted member `begin`/`end` function is encountered, while `ranges` CPOs continue to consider ADL-found `begin`/`end`.
As a result, we should still use `ranges::begin`/`ranges::end`.
Fixes #5172.

`<ranges>`: Fix regression with `ranges::to` for ADL-only `begin`/`end`

---

stl/inc/format

This is the followup of #5173.

`<ranges>`: Fix formatting ranges for ADL-only ranges

---

stl/debugger/STL.natvis

`std::string_view` should be shown similar to `std::string` in debugger for basic view.

`STL.natvis`: Simplify visualization for `string_view`

---

stl/debugger/STL.natvis

It appears that debugger visualizer accepts `na` regardless if underlying char type

`STL.natvis`: Simplify visualization for `string`

---

stl/inc/__msvc_ranges_tuple_formatter.hpp
stl/inc/any
stl/inc/chrono
stl/inc/exception
stl/inc/execution
stl/inc/expected
stl/inc/experimental/filesystem
stl/inc/filesystem
stl/inc/functional
stl/inc/future
stl/inc/memory
stl/inc/optional
stl/inc/regex
stl/inc/stdexcept
stl/inc/system_error
stl/inc/typeinfo
stl/inc/xiosbase
tests/libcxx/expected_results.txt
tests/std/tests/P2505R5_monadic_functions_for_std_expected/test.cpp

A [reddit thread](https://www.reddit.com/r/cpp/comments/1h9u4us/should_stdexpected_be_nodiscard/) has persuaded me to explore marking entire types as `[[nodiscard]]`, which previously we reserved for guard types only.
We're very careful about avoiding `[[nodiscard]]` false positives. Marking an entire type affects all user-defined functions returning that type (as well as all temporary constructions), with no `[[discard]]` antidote available for function declarations. (Individual callsites can always be `(void)` suppressed.) For existing types like C++11 `error_code`, I continue to believe that too much time has passed for it to be reasonable to mark the entire type now.
However, while explaining our original decision again, I remembered that `<expected>` is actually still new to C++23. I …

Mark `expected`, `unexpected`, and ALL exception types as `[[nodiscard]]`

---

stl/inc/yvals_core.h

Update C++20 section of <yvals_core.h> for WG21-P3136R1 Retiring Niebloids

---

tests/CMakeLists.txt
tests/utils/stl/test/params.py
tests/utils/stl/test/tests.py

Adding a new target STL-only-edg-tests which will run only edg tests.

Add support for running only edg tests

---

stl/inc/regex
tests/std/tests/Dev10_814245_regex_character_class_crash/test.cpp

This PR deals with three related problems for character ranges in case-insensitive mode:
* `_Builder::_Add_range()` casts the character bounds to `unsigned int`. As a consequence, characters with negative numeric values are not added to the bitmap, but rather to the `_Large` list of characters. This means that these characters are not found during matching. (Note the suspiciously different casts in the else branch for the case-sensitive case.)
* The parser fails to reject some empty ranges in case-insensitive mode such as `[Z-a]` (= `[z-a]`).
* When both the `collate` and `icase` flags are set, there is an unnecessary call to translate the bounds by `_Traits.translate()` first before passing them to `_Traits.translate_nocase()`. The standard says in [\[re.grammar\]/14.1 and …

`<regex>`: Fix character range bounds in case-insensitive regexes

---

stl/inc/regex
tests/std/tests/VSO_0000000_regex_use/test.cpp

According to [Sections 9.3.6 and 9.5.1 of the POSIX standard](https://pubs.opengroup.org/onlinepubs/9699919799.2008edition/basedefs/V1_chap09.html#tag_09_03_06), a backreference is a backslash followed by a single digit, so `\1` to `\9`. Thus, `\(a\)\10` is a valid basic regular expression matching the string `aa0`, because `\10` is a backreference to capture group 1 (`\(a\)`) plus the digit 0. However, the regex parser currently rejects this regular expression because it interprets `\10` as a backreference to capture group 10.
After this PR, the parser only reads a single digit in basic regular expression (and grep) mode, so `\10` is parsed correctly as a backreference to capture group 1 plus digit 0.

`<regex>`: Limit backreference parsing to single digit for basic regular expressions

---

tests/libcxx/expected_results.txt

... which are mostly related to `<regex>`.

Categorize some failing libcxx tests

---

stl/inc/xlocale
stl/inc/yvals_core.h
stl/src/locale0.cpp

Towards #5184.
I'm not sure whether it is wanted to expose equivalent functionality under an _Ugly name.

`<xlocale>`: Deprecate non-Standard `locale::empty()`

---

stl/inc/expected
stl/inc/optional
tests/std/tests/P0220R1_optional/test.cpp
tests/std/tests/P0323R12_expected/test.cpp

Also speculatively implement LWG-3424 for `expected` to avoid `volatile`-qualified return types, and complete the speculative implementation for `optional`.
Some parts of the resolution is not meaningful yet and not tested due to LWG-3891.
Fixes #5119.

Implement LWG-3886 Monad mo' problems (in `optional` and `expected`)

---

stl/inc/thread

Fixes #5234.
We were carefully forming `decltype(_Now + _Rel_time) _Abs_time`, the common type of the given `_Rel_time` (which could be coarse or fine) and `chrono::steady_clock::now()` (which is nanoseconds).
In this bug scenario, `_Rel_time` and therefore the common type are picoseconds.
The problem was that we weren't careful about our `_Forever` constant. We were using `(chrono::steady_clock::time_point::max)()`, but then converting it to the common type (implicitly in the subtraction `_Forever - _Rel_time`, and in the assignment `_Abs_time = _Forever`). When the common type is finer-grained, this attempts to multiply the stored value, but it's already the maximum, so we overflow.
The fix is to use the common type for `_Forever`. This stores the maximum rep with the proper period of …

`<thread>`: Avoid overflow in `_To_absolute_time()`

---

README.md

This is an exceedingly _minor_ contribution, so feel free to disregard it. 
When running the ASan'ized tests, I could have used a reminder that the python test script resides within the `.\out\<arch>` folder. The preceeding `cmake` commands should run in the repo's root, so it's easy to forget changing your directory when running the `python <pathToTestScript>/stl-lit.py` command.
This PR adds a reminder that the call to `stl-lit.py` should be performed from `out\x64\` , to make this clearer.
Please feel free to dismiss this, it's a subjective contribution. Thanks!

Clarify ASan test running instructions

---

tests/std/tests/P0323R12_expected/test.cpp

Copy of #5246, but restructured into two commits.
@CaseyCarter left Microsoft, so the CLA bot is blocking his original PR. The changes were written before he left, so Microsoft owns them, and I can copy them here.

Expand workaround for EDG bug in `P0323R12_expected`

---

README.md
azure-devops/config.yml
azure-devops/provision-image.ps1
stl/inc/type_traits
tests/std/tests/P0898R3_concepts/test.cpp
tests/std/tests/P1502R1_standard_library_header_units/custom_format.py

+ Updated build compiler to VS 2022 17.13 Preview 4.
* PowerShell 7.5.0.
* New pool.
* VS 2022 17.13 Preview 4.
+ Still not yet required due to the internal toolset being 17.12-based.
* Remove workaround for VSO-2293247.
* Remove workarounds for DevCom-1627396.
[STL-ASan-CI passed.](https://dev.azure.com/vclibs/STL/_build/results?buildId=18204&view=results)

Toolset update: VS 2022 17.13 Preview 4

---

stl/inc/xstring
tests/std/tests/GH_002030_asan_annotate_string/test.cpp

Fixes #5251
**Problem:**
As described in the linked bug, the following program should throw under `/fsanitize=address`:
```C++
int main()
{
// This crashes (expectedly)
//std::vector<int> vec;
//vec.reserve(100);
//vec.data()[50] = 1;
// This does not crash (it should crash, like `vector`)
std::basic_string<char> myString;
myString.reserve(100);
char* data = &myString[0];
data[50] = 'A';
}
```
But it does not. This PR aims to fix that.
**Approach:**
The issue resides in `xstring`'s [`reserve` implementation](https://github.com/microsoft/STL/blob/9b38fb9ccca90fd8b31fd37d4512b190aeef4fe7/stl/inc/xstring#L2409-L2421), inlined below:
```C++
constexpr void reserve(_CRT_GUARDOVERFLOW const size_type _Newcap) {
// [... removed stuff]
const size_type _Old_size …
```

ASan should detect writing to a `basic_string`'s reserved but uninitialized memory

---

stl/inc/__msvc_chrono.hpp
stl/inc/__msvc_ranges_tuple_formatter.hpp
stl/inc/ostream
stl/inc/print
stl/inc/yvals_core.h
stl/src/print.cpp
stl/src/vector_algorithms.cpp
tests/std/tests/P2093R14_formatted_output/test.cpp

@GabrielDosReis informed me that the optimizer team discourages use of the `[[likely]]` and `[[unlikely]]` attributes, and instead encourages PGO/SPGO. (This aligns with what I've always said, "don't help the compiler".) We've accumulated a fair amount of usage of these attributes, *none* of which was motivated by benchmarking. Let's remove this noise from our codebase. If we ever find places where it actually affects performance (presumably for Clang/LLVM, since C2 pays minimal attention to the attribute), we can decide what to do.
* Remove direct usage of `[[likely]]` and `[[unlikely]]`.
* Remove `_LIKELY_X86_X64`, `_LIKELY_ARM_ARM64`, and clang-format suppression.
* Remove `_LIKELY` and `_UNLIKELY`.

Remove usage of `[[likely]]` and `[[unlikely]]`

---

README.md
azure-devops/config.yml
azure-devops/provision-image.ps1
stl/inc/__msvc_chrono.hpp
stl/inc/__msvc_ranges_tuple_formatter.hpp
stl/inc/ostream
stl/inc/print
stl/inc/type_traits
stl/inc/xstring
stl/inc/yvals_core.h
stl/src/print.cpp
stl/src/vector_algorithms.cpp
tests/std/tests/GH_002030_asan_annotate_string/test.cpp
tests/std/tests/P0898R3_concepts/test.cpp
tests/std/tests/P1502R1_standard_library_header_units/custom_format.py
tests/std/tests/P2093R14_formatted_output/test.cpp

Merge `main` to `feature/flat_map`

---

stl/inc/vector
stl/inc/xmemory
stl/inc/xstring
tests/std/tests/GH_002030_asan_annotate_string/test.cpp
tests/std/tests/GH_002030_asan_annotate_vector/test.cpp

**Context:**
The STL "annotates" the `vector` and `basic_string` containers so that ASan will report `container-overflow` whenever allocated _but un-initialized_ data is accessed.
A simple repro is the [`container overflow`](https://learn.microsoft.com/en-us/cpp/sanitizers/error-container-overflow?view=msvc-170#example-access-reserved-memory-in-a-stdvector) error fired in this sample program (assuming it's `/fsanitize=address`'ed):
```C++
// Compile with: cl /EHsc /fsanitize=address /Zi
int main() {   
std::vector<int> v(10);
v.reserve(20); // we've allocated 20 entries, but only initialized only 10
// Accessing the 10th entry (0-indexed, naturally) triggers an AV 
v[10] = 1;
}
```
This is sensible behavior in most cases. 
One case where it does not bode well is when an …

Add the ability to opt-out of ASan container annotations on a per-allocator basis

---

tests/libcxx/expected_results.txt

Mirrors internal MSVC-PR-610616 "Zc for conformant u8 string encoding of escape sequences".
(I'm refraining from nitpicking the comment too closely because updating it requires rerunning the internal PR checks and that's time-consuming.)
These are phrased as `:9 SKIPPED` which skips them for the MSVC-internal test harness only, as the new warning has not yet shipped. When it does, we'll need to update this to `:0 FAIL` and `:1 FAIL`, or work with upstream LLVM to fix their non-conformant test code.

Update libcxx skips for a new compiler warning

---

.gitignore
README.md
azure-devops/config.yml
azure-devops/create-1es-hosted-pool.ps1
azure-devops/provision-image.ps1
stl/inc/__msvc_bit_utils.hpp
stl/inc/__msvc_ranges_to.hpp
stl/inc/__msvc_ranges_tuple_formatter.hpp
stl/inc/experimental/filesystem
stl/inc/functional
stl/inc/memory_resource
stl/inc/mutex
stl/inc/ranges
stl/inc/xstring
stl/inc/xutility
stl/inc/yvals_core.h
stl/src/vector_algorithms.cpp
tests/libcxx/expected_results.txt
tests/std/tests/P1169R4_static_call_operator/test.compile.pass.cpp
tools/scripts/print_failures.py

+ Updated build compiler to VS 2022 17.14 Preview 1.
+ Updated Google Benchmark to 1.9.1.
+ Updated Python to 3.13.2.
* VS 2022 17.14 Preview 1.
* Remove workaround for DevCom-10373274 "vcruntime nothrow array operator new falls back on the wrong function".
* Remove workaround for DevCom-10808176 "MSVC doesn't properly destroy a loop variable in constant evaluation".
+ However, `mdspan/index_operator.pass.cpp` is still failing due to a likely MSVC constexpr bug, "note: failure was caused by a read of a variable outside its lifetime".
All of MSVC/Clang/EDG now support C++23 WG21-P1169R4 `static operator()`, so let's update the codebase:
* Remove `#ifdef __cpp_static_call_operator` …

Toolset update: VS 2022 17.14 Preview 1

---

stl/inc/generator

Resolves #5111 
I decided to look into this issue because I like coroutines and wanted to try contributing something.
It turns out that the implementation is quite straight forward, just adding a `yield_value` overload taking a generator by lvalue reference which is otherwise the exact same as the overload taking a generator by rvalue reference.
Since the LWG paper doesn't state specific numbers and to test the implementation I wrote a short test which I tried with both the current STL (as shipped with VS 17.13.0) and my patched version and in both Debug and Release configurations.
```
#include <generator>
#include <algorithm>
#include <chrono>
#include <print>
constexpr int N = 100000;
std::generator<int> f() {
co_yield 1;
}
std::generator<int> g_rvalue()
{
for (int i = 0; i < N; i++) { …
```

LWG-3899 co_yielding elements of an lvalue generator is unnecessarily inefficient

---

.github/workflows/update-status-chart.yml
README.md
azure-devops/checkout-self.yml
azure-devops/config.yml
azure-devops/create-1es-hosted-pool.ps1
azure-devops/provision-image.ps1
stl/inc/__msvc_bit_utils.hpp
stl/inc/__msvc_int128.hpp
stl/inc/__msvc_iter_core.hpp
stl/inc/__msvc_ranges_tuple_formatter.hpp
stl/inc/array
stl/inc/cmath
stl/inc/string
stl/inc/utility
stl/inc/xmemory
stl/inc/yvals_core.h
tests/libcxx/expected_results.txt
tests/std/tests/Dev11_0535636_functional_overhaul/test.cpp
tests/std/tests/GH_000639_nvcc_include_all/test.compile.pass.cpp
tests/std/tests/P0019R8_atomic_ref/test.cpp
tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp
tests/std/tests/P0896R4_views_take/test.cpp
tools/format/CMakeLists.txt

Resolves #5074. Resolves #5282. Resolves DevCom-10863472 VSO-2411436.
- Fixed bugs:
* Fixed compiler errors when using `<format>` in a CUDA project, by adding a compiler bug workaround.
+ Updated build compiler to VS 2022 17.14 Preview 2 (now required).
+ Updated Clang to 19.1.5.
* Node.js 23.9.0.
+ Increasing our minimum required Node version for the Status Chart isn't necessary at this time, but I like to keep this updated on a semi-regular basis.
* Require VS 2022 17.14.
+ The MSVC-internal toolset has *finally* been updated, allowing us to require 17.14.
* Remove workaround for CUDA 9.2's lack of `if constexpr`.
+ I added this workaround in #772, merged 2020-05-01. We began …

Toolset update: VS 2022 17.14 Preview 2, Clang 19.1.5

---

stl/inc/xutility
tests/std/tests/P2278R4_basic_const_iterator/test.cpp

By befriending `basic_const_iterator` specializations. Fixes #5321.

`<xutility>`: Fix conversion between `basic_const_iterator`s

---

stl/inc/chrono
tests/std/tests/P0355R7_calendars_and_time_zones_io/test.cpp

Implement LWG-3956 `chrono::parse` uses `from_stream` as a customization point

---

.github/workflows/compile-typescript.yml
README.md
package-lock.json
package.json
src/weekly_table.mts

In addition to the usual weekly/dependency updates, this updates the Personal Access Token instructions in response to GitHub and MS policy changes.

Status Chart: Weekly updates, PAT instructions

---

stl/debugger/STL.natvis

This PR adds visualizers for `std::flat_set` and `std::_Pairing_iterator_provider<*>::_Iterator`. In https://github.com/microsoft/STL/pull/4887, I didn't add a visualizer for the iterator of `std::flat_map`.
<details><summary>Example/Preview</summary>
This is a bit larger, but shows a `std::flat_map` in {vector, deque}*{vector, deque} combos, a `std::flat_set` with vector and deque containers, a `std::map` + `std::set` (for comparison), and their iterators.
<details><summary>Code</summary>
```cpp
#include <deque>
#include <flat_map>
#include <flat_set>
#include <map>
#include <set>
template <typename KeyContainer, typename MappedContainer> auto makeFlatMap() {
std::flat_map<int, std::string, std::less<int>, KeyContainer, MappedContainer>
map;
map.emplace(42, "hello …
```

Add visualizer for `std::flat_set` and flat-map iterators

---

stl/inc/algorithm

Improves control flow by avoiding negation and `continue`.
Also a performance improvement, though a very minor one, and, as such, probably falls under _Don't Help The Compiler_ ™️

`<algorithm>`: avoid `continue` in `ranges::search_n`

---

README.md

This PR updates the C++ Working Draft reference in README.md from N5001 to N5008.
- Line 61: Updated "[N5001][]" to "[N5008][]".
- Line 571: Updated the reference link from "https://wg21.link/N5001" to "https://wg21.link/N5008".
This is a minor documentation update and does not affect the code or ABI.
Fixes #5342

Update README.md to reference N5008 instead of N5001

---

tests/std/tests/P0896R4_ranges_iterator_machinery/test.cpp

The compiler recently addressed an [external bug](https://developercommunity.visualstudio.com/t/conditional-operator-gives-wrong-result-/10665330) and along with that is a better system for handling user-authored casts in `decltype` expressions.
The fix above does not completely fix the compiler behavior mentioned in the workaround, it only makes the compiler more consistently return the type determined in cast expressions.

Prepare ranges test for MSVC fix

---

stl/inc/regex
tests/std/tests/VSO_0000000_regex_use/test.cpp

This PR provides the symmetric change to #5165 for the dollar sign in basic and grep mode. Similar to the handling of the caret anchor, this PR recognizes a dollar sign as an anchor in a basic regular expression if it is at the end of an alternative. It does so by doing a bit of lookahead.
Drive-by: Remove a duplicated test that was accidentally added in #5165.

`<regex>`: Properly parse dollar anchors in basic and grep mode

---

stl/inc/regex
tests/std/tests/VSO_0000000_regex_use/test.cpp

Fixes a regex miscompilation noticed in #5165.
The POSIX standard says that the right bracket ] is not special at the beginning of a bracketed character class (https://pubs.opengroup.org/onlinepubs/009696699/basedefs/xbd_chap09.html#tag_09_03_05). This means that an initial ] behaves like any other character, so it may also be the start of a character range.

`<regex>`: Allow initial `]` to start character ranges in POSIX regular expressions

---

stl/inc/regex
tests/std/tests/VSO_0000000_regex_use/test.cpp

Fixes #5371.
The [ECMAScript standard](https://262.ecma-international.org/#sec-compileassertion) effectively states that `\b` matches a position `i` in the string iff `IsWordChar(i-1) xor IsWordChar(i)` is true. It also defines that for positions `i = -1` and `i = length(input)`, `IsWordChar(i)` always returns `false`. Thus, `\b` does not match anything in the empty string.
Since `\b` does not match the empty string, the flags `match_not_bow` and `match_not_eow` don't matter in this case.

`<regex>`: Fix word bounds `\b` and `\B` when applied to the empty string

---

stl/inc/regex
tests/std/tests/VSO_0000000_regex_use/test.cpp

`<regex>`: Make back-references to unmatched capture groups not match anything in POSIX basic regexes

---

stl/inc/regex
tests/std/tests/VSO_0000000_regex_use/test.cpp

Towards #5365. Fixes the behavior for POSIX regexes: [Section 9.3.6](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap09.html#tag_09_03_06) says that backreferences always refer to the last matched string if a capture group/subexpression has been matched more than once, so captures should not be cleared during matching at all.

`<regex>`: Do not reset matched capture groups in POSIX regexes

---

stl/inc/type_traits

MSVC and EDG don't provide this intrinsic yet, for which DevCom-10870354 is filed.
Closes #5333.

`<type_traits>`: Use the `__is_scoped_enum` intrinsic for Clang

---

stl/inc/future
stl/inc/memory

These comments referenced proposed resolutions for LWG-3210, LWG-4024, and LWG-4154, which have now been officially accepted as part of the Working Draft (November 2024 meeting). The implementations were already aligned with the standard, so the references are no longer necessary.
This PR simply removes those comments, with no behavioral changes.
Fixes #5127.

Remove comments for LWG-3210, LWG-4024, and LWG-4154

---

benchmarks/src/unique.cpp
stl/src/vector_algorithms.cpp

Vectorized `remove` has carefully considered `find` before actual removal loop. But the similar `adjacent_find` was missed in `unique`.
The effect is at least performance. Find is faster as vectorization, and it also avoids extra writes. I doubt about whether they have correctness impact though.
I've added the missing piece in separately compiled code. This is not the same as in `remove`, where it is in the header. But `unique` has in-place search for duplicates in scalar part that is tightly coupled with the rest of it, so I thought it is better to avoid disrupting that.
The modified benchmark adds two regions without duplicates: at the beginning and at the end of the range. The beginning one is avoidable with `adjacent_find`.
I've ran the modified benchmark for the `main` before #5092, …

Search for first duplicate in vectorized `unique`

---

.github/ISSUE_TEMPLATE/bug-report.md

Approximately every issue has backticks around the header name, surely the template should have em too?

`bug-report.md`: Add backticks to default title

---

stl/inc/xfilesystem_abi.h

I noticed some rather peculiar behavior regarding the Win32 API `GetFileAttributesExW()`. Specifically, I found that upon calling this function with an invalid path (in my case, a remote URI) in two separate applications, both would fail as expected. What is interesting is that - for some inexplicable reason - the error code returned by `GetLastError()` differed between these two applications. Specifically, it was always either one of the following:
* `ERROR_INVALID_NAME`: The file name, directory name, or volume label syntax is incorrect.
* `ERROR_BAD_PATHNAME`: The specified path is invalid.
When this occurred, I was making use of the throwing `std::filesystem::exists()` overload. So, you could imagine my surprise when this function threw an exception on one of the applications and …

Added a missing case for `__std_is_file_not_found()`.

---

stl/inc/utility
stl/inc/variant
stl/inc/xutility
stl/inc/yvals_core.h

Move `monostate` (from `<xutility>`) and related definitions (from `<variant>`) to `<utility>`.
`<utility>` is included by both headers, so no code is broken.
resolves #5294

Implement P0472R3 - Put `monostate` in `<utility>`

---

tests/std/tests/P0896R4_ranges_alg_copy/test.cpp
tests/std/tests/P0896R4_ranges_alg_transform_unary/test.cpp
tests/std/tests/P2321R2_views_adjacent/test.cpp
tests/std/tests/P2321R2_views_adjacent_transform/test.cpp
tests/std/tests/P2441R2_views_join_with/test.cpp

Fixes internal VSO-2431296, where `P2321R2_views_adjacent` is sporadically running out of memory for x86-native `/analyze:only` configurations. (Internal builds of the compiler have a bit more debug logic than retail builds, which is why we haven't seen these failures in our GitHub PR/CI system.)
Related:
* #1030
* #3567
Our stressful ranges/views tests, combined with Static Analysis's increased compiler memory consumption, interact poorly with the ***ABSOLUTE ABOMINATION*** of x86-hosted toolsets in the year 2025.
I modified #3567's incantations to find all of the tests that were consuming 3+ GB for x86-native `/analyze:only`, then added our usual workarounds, reducing the peak working set sizes (in bytes) to reasonable levels:
Test                                 |     Before    | …

Fix sporadic test failures by avoiding excessive compiler memory consumption

---

stl/inc/ranges
tests/std/tests/P2474R2_views_repeat/test.cpp

Currently, there're  (at least) three bugs in the `piecewise_construct_t` constructor of `repeat_view`:
1. It can be ambiguous with the internal constructor it uses when constructing `repeat_view` from empty braces.
2. The internal constructor it uses contains an unqualified call to `_Tuple_get`, which can cause hard error when used with some ADL-unfriendly types.
3. It constructs the sentinel with `_STD make_from_tuple<_Bo>(_Bound_args)`, where a `std::move` cast specified by [[range.repeat.view]/5](https://eel.is/c++draft/range.repeat.view#5) is missing.
This PR removes the internal constructor and introduces a `_Make_box_from_tuple` function template that emulates `std::make_from_tuple` to implement [[range.repeat.view]/5](https://eel.is/c++draft/range.repeat.view#5) more closely to …

`<ranges>`: Fix piecewise construction for `repeat_view`

---

stl/debugger/STL.natvis

When the `time_point` is sometime in February, the debugger visualization of the year will be off-by-one.
You can test this with this little snippet:
```
#include <chrono>
int main()
{
using namespace std::chrono;
constexpr year_month_day ymd = 2025y / 2 / 15;
constexpr system_clock::time_point tp = sys_days{ ymd };
std::cout << ymd << " | " << tp << std::endl;
}
```
The console output will be correct:
`2025-02-15 | 2025-02-15 00:00:00.0000000`
But the debugger shows a year of 2024 for `tp`:
As per the [referenced calculation](https://howardhinnant.github.io/date_algorithms.html#civil_from_days) used to construct the debugger visualization, the year should be calculated by this formula:
`const Int y = static_cast<Int>(yoe) + era * 400; ... (y + (m <= 2)`
But the nativs …

`STL.natvis`: Fixed `time_point` visualization of year off-by-one

---

stl/debugger/STL.natvis

`clang-cl` will produce 
```
std::chrono::time_point<std::chrono::system_clock,std::chrono::duration<long long,std::ratio<1,10000000>>>
```
as the type name for `std::chrono::system_clock::time_point` whereas MSVC will produce 
```
std::chrono::time_point<std::chrono::system_clock,std::chrono::duration<__int64,std::ratio<1,10000000>>>
```
Notice: `long long` vs `__int64` (https://github.com/llvm/llvm-project/issues/134156).
As a workaround, I added the type from `clang-cl` as an `<AlternativeType>`.

`STL.natvis`: Add alternative type name for `time_point`

---

stl/inc/flat_map
tests/libcxx/expected_results.txt

* Add missing constraints:
* `is_constructible_v<key_type, K>` is `true`
* `is_constructible_v<mapped_type, Args...>` is `true`
* Ignore ignoring return value of `operator[]`

Fix [flat.map.access] bugs found by libcxx tests

---

stl/inc/flat_map
tests/libcxx/expected_results.txt

* Add missing constraints:
* `is_constructible_v<pair<key_type, mapped_type>, Args...>` is `true`
* Always call `insert` in `insert`

Fix [flat.map.modifiers] bugs found by libcxx tests

---

stl/inc/deque
stl/inc/flat_map
stl/inc/vector
stl/inc/xmemory
stl/inc/xstring

libc++ tests seem to use some hostile sequence containers whose `push_back` have non-standard semantics for `flat_meow`. Per [[sequence.reqmts]/104](https://eel.is/c++draft/sequence.reqmts#104) and [/108](https://eel.is/c++draft/sequence.reqmts#108), this is unfortunately permitted, because `push_back` with the standard semantics is only required for `basic_string`, `deque`, `inplace_vector`, `list`, and `vector`.
AFAIK, most uses of flat container adaptors will use `vector` as the underlying containers. Also, every standard container adoptable for `flat_meow` has `push_back` with guaranteed semantics. So I think it's worthy enable `push_back` for the most usual uses.
Notes:
- Partial specialization of `_Has_guaranteed_push_back` for `list` is deliberately missing because `list` isn't …

`<flat_map>`: Restore use of `push_back` in `flat_(multi)map::insert`

---

CMakeLists.txt
README.md
azure-devops/config.yml
azure-devops/provision-image.ps1
stl/inc/random
tests/libcxx/expected_results.txt
tests/std/tests/P0088R3_variant/test.cpp
tests/std/tests/P0220R1_optional/test.cpp
tests/std/tests/P0758R1_is_nothrow_convertible/test.compile.pass.cpp
tests/std/tests/P0898R3_concepts/test.cpp
tests/std/tests/P2165R4_tuple_like_relational_operators/test.compile.pass.cpp

+ Updated build compiler to VS 2022 17.14 Preview 3.
+ Updated Python to 3.13.3.
* Python 3.13.3.
* New pool.
* VS 2022 17.14 Preview 3.
* Remove workarounds for:
+ VSO-2283373 "EDG: Failure to compare pointers to array elements in a constant expression".
+ DevCom-10107834 "EDG, `decltype` can't deduce type".
+ VSO-892705 "EDG reports `__is_convertible_to(int[], int*) == false`".
+ DevCom-1326684 "list-init of aggregate with explicitly-default-constructible member incorrectly accepted".
+ VSO-2417491 "C1XX `/permissive-` (strict mode) mishandles a variable template detecting static constexpr member functions".
+ DevCom-10701277 "`__builtin_memcmp()` yields erroneous results if …

Toolset update: VS 2022 17.14 Preview 3

---

stl/inc/regex
tests/std/tests/GH_005244_regex_escape_sequences/test.cpp

Short follow-up to #5380 to support escapes for closing brackets in POSIX regexes in accordance with the most recent POSIX standard version: https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/V1_chap09.html#tag_09_03_02 for basic and https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/V1_chap09.html#tag_09_04_02 for extended regexes.
Because of the (expected) test failures caused by this change, I noticed that the tests in `gh_5244_atomescape_posix_common` are called twice for `extended` and `egrep` from `test_gh_5244_atomescape_extended_or_egrep`: Once via `gh_5244_atomescape_posix_not_awk` and once via `gh_5244_atomescape_extended_egrep_awk`. That's once more than necessary, so let's get rid of this double-testing. I opted to remove the call of …

`<regex>`: Permit escaping of closing brackets in POSIX regexes

---

stl/inc/regex

Since we settled on some reasonable semantics for leftmost-longest matching in #5218, I think we should remove the code for some other (abandoned) attempt to implement the leftmost-longest rule in `_Matcher::_Do_if`: An attempt to set `Tgt_state` to the leftmost-longest match found under this `_N_if` node.
This is neither necessary (in leftmost-longest mode, we take the final result from `_Res`, not `_Tgt_state`) nor sufficient (it assigns one of the longest matches to `_Tgt_state`, but if there are several of the same length it doesn't necessarily pick the correct one among these matches).
On the other hand, this saves 96 bytes of stack space per call to `_Do_if` in debug mode, slightly alleviating the stack overflow issues (#997, #1528).
Potentially leaving `_Tgt_state` in a garbage …

`<regex>`: Simplify matching of `_N_if` NFA nodes in leftmost-longest mode

---

stl/inc/barrier
tests/std/tests/P1135R6_barrier/test.cpp

Currently, `barrier`'s constructor is unconditionally `noexcept`, but according to [`[thread.barrier.class]/11`](http://eel.is/c++draft/thread.barrier.class#11) this is incorrect. This PR fixes the problem by changing exception specification from `noexcept(true)` to `noexcept(is_nothrow_move_constructible_v<_Completion_function>)`.

`<barrier>`: Fix constructor's exception specification

---

benchmarks/src/adjacent_difference.cpp
benchmarks/src/minmax_element.cpp
tests/std/tests/VSO_0000000_vector_algorithms_floats/test.cpp

There's no reason to be negative biased.

Fix inconsistent use of `normal_distribution` in benchmarks and tests

---

stl/inc/optional

#5369 revealed VSO-2444237 "\[RWC\]\[prod/fe\]\[std:c++latest\]\[Regression\] LLVM failed with Assertion failed: `ParseTree::Utility::SigStack::sigStack.size() == 1`".
@xiangfan-ms tracked this down to the introduction of `_Derived_from_optional` and reduced it to a library-free repro. The compiler is having trouble with the lambda's templated function call operator.
To unblock our Real World Code test suite, we should extend the workaround we're currently using for EDG to also cover MSVC.

`<optional>`: Extend compiler bug workaround to MSVC

---

stl/inc/xstring
tests/std/test.lst
tests/std/tests/GH_005402_string_with_volatile_range/env.lst
tests/std/tests/GH_005402_string_with_volatile_range/test.cpp

Formerly, `(const) volatile CharT` arrays were inconsistently handled in legacy iterator pair functions and new functions added in C++23 WG21-P1206R7. In legacy functions, `(const) volatile CharT*` were not specially treated due to `_Is_elem_cptr`, but in P1206R7 functions, they were consistently treated with `(const) CharT*` due to `_Contiguous_range_of`.
This PR chooses to follow the convention of `_Contiguous_range_of` and changes `_Is_elem_cptr` to `_Is_elem_cvptr` to handle `(const) volatile CharT*`. For volatile contiguous ranges, we need to use non-vectorized element-wise assignment.
Fixes #5402.

`<string>`: Fix construction and insertion of `basic_string` with volatile ranges

---

stl/inc/random

This patch simplifies the construction of `std::poisson_distribution` by avoiding the computation of members that are not used when the mean is small, and vice versa.
This leaves the unused fields uninitialized, though it is unclear to me if this is acceptable or not.

`<random>`: Improve performance of `poisson_distribution` constructor

---

stl/inc/xutility

Inspired by https://github.com/microsoft/STL/issues/4676#issuecomment-2813715117

Remove mentions of 'fast math' from floating vectorization control

---

stl/inc/ranges
stl/inc/yvals.h

* Will be merged after #5432.
* Followup to #5274.
* For MSVC, this uses [`__fastfail`](https://learn.microsoft.com/en-us/cpp/intrinsics/fastfail?view=msvc-170):
+ "Support for the native fast fail mechanism began in Windows 8."
+ I am manually declaring the intrinsic because it's currently declared by the large `<intrin.h>`. We generally try to avoid duplicating intrinsic declarations (due to calling convention madness) but in this one case I think it's fine. Because `<yvals.h>` is very central and special, moving the declaration into `<intrin0.h>` might still be overly impactful.
+ I also need to hardcode `FAST_FAIL_INVALID_ARG` because there's no way we can drag in `<winnt.h>`.
* For Clang, this uses [`__builtin_verbose_trap`](https://clang.llvm.org/docs/LanguageExtensions.html#builtin- …

Win8 baseline: Improve STL Hardening codegen size

---

stl/src/filesys.cpp
stl/src/filesystem.cpp

* Will be merged after #5432.
* These changes are somewhat daring, hence the isolated PR. Our `<filesystem>` implementation (and older `<experimental/filesystem>`) contains several codepaths of the form "if we're a UWP app, call a modern API, otherwise call a legacy API". This is not only twice as much code to maintain, but we don't have automated test coverage for UWP apps, which greatly increases risk. Now that our baseline OS is Win8, we can send everything through the modern APIs.
* The change I'm the least certain about is in Standard `filesystem.cpp`, where `_Get_file_id_by_handle()` has the unusual pattern of calling modern `GetFileInformationByHandleEx()` and then falling back to legacy `GetFileInformationByHandle()`. See the commit notes below for why I suspect this is …

Win8 baseline: Simplify `<filesystem>` API calls

---

README.md

- I'm not a huge fan of backslashes in filenames, but I like inconsistency even less
- Apparently those mermaid diagrams don't like consecutive linebreaks, they return "Unsupported markdown: code" instead

README.md: Fix a few more typos

---

stl/src/vector_algorithms.cpp

Fix accumulated inconsistencies in `vector_algorithms.cpp`, separate commit each:
* More `const`, lately I've been trying to add `const` everywhere, but there is missing one in older code
* Use the same type for a variable as in the other similar branch. Unsigned type is selected, as we do bitwise thing with it
* Drop `_CSTD`, the C run time things used unqualified in this file in some other places
* `_Avx2_tail_mask_32` now takes bytes count. It is odd from the perspective of the function itself, but almost every call site has bytes, and even for the ones that don't, the lack of multiplication by 4 and multiplication by 2 instead of by 8 look odd.
Deliberately skipped namespace as per #5418 for now. These look more controversial, so I'd do just clean stuff first.

`vector_algorithms.cpp`: cleanup

---

stl/inc/random
stl/src/multprec.cpp

I noticed that we had a single remaining usage of separately compiled multiprecision arithmetic machinery. I believe that we can replace this with the modern `_Unsigned128` type, which is far better tested and more widely exercised. As @AlexGuteniev observed, `_Unsigned128` uses intrinsics, so it should also be faster than multprec.cpp. And as a final bonus, it makes this codepath strongly resemble the 32-bit and 64-bit codepaths above.
The function comment says: https://github.com/microsoft/STL/blob/b5df16a98934319e2e6864d6036cbe9cd9c74faf/stl/inc/random#L474-L482
The first part, _Cx <= (2^128 - 1), is obviously true.
The next part is (_Mx - 1) <= ((2^128 - 1) - _Cx) / _Ax. This is the hardest to achieve for the largest LHS (caused by the largest _Mx) and the smallest RHS (caused by the …

`<random>`: Use `_Unsigned128` for `linear_congruential_engine`

---

stl/inc/flat_map
tests/libcxx/expected_results.txt

Also makes `_Valid_compare_for_container` stricter per [container.adaptors.general]/6.2.

`<flat_map>`: Workaround for CWG-2369 in deduction guides

---

stl/inc/flat_map
tests/libcxx/expected_results.txt

There are some situations to care about:
* The comparator should always be copied, not ever moved, since moved out comparator may not satisfy invariants as it may not be able to compare at all (consider moved-out `std::function`)
* The keys and values size should always be equal, even for moved-out container when exception is thrown. The easiest way to accomplish that is to clear both in a scope guard
* For assignment, need to care about the target object as well
The PR addresses these situations as follows:
* Turn `_Flat_map_base(_Derived&& _Other)` to actual move constructor
* Add copy and move assignment operators
* In `noexcept()` of move constructor and move-with-allocator constructor ask for both noexcept-copy (as we need it) and noexcept-move (as per spec, there is a test for that) …

`<flat_map>`: move invariants preserving

---

stl/inc/flat_map

Remove these exception specifications:
* move-with-allocator constructor throws because allocator throws
* ditto the extracted machinery `_Extract_using_allocator`
* ditto copy assignment
Bugs introduced in #5454, before that there was only one of them, and it was in a constructor that was never called.
I'm not sure if move constructor and move assignment exception specifications are right. That's vector-like thing we have in `flat_map`, not necessarily `vector`, what if it might not have `noexcept` moves.

`<flat_map>`: drop bogus exception specifications

---

stl/inc/algorithm
stl/inc/flat_map
stl/inc/flat_set
stl/inc/vector

Tested with llvm/llvm-project@0b2ab11321d2b400987e9ade28a221dff67aea7d.
- Fixes narrowing conversion in `std::inplace_merge` due to assumption that the every wrapped iterator type has the same difference type as the unwrapped version.
- Removes uses of optional-for-sequence-containers `cbegin`/`cend`.
- Properly constrains constructors and deduction guides of `flat_(multi)set`.
Many libcxx tests seem to be buggy - e.g. some are testing uses with underlying containers that lack `assign` or `insert_range`, some are test moving comparators, some are testing bogus `emplace` member functions.

`<flat_set>`: Fix some significant bugs caught by latest libcxx tests

---

stl/inc/flat_map
stl/inc/flat_set

Currently, the implementation details of `<flat_map>` and `<flat_set>` are quiet inconsistent. E.g. some functionally similar `bool` template parameters have negated meanings.
This PR tries to modify `flat_(multi)set`'s internal base classes to make them more similar to `flat_(multi)map`'s.
- Changes `_Base_flat_set` to `_Flat_set_base`.
- Turns redundant template parameters `_Deriv` and `_Tsorted` into internal typedef-names `_Derived` and `_Sorted_t`.
- Consistently uses `_IsUnique` and `_NeedSorting`.
- Merges `_Emplace` and `_Emplace_hint` overloads.
For `_Flat_map_base`, this PR makes `_Insert_range` used a bit more places, and removes redundant `_NeedDeduping` template parameter from it, because the corresponding template argument is always `_IsUnique`.
These changes should be …

Make implementation details of `flat_meow` more similar

---

stl/inc/regex
tests/std/tests/VSO_0000000_regex_use/test.cpp

Fixes #5243 by repurposing another unused flag bit when the combined character class of "w" and another named class has to be represented.
After this PR, a different value is assigned to the `_Classes` field in the NFA node when we run into the buggy scenario, but the code takes care that the same value is assigned in all other cases. This means that the old matcher may only match different characters in the buggy scenario for code points >= 0x100: It will now match the members of the other named character classes rather than the members of the character class "w".

`<regex>`: Make `wregex` properly match the combination of `\w` and another named character class

---

stl/inc/regex

Fixes #5452. This is the minimal fix in `_Matcher::_Skip` that I mentioned in the issue: It avoids worst-case running time quadratic in the size of the searched string by giving up on `_N_if` nodes with two or more branches.
Unfortunately, we can't just give up whenever an `_N_if` is encountered because the parser currently likes to generate such nodes with a single branch. In particular, there is one such node at the beginning of each generated NFA. This means that giving up on such nodes would render `_Skip` pointless for all regular expressions.
I confirmed locally that this change is sufficient to fix the quadratic running time that #5452's test case exposes (though the quantifiers still almost double the running time.)

`<regex>`: Fix quadratic complexity in `regex_search` when regex starts with `?` quantifier or several alternatives

---

stl/inc/locale
tests/std/tests/GH_005236_collate_facet/test.cpp

Fixes #5212.
At first glance, calling `LCMapStringEx` with `LCMAP_HASH` seems to be the obvious solution, [but the docs state](https://learn.microsoft.com/en-us/windows/win32/api/winnls/nf-winnls-lcmapstringex) (emphasis mine):
> Strings that appear equivalent **typically** return the same hash (for example, "hello" and "HELLO" with LCMAP_IGNORECASE). **However, some complex cases, such as East Asian languages, can have similar strings with identical weights that compare as equal but do not return the same hash.**
I briefly tested this and the warning seems to be true, as the following program finds some single-character strings that collate the same but yield different hashes:
```cpp
#include <windows.h>
int main() {
const wchar_t* locale = …
```

`<locale>`: make `collate::hash` return the same hash for strings that collate the same

---

tests/std/tests/Dev11_0316853_find_memchr_optimization/test.cpp

Thanks for adding some impossible coverage to vector algorithms, @StephanTLavavej! (#5355)
But you seem to miss the one you've then-recently reviewed 😹 (#5352)
I had to damage the sequence in the test array a bit, because for `search_n` coverage to properly cover the right branch, we need to search for more than one consecutive element, otherwise we get special _n=1_ case.

Test coverage for `search_n` with impossible value

---

benchmarks/src/adjacent_difference.cpp
benchmarks/src/adjacent_find.cpp
benchmarks/src/iota.cpp
benchmarks/src/minmax_element.cpp
benchmarks/src/mismatch.cpp
benchmarks/src/remove.cpp
benchmarks/src/replace.cpp
benchmarks/src/std_copy.cpp

Resolves #5035
To avoid trying both aligned and unaligned allocators, try just unaligned. This makes sure we're checking the worst case, where vectorization would be of less  benefit.
Only change the container for potentially-vectorized algorithm benchmark. For, like, random it does not make sense. Also `vector<bool>` is vectorized, if we consider GPR-based vectorization as still vectorization, but this will not be sensitive to the alignment.
Some vector algorithms that are potentially sensitive to the alignment are in fact sensitive to alignment, some are not or almost not. The ones that are sensitive are simplest searches, or data movement. Consider `adjacent_find` as a good example of the sensitive one, here's how the results became worse:
Benchmark                            |  Before …

Benchmark: use `not_highly_aligned_allocator` in more places

---

stl/src/vector_algorithms.cpp

Resolves #5418
The goals were:
* Being able to locate functions using IDE navigation
* Group related stuff to make it clearer what uses what
Both goals are achieved with partial success:
* IDE navigation is way better, but still clobbered with now-empty unnamed namespaces. DevCom-10889095 is about that.
* Grouping works, but some algorithms still use `_Find_trats_` or `find` itself, now it happens across namespaces
* Move functions so that the related are grouped and unrelated are ungrouped; each group contains its trait structs, implementation functions, and export functions
* Separate traits from `_Find_traits_` where makes sense
* Rename existing namespaces and functions to match usual _Naming_style.
* Add new namespaces
* Rename some identifiers to shorter, as they now, in particular …

`vector_algorithms.cpp`: introduce namespaces

---

stl/inc/forward_list
stl/inc/list
stl/inc/vector
stl/inc/xhash
stl/inc/xmemory
stl/inc/xstring
stl/inc/xtree

Also receive its values with `auto`. Fixes #5448.

Replace `_GET_PROXY_ALLOCATOR` with a function template

---

stl/inc/xlocnum
tests/std/tests/GH_001277_num_get_bad_grouping/test.cpp

Previously, (when `boolalpha` is not set) `num_get::do_get` always parsed a wrongly grouped input for `bool` as `true`. But the parsed result shouldn't be affected by grouping.
Fixes #5470.

Fix `num_get::do_get` for `bool` on bad grouping

---

stl/msbuild/stl_base/msvcp.settings.targets
stl/src/cthread.cpp

[Microsoft Learn `GetLogicalProcessorInformationEx`](https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getlogicalprocessorinformationex)
Fix #5453.

Enable `thread::hardware_concurrency()` to handle more than 64 processors

---

stl/inc/mdspan
tests/libcxx/expected_results.txt
tests/std/tests/P0009R18_mdspan_layout_stride/test.cpp

Currently, our implementation of `layout_stride::mapping<E>::is_exhaustive()` gives incorrect result for some "unusual" extents. This PR attempts to fix it by adding a new way to compute an answer to the problem described in [[mdspan.layout.stride.obs]/5.2](http://eel.is/c++draft/mdspan.layout.stride.obs#5.2) and extra return paths for simple cases:
* When `E::rank() == 1`, `is_exhaustive()` returns `true` if and only if `stride(0) == 1`.
* When `E::rank() == 2`, `is_exhaustive()` returns `true` if and only if one of the strides is equal to `1` and the other stride is equal to extent corresponding to the previous stride.
* When two or more extents are equal to `0`, then `is_exhaustive()` always returns `false`.
* When there are no extents equal to `0` or `1` (these are "unusual" extents) …

`<mdspan>`: Fix `layout_stride::mapping<E>::is_exhaustive()`

---

stl/inc/type_traits
stl/inc/yvals.h

Once again, we need to add a workaround for the Taichi project in our Real World Code test suite, which is using an ancient version of Clang that we don't generally support (Clang 14). It turns out that the [`__builtin_verbose_trap`](https://clang.llvm.org/docs/LanguageExtensions.html#builtin-verbose-trap) intrinsic that I used in #5433 was only added in Clang 19. 
As a workaround, we can use the [`__builtin_trap`](https://clang.llvm.org/docs/LanguageExtensions.html#builtin-trap) intrinsic, which has been supported since the Age of Legends.
(At some point, if this keeps causing headaches, I'll throw up my hands and declare that we can't keep quasi-supporting this scenario anymore. But for now, adding a couple of lines isn't too intrusive, and it may also help with our quasi-support of the …

RWC workaround: Use `__builtin_trap` for ancient Clang

---

tests/utils/stl/test/features.py

Noticed by @muellerj2 in https://github.com/microsoft/STL/pull/5444#discussion_r2078610648. Windows 11 24H2 recognizes the locale name `'Czech_Czechia.1250'` and doesn't recognize `'Czech_Czech Republic.1250'`. I wasn't able to figure out *when* this change happened in Windows (a moderate amount of searching turned up nothing, and I even tried GitHub Copilot but it neither provided consistent answers nor cited any authoritative sources I could confirm), but it seems to have happened a while ago. (Presumably after our Python-powered test harness was added in 2020.)
We can assume/require that contributors and maintainers are running modern builds of Win11, and our CI infrastructure is now using Windows Server 2025, so we should switch to looking for the new locale name here. I believe our …

`features.py`: Recognize the `'Czech_Czechia.1250'` locale

---

stl/inc/flat_map
stl/inc/flat_set

#5498 will change `_Transparent` to be implemented in a simpler way, and it seemingly causes less burdensome to directly use `_Transparent` in `flat_meow`. Also, switching to use `_Transparent` ensures that uses of `_Is_transparent_v` can be restricted within `<xtree>`.

Use the `_Transparent` concept for `flat_meow`

---

tests/libcxx/expected_results.txt

`MinSequenceContainer` in the test suite looks underimplemented

`<flat_set>`: some libc++ tests look bogus

---

stl/inc/flat_set
tests/libcxx/expected_results.txt

On exception have to restore invariants. As usual, the only easy way is to clear it.

`<flat_set>`: insert range invariant fix

---

CMakeLists.txt
README.md
azure-devops/config.yml
azure-devops/provision-image.ps1
benchmarks/CMakeLists.txt
tools/CMakeLists.txt
tools/format/CMakeLists.txt
tools/validate/CMakeLists.txt

* PowerShell 7.5.1.
* VS 2022 17.14 Preview 7.
* CMake 3.31 (now required).
* New pool.
[STL-ASan-CI passed.](https://dev.azure.com/vclibs/STL/_build/results?buildId=18773&view=results)
+ Updated build compiler to VS 2022 17.14 Preview 7.
+ Updated CMake to 3.31 (now required).

Toolset update: VS 2022 17.14 Preview 7

---

stl/inc/regex

Follow-up to #5403: Since the matcher class just got renamed, we can add some member variables to cache the bitmasks for negated character classes when such negated character classes appear in the regex. This way, we can avoid the class lookup whenever we encounter such character classes during matching.
I also removed the duplicated class-matching logic in `_Skip`: It was annoying to keep `_Skip` and `_Do_class` in sync, and the logic in `_Skip` is by far not as well-tested as `_Do_class`.
To fuse the duplicated logic, I changed `_Do_class` to no longer modify the matcher's current position. Instead, it now takes a position starting from which the class should match and returns the position *just after* the sequence actually matched by the class. (Note that this can be more than one …

`<regex>`: Cache bitmasks of negated character classes during matching

---

stl/inc/__msvc_string_view.hpp

#3334 (and following-up #4047) made `basic_string` correctly handle lifetime of elements in constant evaluation, and #4613 made `char_traits::assign` no longer consider lifetime of elements (as specified by the standard).
However, there're some forwarding calls in `char_traits::assign` (added by #2305) that were made redundant but not removed. This PR removes the redundant forwarding.

`<__msvc_string_view.hpp>`: Avoid redundant forwarding in `char_traits::assign`

---

stl/inc/xhash
stl/inc/xmemory
stl/inc/xtree

#3736 added `_Is_transparent` and `_Transparent` but didn't use them.
I think it's time to use the `_Transparent` concept for C++20-and-later-only code. And it seems less burdensome for compilers if `_Is_transparent_v` is changed to be implemented with a concept. After the changes, `_Is_transparent_v` will be only necessary for `<xtree>`, so this PR moves `_Is_transparent_v` to that header.
`<flat_map>` and `<flat_set>` will be changed in another PR.
Theoretically, `_Is_transparent` would be useful in the cases where `conjunction(_v)` or `disjunction(_v)` is used. But I think there won't be such a case in MSVC STL - for new code it's probably better to use requires-clauses, and the uses of `_Is_transparent_v` in `<xtree>` seem stable enough. So I decide to remove it.

Use the `_Transparent` concept and remove `_Is_transparent`

---

stl/inc/mdspan
tests/std/tests/P0009R18_mdspan_layout_stride/test.cpp
tests/std/tests/P0009R18_mdspan_layout_stride_death/test.cpp

This PR:
* Implements precondition described in [[mdspan.layout.stride.cons]/4.3](http://eel.is/c++draft/mdspan.layout.stride.cons#4.3).
* Unfortunately, we cannot check this precondition when one or more extents are equal to `0`. For example:
```console
extents = [3, 0, 3, 0]
strides = [1, 3, 1, 3]
pairs = [(1, 3), (3, 0), (1, 3), (3, 0)] // these pairs satisfy our precondition
after sorting = [(1, 3), (1, 3), (3, 0), (3, 0)] // false positive
```
"Sorting" approach (presented in this PR) would fail, even though these values satisfy previously mentioned precondition.
* Fixes incorrect strides in the test code.
* Adds extra death tests.

`<mdspan>`: Implement missing precondition in `layout_stride::mapping<E>`'s constructor

---

stl/CMakeLists.txt

Followup to #5432, which linked against `Synchronization.lib` for all architectures.
This will be paired with a change to MSVC-internal `src/vctools/crt/crt_build.targets` (validated internally).

`stl/CMakeLists.txt`: Remove redundant `Synchronization.lib`

---

stl/inc/yvals_core.h

* Followup to #5432.
* The impact on the GitHub side is minimal, but I'll be adding more significant MSVC-internal changes when mirroring.
+ Together, the removal of Win7, Win8, and Win8.1 support will shrink the VCRedist executables by 6.7 MB each.
* Works towards #4858.
+ I'll need to get our documentation updated.
* This is for VS 18.0 Preview 1 and will not be backported.
+ For the rest of its lifecycle, VS 2022 17.14 will support Win7, Win8, and Win8.1.
This removal was formally approved today (internal VSO-2441848). We are fully aware that their counterparts Server 2012 and Server 2012 R2 are entering their final year of ultra-extended super-premium paid support.
* The STL no longer supports targeting Windows 7 / Server 2008 R2, Windows 8 / Server 2012, and Windows 8.1 / Server 2012 …

Win10 baseline: Drop support for Win8.1 / Server 2012 R2

---

stl/inc/flat_set
tests/libcxx/expected_results.txt

Flat adapter rule: when in doubt, clear the underlying collection.

`<flat_set>`: more invariants fixes

---

stl/inc/flat_map

If `_Hint_order == weak_ordering::equivalent` and `_IsUnique` are `true`, then `_Position != _Begin` or `!_Key_compare(*_STD prev(_Position._Key_it), _Key_val)` is `false`.

`<flat_map>`: Remove unreachable code

---

stl/inc/flat_set
tests/libcxx/expected_results.txt

* Reverts #5516, as supporting non-standard requirement is non-goal
- #5514 still looks valid
* Link these test failures to LLVM-140448
* Also link previously reported test failures to LLVM-140287

Revert incorrect `<flat_set>` change, and update test failure reason

---

stl/inc/regex
tests/std/include/test_regex_support.hpp
tests/std/tests/GH_005244_regex_escape_sequences/test.cpp

Towards #995. ECMAScript 15.10.1 defines the production `ControlLetter` such that only ASCII alphabetic characters are allowed. Such restricted character sets are often extended to corresponding POSIX character classes (to include Unicode characters) by Boost.Regex or `<regex>` implementations. But such an extension doesn't make much sense in this specific case, because these `\c` + letter escapes are supposed to emulate what pressing Ctrl + ASCII character does in the terminal. (It would actually make more sense to support "\c[" and similar, but the ECMAScript standard doesn't say so.)
Alternative: If non-ASCII characters should remain supported, we could query the bitmask of the character class "alpha" from the traits class.

`<regex>`: Restrict control letters in escapes to alphabetic ASCII characters

---

CMakeLists.txt
azure-pipelines.yml
tests/std/tests/GH_001103_countl_zero_correctness/test.cpp
tests/std/tests/GH_002206_unreserved_names/test.compile.pass.cpp
tests/std/tests/P1502R1_standard_library_header_units/custom_format.py
tests/std/tests/P1502R1_standard_library_header_units/custombuild.pl
tests/std/tests/P1502R1_standard_library_header_units/test.cpp
tests/std/tests/P2465R3_standard_library_modules/test.cpp
tests/std/tests/VSO_1775715_user_defined_modules/test.cpp
tests/utils/stl/test/features.py
tests/utils/stl/test/tests.py

Closes #2310 
- 7 libc++ tests and 51 std tests include `<Windows.h>` (possibly via a centralized header, e.g. `test_death.hpp`), and produce warning C28301: `C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\winnt.h(3209) : warning C28301: No annotations for first declaration of '_InterlockedCompareExchange128'. See c:\program files\microsoft visual studio\2022\preview\vc\tools\msvc\14.44.35207\include\intrin0.inl.h(185).`
- I've suppressed the warning by adding the `/wd28301` compiler option. It might also be possible to instead add a pragma to each affected file.
- Windows SDK 10.0.22621.0 uses `#pragma intrinsic(fabsf)` in `<corecrt_math.h>` for ARM64EC, which seems to cause problems in several tests.
- `GH_002206_unreserved_names` needs to avoid defining `intrinsic` as a …

Build tests for ARM64EC pipeline

---

stl/src/vector_algorithms.cpp

Two orthogonal but related changes:
* Exclude AVX2 `search` path for 8-bit elements (but not for `find_end`). Address concern in https://github.com/microsoft/STL/pull/5484#issuecomment-2886833974
* Add SSE4.2 paths for 32-bit and 64-bit elements. They are expectedly about 2 times slower than AVX2 counterparts, which is still an improvement over the scalar (except for evil cases)
Nothing more to tell about the 8-bit AVX2 `search` path removal. Some details on SSE4,2 path for 32-bit and 64-bit elements:
* Traits are separate for AVX2 and SSE4.2, like algorithms in `_Sorting` or bitset algorithms
* Unlike `_Sorting`, BSF and BSR are traits members. In `_Sorting`, these functions were called infrequently, so they were not worth differentiating for AVX2/SSE4.2. Here we use them in tightest …

Improve `search` and `find_end` vectorization

---

stl/src/vector_algorithms.cpp

Follow up for #5519 
1. Scope guard for multiple return. This pattern is used in other places where we have multiple return.
2. Drop `_bittestandreset`. The compiler emits `btc` for the `^= 1 << n` pattern, which has the same performance as `btr` for `_bittestandreset`.
- For `search` could also use `_Bingo &= _Bingo - 1`, or `_blsr_u32`, but there's not enough evidence in significant enough performance advantage to use this
- For `find_end` could try `_bzhi_u32`, but didn't even bother, here the expectation is even lower.
4. Always use unsigned 32-bit for bit masks from `movemask*`. Always 32 bit because internally there is 32-bit destination register, always unsigned because bitmask.
- Still `int` for `cmpestr*` masks, it is compile time, and only few bits, and intrinsic takes `int`
- …

Clean up `vector_algorithms.cpp` again: unsigned bit manipulation, scope guard for multiple return

---

stl/inc/regex
tests/std/tests/GH_002206_unreserved_names/test.compile.pass.cpp
tests/std/tests/VSO_0000000_regex_use/test.cpp

Resolves #438. There were two remaining uses of `error_syntax`:
* One is in the region parsing non-capturing groups and assertions. If it is not one of these, then `?` is essentially a quantifier applied to nothing, so `error_badrepeat` seems an apt choice among the available codes to me. (The error code `error_paren` used by libstdc++ feels a bit weird to me in this context because this error code is intended for unbalanced parentheses, which this isn't.)
* The other case can only be reached by an STL or compiler bug, so I replaced it by `_STL_INTERNAL_CHECK`: `_Alternative()` only returns normally when `_Mchar` is `_Meta_eos`, `_Meta_bar` or it is `_Meta_rpar` while `_Disj_count != 0`. Its caller, `_Disjunction()`, only returns if `_Mchar` is not `_Meta_bar` after `_Alternative()` …

`<regex>`: Remove `error_syntax`

---

stl/inc/__msvc_bit_utils.hpp
stl/inc/bit

provides 1.05 to 1.1 times speed up on x64 targets.
**x64 results**
```
Benchmark                               Time 
---------------------------------------------
bm_has_single_bit_if<uint8_t>        13.4 ns 
bm_has_single_bit_if_new<uint8_t>    12.7 ns 
bm_has_single_bit_if<uint16_t>       13.9 ns 
bm_has_single_bit_if_new<uint16_t>   10.8 ns 
bm_has_single_bit_if<uint32_t>       15.9 ns 
bm_has_single_bit_if_new<uint32_t>   12.6 ns 
bm_has_single_bit_if<uint64_t>       14.3 ns 
bm_has_single_bit_if_new<uint64_t>   11.0 ns 
bm_has_single_bit<uint8_t>           6.34 ns 
bm_has_single_bit_new<uint8_t>       5.88 ns 
bm_has_single_bit<uint16_t>          6.19 ns 
bm_has_single_bit_new<uint16_t>      4.52 ns 
bm_has_single_bit<uint32_t>          5.57 ns 
bm_has_single_bit_new<uint32_t> …
```

`<bit>`: Use popcount for `has_single_bit()` if it's always available

---

stl/inc/vector

@Codiferous is implementing WG21-P2280R4 in MSVC. With this Defect Report implemented, MSVC emits its (extremely annoying) warning C4127 "conditional expression is constant" for `vector<bool>::max_size()`, because we marked a local variable as `const` and that causes "trial evaluation" to happen. With WG21-P2280R4, `_Ints_max` is recognized as a compile-time constant, causing the `if`-statement below to emit the warning.
Unfortunately, the underlying `vector`'s `max_size()` has to be implemented in terms of the allocator's `max_size()`, and there's no requirement that it be a compile-time constant. So we can't just boil this whole thing down to an `if constexpr`.
To avoid this, we can extract the condition into a `const bool` and add a comment why. C4127 has a special case to avoid …

`<vector>`: Avoid a compiler warning with Defect Report P2280R4

---

tests/std/tests/P1208R6_source_location/header.h
tests/std/tests/P1208R6_source_location/test.cpp

EDG is changing their `source_location` builtins to produce output that more closely resembles C1XX's. To keep our tests passing as these changes are introduced into VS, I'm updating the tests to accept either the old output or the new output. After the changes have shipped and we can update the toolset on GitHub, I can remove the old expected outputs.
@jgoshi has validated that this passes with the upcoming changes.

Update `source_location` tests for upcoming EDG changes

---

benchmarks/src/regex_search.cpp
stl/inc/regex
tests/std/tests/VSO_0000000_regex_use/test.cpp

Towards #5468. This extends the skip heuristic to the remaining unhandled assertions: word boundaries and lookahead assertions.
* The handling of word boundaries turns out to be much simpler in `_Matcher2::_Skip()` than in `_Matcher2::_Is_wbound()`, because we don't have to do any special handling for the start or end of the input string: `_Skip()` is never called for the start (or as the comment at the top says, `--_First_arg` is valid) and it cannot skip beyond the end of the input string (`_Last`) anyway. So we only have to handle the middle case and have to keep looking for the first position where the word character property changes (`\b`) or where it does not change (`\B`).
* For negative lookahead assertions, the easiest thing to do is to just ignore the assertion body (i.e., to …

`<regex>`: Speed up searches for regexes that start with assertions

---

stl/src/tzdb.cpp

This PR adds a fallback time zone abbreviation of the form  `-05` or `+0530` when the system's code page cannot represent the localized time zone short ID produced by ICU. Previously such time zone short ID would result in `ERROR_NO_UNICODE_TRANSLATION` exceptions.
The numeric offset form (`-05` or `+0530`) is chosen because it is similar to the time zone abbreviation in [`tzdb`](https://data.iana.org/time-zones/tzdb/theory.html#abbreviations), and distinguishable from ICU's output.
The behavior depends on the current user locale and the current code page. For [ICU 77.1](https://github.com/unicode-org/icu/tree/release-77-1), the following locales have time zone short ID with non-ASCII characters, and thus might be affected by this fallback: `am`, `ar`, `as`, `bg`, `blo`, `brx`, `ckb`, …

`tzdb.cpp`: Fall back to numeric offset when the current code page cannot represent the time zone short ID

---

stl/src/filesystem.cpp

[`GetModuleHandleW`](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulehandlew) is a "desktop apps only" API. We avoid calling it for OneCore:
https://github.com/microsoft/STL/blob/7841cf88ff9af837fb980f2d2d4ac0f267e714c7/stl/src/winapisupp.cpp#L179-L194
and so we can't load [`GetTempPath2W`](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-gettemppath2w) for OneCore and must always use the [`GetTempPathW`](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-gettemppathw) fallback instead:
https://github.com/microsoft/STL/blob/7841cf88ff9af837fb980f2d2d4ac0f267e714c7/stl/src/winapisupp.cpp#L164-L175
`winapisupp.cpp` is built into the STL's DLL, and the non-dllexported `__crtGetTempPath2W` is used by …

`filesystem.cpp`: Avoid loading `GetTempPath2W` for OneCore

---

stl/inc/vector

Followup to #5550.
When Defect Report WG21-P2280R4 is implemented in MSVC, for libcxx's pathological tests for allocators with tiny `size_type`s like `uint8_t`, the compiler will notice that `_Ints_max * _VBITS` undergoes integral promotion, but isn't smart enough to realize that we've avoided actual truncation.
We should consistently follow our pattern of `static_cast`ing to avoid warnings with integral promotions.

`<vector>`: Avoid another compiler warning with Defect Report P2280R4

---

stl/inc/yvals_core.h

Fixes #5564
This updates the _MSVC_STL_UPDATE macro from 202505L to 202506L.

Update _MSVC_STL_UPDATE macro to 202506L

---

stl/inc/semaphore
stl/inc/xatomic_wait.h
stl/src/atomic_wait.cpp

Fixes #5574 
Abandon `__std_atomic_wait_get_deadline` and `__std_atomic_wait_get_remaining_timeout`. Originally they were used as fast and convenient steady clock, that is just as precise as the wait itself. But we have to use the `steady_clock`, not _a steady clock_, and be as precise as it is.
No need in `_Clamped_rel_time_ms_count`. The existing `_Semaphore_remaining_timeout` is good enough, although it diverges in that it clamps to 10 days, not to 1 day. Importantly. both use `chrono::ceil` to get larger rather than smaller timeout when rounding.

`<semaphore>`: use `steady_clock`

---

CMakeLists.txt
README.md
azure-devops/config.yml
azure-devops/provision-image.ps1

+ Updated build compiler to VS 2022 17.14.8 Preview 1.
+ Updated Python to 3.13.5.
* provision-image.ps1: Remove 32-bit ARM (from #5594)
* PowerShell 7.5.2.
* Python 3.13.5.
* VS 2022 17.14.8 Preview 1.
* Newer pool.

Toolset update: VS 2022 17.14.8 Preview 1

---

stl/inc/iterator

Closes #5582
Removed the `/* strengthened */` comments from [`STL/stl/inc/iterator`](https://github.com/microsoft/STL/blob/7841cf88ff9af837fb980f2d2d4ac0f267e714c7/stl/inc/iterator#L1314-L1317) at all the necessary locations where `noexcept` is now expected as per LWG-4245.

Remove comments for LWG-4245

---

stl/inc/regex

#4451 limited recursion for capture groups in the parser. However, unlimited recursion in the parser is still possible for regexes that use non-capturing groups or lookahead assertions. This PR similarly limits the recursion for such constructs by using the parser's pre-existing internal recursion counter, `_Disj_count`.
This supersedes the capture group limit introduced by #4451 as a way to prevent stack overflows. But I'm leaving it in because regexes using more than 1000 capture groups strike me as bogus anyway. (I think the error code `error_space` would be more appropriate in this case now, since the limit is no longer about preventing recursion, but it's probably not worth introducing a minor behavior difference just for this reason. One could even argue that `error_space` is more …

`<regex>`: Limit recursion in the parser

---

stl/src/vector_algorithms.cpp

I'm not completely sure what exactly ARM64EC is (#2740). 
But the upstream `memchr` / `wmemchr` are apparently properly optimized for it.
I didn't benchmark or test this change. It seems to compile though.

Optimize `find` for ARM64EC

---

stl/inc/xloctime

This is cpp/microsoft/public/leap-year/unchecked-after-arithmetic-year-modification, "Year field changed using an arithmetic operation without checking for leap year".
Only the line with the conditional operator appeared to be emitting this warning, but to be safe I'm restructuring the code to use if-statements consistently (the comments make it clearer anyways), and to suppress the CodeQL warning whenever we're performing arithmetic.
Should prevent a blizzard of internal bugs like OS-57986329 from being created in the future.

`<xloctime>`: Silence CodeQL warning SM03231 about leap year arithmetic

---

stl/inc/xutility

`ranges::find` is not using `wmemchr` after #5284. Yet, `std::find` uses it.
For `wmemchr` we drag in `<cwchar>` which is heavy, specifically due to `wmemchr` optimization. So it seems silly not to take the full advantage of `wmemchr`. The PR addresses that by making `ranges::find` also using `wmemchr`.
This affects ARM64 (non-EC), and builds with vector algorithms disabled.
See also #5596. Not sure if this PR closes that issue, because merging the PR does not preclude doing also Windows SDK throughput optimization or otherwise addressing the throughput in the future.

Restore `wmemchr` optimization in `ranges::find`

---

stl/CMakeLists.txt
stl/msbuild/stl_1/msvcp_1.settings.targets
stl/msbuild/stl_2/msvcp_2.settings.targets
stl/msbuild/stl_atomic_wait/msvcp_atomic_wait.settings.targets
stl/msbuild/stl_base/libcp.settings.targets
stl/msbuild/stl_base/msvcp.settings.targets
stl/msbuild/stl_codecvt_ids/msvcp_codecvt_ids.settings.targets
stl/src/excptptr.cpp
stl/src/pplerror.cpp

Defining `_VCRT_ALLOW_INTERNALS` allows `<vcruntime_internal.h>` to be dragged in:
```cpp
#if !defined _VCRT_BUILD && !defined _VCRT_ALLOW_INTERNALS
// This is an internal C Runtime header file.  It is used when building the
// C Runtime only.  It is not to be used as a public header file.
#error ERROR: Use of C Runtime library internal header file.
#endif
```
The entire STL build (in CMake and MSBuild) defines this macro, but only two translation units need it (for EH machinery). To prevent unintentionally using VCRuntime internals in the future, we should limit the use of the macro to where it's needed.
Ordinarily, I would hiss at defining macros in source files, as opposed to in the build system. However, because this merely guards an `#error` (instead of affecting something …

Cleanup: Mostly remove `_VCRT_ALLOW_INTERNALS`

---

stl/inc/yvals_core.h

Reverse-mirrored from toolset update MSVC-PR-650818 targeting MSVC `main`.
The compiler has implemented a new warning C5291: "'DERIVED': deriving from the base class 'BASE' can cause potential runtime issues due to an ABI bug. Recommend adding a 4-byte data member to the base class for the padding at the end of it to work around this bug." This is emitted in the STL for `basic_iostream` and `basic_ostringstream`, which each derive from `basic_ostream`, when we try to self-build MSVC with a sufficiently updated compiler.
Whatever this ABI bug is, it's frozen in our layout of `basic_ostream`. Since we can't do anything about it until vNext, I'm globally suppressing it in the STL, with a TRANSITION, ABI comment.
I considered fine-grained suppression around `basic_iostream` and …

Silence ABI warning C5291 for the entire STL

---

CMakeLists.txt
README.md
tests/utils/stl/test/tests.py

Reverse-mirrors MSVC-PR-656388 "Update WinSDK to 10.0.26100.4654", where I'm updating the MSVC toolset's usage of the WinSDK. This is a major change for MSVC but has extremely limited impact for the STL as we've already made this change for the GitHub build on 2025-06-13, when #5580 updated azure-devops/provision-image.ps1 to select `Microsoft.VisualStudio.Component.Windows11SDK.26100`.
* Drop TRANSITION comment now that we set `NTDDI_WIN11_GE` internally.
* The WinSDK in the VS Installer has been updated in-place from 10.0.26100.3916 (released 2025-04) to 10.0.26100.4188 (released 2025-05). Update our various comments accordingly.
+ I checked that all of the TRANSITION bugs are still present. Note that as of VS 17.14.10 Preview 1, WinSDK 10.0.26100.4654 (released 2025-07) is not yet …

Update WinSDK comments

---

stl/inc/execution
tests/std/test.lst
tests/std/tests/LWG2510_tag_classes/env.lst
tests/std/tests/LWG2510_tag_classes/test.compile.pass.cpp
tests/std/tests/VSO_0000000_more_pair_tuple_sfinae/test.cpp

Addresses https://github.com/microsoft/STL/issues/5567#issuecomment-2932355408 for which I filed LWG-4273. IIUC we can make the changes even without corresponding changes in the standard wording.
The test suite is reworked to cover tag class types more specifically. I'm trying to cover implementation-internal construction tag types together, although the list seems messy and it might be better to make some cleanup later.

Speculatively implement LWG-4273 Standard execution policy types should be conventional tag class types

---

tests/std/tests/Dev11_0000000_null_forward_iterators/test.cpp

The merged PR [#117387](https://github.com/llvm/llvm-project/pull/117387) in Clang warnings when a parameter of memcpy is pointer to non-trivial-copyable types. This PR suppress the warning to avoid test failures.
Also, the `<filesystem>` and `<span>` headers were not properly guarded, and this PR guards them as seen in L166 and L182. The above two issues would cause this test to fail.
https://github.com/microsoft/STL/blob/f015db5833e8daf3a5534c4ce2b6c9acc9689b0c/tests/std/tests/Dev11_0000000_null_forward_iterators/test.cpp#L166-L168

`Dev11_0000000_null_forward_iterators`: Avoid Clang warnings, guard headers for C++17/20

---

tests/std/tests/VSO_0000000_initialize_everything/test.cpp

Clang also generates the -Wnontrivial-memcall warning for this test, similar to #5654.

`VSO_0000000_initialize_everything`: Avoid compiler warnings

---

tests/std/tests/VSO_0180466_algorithm_overhauls/test.cpp

Lines 35-84 of this test involve comparisons between different `charN_t` types, so similar to #5653, Clang will also generate warnings for this.
https://github.com/microsoft/STL/blob/f015db5833e8daf3a5534c4ce2b6c9acc9689b0c/tests/std/tests/VSO_0180466_algorithm_overhauls/test.cpp#L35-L84

`VSO_0180466_algorithm_overhauls`: Suppress `-Wcharacter-conversion` for Clang 21

---

CMakeLists.txt
README.md
azure-devops/config.yml
azure-devops/provision-image.ps1
stl/inc/expected
tests/std/tests/P0323R12_expected/test.cpp

+ Updated build compiler to VS 2022 17.14.12 Preview 1.
+ Updated Python to 3.13.6.
* Python 3.13.6.
* VS 2022 17.14.12 Preview 1.
* New pool.
* Remove workaround for DevCom-10655311.

Toolset update: VS 2022 17.14.12 Preview 1

---

stl/inc/regex
tests/std/tests/GH_000995_regex_custom_char_types/env.lst
tests/std/tests/GH_000995_regex_custom_char_types/test.cpp
tests/std/tests/GH_005244_regex_escape_sequences/test.cpp
tests/std/tests/GH_005553_regex_character_translation/test.cpp

Resolves #995 by eliminating `_Uelem` completely.
This PR does not quite complete support for custom character types: The internals of `regex_search` still place some additional requirements on such types. But except for ADL resilience, the support should be complete for `regex_match`, as the passing test confirms.
* Remove usage of `_Uelem` from `_Is_word` by converting to `unsigned char` instead combined with a check that re-conversion to the character type yields the same character again.
* At this opportunity, `_STD`-qualify some `_Is_word` calls.
* Remove usage of `_Uelem` from `_Lookup_range` by relying on the `lt()` function in the char traits type instead.
* Since this is possibly called in a tight loop, I added two overloads for `char` and `wchar_t` that avoid calling the `lt()` …

`<regex>`: Remove non-standard `_Uelem` from matcher

---

benchmarks/src/regex_search.cpp
stl/inc/regex
tests/std/tests/VSO_0000000_regex_use/test.cpp

In the default `std::regex_traits<char>` and `std::regex_traits<wchar_t>` implementation, the `translate()` function just returns its argument unchanged ([see \[re.traits\]/4](https://eel.is/c++draft/re.traits#4)). This means that the call to this function can be skipped for these traits classes.
This PR implements this change, and as a consequence, the skip optimization now engages the vectorized `std::search` implementation in `collate` mode as well.
The tests added by #5553 already check correct handling of `translate()` in the skip optimization for user-provided regex traits, so this PR just adds a short variant of this test for default `std::regex` and `std::wregex`.
Benchmark (only relevant lines):
name | before | after | speedup
-- | -- | -- | --
bm_lorem_search/"bibe"/2 | 2825 ns …

`<regex>`: Speed up skip optimization for default `regex_traits` in `collate` mode

---

tests/std/tests/P0811R3_midpoint_lerp/test.cpp

This mirrors the STL part of the compiler backend MSVC-PR-661055 "Inlining Related Fixes" by @manbearian:
> Disable warning about overflow in constant math that shows up if the inliner does more aggressive inlining.
Although this MSVC-PR is targeted at internal `prod/be`, it's safe to mirror this suppression to GitHub and our usual branch `prod/fe`, where they'll merge harmlessly in MSVC `main`.

`P0811R3_midpoint_lerp`: Suppress warning C4756

---

stl/inc/algorithm

Reported by Aditya Anand to our internal C++ mailing list.
On x86, it's barely possible for `stable_sort()` to trigger an integer overflow when repeatedly doubling a chunk size. This happens when sorting over a billion 1-byte elements; the test case below uses 2^30 + 2 bytes. Surprisingly, this bug has been present since the beginning of time; we've historically been pretty good about checking for overflow before multiplying (e.g. in geometric growth), but missed this case.
We can avoid this integer overflow by testing whether we're done before doubling the chunk size. As the comment explains, I've carefully transformed the test to avoid even/odd issues. `ranges::stable_sort` was equally affected.
I'm not altering the initial doubling in this loop. Because we start with 32, i.e. 2^5, the …

`<algorithm>`: Avoid integer overflow in `stable_sort()` and `ranges::stable_sort` for huge inputs on x86

---

stl/inc/regex
tests/std/tests/GH_000995_regex_custom_char_types/test.cpp

Fixes #5673 and fixes VSO-2548012 in conjunction with small Build2 changes.
Build2 is doing something extremely complicated and fragile with user-defined character types and `regex`. When we construct user-defined `_Elem` from ordinary `char`s, that triggers assertions in their machinery, even though the resulting homogeneous comparisons between `_Elem` and `_Elem` are arguably more cromulent.
This PR slightly backs off from the purity of such comparisons, resulting in code that's somewhat closer to our old way of doing things, but still avoiding the internal `_Uelem` machinery. Now we directly compare `_Elem` to `char`. Build2 has heterogeneous comparison operators that handle this.
It will still be necessary to update Build2 to round-trip their user-defined character type instead of …

`<regex>`: Compare against `char` directly

---

tests/std/tests/P0811R3_midpoint_lerp/test.cpp

This works around #5685 until we can find and fix the root cause.
Reverse-mirrored from MSVC-PR-662395 where we have ARM64 runtime coverage, also manually verified in an ARM64 VM. (Someday I'll set up ARM64 runtime coverage for GitHub if I can ever step off from the review treadmill for a moment.)

`P0811R3_midpoint_lerp`: Work around ARM64 assertions

---

stl/inc/vector

To handle the difference between counting ones and counting zeros, `_Count_vbool`'s core loop conditionally complements every block it processes: that's O(n) work. We can do better: we can unconditionally count ones, then, after the loop, if we actually wanted zeros, subtract the number of ones from the number of bits we processed: O(1) work.

Optimize core loop of `_Count_vbool`

---

stl/inc/regex

This is the first minor step on the journey of making the matcher non-recursive to deal with #997 and #1528.
This moves all instances of `_Tgt_state` or `_Bt_state` from the stack to the heap (into a `vector`). These objects store the current match state and are used to restore it when backtracking. In functions, the `_Tgt_state` objects in the vector are referenced using their indices (and **not** using pointers because the vector might reallocate).
Note that we have to pop the frames from the stack whenever we return during backtracking, but we don't have to worry about exceptions: If an exception occurs, the whole `_Matcher2` object will be destructed.
Since these objects are large, this slightly reduces stack pressure: Copying #997 to a test and running it with the usual matrix, the …

`<regex>`: Move saved match state to the heap

---

tests/libcxx/expected_results.txt

`<flat_map>`, `<flat_set>`: mark unused variables and typedef libc++ test failures as known upstream

---

stl/inc/xloctime

Followup to #5625. Fixes internal VSO-2566953.
Previously, I silenced "Year field changed using an arithmetic operation without checking for leap year" for all of the locations that were performing arithmetic. Now we've got a new round of warnings, same opaque ID SM03231 but a different message "Field `tm_year` on variable `_Pt` has been modified, but no appropriate check for LeapYear was found", so we need to suppress every line modifying `tm_year`.
Once again it's time to quote:
> "I remember that we cleared this world out. We won. Is a future coming in which we will, eventually, truly, have won?"
\- Ra (Abstract Weapon) by qntm

`<xloctime>`: Silence CodeQL warning SM03231 about leap years, again

---

stl/inc/regex

... to allow for the layout changes that are necessary to make the matcher non-recursive.
This PR does not include any further changes because the next step is a relatively complex change that implements manual unwinding of the match state stack in the function `_Match_pat()`.

`<regex>`: Rename the matcher again

---

stl/inc/atomic

`<atomic>`: Workaround `__iso_volatile_{load,store}64` being non-atomic with clang-cl on 32-bit x86

---

stl/inc/vector

Fixes #5720.
`_IsSingleBlockDest` has special case when that single block touches edge, and `_DestEnd` is greater that `_Dest`, and `_DestEnd._Myoff == 0`. This is handled elsewhere:
https://github.com/microsoft/STL/blob/43e96b29a971a7a26aceaa539d22cbedfcf13687/stl/inc/vector#L3834
https://github.com/microsoft/STL/blob/43e96b29a971a7a26aceaa539d22cbedfcf13687/stl/inc/vector#L3843
https://github.com/microsoft/STL/blob/43e96b29a971a7a26aceaa539d22cbedfcf13687/stl/inc/vector#L3860
Now we need to add missing handling in the UB causing line. If `_DestEnd._Myoff == 0`, we have the only case when the subtraction result is negative. We actually need to subtract from full 32 bits in this case.
The UB didn't cause runtime behavior difference, as the shift instruction just ignores high bits.

Fix UB in `vector<bool>` by adding missing special case

---

stl/inc/vector

Reported by Weipeng Liu internally. Consider the following code, which is activating our escape hatch to disable enforcement of WG21-N5014 \[container.alloc.reqmts\]/5 "*Mandates:* `allocator_type::value_type` is the same as `X::value_type`."
```
D:\GitHub\STL\out\x64>type meow.cpp
```
```cpp
#include <memory_resource>
int main() {
vector<int, pmr::polymorphic_allocator<double>> my_vector;
my_vector.emplace_back(3);
}
```
```
D:\GitHub\STL\out\x64>cl /EHsc /nologo /W4 /std:c++latest /D_ENFORCE_MATCHING_ALLOCATORS=0 meow.cpp
meow.cpp
D:\GitHub\STL\out\x64\out\inc\vector(897): error C2440: 'initializing': cannot convert from 'std::pmr::polymorphic_allocator<_Newfirst>' to '_Alloc &'
with
[
_Newfirst=int
]
and
[ …
```

`<vector>`: Fix allocator types in reallocation guards

---

tests/std/tests/P0466R5_layout_compatibility_and_pointer_interconvertibility_traits/test.cpp

An upcoming MSVC version will fix a bug that caused us to accept some template argument deduction cases that should be deduction failures. Specifically, with a template parameter `R (C::*)` where `C` was explicity specified you can't deduce `R` from a pointer-to-member with a mismatched class type, even one that has an implicit conversion.
The pointer interconvertibility trait tests included a few of these situations where a template argument was explicitly specified but a pointer-to-member of a base class type was provided.

Deduction failures in pointer interconvertibility trait tests

---

stl/inc/random

> _It's perfectly stable, so long as tha don't shift it about too much...._
>
> &mdash;Thomas Pynchon, _Mason & Dixon_
Fixes #5719.
The second loop in `operator()` is fine because it's only executed if multiple random values are needed (modulo the rejection sampling), i.e., `_Nx > 1`. In such cases, `_Wx0 <= _Wx / _Nx <= sizeof(_Eres)*8 / 2`, so `_Wx0+1 < sizeof(_Eres)*8` as long as `_Eres` is more than two bits.

`<random>`: Prevent full-width shifts in `independent_bits_engine`

---

benchmarks/inc/utility.hpp
benchmarks/src/vector_bool_copy.cpp
benchmarks/src/vector_bool_copy_n.cpp
benchmarks/src/vector_bool_count.cpp
benchmarks/src/vector_bool_move.cpp

Fuse `random_bool_vector` into  `random_vector`

Fix non-inline `random_bool_vector` in benchmarks

---

stl/src/vector_algorithms.cpp

Found by compiling with `clang-cl stl\src\vector_algorithms.cpp -std:c++latest -march=x86-64-v3`.
Whereas we don't build STL with that, there are still reason why compiling this particular file with `clang-cl` may be useful:
* Catch instructions not available on a particular arch. If `-march=x86-64-v3` is dropped, there would be a lot of target errors, that are solved by placing `gnu::target` attributes. When they are placed expectedly, unexpected instruction on an unverified properly code path will trigger an error.
* Run with `-fsanitize=undefined` to avoid any UB.
* Conformance by itself is good.

`vector_algorithms.cpp`: Improve conformance by adding missing `template` and `typename` for dependent things

---

stl/src/vector_algorithms.cpp

Discovered while experimenting with `clang-cl stl\src\vector_algorithms.cpp -std:c++latest` command.
A couple of functions are non-unique, and should be removed.
Two other ones are also exiting this file, as scope guard is used instead.

`vector_algorithms.cpp`: remove unused functions

---

stl/inc/regex

Towards #997 and #1528.
We have to handle disjunctions (represented by `_N_if` nodes) differently depending on longest mode: When `_Longest` is true, we have to evaluate all alternatives during unwinding no matter if they matched successfully or not. Otherwise, we always may (and usually must) stop evaluating alternatives after one succeeded. The former is implemented by the case `_Disjunction_eval_alt_always`, the latter by `_Disjunction_eval_alt_on_failure`. We can implement the latter case by falling through to the former.
During unwinding, `_Frame` already holds the correct values to evaluate further alternatives in the disjunctions except for the NFA node it points to. So we can just update the node pointer and "push" `_Frame` on the stack again by incrementing `_Frames_count`.
In …

`<regex>`: Process disjunctions non-recursively

---

stl/inc/__msvc_string_view.hpp
tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp
tests/std/tests/VSO_0000000_vector_algorithms_floats/env.lst
tests/std/tests/VSO_0000000_vector_algorithms_mismatch_and_lex_compare/test.cpp
tests/std/tests/usual_matrix.lst
tests/utils/stl/test/features.py

Fixes #3568.
This was briefly enabled for Clang 15 by #3452 on 2023-03-13, then disabled for Clang 16 by #3711 on 2023-05-18. After updating to Clang 20 by #5717 on 2025-09-15, we can re-enable this test coverage.
Note that `tests/utils/stl/test/features.py` disabled the configurations. We accumulated a couple of changes to `tests/std/tests/VSO_0000000_vector_algorithms_floats/env.lst` and `tests/std/tests/usual_matrix.lst` commenting out configurations, but I believe those changes were unnecessary. This PR updates `features.py` to enable the feature, uncomments the commented-out configurations, and doesn't change the large number of already-uncommented configurations across other files.
I audited our `env.lst` and related files, and I believe our UBSan coverage is reasonably …

Reactivate Clang UBSan test coverage

---

stl/inc/yvals_core.h

Resolves #5750 
This change updates the implementation-specific library version macro **`_MSVC_STL_UPDATE`** in `STL/stl/inc/yvals_core.h`.
Following the established YYYYMM format, the value is updated from `202509L` (September 2025) to **`202510L`** (October 2025).

fixing MSVC_STL_UPDATE Macro
